### ISSUE TITLE
Bundling Java error

### ISSUE THREAD

**Issue by ghost** [AppImage/AppImageKit#1001]
I try to package my [game ](https://github.com/devnewton/newton_adventure ) using appimage.

I have followed the [wiki instructions](https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps): https://github.com/devnewton/newton_adventure.appimage

When I run the generated appimage, it prints this error:

> execv error: No such file or directory

I cannot figure out what is different from the wiki instructions.

**Comment by probonopd** [comment]
Getting

https://travis-ci.com/probonopd/newton_adventure.appimage/builds/134259241#L1453-L1462

whatever this means. How did you get around this?

**Comment by devnewton** [comment]
Oups sorry I forgot a dependency. Just commited a fix on https://github.com/devnewton/newton_adventure.appimage

Back to the execv error, I suspect the bundled jdk not being available in path, but didnt manage to make it work.

**Comment by probonopd** [comment]
For starters, your sh script is not in `./usr/bin` and hence not on the `$PATH`, or is it?

**Comment by probonopd** [comment]
First we need to get the thing to compile.

Running into another error:
https://travis-ci.com/probonopd/newton_adventure.appimage/builds/134271605#L1909
