### ISSUE TITLE
Is it possible to pack libc into appimage on linux?

### ISSUE THREAD

**Issue by pangqingyuan1991** [AppImage/AppImageKit#1014]
Many linux desktop uses glibc as C library. I have a Qt5 based GUI app which is linked with musl dynamically. In linux, the path of runtime linker (named ld-linux-x86-64.so.2 normally) must be absolute. I found appimage mounts squashfs in /tmp/xxx, but xxx is a random string. So even I pack musl libc.so into appimage,  the kernel can't find linker.
Is there a way to make the mountpoint a fixed path? Just like /tmp/.MyApp when the app name is MyApp.

**Comment by TheAssassin** [comment]
No, you cannot make it a fixed path. Neither do you have to have an absolute path.

Put your linker into the AppImage as well. Then, write an `AppRun` shell script that calls your main binary through the linker explicitly.

```sh
#! /bin/sh

"$APPDIR"/ld-linux.so.2 "$APPDIR"/usr/bin/myapp
```

**Comment by probonopd** [comment]
There's more to it.

if you want to bundle glibc, then you need to bundle not only glibc and (as @TheAssassin wrote) ld-linux, but really [everything that comes with the glibc package](https://packages.debian.org/sid/amd64/libc6/filelist), and you must make sure that these things do _not_ get loaded from the system but that your private versions are used.

Coincidentally I am working on a tool that will do this (it is still experimental). You can try appimagetool from https://github.com/probonopd/go-appimage/releases/continuous.

I am not sure whether it is possible to use a Qt app that was linked against musl on a glibc-based system, but I am very interested in this topic.

**Comment by TheAssassin** [comment]
@pangqingyuan1991 wants to bundle a musl-linked app, I'm pretty sure it's easier than bundling glibc.

**Comment by probonopd** [comment]
Indeed. The question, though, is whether a musl-based Qt app will ever run on a libc-based target system. I am not sure on this, yet.

**Comment by azubieta** [comment]
@pangqingyuan1991 https://github.com/AppImageCrafters/appimage-builder does that job for you. Check the examples folder, there are recipes for bundling Qt apps that way.

**Comment by pangqingyuan1991** [comment]
Yeah, musl is more simple and easy to be bundled since it is all-in-one libc.so including runtime linker. And I am sure it can run on glibc-based target.

**Comment by probonopd** [comment]
@pangqingyuan1991 please let me know once you have a Qt app with musl that runs on glibc systems, I would like to try it. Thanks!

**Comment by pangqingyuan1991** [comment]
@probonopd 
I have finished it. https://github.com/pangqingyuan1991/wireshark-appimage/releases/download/V3.2.0rc1/wireshark
All resources including fonts are packed.

**Comment by probonopd** [comment]
@pangqingyuan1991 very, _very_, __very__ good :+1: 

```
me@host:~$ file '/tmp/.Wireshark/bin/wireshark'
/tmp/.Wireshark/bin/wireshark: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /tmp/.Wireshark/lib/libc.so, stripped
```

Congratulations. The first Qt based application using musl running from a self-contained AppImage using musl.

**Comment by pangqingyuan1991** [comment]
@probonopd 
I use buildroot,not Alpine. buildroot can make toolchain very easily

**Comment by pangqingyuan1991** [comment]
I use cmake option -DCMAKE_INSTALL_PREFIX=/tmp/.Wireshark. So wireshark may lookup its plugins in this fixed path. It is so boring to solve such problem. So I choose symlink instead.

**Comment by probonopd** [comment]
Here is KCalc from KDE 19.08.3 (from Alpine with musl) running on Ubuntu 14.04.1:

![](https://user-images.githubusercontent.com/2480569/70391530-2e5c9c00-19ce-11ea-95ac-819b9d7ecf05.png)

Made with my experimental Go implementation of appimagetool: https://github.com/probonopd/go-appimage/issues/21
