### ISSUE TITLE
How do AppImage umount fuse without root?

### ISSUE THREAD

**Issue by pangqingyuan1991** [AppImage/AppImageKit#1016]
Hi,
Does AppImage call external command fusermount to umount fuse when app is closed?
I try to implement my own packer like AppImage, but now I have no idea how to umount the fuse without external dependency.

**Comment by azubieta** [comment]
Hi @pangqingyuan1991, AppImage uses squashfuse with a few teaks to make it a library. So it uses the squashfuse routine to unmount the filesystem.

**Comment by TheAssassin** [comment]
We use an API call provided by squashfuse, as @azubieta stated. You can use `fusermount -u` as well. It doesn't really matter which one you use. Even a plain FUSE API call should do.

**Comment by probonopd** [comment]
> I try to implement my own packer like AppImage

Hi  @pangqingyuan1991 you are doing very interesting work, what can we do to work together? I think this can be much better if we can work together, rather than have yet another format.

**Comment by pangqingyuan1991** [comment]
> > I try to implement my own packer like AppImage
> 
> Hi @pangqingyuan1991 you are doing very interesting work, what can we do to work together? I think this can be much better if we can collaborate, rather than have yet another format.

I agree with you. But appimagetool is a bit complex now. I need to do some learning first.
