### ISSUE TITLE
Cannot get Zoho Mail to run, says please check you FUCE install

### ISSUE THREAD

**Issue by GraveDigger1** [AppImage/AppImageKit#1018]
i'm running manjaro 18.1.4 kde testimg and when i try to launch zoho mail i keep getting. which led me to the one page you have posted. according to manjaro's update manager i have fuse-common 3.8.0-1. any help getting this fixed would be greatly appreciated. thanks

```
Cannot mount Appimage, please check your FUSE setup.

You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information 
```

**Comment by probonopd** [comment]
Does your use have permissions to use FUSE?
Please see https://github.com/AppImage/AppImageKit/wiki/FUSE for more information.

Please try with a Manjaro Live ISO. Does it work there?

**Comment by GraveDigger1** [comment]
yes fuse-common is installed during os install. now that said i did a restart, attempted to launch again got the one zoho page, attempt again got to the second screen that ask about location, attempted again and got to the screen asking for email address and password, attempted one last time and it launched the zoho without any issue. i have not had a problem with zoho since that last attempt. while zoho was running me through hoops i remembered that i believe i went through this with zoho the last time i used it's appimage. since fuse was already installed that would make this a problem with the zoho appimage itself. i know i made a thread about fuse on their forums, so i'll let them know they have a problem especially since this is a newer version than the last time it happened. thanks very much for getting back to me.
