### ISSUE TITLE
`install-build-deps.sh` mentioned in `README.md` doesn't exist

### ISSUE THREAD

**Issue by zaoqi** [AppImage/AppImageKit#1020]
https://github.com/AppImage/AppImageKit/blame/64321b72bc35fc886772ab7d95f3924b67207b32/README.md#L193

**Comment by probonopd** [comment]
Thanks @zaoqi. That part of the README was written by me before CMake was introduced by @TheAssassin. So @TheAssassin would you like to update the README (before I write something half-correct)?

**Comment by TheAssassin** [comment]
Fixed.
