### ISSUE TITLE
make an appimage for the qmasterpassword app

### ISSUE THREAD

**Issue by chrisWith** [AppImage/AppImageKit#1022]
Hi,

I'm using qmasterpassword from arch Linux AUR and very happy with this app. Unfortunately there is no other linux distro with a running version. Now I'm back on debian or for special purpose also other exotic linux distros on the way and it would be extrem cool by having this little  app packed in an appimage format.

Can you support for that matter? 

the app:
https://github.com/bkueng/qMasterPassword

Thank you 

best regards

**Comment by probonopd** [comment]
Thanks @chrisWith for your interest in AppImage.

Closing here in favor of https://github.com/bkueng/qMasterPassword/issues/7. This project just provides the tools for application authors to make AppImages of their applications.
