### ISSUE TITLE
Failed to execute latest AppImages anywhere

### ISSUE THREAD

**Issue by linuxhw** [AppImage/AppImageKit#1023]
I've just rebuilt [my AppImage](https://build.opensuse.org/package/binaries/home:linuxbuild/hw-probe/AppImage) and it doesn't run anymore due to the error:

```
Can't load '/tmp/.mount_hw-proI9ACbN/usr/lib/perl5/auto/Cwd/Cwd.so' for module Cwd: /tmp/.mount_hw-proI9ACbN/usr/lib/perl5/auto/Cwd/Cwd.so: undefined symbol: PL_stack_sp at /tmp/.mount_hw-proI9ACbN/usr/lib/perl5/XSLoader.pm line 93.
 at /tmp/.mount_hw-proI9ACbN/usr/lib/perl5/Cwd.pm line 82.
Compilation failed in require at /tmp/.mount_hw-proI9ACbN/usr/lib/perl5/File/Path.pm line 6.
BEGIN failed--compilation aborted at /tmp/.mount_hw-proI9ACbN/usr/lib/perl5/File/Path.pm line 6.
```

I've compared it with the [previous AppImage version](https://github.com/linuxhw/hw-probe/releases/download/1.4/hw-probe-1.4-141-x86_64.AppImage) by diffing extracted contents and seems nothing changed in *.so or *.pm files. So probably something is changed in the AppImage format itself.

How to fix or workaround this?

Thanks.

**Comment by linuxhw** [comment]
Seems that `usr/bin` internal directory has been disappeared from the search paths of `AppRun` executable for some reason.

**Comment by linuxhw** [comment]
@probonopd 

Could you please look?

**Comment by probonopd** [comment]
I am getting:

```
me@host:~$ /home/me/Downloads/hw-probe-0-Build144.1.glibc2.17-x86_64.AppImage 
Can't load '/tmp/.mount_hw-proh9F1iI/usr/lib/perl5/auto/Cwd/Cwd.so' for module Cwd: /tmp/.mount_hw-proh9F1iI/usr/lib/perl5/auto/Cwd/Cwd.so: undefined symbol: PL_stack_sp at /tmp/.mount_hw-proh9F1iI/usr/lib/perl5/XSLoader.pm line 93.
 at /tmp/.mount_hw-proh9F1iI/usr/lib/perl5/Cwd.pm line 82.
Compilation failed in require at /tmp/.mount_hw-proh9F1iI/usr/lib/perl5/File/Path.pm line 6.
BEGIN failed--compilation aborted at /tmp/.mount_hw-proh9F1iI/usr/lib/perl5/File/Path.pm line 6.
Compilation failed in require at /tmp/.mount_hw-proh9F1iI/usr/bin//hw-probe line 75.
BEGIN failed--compilation aborted at /tmp/.mount_hw-proh9F1iI/usr/bin//hw-probe line 75.
```

This shows that `usr/bin//hw-probe` is being executed, which means that `usr/bin` is definitely on the `$PATH`.

The problem is `undefined symbol: PL_stack_sp`.

The shebang in your main executable makes the system Perl be loaded, rather the one in the AppImage. By using `#!/usr/bin/env perl` you can make it use the one inside the AppImage.

**Comment by linuxhw** [comment]
Thanks a lot!
