### ISSUE TITLE
Wiki page is empty

### ISSUE THREAD

**Issue by Symbian9** [AppImage/AppImageKit#1024]
According to website link to "WIKI"...

![pic.1](https://i.imgur.com/zDrNbsd.jpg)

... I redirected to:

- https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

BUT this page is empty!

**Comment by probonopd** [comment]
@TheAssassin I quick-"fixed" it by editing the wiki page, but maybe you can do a cleaner solution by linking the html to the docs properly. Thanks

**Comment by TheAssassin** [comment]
Done.
