### ISSUE TITLE
Call AppImage via AppImage?

### ISSUE THREAD

**Issue by MrMontag** [AppImage/AppImageKit#1028]
I have two simple AppImages (A and B), which can run on their own without any issues. The AppImage A can also call AppImage B. If A does this I always get the message shown below.

![message](https://user-images.githubusercontent.com/10455184/73183666-7de05e00-411b-11ea-90a9-bd81fdff2de4.png)

Is it possible to call B via A without using `--appimage-extract`?

**Comment by probonopd** [comment]
How exactly does your AppImage A call AppImage B?

Maybe the easiest solution would be to make one AppImage that contains both A and B. This would also be more in line with the philosophy that an AppImage shall have no dependencies other than the base system (distribution).

**Comment by MrMontag** [comment]
I use QProcess to call the AppImage. For me it look like a FUSE related thing... but I don't have much background knowledge about it.

```cpp
QProcess app; // class member in original code

app.setProgram("b.appimage");
app.setWorkingDirectory("some/dir");
app.start();
```

**Comment by TheAssassin** [comment]
Please provide more details about your system. Have you been able to reproduce this on other systems?

**Comment by MrMontag** [comment]
The test systems are Ubuntu 18.04 LTS and openSUSE Leap. The error occurs on both systems. A is build on Ubuntu 16.04, uses Qt 5.12.6 and is created via linuxdeployqt release 6. The AppImage B is created on Ubuntu 18.04 and is an Electron app.

**Comment by MrMontag** [comment]
So far I can tell that it is **not** a general issue. Using a test app (https://github.com/MrMontag/appimage-via-appimage) to call other AppImages works without any issues.

If I go for a more complex one, like [GAMS Studio](https://github.com/GAMS-dev/studio/releases) I get the message below. In this case GAMS Studio is used to call another AppImage. The issues occurs on Ubuntu 18.04, Fedora 31 and openSUSE Leap.

```
fusermount: old style mounting not supported

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```
In addition to this I have the following error before the aforementioned message on Ubuntu 18.04.

`ERROR: ld.so: object '/tmp/.mount_studioSuefMC/usr/optional/exec.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored 10m 35s 3m 18s`

Resetting `LD_PRELOAD` as well as `LD_LIBRARY_PATH` does not change the outcome.

**Comment by probonopd** [comment]
What I can tell from experience is that you can put an AppImage inside another AppImage (e.g., in `usr/bin/`) and exec that. (Whether that is a good idea is another question.)

`wrong ELF class: ELFCLASS64` sounds like there are either multiple architectures inside the AppImage(s) or _something_ doesn't like the magic bytes we are inserting into AppImage headers (could that be the cause @TheAssassin?).

**Comment by MrMontag** [comment]
Thanks for your reply.

The issues has been found. As soon as I use the changes below calling an AppImage will fail. As soon as this section gets removed from my other projects (initial test app and GAMS Studio) everything works fine. 

https://github.com/MrMontag/appimage-via-appimage/commit/f70e932edef70f692245402d8c548321fb3d6bb0?diff=unified

**Comment by TheAssassin** [comment]
There is more than just one reason I don't like this ABI hack. Thanks for providing the actual breakage, will be useful in the future.

**Comment by probonopd** [comment]
Thanks for investigating @MrMontag. It's better to build on an older build system so that you won't need "this ABI hack" in the first place.
