### ISSUE TITLE
rename the the output image

### ISSUE THREAD

**Issue by skinnyMan** [AppImage/AppImageKit#1029]
is there a way to rename the output image? it seems that when we rename the output image our icons seem to dissappear...

**Comment by probonopd** [comment]
With "output image" you man the AppImage created by `appimagetool`? You can rename it and it should still work, but we generally don't recommend it since there is a default naming scheme for a reason - consistency. What don't you like about the default name?

**Comment by skinnyMan** [comment]
Hi @probonopd - thanks for the quick response.
well i figure if I create an app called 'calculator' and i package it up and distribute it, I'd want the executable to be named 'calculator,' and not 'calculator.appimage'

**Comment by probonopd** [comment]
Ideally, it is called `calculator-1.0-x86_64.AppImage`:

* `calculator` - the name of your application
* `1.0` - the version of your application
* `x86_64` - the architecture, this is important information
* `.AppImage` - the file format, like `.exe` for Windows. Without this no one knows what to do with the file

So while you are free to rename your AppImage as you like, I really recommend to stick to the standard naming scheme above.
