### ISSUE TITLE
default cmake version 3.5.1 ,can't compile in ubuntu1604.

### ISSUE THREAD

**Issue by lmq3342xja** [AppImage/AppImageKit#1030]
xiaoyi@xiaoyi-admin:~/appimage/AppImageKit$ ./build.sh 
68b329da9893e34099c7d8ad5cb9c940  -
+++ readlink -f ./build.sh
++ dirname /home/kylin/appimage/AppImageKit/build.sh
+ HERE=/home/kylin/appimage/AppImageKit
+ cd /home/kylin/appimage/AppImageKit
+ git submodule update --init --recursive
+ '[' -d build/ ']'
+ rm -rf build/
+ mkdir build
+ cd build
+ export PKG_CONFIG_PATH=/deps/lib/pkgconfig/
+ PKG_CONFIG_PATH=/deps/lib/pkgconfig/
+ '[' '' == armhf ']'
+ '[' '' == aarch64 ']'
+ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=ON -DAPPIMAGEKIT_PACKAGE_DEBS=ON
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for program aclocal
-- Found program aclocal: /usr/bin/aclocal
-- Checking for program autoheader
-- Found program autoheader: /usr/bin/autoheader
-- Checking for program automake
-- Found program automake: /usr/bin/automake
-- Checking for program autoreconf
-- Found program autoreconf: /usr/bin/autoreconf
-- Checking for program libtoolize
-- Found program libtoolize: /usr/bin/libtoolize
-- Checking for program patch
-- Found program patch: /usr/bin/patch
-- Checking for program sed
-- Found program sed: /bin/sed
-- Checking for program wget
-- Found program wget: /usr/bin/wget
-- Checking for program xxd
-- Found program xxd: /usr/bin/xxd
-- Checking for program desktop-file-validate
-- Found program desktop-file-validate: /usr/bin/desktop-file-validate
-- Checking for program objcopy
-- Found program objcopy: /usr/bin/objcopy
-- Checking for program objdump
-- Found program objdump: /usr/bin/objdump
-- Checking for program readelf
-- Found program readelf: /usr/bin/readelf
-- Checking for program strip
-- Found program strip: /usr/bin/strip
-- Checking for program make
-- Found program make: /usr/bin/make
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Importing target libglib via pkg-config (glib-2.0>=2.40, shared)
-- Checking for module 'glib-2.0>=2.40'
--   Found glib-2.0, version 2.48.2
-- Importing target libgobject via pkg-config (gobject-2.0>=2.40, shared)
-- Checking for module 'gobject-2.0>=2.40'
--   Found gobject-2.0, version 2.48.2
-- Importing target libgio via pkg-config (gio-2.0>=2.40, shared)
-- Checking for module 'gio-2.0>=2.40'
--   Found gio-2.0, version 2.48.2
-- Importing target libzlib via pkg-config (zlib, shared)
-- Checking for module 'zlib'
--   Found zlib, version 1.2.8
-- Importing target libcairo via pkg-config (cairo, shared)
-- Checking for module 'cairo'
--   Found cairo, version 1.14.6
-- Downloading and building xz
-- Downloading and building squashfuse
-- Downloading and building libarchive
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for modules 'glib-2.0>=2.40;IMPORTED_TARGET'
--   No package 'IMPORTED_TARGET' found
-- Checking for modules 'gobject-2.0>=2.40;IMPORTED_TARGET'
--   No package 'IMPORTED_TARGET' found
-- Checking for modules 'gio-2.0>=2.40;IMPORTED_TARGET'
--   No package 'IMPORTED_TARGET' found
-- Checking for modules 'zlib;IMPORTED_TARGET'
--   No package 'IMPORTED_TARGET' found
-- Checking for modules 'cairo;IMPORTED_TARGET'
--   No package 'IMPORTED_TARGET' found
-- Checking for program aclocal
-- Found program aclocal: /usr/bin/aclocal
-- Checking for program autoheader
-- Found program autoheader: /usr/bin/autoheader
-- Checking for program automake
-- Found program automake: /usr/bin/automake
-- Checking for program autoreconf
-- Found program autoreconf: /usr/bin/autoreconf
-- Checking for program libtoolize
-- Found program libtoolize: /usr/bin/libtoolize
-- Checking for program patch
-- Found program patch: /usr/bin/patch
-- Checking for program sed
-- Found program sed: /bin/sed
-- Checking for program wget
-- Found program wget: /usr/bin/wget
-- Checking for program xxd
-- Found program xxd: /usr/bin/xxd
-- Checking for program desktop-file-validate
-- Found program desktop-file-validate: /usr/bin/desktop-file-validate
-- Checking for program objcopy
-- Found program objcopy: /usr/bin/objcopy
-- Checking for program objdump
-- Found program objdump: /usr/bin/objdump
-- Checking for program readelf
-- Found program readelf: /usr/bin/readelf
-- Checking for program strip
-- Found program strip: /usr/bin/strip
-- Checking for program make
-- Found program make: /usr/bin/make
-- Importing target libfuse via pkg-config (fuse, shared)
-- Checking for module 'fuse'
--   Found fuse, version 2.9.4
-- Importing target libssl via pkg-config (openssl, shared)
-- Checking for module 'openssl'
--   Found openssl, version 1.0.2g
-- Release build, optimizing runtime
CMake Warning at src/build-runtime.cmake:118 (message):
  CMake version < 3.13, falling back to using target_link_libraries instead
  of target_link_options
Call Stack (most recent call first):
  src/CMakeLists.txt:16 (include)

-- Installing auxiliary files in path: lib/appimagekit
CMake Error at src/CMakeLists.txt:150 (install):
  install TARGETS given unknown argument "EXCLUDE_FROM_ALL".

CMake Error at src/CMakeLists.txt:155 (install):
  install FILES given unknown argument "EXCLUDE_FROM_ALL".

CMake Error at src/CMakeLists.txt:156 (install):
  install FILES given unknown argument "EXCLUDE_FROM_ALL".

CMake Error at src/CMakeLists.txt:157 (install):
  install FILES given unknown argument "EXCLUDE_FROM_ALL".

CMake Error at cmake/cpack_debs.cmake:2 (cmake_minimum_required):
  CMake 3.6 or higher is required.  You are running version 3.5.1
Call Stack (most recent call first):
  CMakeLists.txt:90 (include)

-- Configuring incomplete, errors occurred!
See also "/home/kylin/appimage/AppImageKit/build/CMakeFiles/CMakeOutput.log".
See also "/home/kylin/appimage/AppImageKit/build/CMakeFiles/CMakeError.log".

**Comment by lmq3342xja** [comment]
http://old-releases.ubuntu.com/ubuntu/pool/main/c/cmake/
update cmake 3.7.2 is ok

**Comment by TheAssassin** [comment]
You can always use our official AppImages. Also, you can compile CMake yourself, we do that, too. And there's the option to use the prebuilt binaries from https://cmake.org.

**Comment by lmq3342xja** [comment]
thanks
