### ISSUE TITLE
AppImage for console applications

### ISSUE THREAD

**Issue by silvioprog** [AppImage/AppImageKit#1031]
Hi.

As a command line tool (CLI), my application doesn't contains an icon/.desktop (shortcut), and the user interacts with it only via terminal. However, I would like to distribute my application as an AppImage because it resolves a lot of dependencies into a single executable file, making it easy to be downloaded from some download page.

So, is there alternative to make AppImage for those kind of applications?

TIA for any help!

**Comment by probonopd** [comment]
You can make an AppImage just like for any other application, the only difference is that you need to set `Terminal=true` in the desktop file.

You will still need to include an icon file, this is used e.g., in app stores, app centers, as a file icon, etc.
