### ISSUE TITLE
How to make application paths relative in AppImage?

### ISSUE THREAD

**Issue by cecilios** [AppImage/AppImageKit#1035]
I'm attempting to create my first AppImage package for my application (c++). I built it without errors but when run it the program fails to locate the needed resources.

After some research (e.g. AppImage/AppImageKit#508 and AppImage/AppImageKit#172) I understand that my problem is caused because my app is trying to load some resources from an absolute path (e.g. _/usr/share/xxxxx_) and AppImage requires that all paths must be relative to the AppImage executable.

For instance, in AppImage/AppImageKit#508 it is suggested to use `getcwd()` and in AppImage/AppImageKit#172 they point to using `$APPIMAGE`.

But IMO, using `getcwd()` is not the solution as the value provided by `getcwd()` points to the directory in which the app was started, and not to the folder in which the app is installed. So it does not work when the user runs the appimage by mouse click on symlinks.

In Linux I've not found a simple way of determining the app installation path at run time (see for example https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe).

So, my options are reduced to using `$APPIMAGE` but I don't know how to use it: 
- Is it always accessible with `getenv("APPIMAGE")` when running the appimage file and it always points to the folder in which the appimage file is located? Even when the appimage is run by clicking on a symlink?
- My app must work also in normal installation packages so the solution must detect when it is running in an appimage and when it is a 'native' running.

How is this solved in other programs? Any help and code examples will be especially welcome. Thank you!

**Comment by TheAssassin** [comment]
Please see https://github.com/linuxdeploy/linuxdeploy/issues/123, where exactly this has been discussed not even one hour ago. `getcwd()` does not work at all, `$APPIMAGE` is not portable, your best bet is to use `/proc/self/exe`, which works fine in many applications.

**Comment by cecilios** [comment]
Thanks! I moved the issue here as I though it was the right place and was not getting feedback in https://github.com/linuxdeploy/linuxdeploy/issues/123. Didn't know they were repos from the same team and didn't see your answer. Thanks and sorry for the noise.

**Comment by TheAssassin** [comment]
Shame on me for not recognizing the same user name... happens very rarely to me. 

Please feel free to join our IRC chat, too (#appimage on Freenode), where you can get in touch with lots of other AppImage authors.

**Comment by probonopd** [comment]
Do you want to get the path in which the AppImage is located, or do you want to get the path to your executable inside the AppImage?

**Comment by cecilios** [comment]
I need the path to the resorces packaged inside my AppImage. So I unsderstand that I first need to get the path to my executable inside the AppImage, and then find any other resorce path relative to the root of the binary. Is this the correct approach?

**Comment by TheAssassin** [comment]
Yep. That's perfectly portable, works both in AppImages (which have to be relocatable) and "regular" installations (where a prefix might be known). Qt for instance also recommends this approach, and they provide a proper API for that.

**Comment by cecilios** [comment]
In my app I use a prefix but now I have to use it when it is a "regular" run and replace it when it is an "appimage" run. But need to identify at run time the case and need to replace the prefix by something:  `$APPIMAGE`? `/proc/self/exe`? other?

**Comment by TheAssassin** [comment]
`$APPIMAGE` is, again, not portable, only works for AppImages. You don't need to rely on that.

If your application is usually in `/usr/bin/myapp` and your resources are in e.g., `/usr/share/myapp`, you can also express it as `/usr/bin/../share/myapp`, right? So, basically, resolve the symlink `/proc/self/exe`, get its `dirname`, then append `../share/myapp` and you're all set. Again, this approach works fine for AppImage and also for your regularly installed application.

**Comment by cecilios** [comment]
> If your application is usually in /usr/bin/myapp and your resources are in e.g., /usr/share/myapp, you can also express it as /usr/bin/../share/myapp, right?

Yes, that's my case. I will try your suggestion of using /proc/self/exe.

Thanks!!
