### ISSUE TITLE
Failed to register

### ISSUE THREAD

**Issue by QQ-88** [AppImage/AppImageKit#1038]
I am trying to install [Tandem](https://tandem.chat/) but get the following [error](https://i.imgur.com/kg89Tno.png).

Other image files (before and afterwards trying this)  work without problems.
Any idea what's the issue?

**Comment by probonopd** [comment]
That error is coming from AppImageLauncher, closing here. Discussion continues in https://github.com/TheAssassin/AppImageLauncher/issues/315.

**Comment by probonopd** [comment]
Duplicate of https://github.com/AppImage/AppImageKit/issues/1037, too.

**Comment by TheAssassin** [comment]
@probonopd actually, no, it's coming from libappimage. But we'll continue over at my repo.
