### ISSUE TITLE
Appimage dont start on debian

### ISSUE THREAD

**Issue by koreanfan** [AppImage/AppImageKit#1039]
Hello. I download appimage from "https://restream.io/chat". I made this file executable and launch, but application wont start. Here output terminal:
"$ ./Restream+Chat-2.5.4-beta.AppImage[13108:0405/030554.822091:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_RestrewA6Bfo/chrome-sandbox is owned by root and has mode 4755.Ловушка трассировки/останова"
This app dont launch on debian bullseye and buster. I try this app on manjaro, ubuntu and this appimage works on this distro. Can you help me?

**Comment by probonopd** [comment]
Please ask https://restream.io to provide a fixed AppImage (they need to invoke their application from `AppRun` with `--no-sandbox`).

https://lmgtfy.com/?q=appimage+setuid_sandbox_host.cc

In the meantime, you can do:

`sudo sysctl kernel.unprivileged_userns_clone=1 ` on your system.

**Comment by TheAssassin** [comment]
It's not *really* a solution to entirely disable sandboxing...

**Comment by probonopd** [comment]
The right thing to do would probably be to have a check in AppRun whether `sudo sysctl kernel.unprivileged_userns_clone=1` set and if it is not, then print a clear warning on the command line and add the `--no-sandbox` parameter.

Assuming that Debian won't change their configuration and Google won't change their sandbox, this is the only practical solution I can think of. Wdyt @TheAssassin?

**Comment by koreanfan** [comment]
I think sudo sysctl kernel.unprivileged_userns_clone=1 its not good for system security

**Comment by TheAssassin** [comment]
> Assuming that Debian won't change their configuration and Google won't change their sandbox, this is the only practical solution I can think of. Wdyt @TheAssassin?

Disabling the sandbox is a bad idea. I am not sure what consequences your kernel setting has either. @koreanfan please provide any credible resources if you think it's a security hazard.

The *best* solution in my opinion is to keep this web javascript stuff out of desktop applications and in the browsers, where sandboxing etc. can be done properly... but that's not really practicable either, is it?

You should perhaps talk to these Electron folks about the problem. `suid` binaries can never be created/set up on a system without root permissions anyway (not to mention I don't want to download `suid` binaries from random sources on the Internet anyway!), so these user namespaces seem like a viable solution. They can't be too harmful, otherwise some distributions would not have enabled those, I presume. Maybe Debian simply has to move on to the future.

**Comment by probonopd** [comment]
> I think sudo sysctl kernel.unprivileged_userns_clone=1 its not good for system security

@koreanfan do you have more details? I would like to learn more about it. Thank you.

**Comment by probonopd** [comment]
This is how I had dealt with this annoying [Electron/Debian/AppImage issue](https://github.com/AppImage/AppImageKit/issues/1039) in another project:

https://github.com/probonopd/nativefier-test/blob/e38bc4b39def3c27046de512e24a220bb9c3ced2/nativefier.bash#L41-L52

I'd be happy to hear whether there are better solutions.

**Comment by koreanfan** [comment]
Maybe Linus Torvalds know how to fix it

**Comment by probonopd** [comment]
Well I am not Linus Torvalds but I know this too.
Configure the kernel like this: ` sysctl kernel.unprivileged_userns_clone=1 `

**Comment by TheAssassin** [comment]
You need to add `-w`, too. To make it persistent, please edit `/etc/sysctl.conf` and append:

```
kernel.unprivileged_userns_clone=1

**Comment by TheAssassin** [comment]
I'm writing a docs page right now, where also all FUSE related content will go now. This command will be included. @probonopd do you have any external references I can cite? It's a more or less invasive change, and I don't want to express any form of responsibility. We have not come up with this in the first place anyway.

**Comment by TheAssassin** [comment]
Please see https://docs.appimage.org/user-guide/troubleshooting.html#i-have-issues-with-electron-based-appimages-and-their-sandboxing.

**Comment by TheAssassin** [comment]
I think we can close this question.

**Comment by probonopd** [comment]
Thanks @TheAssassin for your very detailed writeup.
