### ISSUE TITLE
AppImages can't handle relative paths in arguments

### ISSUE THREAD

**Issue by bdantas** [AppImage/AppImageKit#1045]
I use several AppImages at the command line. A pain point has always been that if an argument to the AppImage is a file or directory name, then an absolute path must be used:
```
bruno@box:~$ WonderfulApplication.AppImage foo.txt
file not found
bruno@box:~$ WonderfulApplication.AppImage ./foo.txt
file not found
bruno@box:~$ WonderfulApplication.AppImage /home/bruno/foo.txt
it works
```
Ideally, before cd'ing to `/tmp/.mount_fooXXXX/usr` the runtime or AppRun should convert file and directory arguments to quoted absolute paths, so that the files and directories can still be found after the AppImage changes its working directory.

**Comment by bdantas** [comment]
While this is an issue, I've developed workarounds.

**Workaround for binary AppRun:**
Rename the AppRun `AppRun-real` and create a "wrapper" `AppRun` that converts file and directory arguments to absolute paths within double quotes, while leaving other arguments alone:

```
#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

# convert file and dir arguments to absolute paths
NEWARGS=""
for arg in "$@"; do
	if ([ -f "$arg" ] || [ -d "$arg" ]); then
		newarg="$(readlink -f "$arg")"
		NEWARGS="$NEWARGS \"$newarg\"" 
	else
		NEWARGS="$NEWARGS $arg" 
	fi
done

eval exec $HERE/AppRun-real $NEWARGS
```
**Workaound for shell script AppRun:**
Edit `AppRun` so that it looks something like this, for example: 
```
#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="$HERE/usr/lib"
export PATH="$HERE/usr/bin:$PATH"

# convert file and dir arguments to absolute paths before cd'ing
NEWARGS=""
for arg in "$@"; do
	if ([ -f "$arg" ] || [ -d "$arg" ]); then
		newarg="$(readlink -f "$arg")"
		NEWARGS="$NEWARGS \"$newarg\"" 
	else
		NEWARGS="$NEWARGS $arg" 
	fi
done

cd "$HERE/usr"
eval exec foobar $NEWARGS
```

**Comment by probonopd** [comment]
Or just use your custom `AppRun` script or symlink, and not need any of those workarounds.

**Comment by TheAssassin** [comment]
Just for the record: if anyone ever finds AppImages behaving like that, please file a bug report, especially if those AppImages are supposed to take paths as commandline arguments.

**Comment by bdantas** [comment]
So it seems it's the AppImage's creator to make sure that their AppRun does the appropriate thing. Fair enough.

> Just for the record: if anyone ever finds AppImages behaving like that, please file a bug report, especially if those AppImages are supposed to take paths as commandline arguments.
Will do.

Happy hacking!
