### ISSUE TITLE
armhf not present in latest "continuous" release

### ISSUE THREAD

**Issue by tommag** [AppImage/AppImageKit#1049]
Hello, 
Is there a reason for the armhf runtime and executables not to be present in https://github.com/AppImage/AppImageKit/releases/tag/continuous ? 
I'll stick with the latest stable release for now :)
Thanks !

**Comment by probonopd** [comment]
Thanks @tommag. I have restarted the armhf build job, hopefully this will fix it.
https://travis-ci.org/github/AppImage/AppImageKit/jobs/684610520

**Comment by TheAssassin** [comment]
The joy of Travis CI, or CI-you-don't-host-yourself in general. I've restarted the build once again.

**Comment by TheAssassin** [comment]
Worked now. Binaries are available again. Thanks for notifying us.
