### ISSUE TITLE
How to reach folder inside Appimage from program?

### ISSUE THREAD

**Issue by MyraBaba** [AppImage/AppImageKit#1052]
Hi,

I created Appimage succesfully. I put some binary file in lib folder to be included in the Appimage.

How can I reach these binary files from from my program ?  when I said :

lib/cassadasd

it says not found.

**Comment by azubieta** [comment]
The AppImage runtime sets the APPDIR environment variable at startup, therefore you can read this variable from your application. If the file is a shared library (.so) you should place it next to the others. The AppImage creation tools can assist you on this. If you are already using one please let us know.

If you're building your bundle manually please consider using:
- https://appimage-builder.readthedocs.io/
- https://github.com/linuxdeploy/linuxdeploy

**Comment by MyraBaba** [comment]
Thanks,

I just figured it yesterday with readin the environment variables from inside program.

Best

**Comment by probonopd** [comment]
Please note: When you unpack an AppImage using --appimage-extract, `$APPDIR` will not be set; hence it is more robust to figure out the path using e.g., something like https://stackoverflow.com/questions/5525668/how-to-implement-readlink-to-find-the-path.
