### ISSUE TITLE
Continuous build AppRun-x86_64 404 Not Found

### ISSUE THREAD

**Issue by SwagDevOps** [AppImage/AppImageKit#1060]
```
+ '[' -z '' ']'
+ get_apprun
+ TARGET_ARCH=x86_64
+ wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 -O AppRun
--2020-07-07 23:10:49--  https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-07 23:10:50 ERROR 404: Not Found.
```

Using ``pkg2appimage`` (``master``).
URL: https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64

**Comment by prabhu** [comment]
May be something with GitHub again?

**Comment by prabhu** [comment]
As a workaround, use wget to download the previous version and copy it to `appimage-builder-cache/` directory

**Comment by SwagDevOps** [comment]
Or, here : https://github.com/AppImage/AppImageKit/releases/tag/continuous
the following assets are missing : 

* ``AppRun-amd64``
* ``appimagetool-amd64``

(at least, as seen in ``functions.sh``)… I guess...

**Comment by PanderMusubi** [comment]
`appimagetool-amd64` is no longer there. Also running into these new issues:

    Traceback (most recent call last):
      File "/usr/local/bin/appimage-builder", line 18, in <module>
        __main__();
      File "/usr/local/lib/python3.8/dist-packages/AppImageBuilder/__main__.py", line 63, in __main__
        builder.build()
      File "/usr/local/lib/python3.8/dist-packages/AppImageBuilder/app_dir/builder.py", line 68, in build
        self._generate_runtime()
      File "/usr/local/lib/python3.8/dist-packages/AppImageBuilder/app_dir/builder.py", line 90, in _generate_runtime
        runtime.generate()
      File "/usr/local/lib/python3.8/dist-packages/AppImageBuilder/app_dir/runtimes/wrapper/runtime.py", line 44, in generate
        app_run.deploy()
      File "/usr/local/lib/python3.8/dist-packages/AppImageBuilder/app_dir/runtimes/wrapper/app_run.py", line 57, in deploy
        shutil.copy(wrapper_path, os.path.join(self.app_dir, lib_paths[0], "libapprun_hooks.so"))
      File "/usr/lib/python3.8/shutil.py", line 415, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/USERNAME/WORKSPACE/PROJECT/appimage/AppDir/usr/local/lib/x86_64-linux-gnu/libapprun_hooks.so'

These files are now in `AppDir/usr/lib`

**Comment by prabhu** [comment]
Yes, hardcoded in appimage-builder

This is how I'm handling this error - https://github.com/ShiftLeftSecurity/sast-scan/blob/master/.github/workflows/appimage.yml#L19

**Comment by Optiligence** [comment]
the release process seems to have failed to complete successfully
https://travis-ci.org/github/AppImage/AppImageKit/jobs/705943662#L4167-L4181
vs
https://travis-ci.org/github/AppImage/AppImageKit/jobs/697268374#L4031-L4210

**Comment by Optiligence** [comment]
at least `appimagetool-x86_64.AppImage` was added again today

**Comment by TheAssassin** [comment]
I've had to manually re-run some jobs, and have them recreate the release. There's more than one potential race condition in this uploadtool we use, which have never been fixed. Now, all binaries are up again.

When I merge PRs, I usually monitor the builds and make sure everything's been uploaded again. But I hadn't merged the last one. @probonopd please remember to check whether uploading worked next time, thanks.

**Comment by yunusem** [comment]
@TheAssassin This one still persist about giving 404 : 
https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
FYI

**Comment by TheAssassin** [comment]
Damn. I'll re-run that job again.

**Comment by TheAssassin** [comment]
Fixed. Thanks for notifying us.

**Comment by shoogle** [comment]
Thanks for fixing! Perhaps there could be a test that looks to see if all the expected files are available before deleting the old version or publishing a new release?
