### ISSUE TITLE
[feature request] App's files.

### ISSUE THREAD

**Issue by mnini** [AppImage/AppImageKit#1061]
App could be packed in a way, that if it it uses some kind of it's own document directory, you should be able to pick it. Or store it on OS virtually mounted as compressed file, if it's not big.

**Comment by shoogle** [comment]
It's tricky to do this given that you wouldn't want to have to repack the whole squashFS archive every time you run it. One possibility would be to structure the AppImage as follows:

```
   MyApp.AppImage
+------------------+
|      Runtime     |
|   (ELF binary)   |
+------------------+
|                  |
|    Application   |
| (squashfs image) |
|                  |
+------------------+
|     Documents    |
|   (zip archive)  |
+------------------+
```

Here the documents are stored in a Zip (or tar, or whatever) archive that is appended to the AppImage in much the same way that the SquashFS image is appended to the runtime binary. When the application is run, the SquashFS part of the archive is mounted as normal, but the documents are extracted to a temporary directory, the location of which is passed to the application as `$HOME` (see [portable mode](https://docs.appimage.org/user-guide/portable-mode.html)). This temporary directory would get recompressed when the application exits, and it would replace the existing archive at the end of the AppImage.

Alternatively, the SquashFS image could even be stored within the Zip archive as an uncompressed file:

```
   MyApp.AppImage
+------------------+
|      Runtime     |
|   (ELF binary)   |
+------------------+
|    Zip Archive   |
++----------------++
||                ||
||   Application  ||
||(squashfs image)||
||                ||
|+----------------+|
||    Documents   ||
|+----------------+|
+------------------+
```

**Comment by probonopd** [comment]
By design, we want AppImage files to be read-only and immutable so that their integrity can easily be checked at any time. For storing data, there is https://github.com/AppImage/AppImageKit/#special-directories.
