### ISSUE TITLE
[Question] how to use zsync with continuous build

### ISSUE THREAD

**Issue by silverhikari** [AppImage/AppImageKit#1062]
when i try to use zsync with the continuous build i get this 
$ failed on url https://github.com/AppImage/zsync2/releases/download/continuous/zsync2-156-10e85c0-x86_64.AppImage.zsync 
$ could not read control file from URL https://github.com/AppImage/zsync2/releases/download/continuous/zsync2-156-10e85c0-x86_64.AppImage.zsync

am i using the wrong url or using zsync the wrong way?

**Comment by probonopd** [comment]
> am i using the wrong url or using zsync the wrong way?

Hi @silverhikari please post the exact command you were trying.

**Comment by silverhikari** [comment]
the command i am typing is this "zsync https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage.zsync"

**Comment by TheAssassin** [comment]
@silverhikari zsync doesn't work because it doesn't support HTTPS at all. Try https://github.com/AppImage/zsync2.

In general, you should be using https://github.com/AppImage/AppImageUpdate, though.

**Comment by silverhikari** [comment]
thank you, i had not known that zsync doesn't support HTTPS
