### ISSUE TITLE
--appimage-extract fails after rebuilding AppImage

### ISSUE THREAD

**Issue by gcascio** [AppImage/AppImageKit#1064]
I am building an Appimage `my.AppImage` with electron-builder. Due to a needed feature I have to patch the desktop file of the AppImage, therefore I extract it with `my.AppImage --appimage-extract`, patch the desktop file in the `squashfs-root` folder and pack the folder back to an AppImage with `appImageTool -n --comp xz squashfs-root my.AppImage`. So far his works fine.
If I make some changes to my source files and rebuild the AppImage the extraction stops working and I get
```
Something went wrong trying to read the squashfs image.
Failed to open squashfs image
```

Now if I rename the file (for exaple to `my_renamed.AppImage`) the extraction works again.

I couldn't find a solution for this and wonder what I am missing here?

**Comment by probonopd** [comment]
Sounds mysterious, I can't quite follow what is going on. Can you post a link to the AppImage in question and the _exact_ steps you are doing (copy and paste from the terminal window) please.

**Comment by gcascio** [comment]
Another weird effect is, that if I copy the AppImage into another directory the extraction works.

A minimal [example](https://github.com/gcascio/electron-custom-url-workaround) of my project also works without problems. I just tested it on a other machine and there it works without a flaw. So I guess this is some local problem of my current setup which is not worth fixing at the moment. If I stumble across this issue again I will continue investigating.
Thank you for your time @probonopd, I thought this might be related to some cache effect which could be pointed out to me.

**Comment by probonopd** [comment]
Thanks @gcascio - feel free to reopen the issue if you can reproduce the problem on another machine.
