### ISSUE TITLE
"Download as AppImage" banner for GitHub README

### ISSUE THREAD

**Issue by KhushrajRathod** [AppImage/AppImageKit#1065]
Hi, I was wondering if there's a "Download as AppImage" banner that I could use in my GitHub README. Something like e.g. the Snap Store banner:

<a href="#">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

I'm not sure if this is the correct place to ask about this, so I'm sorry if I got it wrong.
Thanks :)

**Comment by KhushrajRathod** [comment]
Hi, so since I was unable to find a banner, I've created one myself :)  
![Download as AppImage](https://raw.githubusercontent.com/KhushrajRathod/TeleDrive/main/icon/vector/download-appimage.svg)
If anyone wants to use it, feel free to, it's
![CC0](https://licensebuttons.net/p/zero/1.0/88x31.png)

**Comment by probonopd** [comment]
Cool :+1: 

If you want it more official looking, the font we are using for AppImage is Montserrat Bold designed by Julieta Ulanovsky:
https://www.fontsquirrel.com/fonts/montserrat

**Comment by KhushrajRathod** [comment]
Hi,
Here's the one with Montserrat Bold:

![Appimage-Montserrat](https://raw.githubusercontent.com/KhushrajRathod/KhushrajRathod/master/download-appimage.svg)

**Comment by probonopd** [comment]
Thank you very much @KhushrajRathod

**Comment by KhushrajRathod** [comment]
Sure :)

**Comment by probonopd** [comment]
Opened a ticket to get it mentioned in the documentation.
