### ISSUE TITLE
file command is missing but required, please install it

### ISSUE THREAD

**Issue by OrangeCxl** [AppImage/AppImageKit#1066]
When I execute `./appimagetool-x86_64.AppImage --list navicat15-premium-cs.AppImage` in docker,
 it has the following errors:

```
appimagetool, continuous build (commit effcebc), build 2084 built on 2019-05-01 21:02:41 UTC
file command is missing but required, please install it
```

And when I execute `./appimagetool-x86_64.AppImage --list navicat15-premium-cs.AppImage` in Ubuntu 18.04,
 it has the following errors:
```
appimagetool, continuous build (commit effcebc), build 2084 built on 2019-05-01 21:02:41 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
```

The problem vexed me.
I want to know how I can solve them.

**Comment by OrangeCxl** [comment]
Supplement: Them version
```
+ ./appimagetool-x86_64.AppImage --appimage-version
Version: effcebc
```

**Comment by probonopd** [comment]
`sudo apt-get -y install file appstream` should do the trick.

**Comment by OrangeCxl** [comment]
Yeah! It's OK
