### ISSUE TITLE
"Appimagetool-x86_64.AppImage" doesn't run on Manjaro Linux

### ISSUE THREAD

**Issue by CineEncoder** [AppImage/AppImageKit#1069]
Hi, 

I decided to create Appimage using Appimagetool-x86_64, but I ran into the problem that "Appimagetool-x86_64. AppImage" doesn't run on Manjaro Linux.
My project: https://github.com/CineEncoder/cine-encoder
appimage-builder.yml (https://github.com/CineEncoder/cine-encoder/blob/master/appimage-builder.yml)
requirements.txt (https://github.com/CineEncoder/cine-encoder/blob/master/requirements.txt)

**Comment by probonopd** [comment]
Hi, thanks for our interest in AppImage. Please report appimage-builder related issues over at https://github.com/AppImageCrafters/appimage-builder/issues. This project is not about appimage-builder. Thank you for your understanding.

**Comment by CineEncoder** [comment]
I want to use Appimagetool-x86_64,

**Comment by probonopd** [comment]
Please see https://github.com/AppImage/AppImageKit/issues/1070.
