### ISSUE TITLE
Get into hacktoberfest to get new contributors

### ISSUE THREAD

**Issue by antony-jr** [AppImage/AppImageKit#1077]
**CC**: @probonopd 

See https://hacktoberfest.digitalocean.com/

Hacktoberfest can bring some developers to AppImage. Tag easy issues with **hacktoberfest**. More open source attention means more adaptation of AppImages.

**Comment by probonopd** [comment]
Thanks @antony-jr. I've added the hacktoberfest tag to the repo, but do not have the time to go through all the issues to find the easy ones, especially since _easy_ is very subjective a term... what is easy for me might be hard for someone else and vice versa.

**Comment by antony-jr** [comment]
Closing this issue as it is somewhat resolved. I leave it to the maintainers to tag any issues with hacktoberfest.

**Comment by TheAssassin** [comment]
Absolutely against supporting this pseudo-supporting annoyance called "Hacktoberfest". It's hurting the open-source community and should *not* be picked up by projects, especially projects with few resources.

https://blog.domenic.me/hacktoberfest/

**Comment by antony-jr** [comment]
> Absolutely against supporting this pseudo-supporting annoyance called "Hacktoberfest". It's hurting the open-source community and should not be picked up by projects, especially projects with few resources.

> https://blog.domenic.me/hacktoberfest/

Haha, Okay then just forget the idea. Thank you for the link.

**Comment by TheAssassin** [comment]
You're welcome. If it were opt-in and you have the resources to moderate this, you might be willing to participate. But still, most PRs are really just nitpicking spam, e.g., fixing 10 typos in 10 commits/PRs or something like that to generate enough PRs/commits to get some "free" shirt. Actions like these don't ever generate new contributors. Even GSoC doesn't necessarily, but at least they try it the right way.

**Comment by antony-jr** [comment]
> You're welcome. If it were opt-in and you have the resources to moderate this, you might be willing to participate. But still, most PRs are really just nitpicking spam, e.g., fixing 10 typos in 10 commits/PRs or something like that to generate enough PRs/commits to get some "free" shirt. 

I really don't want to teach non-techs how to do PRs and stuff for some free T-Shirt. I really hope AppImage gets more contributors.

**Comment by TheAssassin** [comment]
Me, too. But the best way is to write more documentation that allows newbies to learn the technology, the motivation, concepts, components etc. Both https://docs.appimage.org/ and our in-project docs could be improved there.

**Comment by antony-jr** [comment]
> Me, too. But the best way is to write more documentation that allows newbies to learn the technology, the motivation, concepts, components etc. Both https://docs.appimage.org/ and our in-project docs could be improved there.

Yes the documentation needs a lot of work. If I have time I will send some PR for that.

**Comment by probonopd** [comment]
> It would be interesting to see if it can run a AppImage.

Why not, if you have an aarch64 one. E.g., https://github.com/probonopd/go-appimage/releases/tag/continuous has some.
