### ISSUE TITLE
AppImage.org is down as of 04.11.2020.

### ISSUE THREAD

**Issue by antony-jr** [AppImage/AppImageKit#1082]
Just reporting.

**Comment by srevinsaju** [comment]
iirc, its down since 3 AM UTC ig, as on #appimage

**Comment by antony-jr** [comment]
My speculations are 30 minutes from when I started calculating. :smiley:

**Comment by srevinsaju** [comment]
Oh :sweat_smile: 

cc @TheAssassin 

I guess @azubieta tried contacting TA

**Comment by BrandonTheHamm** [comment]
Is there any other way to get to the appimage documentation other than their website?

**Comment by srevinsaju** [comment]
@BrandonTheHamm take a look at https://github.com/AppImage/docs.appimage.org/blob/master/source/introduction/index.rst and other `*.rst` files

**Comment by srevinsaju** [comment]
@BrandonTheHamm I set up a mirror here: https://www.srevinsaju.me/docs.appimage.org/

**Comment by azubieta** [comment]
Maybe it would be a good idea to also host it using github pages and readthedocs.

**Comment by BrandonTheHamm** [comment]
> @BrandonTheHamm I set up a mirror here: https://srevinsaju.me/docs.appimage.org/

Awesome, thank you

**Comment by srevinsaju** [comment]
@azubieta https://srevinsaju.me/docs.appimage.org/ is on GitHub pages, you can copy the CI https://github.com/srevinsaju/docs.appimage.org/pull/1 which can be used to deploy the docs to GitHub Pages.

**Comment by antony-jr** [comment]
Seems to be fixed.

**Comment by probonopd** [comment]
Thanks @TheAssassin for looking into and resolving this. Maybe we should have a mirror on gh-pages that is available as a fallback?

**Comment by TheAssassin** [comment]
This one minor outage brings the overall uptime to ~99.7% this year. I don't think that's that bad.

**Comment by probonopd** [comment]
Agree :+1:
