### ISSUE TITLE
appimaged does not start after booting

### ISSUE THREAD

**Issue by epassaro** [AppImage/AppImageKit#1088]
This issue has been discussed previously in #259.

A solution was provided [here](https://forums.opensuse.org/showthread.php/538796-How-to-start-appimaged-via-systemd/page2) and consist in editing the file `/usr/lib/systemd/user/appimaged.service`:

```
[Unit]
Description=AppImage daemon
After=basic.target

[Service]
ExecStart=/usr/bin/appimaged
Restart=always
RestartSec=5s
StartLimitInterval=0

[Install]
WantedBy=graphical.target
```

and replace the last line by `WantedBy=default.target`. Then:

```
systemctl --user enable appimaged
systemctl --user start appimaged
systemctl --user status appimaged
```

and reboot.

**Comment by TheAssassin** [comment]
Wrong repository. See https://github.com/AppImage/appimaged.

appimaged has been deprecated and is no longer maintained.
