### ISSUE TITLE
Distribute runtime.c or a link to it inside the AppImage

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#109]
Distribute runtime.c or a link to it inside the AppImage

**Comment by Acharvak** [comment]
This is actually an interesting idea.

You'd also need to include a copy of the GPL though (whichever version applies). And do you think fuseiso.c, isofs.c and md5.c should also be included?

**Comment by probonopd** [comment]
AppImage is under the MIT license.

**Comment by darealshinji** [comment]
Any specific reason why?
You may also want to include elf.h and getsection.h, or you create a copy like this:
``` sh
cat elf.h getsection.h runtime.c | sed 's|^#include "elf.h"|\/\/#include "elf.h"|; s|^#include "getsection.h"|\/\/#include "getsection.h"|' > runtime_new.c
```

**Comment by Sod-Almighty** [comment]
What possible reason could there be to distribute source code inside AppImages?

**Comment by probonopd** [comment]
>  fuseiso.c, isofs.c and md5

they have been removed from the current branch, `master/appimagetool` and are no longer needed for type 2 AppImages.

**Comment by probonopd** [comment]
> What possible reason could there be to distribute source code inside AppImages?

It would make it easier for people to reproduce and create their own AppImages.

**Comment by TheAssassin** [comment]
Even if we included GPL, according to the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowDownloadFee) we just need to provide "equivalent access". If people are supposed to fetch the official builds from GitHub, and can access the relevant GPL code from the code browser next to the releases page, it should be perfectly fine.

That means there's no need to distribute source code, at least not for licensing reasons. Also, the GPL code is no longer included in appimagetool anyway. Thus we can close this issue.
