### ISSUE TITLE
feature: AppImage should provide GUI feedback if the app fails to start

### ISSUE THREAD

**Issue by mihaiav** [AppImage/AppImageKit#1093]
A common case is a library missing. If you run the app from the GUI you get no feedback. You only see the error from the command line. I believe that is bad for the user experience.

**Comment by probonopd** [comment]
How did you launch the application? Can you give more details please?

This is what __should__ happen when the application is launched through the [`launch` command](https://github.com/helloSystem/launch):

![image](https://user-images.githubusercontent.com/2480569/100541995-d99ddb00-3247-11eb-84e6-0919f18a68a9.png)

If this does not happen in some places, then the application probably was not launched through the `launch` command?
