### ISSUE TITLE
zstd / lz4 compression, block size

### ISSUE THREAD

**Issue by mralusw** [AppImage/AppImageKit#1101]
It's not currently possible to tweak `mksquashfs` options, but, more perversely, the AppImage header makes damn sure that only xz/gzip embedded images work. It seems the kind of breakage where the developers had to write code to prevent a simple mount from *just working*.

I've tried hacking around this intentional breakage by calling `--appimage-offset`, then `cat`-ing the header and a recompressed squashfs, but the header checks the compression; since this header is an executable not a script, it can't be easily unbroken.

zstd should be able to achieve better compression. lz4 should be much, much faster, for the development stage. If not supported by default, it should be at least possible to tweak the AppImage more easily by hand.

**Comment by probonopd** [comment]
>  the AppImage header makes damn sure that only xz/gzip embedded images work

How so? The header _mounts_ the thing. So it needs to be _able_ to mount it.

There is a ticket for bringing in zstd support: https://github.com/AppImage/AppImageKit/issues/478
