### ISSUE TITLE
[runtime.c] --appimage-extract <pattern> does not resolve symlinks

### ISSUE THREAD

**Issue by mttbernardini** [AppImage/AppImageKit#1106]
By testing the command on an AppImage with runtime version 8bbf694 I noticed that if `<pattern>` matches a symlink, the extracted file is a broken symlink pointing to content that was not extracted. I don't know if this is intended behavior, but I think it's sensible to expect that extracting a symlink should also extract the pointed file, instead of having a broken link.

If this behavior is intended feel free to close this issue, but I think that at least it should be properly documented in `--appimage-help`.

PS: I didn't check if there's any code relying on `--appimage-extract .DirIcon` to extract the AppImage icon (i.e. for thumbnail generation in `appimaged` or `AppImageLauncher`), but since in most cases `.DirIcon` tends to be a symlink to `appname.png` or `usr/share/icons/hicolor/....`, extracting the icon in this way would be broken due to this issue.

Thank you for your time.

**Comment by KaKi87** [comment]
Hello @probonopd,

Any news on this ?

Also, I'm wondering how the `pattern` argument has documentation, because I can't figure out how to extract files matching multiple extensions (I tried `"*.{foo,bar}"` without success).

Thanks

**Comment by probonopd** [comment]
> By testing the command on an AppImage with runtime version https://github.com/AppImage/AppImageKit/commit/8bbf694455d00f48d835f56afaa1dabcd9178ba6 I noticed that if <pattern> matches a symlink, the extracted file is a broken symlink pointing to content that was not extracted.

Yes, this is what has been implemented so far.

> I don't know if this is intended behavior, but I think it's sensible to expect that extracting a symlink should also extract the pointed file, instead of having a broken link.

While this could be implemented, it would increase code complexity in the AppImage runtime, which is why it hasn't been implemented. You need to look where the dangling symlink points to, and extract that file as well. Or, as a shortcut, just extract the entire AppImage.

**Comment by probonopd** [comment]
> Also, I'm wondering how the pattern argument has documentation, because I can't figure out how to extract files matching multiple extensions (I tried "*.{foo,bar}" without success).

This is not implemented.

**Comment by KaKi87** [comment]
Well, Linux follows symlinks by default, e.g. copying a symlink pastes the linked file, so it would make sence for this command to extract the actual file as well.
