### ISSUE TITLE
Broken Link on wiki

### ISSUE THREAD

**Issue by 04ELY** [AppImage/AppImageKit#1110]
Hi!
In [How do I bundle my application as an AppImage?](https://github.com/AppImage/AppImageKit/wiki#-how-do-i-bundle-my-application-as-an-appimage) section of wiki
there is a link, but it gives this
![image](https://user-images.githubusercontent.com/60751519/104362037-55b45f80-5524-11eb-9598-00a6889f4962.png)
:)

**Comment by srevinsaju** [comment]
@04ELY you may like to use [docs.appimage.org](https://docs.appimage.org)

**Comment by 04ELY** [comment]
> @04ELY you may like to use [docs.appimage.org](https://docs.appimage.org)

I know but it says 
> Deeplinks **must not** break.

So I opened an issue :)

**Comment by probonopd** [comment]
The original text is still linked under the long URL under "but here is the solution" :)
