### ISSUE TITLE
Compile on non-GNU system, possible?

### ISSUE THREAD

**Issue by kyx0r** [AppImage/AppImageKit#1113]
I am running a system with musl C library. I tried to compile this with Cmake but the build requires libtool, which is part of GNU. Can you please get rid of libtool dependency, and also no cmake would be nice too. Thanks.

**Comment by probonopd** [comment]
I would like this to be possible, but no one is working on it so far.

**Comment by kyx0r** [comment]
On 6/28/22, BEEDELLROKEJULIANLOCKHART ***@***.***> wrote:
> Why is this ability advantageous? Surely the fewer dependencies, the more
> custom code to maintain.

There is no less or more in this case.
I don't like when things are all over the place in my room and same
goes for the software. When I compile a program I want the process to
be straight forward. There's objectively no reason to restrict user
freedom.

Kind Regards,
Kyryl

**Comment by probonopd** [comment]
We are building the runtime on Alpine Linux with musl libc now.

The latest https://github.com/AppImage/type2-runtime/releases/tag/continuous build has it.

If you want to try:
https://github.com/AppImage/appimagetool/releases/tag/continuous uses it.

Thanks for retesting.
