### ISSUE TITLE
Misleading architecture string for arm on appimagetool

### ISSUE THREAD

**Issue by azubieta** [AppImage/AppImageKit#1114]
`appimagetool` expects `arm_aarch64` as architecture string for `aarch64` and arm for `armhf`. Is there an special reason for this name changes? From my point of view it's extremely misleading considering that the binaries are published using `aarch64` and `armhf`.

https://github.com/AppImage/AppImageKit/blob/master/src/appimagetool.c#L362

**Comment by probonopd** [comment]
Hi @azubieta I think it is an unintentional bug.

**Comment by adrianinsaval** [comment]
for anyone stumbling upon this use the release from https://github.com/AppImage/appimagetool/releases/tag/continuous instead as it was is fixed there, see https://github.com/AppImage/appimagetool/pull/54
