### ISSUE TITLE
AppImagetool generated by GitHub Actions now shows that it is a 'local build'

### ISSUE THREAD

**Issue by srevinsaju** [AppImage/AppImageKit#1115]
Steps to reproduce:
* Download and `chmod +x` the `continuous` release as of Feb 10, 2021
* `./appimagetool*.AppImage --version` 

Output
```
appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
```

**Comment by TheAssassin** [comment]
CI scripts probably need a minor update to use the env vars exposed by actions to determine some sort of build number. The Travis variables don't work any more. PRs welcome.

**Comment by probonopd** [comment]
Only official builds released by the AppImage projects have something else than "local dev build". This is so that one knows that one is not using an official version. Works as designed.
