### ISSUE TITLE
Non-Optimal handling of AppImage files

### ISSUE THREAD

**Issue by deezznutz** [AppImage/AppImageKit#1117]
If an AppImage file has been "integrated" into the OS and you run it, but the drive where it was "integrated" to is offline, say on a RAID array that failed to mount, then the AppImage file will be deleted.  Not just move to Trash.  Deleted.  For real. Gone.  No questions.  Just gone.  Double-clicking a file that would have launched the app now does nothing.  The app's icon is gone from Ubuntu's "Show Applications" list.

If you then download the app again and run it, and tell it to Integrate with the OS, it will tell you it's already been integrated. I beg to differ.

**Comment by probonopd** [comment]
Hi @deezznutz

> the AppImage file will be deleted

That __really__ sucks!
Whatever sotware is doing this, it is 99.9% certain not AppImageKit.

Which tool are you using for integrating AppImages with the system? Please report this bug to the bug tracker of that tool.

Thank you.

**Comment by deezznutz** [comment]
I'm just running the appimage file on Ubuntu 20.10

Feb 16, 2021 1:09:35 PM probonopd <notifications@github.com>:

**Comment by probonopd** [comment]
Which application?

**Comment by deezznutz** [comment]
Ultimate Cura.

https://ultimaker.com/software/ultimaker-cura

Feb 16, 2021 1:14:13 PM probonopd <notifications@github.com>:

**Comment by probonopd** [comment]
Does it happen with other applications too?
