### ISSUE TITLE
icon do not show

### ISSUE THREAD

**Issue by natxopedreira** [AppImage/AppImageKit#1119]
i have a desktop file

```
[Desktop Entry]
Name=myApp
Exec=myApp
Icon=myApp
Type=Application
Categories=Utility;

and in the same level a png called myApp.png
```
Apps build and runs but app icon is not my png, can you please help me to make app use my icon

Thanks

**Comment by probonopd** [comment]
Please post a screenshot, thanks.
In which place would you expect the icon to show up?

**Comment by natxopedreira** [comment]
Thank you

I expect to show icon in the file navigator, instead i get the default one
<a href="https://imgbb.com/"><img src="https://i.ibb.co/ZSxLNJ6/folder.png" alt="folder" border="0" /></a>

I have the icon at the same level of desktop file
<a href="https://imgbb.com/"><img src="https://i.ibb.co/CBLpmxW/folder2.png" alt="folder2" border="0" /></a>

and also put icons 256 in App/usr/share/icons/hicolor/256x256/apps and 128 in the respective folder
<a href="https://imgbb.com/"><img src="https://i.ibb.co/YXSxMMn/path.png" alt="path" border="0" /></a>

**Comment by probonopd** [comment]
Note that for this to work, your file manager/operating system either needs to have native AppImage support (like, e.g., Nitrux), or you need some [desktop integration](https://github.com/AppImage/awesome-appimage#desktop-integration) utility.

What "file navigator" are you using, and which utility for desktop integration?

**Comment by natxopedreira** [comment]
ahhh ok, im on xubuntu 20 i think file manager is thunar

**Comment by probonopd** [comment]
Please check https://github.com/AppImage/awesome-appimage#desktop-integration
