### ISSUE TITLE
fuse-3?

### ISSUE THREAD

**Issue by 2011** [AppImage/AppImageKit#1120]
```
$ /path/to/any.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information


$ ls -al /usr/lib64/libfuse3.so*
lrwxrwxrwx 1 root root     13 2020-10-17 05:19:09 /usr/lib64/libfuse3.so -> libfuse3.so.3*
lrwxrwxrwx 1 root root     17 2020-10-17 05:19:09 /usr/lib64/libfuse3.so.3 -> libfuse3.so.3.9.1*
-rwxr-xr-x 1 root root 249552 2020-10-17 05:19:11 /usr/lib64/libfuse3.so.3.9.1*
```

I found nothing in the documentation mentioning version 3 of fuse, but do note that fuse-3.0.0 arrived in 2016, and the (dead) version 2 has seen no releases in more than two years. I don't understand why you still use version 2.

In searching through issues before making this post, I noticed somebody suggesting that you include (the relevant parts of) fuse in the AppImages. I heartily endorse that idea.

**Comment by probonopd** [comment]
Please install libfuse2 for now; systems like CentOS 6 and 7 still need it.
Ubuntu xenial, the oldest still-supported Ubuntu LTS release, also uses it: https://packages.ubuntu.com/de/xenial/libfuse2
So we do not want to drop libfuse2 support.

As far as I know, no one has started working on (optional) support for libfuse3 so far.
Would it be feasible to link libfuse statically into the embedded AppImage runtime, and would this solve these sorts of issues? This would increase size for the sake of increasing compatibility.

**Comment by TheAssassin** [comment]
You could just `dlopen()` and call the functions from there like it is done with libfuse2 currently. Would be easier. Also a chance to clean up the mess in the runtime, and extract all fuse-related things into some separate module.

**Comment by 2011** [comment]
> Would it be feasible to link libfuse statically into the embedded AppImage runtime, and would this solve these sorts of issues? This would increase size for the sake of increasing compatibility.

The **entire** libfuse3 dynamic library weighs in at less than 250K on my machine (I would expect a smaller size for libfuse2). The increase in size for each AppImage (assuming you only linked in the relevant function calls) seems absolutely trivial relative to the gains in user experience. Plus it solves your problem of having to switch later. Some distributions have started to get very strict about removing apps that link to unmainted software (Python 2.7.x or Gtk+ 2.24.x, to name two), and I expect that those distributions won't even package libfuse 2.x by the end of the year.

**Comment by probonopd** [comment]
> distributions won't even package libfuse2 

Then those distributions don't have a very backward/LTS compatible mindset. In my opinion, when a new major version of a library comes along, the last major version should be carried alongside at least until even the oldest still-supported LTS releases come with the new major version, plus some extra grace period.

**Comment by 2011** [comment]
I don't mean to sound too argumenative here, but doesn't most LTS last about two years (people usually don't get that on many phones)? Libfuse2 has (already) died more than two years ago. Dead software doesn't have the number of eyes looking at it for potential security vulnerabilities, and distribution maintainers almost always have limited resources (and do always have demands that far exceed those resources). I can tell you that distribution packagers hate few things more that having to expend the effort required to maintain applications that demand deprecated versions of tools (and the tools often need patching themselves because other things have changed in the meantime).

Some upstream developers will simply **never** upgrade if they can get away with it (I know software that still requires a version from the last millennium of a common tool). Why doesn't the project upgrade? I have no idea, but can only guess some combination of arrogance, ignorance, and laziness.

**Comment by probonopd** [comment]
> phones

Phones are clearly not our reference point. I know people who are still running 10-year old desktop operating systems.

> I can tell you that distribution packagers hate few things more that having to expend the effort required to maintain applications that demand deprecated versions of tools 

And that is exactly why we need something like AppImage that embraces backward compatibility to older systems. Many distributions simply don't care and that is a problem.

> Why doesn't the project upgrade? I have no idea, but can only guess some combination of arrogance, ignorance, and laziness.

Caring about users who do not want, or cannot, upgrade their operating system every couple of years.

**Comment by 2011** [comment]
> This would promote binary compatibility.

So would not requiring libfuse at all, and placing the function calls needed directly in each AppImage.

> Why don't distributions care about binary compatibility? I have no idea, but can only guess some combination of arrogance, ignorance, and laziness.

That seems specious to me. Distributions often have limited resources (and requests from users to add additional packages). Attempting to include deprecated libraries (especially those where the discovery of security flaws makes that more difficult) places a tremendous load on those resources. When the developer of a library moves to a new (and incompatible) version, application developers who continue to use to old library force **every** distribution that includes that application to do extra work. Eventually that becomes quite selfish (although libfuse2 remains recent enough that I don't mean to include applications that link to it in that description).

**Comment by probonopd** [comment]
> So would not requiring libfuse at all, and placing the function calls needed directly in each AppImage.

True, unless we still need to invoke commands like `fusermount` that need to be binary compatible (which I have not investigated yet).

> places a tremendous load on those resources

Maybe the sweet spot would be to carry (and co-install by default) the current-1 major version, and deprecate it thereafter. Something like that. So that there is an overlap in available major library versions in all distributions (from Enterprise/LTS to bleeding edge) at any point in time. But I suspect that this kind of thinking may be alien to many distributions.

Well, in pragmatic terms, I think we should try what @TheAssassin has suggested:
If `libfuse.so.2` cannot be `dlopen()`ed, then try to `dlopen()` `libfuse.so.3` (and hope that nothing has changed in a breaking way).

If this doesn't work, we can always think about not requiring libfuse (and `fusermount`, in case we currently do) at all...

**Comment by haampie** [comment]
@probonopd what do you mean with using `fusermount`? I grepped it and didn't see it in the sources (including deps).

I'm kinda interested in a static version of `runtime` that has libfuse linked into it. For my use case (high-performance computing) I really don't need all the desktop/icon/update/install stuff that come with AppImages, I just need the self-mounting squashfs. Indeed both libfuse3.so and libfuse.so are roughly 250K, so that's a size I can live with. Any obvious downsides to this?

**Comment by haampie** [comment]
squashfuse is used, not fusermount it seems

**Comment by probonopd** [comment]
Doesn't `squashfuse` use `fusermount` internally? Not 100% sure

**Comment by haampie** [comment]
I think `squashfuse` is just calling `libfuse` functions, and I would presume that ultimately calls `fusermount` yes, because at least on my distro (ubuntu 20.04) that is a setuid binary

**Comment by haampie** [comment]
Yeah, one way to figure this out is by running `strace -f` which dropt the setuid flag for those binaries, and then the program fails:

```
$ strace -f -o out.txt ./my.AppImage
fusermount: mount failed: Operation not permitted
```

**Comment by haampie** [comment]
I quickly looked into this, but the latest tagged version of squashfuse doesn't play well with libfuse 3 (apparently @TheAssassin's [patches](https://salsa.debian.org/sgmoore/squashfuse/-/tree/master/debian/patches) were upstreamed to Debian for the libsquashfuse0); meaning that most people likely use libfuse 2 anyways. I've created an issue in that repo to ask them to release a new version: https://github.com/vasi/squashfuse/issues/50.

**Comment by haampie** [comment]
Actually there is a licensing issue when you statically link libfuse, because it is licensed LGPL. `dlopen` doesn't run into these issues so should be preferred.

**Comment by TheAssassin** [comment]
Static linking sure isn't the way to go. I wonder why this licensing issue was found just now, not a couple days ago.

I think this is the perfect opportunity for some polymorphy. The strategy pattern comes into my mind, but since this is pure C, well... I guess a struct containing function pointers is going to have to do. We just need 2-3 functions in such an API, wrapping libfuse2 and libfuse3 respectively. A factory can initialize a struct accordingly, preferring libfuse3, but falling back to libfuse2 if needed:

```cpp
#include <stdio.h>
#include <assert.h>

typedef struct {
    int (*mount)(char*, ...);
    int (*unmount)(char*, ...);
} fuse_handler_t;

fuse_handler_t* make_fuse_handler() {
    return NULL;
}

int main() {
    fuse_handler_t* fuse_handler = make_fuse_handler();

    assert(fuse_handler != NULL);

    fuse_handler->mount("...");
    
    /* wait until app in AppImage terminates */
    
    fuse_handler->unmount;
}
```

Such a FUSE handler could even hold some state, if needed.

**Comment by haampie** [comment]
Pardon my ignorance, but do you really need to call directly into libfuse in AppImageKit at all? Isn't everything handled through SquashFUSE? SquashFUSE 0.1.104 supports both libfuse2 and libfuse3, and the master branch (which is hopefully tagged soon) adds `libsquashfuse_ll.a` as a separate lib, so you would only have to move the (new) `ll_main.c` function into AppImageKit's runtime.c if you insist on not invoking `squashfuse_ll` as an executable.

Maybe squashfuse can be improved a bit to add support for using dlopen to load either libfuse2 or libfuse3 instead of fixing that at compile time.

**Comment by probonopd** [comment]
squashfuse is compiled in.

**Comment by TheAssassin** [comment]
We use a specific version of squashfuse, patched to load libfuse with `dlopen`.

**Comment by haampie** [comment]
https://github.com/vasi/squashfuse/issues/60

**Comment by haampie** [comment]
They are unfortunately not interested in supporting fuse and fuse3 at the same time

**Comment by almereyda** [comment]
Another tool from the AppImage ecosystem, https://github.com/vinifmor/bauh/, is also offering to be used with fuse (2) and fuse3. Unfortunately it's written in Python, and therefore uses an abstraction that could not be reused here.

What is blocking us here from offering both, the dependency on squashfuse and having to use dlopen?

Two comments from the linked thread stand out:

> `@chipturner` I am concerned all of these options add a bit of complexity for fairly niche use case. What systems only have libfuse2? libfuse3 is four years old and the last release of libfuse2 was Jan 2019.

seconding the argumentation from @2011 .

> `@vasi` How bad would it be to just build separate binaries, and have a small wrapper choose between them at runtime? Most Linux games do something like that.

providing a suggestion which could maybe work here, too?

**Comment by alt-art** [comment]
I have a suggestion, introduce a vulnerability in fuse2 to make everyone migrate to fuse3.

**Comment by pkkid** [comment]
Steam on Ubuntu 22.04 requires fuse3 for xdg-desktop-portal. This seems to make it not really possibly to have both Steam installed and use AppImages on the same system unless I am missing something.

**Comment by probonopd** [comment]
Are you saying fuse2 and fuse3 cannot be installed at the same time @pkkid? What happens if you do? AppImages require fuse2 to be installed and configured.

**Comment by pkkid** [comment]
In Ubuntu 22.04 it doesn't seem to let me install both. I have `fuse3` installed right now, and if I try to install `fuse`, it shows the following:

```bash
22:03:42 pkkid-ubuntu ~: install fuse
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libfuse2
The following packages will be REMOVED:
  fuse3 xdg-desktop-portal xdg-desktop-portal-gtk
The following NEW packages will be installed:
  fuse libfuse2
0 upgraded, 2 newly installed, 3 to remove and 11 not upgraded.
Need to get 0 B/117 kB of archives.
After this operation, 1,120 kB disk space will be freed.
Do you want to continue? [Y/n] 
```

**Comment by haampie** [comment]
I think it would be easiest to just statically link libfuse; it should be OK with MIT being a compatible license, and it just affects the runtime. At the end of the day libfuse3 just executes `fusermount`, and I don't think there's incompatibilities wrt command line arguments. I'm doing that here: https://github.com/eth-cscs/spack-batteries-included

**Comment by probonopd** [comment]
> Fuse3 is a requirement for qemu 6 [1]. Since we don't want to support
two versions of fuse in main, we'd like reverse-dependencies of fuse
to switch to fuse3.

Argh. Trouble is to be expected. This means that all existing AppImages will not run on Ubuntu unless the user manually installs libfuse2 from a non-default official repository. Something that is too difficult for "normal end users" to do.

> Please talk to upstreams and investigate what changes are required to
these packages

Distributions often blindly assume that users are updating everything to the latest versions of everything all the time. Which is not how I see things. Once I have a version of an application that works well for me the last thing I want is to be forced to update it. (At most, I download the new version in addition to the known good one to check out the new features and check for new showstoppers.)

If I understand it right, it Looks like https://github.com/eth-cscs/spack-batteries-included is providing a solution for this. Should we backport these changes into the AppImage runtime?

**Comment by probonopd** [comment]
@pkkid please try `sudo apt-get install libfuse2`.

**Comment by pkkid** [comment]
> @pkkid please try `sudo apt-get install libfuse2`.

That installed with no issue, thanks.

**Comment by 2011** [comment]
> > Fuse3 is a requirement for qemu 6 [1]. Since we don't want to support
> > two versions of fuse in main, we'd like reverse-dependencies of fuse
> > to switch to fuse3.
> 
> Argh. Trouble is to be expected. This means that all existing AppImages will not run on Ubuntu unless the user manually installs libfuse2 from a non-default official repository. Something that is too difficult for "normal end users" to do.

I did warn of this more than a year ago. Distributions don't want to maintain multiple versions. Fuse 3 arrived **six** years ago, and fuse 2 died **three** years ago. Who does not have fuse 3 available? Time to upgrade AppImage to work with fuse 3.

> Distributions often blindly assume that users are updating everything to the latest versions of everything all the time. Which is not how I see things. Once I have a version of an application that works well for me the last thing I want is to be forced to update it. (At most, I download the new version in addition to the known good one to check out the new features and check for new showstoppers.)

I accept that few distributions make it easy to reject updates, but the vast majority of applications should work with current versions (abi compatible - not necessarily the latest releases) of standard system libraries.

**Comment by probonopd** [comment]
> Things are working fine with just libfuse2 installed. 

Thanks @pkkid for confirming.

So, installing **libfuse2** is an immediate workaround until a proper solution is implemented.

**Comment by probonopd** [comment]
@haampie would you be willing to help us implement your solution?

**Comment by probonopd** [comment]
Why is the version "3" now in 2 places in the name `libfuse3.so.3` compared to just 1 place in `libfuse.so.2`?

**Comment by rwjack** [comment]
Ubuntu 22.04, temporary fix:

```
sudo add-apt-repository universe
sudo apt install libfuse2
```

**Comment by dinbtechit** [comment]
Ubuntu 22.04 on VirtualMachine can no longer copy files/clipboard info from the host machine (windows) after installing the fuse. 

```
sudo add-apt-repository universe
sudo apt install libfuse2
```

**Comment by BobSynfig** [comment]
From https://bugs.launchpad.net/ubuntu/+source/lubuntu-meta/+bug/1965636

The AppImage format for distributing applications is centered around the idea that a user can **boot the Ubuntu Live ISO, download an application in AppImage format**, make it executable, and run it **without having to install anything**.

If you download your AppImage, it means you have access to the internet, the workaround is not too much time consuming nor complex.

In case you have already have your AppImages on a usb stick for example, there is a workaround if you don't have access to the internet:
- Download the `libfuse2` package and extract the 2 libs
- Rename `libfuse.so.2.9.9` as `libfuse.so.2` and `libulockmgr.so.1.0.1` as `libulockmgr.so.1` and place them in the same directory as your AppmImages
- Create a little script `AppRun.sh` (same directory) to run an AppImage from the terminal containing 
```
#!/bin/bash
LD_PRELOAD="./libfuse.so.2 ./libulockmgr.so.1" $1 $2 $3 $4 $5 $6 $7 $8 $9
```
Just run ./AppRun.sh ./my-app.appimage
Not marvelous but useful without connection ;)

**Comment by probonopd** [comment]
Instead of `$1 $2 $3 $4 $5 $6 $7 $8 $9` use `"@$"`.

**Comment by Ob1To** [comment]
Guys ... Many people using Ubuntu 22.04 started to write me about my application not running because Fuse2 was missing. I'm telling them to execute
`sudo add-apt-repository universe
sudo apt install libfuse2`
but they are not happy and more and more people start having problems. When a permanent fix would be implemented with Appimage?

**Comment by probonopd** [comment]
> When a permanent fix would be implemented with Appimage?

Hello @Ob1To. Please direct feedback regarding Ubuntu's decision to suddenly start shipping libfuse2 by default at https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1965636.

The AppImage project is aware of the situation and we are currently evaluating different approaches. No ETA is available yet.

**Comment by Ob1To** [comment]
Can't you just implement Fuse3 support as well? I mean ... something like if(Fuse2 installed -> mount) else mount with Fuse 3?
I'm not aware of how it works so I'm just curious why it can't be done. I doubt that Ubuntu will change its politics and support Fuse2 again when the decision has already been made. The problem is that more and more people are installing the latest LTS Ubuntu and our support is on constantly harassed about that problem.

**Comment by TheAssassin** [comment]
It's AppImage with an I.

Installing `fuse` apparently breaks stuff, but installing just `libfuse2` seems to work.

As an update to this issue, in the background work is going on to provide fully static runtimes (or maybe runtimes that just depend on libc) in the future, including libfuse3.

**Comment by andylamp** [comment]
@TheAssassin sorry, I this was a typo in the first mention :). In the second, I got it right. Good to hear that work is underway... and huge thanks for the effort!

**Comment by probonopd** [comment]
> Can't you just implement Fuse3 support as well?

Then it would break again when the next Linux distribution decides to no longer ship that one. So, this time we want a solution that will hopefully not break again.

**Comment by realnc** [comment]
> > Can't you just implement Fuse3 support as well?
> 
> Then it would break again when the next Linux distribution decides to no longer ship that one. So, this time we want a solution that will hopefully not break again.

Why not as a short-term fix for Ubuntu 22.04? The static runtime might take a while.

**Comment by danryu** [comment]
Hopefully a fix will be implemented for this (despite it being marked Closed) as this is a show-stopper for AppImages on the current version of the dominant Linux desktop. Having to add repos and install deprecated libraries runs completely contrary to the streamlined UX I started integrating AppImage to provide :/ 

I fully understand the backward-compatibility arguments, but a bit of pragmatism would be useful in this scenario, bearing in mind Ubuntu 18.04 does not go out of support until mid-2023. That's a hell of a long overlap to expect up-to-date systems to have to jump through hoops.

**Comment by probonopd** [comment]
Technically solved. We just need to make https://github.com/AppImage/AppImageKit/issues/877 the official one sooner or later.

**Comment by danryu** [comment]
> We just need to make https://github.com/probonopd/go-appimage/releases/tag/continuous the official one sooner or later.

That would be great - please go ahead and pull the trigger :)

Otherwise if there's a quick workaround or howto for using the test build in the meantime, that would also be much appreciated.

**Comment by probonopd** [comment]
Sure, just use [go-appimage](https://github.com/probonopd/go-appimage/releases/tag/continuous) ;-)

**Comment by danryu** [comment]
> Sure, you can use [go-appimage](https://github.com/probonopd/go-appimage/) for now.

Not really an option. I have `linuxdeploy` and `linuxdeploy-plugin-qt` already integrated into CI, and I don't have half a day or more in my project timelines to hack around and create a substitute process with go-appimage.
I'll have to wait for when/if this becomes the mainstream option.

**Comment by quyykk** [comment]
> Technically solved. We just need to make [probonopd/go-appimage@continuous (release)](https://github.com/probonopd/go-appimage/releases/tag/continuous) the official one sooner or later.

Any status updates on this? It would be nice if linuxdeploy starts using that runtime.

**Comment by probonopd** [comment]
If you use the tools in https://github.com/probonopd/go-appimage, then you can produce such AppImages today. I am not sure whether/when `linuxdeploy` will start using that runtime.

**Comment by probonopd** [comment]
Reference:
* https://github.com/AppImage/AppImageSpec/issues/34

**Comment by danryu** [comment]
>     * [Release versions/v1.0.md AppImageSpec#34](https://github.com/AppImage/AppImageSpec/issues/34)

Does this mean the ball is rolling now? :)
I'm looking forward to being able to support Ubuntu 22.04 users "out of the box"...

**Comment by danryu** [comment]
@probonopd 
It's 22 months since this issue was opened. Although it is closed, it's still an active issue.

_Most_Linux desktop users are now running on fuse-3 systems.
(AppImage is aimed at Linux desktop users, right?)

Because it's apparently more important to support CentOS 6 and 7, and Xenial Ubuntu (!), _most_ of our users are therefore required to manually install libfuse2 on their systems in order just to run up our AppImage-distributed software.

I don't understand why a package distribution system like AppImage that favours simplicity and ease-of-use for desktop users decides to prioritize a small minority of very old OS versions.

It's especially confusing as apparently there is more than one viable solution already in place, whether it's the previously mentioned go-appimage or the PR here: https://github.com/AppImage/type2-runtime/pull/3.

Could you please clarify on whether there will be any movement on this, so that we're able to make the necessary decisions to continue to best support our Linux-based users - thanks!

**Comment by Ob1To** [comment]
Our clients are in the same situation. We started distributing our application a long time ago via AppImage and now we have to provide additional information for all our customers to install libfuse2 manually which is... let's say inconvenient.

**Comment by quyykk** [comment]
We use https://github.com/probonopd/go-appimage and it works pretty well. You can't start the AppImage if you have the AppImage Launcher, but apart from that there have been no problems using it.

**Comment by probonopd** [comment]
@danryu this was closed in favor of https://github.com/AppImage/AppImageKit/issues/877, which will be the solution and is still open.

[go-appimage ](https://github.com/probonopd/go-appimage/)is already using the new static runtime, for example. A repository for the static runtime has been created, https://github.com/AppImage/type2-runtime, but it has not been integrated into AppImageKit yet.

**Comment by danryu** [comment]
Thanks @probonopd 

go-appimage is not an option for us, as our app relies on custom url handling which needs AppImageLauncher to operate.

How much work is left on integrating the type2-runtime into AppImageKit? From the outside it appears that the effort has stalled.
At least your comments suggest that AppImageKit isn't deprecated, as I feared.
Could a test/beta version be made available to early adopters? Please?

(The "need for libfuse2" argument is surely losing water every day, as fewer fuse2-based installations are used either as build or run platforms.)

**Comment by BobSynfig** [comment]
> (The "need for libfuse2" argument is surely losing water every day, as fewer fuse2-based installations are used either as build or run platforms.)

I think you missed this part :
>  in order to continue to be able to run all the already-existing AppImages out there.

Is is more a constraint to install a single package or to make any existing AppImage to be converted to a new version of runtime?
It is the duty of application's developer to provide compatible binaries.
Why not as developers to produce both libfuse2 and libfuse3 compatible distros AppImages for new apps, as is already the case for bitness and architecture?

**Comment by danryu** [comment]
> I think you missed this part : 
> > in order to continue to be able to run all the already-existing AppImages out there.

No, I didn't miss that. If developers of already-existing AppImages don't want to maintain compatibility with the fuse versions in the mainline of popular Linux distribution development, then that is to be expected.

> Is is more a constraint to install a single package or to make any existing AppImage to be converted to a new version of runtime? 

The latter. If existing AppImages rely on older versions of fuse, then fine, make them install the old version of fuse. But if they have the current, mainline, popular one, then they shouldn't have to do anything.

> It is the duty of application's developer to provide compatible binaries. Why not as developers to produce both libfuse2 and libfuse3 compatible distros AppImages for new apps, as is already the case for bitness and architecture?

The answer to this should be obvious. But maybe one needs to be more involved in user-focused multi-platform app development and distribution to understand it. 
If I'm hypothetically already producing 32-bit and 64-bit versions of both X86 and ARM architectures (ie 4 release builds) for each app version update, I now have to double that to support both fuse2 and fuse3. So I'm up to 8 release builds - for a single app. 

When you want to help users use the software that you make, while also reducing engineering complexity and the maintainability of CI/CD workflows, this is the kind of thing you think about.

**Comment by probonopd** [comment]
By switching to a static build, we won't need any particular libfuse version in the operating system. That's why I want to push for this solution.

**Comment by danryu** [comment]
> By switching to a static build, we won't need any particular libfuse version in the operating system. That's why I want to push for this solution.

This sounds supremely sensible :) 
What's blocking its adoption? And how can I upvote it if necessary?

**Comment by qwertychouskie** [comment]
Ubuntu 16.04 is long EOL, even 18.04 is hitting EOL in ~1 week.  Meanwhile, AppImages don't run on Ubuntu 23.04 out of the box: https://www.omgubuntu.co.uk/2023/04/appimages-libfuse2-ubuntu-23-04

It sounds like static runtimes are the long-term solution, but *right now* AppImages are failing to launch in recent distros (silently if not ran from a terminal!)

**Comment by probonopd** [comment]
> What's blocking its adoption? 

@TheAssassin?

**Comment by Firestar-Reimu** [comment]
> It sounds like static runtimes are the long-term solution, but right now AppImages are failing to launch in recent distros (silently if not ran from a terminal!)

Yes. On archlinux it needs to manually install `fuse2` too.

**Comment by BobSynfig** [comment]
> Yes. On archlinux it needs to manually install `fuse2` too.

Or, in most of the cases, you can just  remove libstdc++.so.6 and libgmodule-2.0.so.0 from the AppImage file
See https://gist.github.com/BobSynfig/b861ead8ea57df22d601edb22324d6a6

**Comment by kskarthik** [comment]
@probonopd i have a strange situation 

My OS: Debian unstable

- I have flatpak installed which relies on `fuse3`

-  nvim appimage does not run because of fuse2 non-availability

- In debian, `fuse3` pkg removes `fuse2`

What can i do in this scenario?

**Comment by probonopd** [comment]
`sudo apt get install libfuse2` - if this wants to remove your existing fuse3 setup, then I'd consider it a bug in Debian, since libfuse2 and libfuse3 were explicitly designed to be installed alongside each other.

**Comment by kskarthik** [comment]
yes, feels like a bug!

```
sk@earth:~$ apt info fuse3
Package: fuse3
Version: 3.14.0-5
Priority: optional
Section: utils
Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Installed-Size: 102 kB
Provides: fuse (= 3.14.0-5)
Depends: libc6 (>= 2.34), libfuse3-3 (= 3.14.0-5), adduser, mount (>= 2.19.1), sed (>= 4)
Breaks: fuse
Replaces: fuse
Homepage: https://github.com/libfuse/libfuse/wiki
Download-Size: 35.8 kB
APT-Manual-Installed: no
APT-Sources: http://deb.debian.org/debian sid/main amd64 Packages
Description: Filesystem in Userspace (3.x version)
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to
 export a virtual filesystem to the Linux kernel. It also aims to provide a
 secure method for non privileged users to create and mount their own filesystem
 implementations.
 ```

**Comment by kskarthik** [comment]
@probonopd thans a lot! it helped

**Comment by jcelerier** [comment]
so, if as of today I want to provide an appimage that will work from, say, ubuntu 18.10 to 23.10, and does not require the user to run apt install manually, what are my options?

**Comment by probonopd** [comment]
That should be doable by using a statically linked AppImage runtime, e.g., https://github.com/AppImage/type2-runtime.

**Comment by BobSynfig** [comment]
But people have to be aware that older (existing) AppImage will still require libfuse2 unless they are altered to use this statically linked runtime.

**Comment by jcelerier** [comment]
sorry, I should have been more clear, it's not too clear for me how to instruct AppImageKit to use this new runtime ? or do I have to do it manually

**Comment by jcelerier** [comment]
I see. I'm not using linuxdeployqt - I do this : https://github.com/ossia/score/blob/master/ci/appimage.build.sh#L25

is the runtime the AppRun file ? The steps would be 
- build the type2-runtime
- rename the output as AppRun
- put it at the same place ? 

Or are more things invlved

**Comment by probonopd** [comment]
No, the runtime is not the AppRun file. And I meant [`appimagetool`](https://github.com/AppImage/appimagetool) above, not linuxdeployqt (I am correcting the above now). Sorry for the confusion.

**Comment by jcelerier** [comment]
thanks a lot! this is great

**Comment by jcelerier** [comment]
super, just in case there is a typo in the command, I think it should be 

    "Score.AppImage --runtime-file runtime-x86_64"

instead of 

    "Score.AppImage" --runtime-file runtime-x86_64

**Comment by probonopd** [comment]
Of course. Correcting above. Thanks!

**Comment by terrancewong** [comment]
years passed, still stuck at end-of-life libfuse2. 

If centos 34567, ubuntu ancient lts  loves old libs, why they not just use older appimage?

**Comment by AsciiWolf** [comment]
fuse2 is sadly unmaintained and insecure. The last released version seems to be from 2019. The other problem is that fuse2 depends on a SUID root binary. See the discussion about [AppImage support removal](https://discussion.fedoraproject.org/t/remove-support-for-appimages/160867) in Fedora.

AppImage (fuse2) out-of-box support was also already removed in current Debian Stable (Trixie) release.

No typical end-user is going to manually install additional system library to get AppImages working.

Please, consider switching to fuse3.

**Comment by probonopd** [comment]
https://github.com/AppImage/appimagetool and the [runtime](https://github.com/AppImage/type2-runtime) it uses hasn't required fuse2 since a long time.

Should the tooling you are using still result in AppImages requiring libfuse2, then please get the tooling authors to adopt the above. Thanks!

**Comment by AsciiWolf** [comment]
Oops, sorry. Yeah, my tooling is based on the (probably outdated) GitHub CI. Great to hear that newer AppImages no longer require fuse2!
