### ISSUE TITLE
working directory should not be changed for Terminal applications

### ISSUE THREAD

**Issue by ganguin** [AppImage/AppImageKit#1121]
AppRun calls chdir to AppImageMount/usr. This is perfectly OK (and a good idea?) for Graphical Applications but weird/problematic for Terminal Applications.

chdir should be performed only when the .desktop file does not contain `Terminal=true`

As a workaround, it is possible to chdir back to the OWD env variable in the bundled application. However, it would be nice to be able to package a console application without having to patch it to make this chdir.

**Comment by TheAssassin** [comment]
The `chdir` is only executed by the (long obsolete and IMO long deprecated) `AppRun.c`. Use, e.g., linuxdeploy, or any other method to deploy your application.

**Comment by ganguin** [comment]
ok, then nevermind, Thanks for the quick response. I find the documentation quite confusing on how to build a simple Appimage. If linuxdeploy is the way to go, I'll try that

**Comment by probonopd** [comment]
To add to the confusion, there is a multitude of different tools each with their own strenghts:
https://github.com/AppImage/awesome-appimage#appimage-developer-tools

**Comment by TheAssassin** [comment]
Don't hesitate to ask for help on IRC: https://docs.appimage.org/contact.html
