### ISSUE TITLE
zsh: command not found: appimagetool

### ISSUE THREAD

**Issue by jinfagang** [AppImage/AppImageKit#1125]
zsh: command not found: appimagetool

I have already download appimagetool and soft link to appimagetool.......

**Comment by probonopd** [comment]
On which system (distribution and version) are you running? Which architecture of your system and of the AppImage?

**Comment by srevinsaju** [comment]
Its likely you linked `appimagetool` to a directory which is not on `PATH`.

```bash
which appimagetool
```

**Comment by jinfagang** [comment]
@srevinsaju  I soft link and also tried copied to /usr/bin and /usr/local/bin

Is it not in PATH?

@probonopd  Ubuntu 20.04
