### ISSUE TITLE
armv7l

### ISSUE THREAD

**Issue by Ben-Faessler** [AppImage/AppImageKit#1128]
Hi Guys. I am using the Nuitka project to compile Python into executable files. Nuitka uses the AppImageKit for the onefile mode. Nuitka will download the appropriate release. For me it is https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-armv7l.AppImage. But since there is no release for this architecture, this does not work. Could you please upload an armv7l version under releases for this (and future) versions?

**Comment by TheAssassin** [comment]
The `armhf` release is the right one for you. We won't add extra files for every alias of that release. Every vendor, distributor etc. uses their own naming scheme. It's nuitka's job to download the right file.

**Comment by kayhayen** [comment]
@TheAssassin thanks for the nice tool and sorry for the noise caused, I am fixing Nuitka to pick this correctly.
