### ISSUE TITLE
 Could not find patchelf caused by non-unique /tmp/ directory 

### ISSUE THREAD

**Issue by mnil** [AppImage/AppImageKit#1129]
Hello, I added the issue below to the linuxdeploy repo but was directed here instead: https://github.com/linuxdeploy/linuxdeploy/issues/174

We use linuxdeploy building multiple targets using the bazel build system by Google. In our setup we have had problems with flaky failures with the symptom:
```
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Could not find patchelf
```
after some debugging we drew the conclusion that this is due using the `--appimage-extract-and-run` which extracts to `  /tmp/appimage_extracted_<hash>`. Since we have multiple targets and bazel is using multiple threads I think the extraction is removing some files used by the other linuxdeploy process. We can't run the AppImage directly either due to the build system running in a docker container.

We solved this by using the `linuxdeploy-x86_64.AppImage --appimage-extract && ./squashfs-root/AppRun <args> && rm -rf ./squashfs-root`. Then every build target gets a unique AppRun. One could maybe mitigate this by using a more unique hash in the /tmp/-dir? Maybe this is a very small use case, but I submit this issues in case anyone else is having the same problem in the future. If you not feel like this is worth a fix just close the issue.

**Comment by probonopd** [comment]
Hello @mnil, thanks for reporting. I am not sure how this could be solved
* We could make `--appimage-extract-and-run` use a deterministic (e.g., derived from the path of the AppImage) location for the temporary files
* But still, at the end of each run the temporary files would still be deleted as we have no way of knowing whether and how many additional parallel runs are running

So how would you like the solution to work?

**Comment by probonopd** [comment]
Thanks  @mnil. Let's close this as it works as-is for the main intended use cases. We don't want to complicate the code for rare edge cases if workarounds are available.
