### ISSUE TITLE
This doesn't look like a squashfs image.

### ISSUE THREAD

**Issue by starsareintherose** [AppImage/AppImageKit#1130]
I'm the maintaner of raxmlgui on AUR of Arch
I try to test it and I found that desktop file can't be shown, I am trying to find the problem.
So I type in the terminal.
```
./raxmlGUI.AppImage                                                        ░▒▓ ✔  17:17:09 ▓▒░
This doesn't look like a squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```
But the file exits, then I try wiki
```
░▒▓ /opt/appimages ▓▒░ sudo chmod u+s  raxmlGUI.AppImage                                      ░▒▓ 127 ✘  17:17:14 ▓▒░
░▒▓ /opt/appimages ▓▒░ ./raxmlGUI.AppImage                                                        ░▒▓ ✔  17:20:30 ▓▒░
This doesn't look like a squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```
But it also doesn't work.

**Comment by TheAssassin** [comment]
> sudo chmod u+s  raxmlGUI.AppImage   

You should _never_ do this unless you _really_ know what you are doing there. It sets the so-called setuid bit, which can create manifold security issues.

**Comment by starsareintherose** [comment]
> > sudo chmod u+s  raxmlGUI.AppImage
> 
> You should _never_ do this unless you _really_ know what you are doing there. It sets the so-called setuid bit, which can create manifold security issues.

Oh, thanks, but it still dosen't Work

**Comment by probonopd** [comment]
Is the AppImage in question available for download?

**Comment by starsareintherose** [comment]
> Is the AppImage in question available for download?

https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.3/raxmlGUI-2.0.3.AppImage
See here

**Comment by starsareintherose** [comment]
> Is the AppImage in question available for download?

I use  command to extract it, and found appimage in the extracted dir, it doesn't work.
Then I try to directly move the original appimage  to /opt/appimages, the appimage file also doesn't work
This is part of my PKGBUILD of AUR https://aur.archlinux.org/packages/raxmlgui/
```
package() {
-  install -Dm755 "${srcdir}/raxmlGUI-${pkgver}.AppImage" "${pkgdir}/opt/appimages/raxmlGUI.AppImage"
+  install -Dm755 ~/.cache/yay/raxmlgui/raxmlGUI-${pkgver}.AppImage "${pkgdir}/opt/appimages/raxmlGUI.AppImage"
   install -dm755 "${pkgdir}/usr/share/"
   mkdir "${pkgdir}/usr/share/applications/" 
   cp ~/.cache/yay/raxmlgui/raxmlgui.desktop "${pkgdir}/usr/share/applications/"

**Comment by probonopd** [comment]
What happens if you run `./raxmlGUI-2.0.3.AppImage --appimage-extract`? Do you get `squashfs-root/AppRun`?

What happens if you run `./raxmlGUI-2.0.3.AppImage --appimage-mount`? Does it print a mount point, and do you have `/AppRun` at that mount point?

**Comment by starsareintherose** [comment]
> What happens if you run `./raxmlGUI-2.0.3.AppImage --appimage-extract`? Do you get `squashfs-root/AppRun`?
> 
> What happens if you run `./raxmlGUI-2.0.3.AppImage --appimage-mount`? Does it print a mount point, and do you have `/AppRun` at that mount point?

# Maintainer: Malacology <guoyizhang at malacology dot com>
# Contributor: Malacology <guoyizhang at malacology dot com>
Yes, all can. But when I try PKGBUILD and find `${pkgdir}/opt/raxmlgui/raxmlgui.AppImage` with this problem. It's so strange, it should be same to the orginial file
```
pkgname=raxmlgui
pkgver=2.0.3
pkgrel=1
pkgdesc="A new user-friendly program integrating RAxML-NG and ModelTest-NG for cutting-edge phylogenetic analysis"
arch=('x86_64')
url="https://antonellilab.github.io/raxmlGUI"
license=('AGPL3')
source=("https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.3/raxmlGUI-2.0.3.AppImage")
sha256sums=('SKIP')

prepare() {
  cd "${srcdir}"
  chmod +x raxmlGUI-${pkgver}.AppImage
  ./raxmlGUI-${pkgver}.AppImage --appimage-extract
}

package() {
    # Install AppImage
    install -Dm755 ~/.cache/yay/raxmlgui/raxmlGUI-${pkgver}.AppImage "${pkgdir}/opt/${pkgname}/raxmlgui.AppImage"

    # Symlink executable
    mkdir -p "${pkgdir}/usr/bin"
    ln -s "/opt/${pkgname}/raxmlgui.AppImage" "${pkgdir}/usr/bin/raxmlgui"

    install -Dm644 ~/.cache/yay/raxmlgui/raxmlgui.desktop "${pkgdir}/usr/share/applications/raxmlGUI.desktop"
}
```

**Comment by probonopd** [comment]
My recommendation would be to not use PGKBUILD . Double-click the AppImage to run it or use one of the [desktop integration tools](https://github.com/AppImage/awesome-appimage#desktop-integration) to integrate AppImages into the system. Looks like this particular application does not run properly from an extracted AppImage.
