### ISSUE TITLE
Pass system env variables like QT_AUTO_SCREEN_SCALE_FACTOR

### ISSUE THREAD

**Issue by izzylaif** [AppImage/AppImageKit#1131]
4k+ displays are becoming increasingly common. However, AppImages using QT seem to ignore important variables to make them actually usable on HiDPI screens.
I've tested VLC, installed vs AppImage. The installed instances respect QT_AUTO_SCREEN_SCALE_FACTOR=1 and similar envs, while the AppImage don't.
Other apps like Clipgrab and XNview do respect the envs even in the packaged format, probably because the developers themselves distribute them as appimages.
This probably should be part on the default launcher, without relying on the package author sanity.

**Comment by azubieta** [comment]
@izzylaif the authors of the VLC AppImage should be setting this env themselves, that's provably why it's not being applied. The AppImage runtime passes the whole environment as it's to the executed application and setting this kind of configuration is something relative to the application itself. To be honest I don't think that we should add this kind of hacks to the runtime.

**Comment by probonopd** [comment]
I don't think the AppImage runtime messes with `QT_AUTO_SCREEN_SCALE_FACTOR` in any way, so the payload applications should respect whatever `QT_AUTO_SCREEN_SCALE_FACTOR` is set. Unless the author of an AppImage has decided to set `QT_AUTO_SCREEN_SCALE_FACTOR` as part of a custom `AppRun` file, in which case you would need to ask the author of that specific AppImage to stop doing this.

Or am I overlooking something here?

**Comment by bphd** [comment]
The author can do what he pleases, but what if the user want to set that variable?

**Comment by probonopd** [comment]
The software inside the AppImage respects environment variables exported before running the AppImage. So you can export  `QT_AUTO_SCREEN_SCALE_FACTOR` and then run the AppImage. Unless a custom script inside the AppImage changes it intentionally, it will be respected.

**Comment by bphd** [comment]
Well, doing `MOZ_ENABLE_WAYLAND=1 zenBrowser.appImage --appimage-extract-and-run` don't seem to make the appimage respecting that variable. Even trying to `export` it don't work

**Comment by probonopd** [comment]
What about

```
export MOZ_ENABLE_WAYLAND=1 
./zenBrowser.appImage
```

**Comment by bphd** [comment]
https://github.com/AppImage/AppImageKit/issues/1154#issuecomment-2466172097
