### ISSUE TITLE
FreeCAD

### ISSUE THREAD

**Issue by snelweg** [AppImage/AppImageKit#1133]
I use the Linkstage3 appimage made by RealThunder at https://github.com/realthunder/FreeCAD_assembly3/releases

Works great, but I wonder why FreeCAD is always inserted into the 'other' menu on my Debian Duster install. Can I move it to a more appropriate  place like 'development' or 'graphics'?

![appimageMenu](https://user-images.githubusercontent.com/1257901/117578789-5636be80-b0f0-11eb-8519-b2f49e7aba59.png)

**Comment by TheAssassin** [comment]
Not an AppImage issue. You need to ask the author of that AppImage to change the `Categories` in their `.desktop` file.

**Comment by snelweg** [comment]
ok, thank you.
