### ISSUE TITLE
What is the right way to modify an existing AppImage?

### ISSUE THREAD

**Issue by trmdi** [AppImage/AppImageKit#1134]
Hi, I'm trying to add a plugin into an existing appimage but don't know why it fails.

Please see this log file: https://build.opensuse.org/package/live_build_log/home:trmdi:test/viber/AppImage/x86_64

In the end lines, it says success at first, but after it runs AppRun, it becomes failed.

```
[   66s] Marking the AppImage as executable...
[   66s] Embedding MD5 digest
[   67s] Success
[   67s] 
[   67s] Please consider submitting your AppImage to AppImageHub, the crowd-sourced
[   67s] central directory of available AppImages, by opening a pull request
[   67s] at https://github.com/AppImage/appimage.github.io
[   67s] /usr/src/packages/SOURCES/squashfs-root should be packaged as Viber-x86_64.AppImage
[   67s] /usr/src/packages/SOURCES
[   67s] /usr/src/packages/viber -0-Build5.1-x86_64 /usr/src/packages/SOURCES
[   67s] No .desktop file found, skipping AppImage creation
[   67s] ### VM INTERACTION START ###
[   71s] [   60.986482] sysrq: Power Off
[   71s] [   60.992559] reboot: Power down
[   71s] ### VM INTERACTION END ###
[   71s] 
[   71s] lamb04 failed "build appimage.yml" at Fri May 14 11:00:36 UTC 2021.
[   71s] 
```

Yaml file: https://build.opensuse.org/package/view_file/home:trmdi:test/viber/appimage.yml?expand=1

CC: @probonopd

**Comment by TheAssassin** [comment]
[Extract](https://docs.appimage.org/user-guide/run-appimages.html#mount-or-extract-appimages), modify, [repack](https://github.com/AppImage/AppImageKit#appimagetool-usage).

No need to annoy people by highlighting them like this.

**Comment by TheAssassin** [comment]
> [ 67s] No .desktop file found, skipping AppImage creation

Well, it tells you everything you need to know. See https://docs.appimage.org/reference/appdir.html.

**Comment by trmdi** [comment]
> [Extract](https://docs.appimage.org/user-guide/run-appimages.html#mount-or-extract-appimages), modify, [repack](https://github.com/AppImage/AppImageKit#appimagetool-usage).
> 
> No need to annoy people by highlighting them like this.

Sorry, I just tag him using @, github make it bold, because I see his name in the document for OBS and I'm not sure if you use OBS, don't mean to annoy anyone.

**Comment by trmdi** [comment]
> > [ 67s] No .desktop file found, skipping AppImage creation
> 
> Well, it tells you everything you need to know. See https://docs.appimage.org/reference/appdir.html.

But it has the .desktop file in the squash dir after I extract it. You can see in the log file.

**Comment by TheAssassin** [comment]
"Tag" means "generate noise in form of emails, redundant notifications, ...". Unless it's absolutely necessary, don't "tag" people.

```
[   57s] + cd squashfs-root/
[   57s] + appimagetool -n ./
[...]
[   58s] File /usr/src/packages/SOURCES/squashfs-root/Viber-x86_64.AppImage changed size while reading filesystem, attempting to re-read
```

You should not generate an AppImage inside an AppDir. I think appimagetool should actually check this. Just call appimagetool outside and see if it helps. The log suggests that this is your issue.

**Comment by trmdi** [comment]
> You should not generate an AppImage inside an AppDir. I think appimagetool should actually check this. Just call appimagetool outside and see if it helps. The log suggests that this is your issue.

Actually this is just a test, I called it outside before that but the result is the same. Ok, I will try the latest appimagetool.AppImage to see if it works.

**Comment by TheAssassin** [comment]
Why should it work? The error is obvious. Do I really have to explain how to debug this? Run `ls -al squashfs-root/` as part of your build script and make sure the desktop file is there.

**Comment by trmdi** [comment]
> Why should it work? The error is obvious. Do I really have to explain how to debug this? Run `ls -al squashfs-root/` as part of your build script and make sure the desktop file is there.

That file does exist. You can see the new log in which I added the `ls` command:
https://build.opensuse.org/package/live_build_log/home:trmdi:test/viber/AppImage/x86_64
Also used the latest appimge tool from your github. But still same result.

**Comment by TheAssassin** [comment]
I don't see any such log messages in there. And we can't really provide support for OBS. I think you should ask them for help.

**Comment by trmdi** [comment]
Never mind. I've fixed it myself.
Thanks for your reply !
