### ISSUE TITLE
Where does `--appimage-extract-and-run` extract to by default?

### ISSUE THREAD

**Issue by omexlu** [AppImage/AppImageKit#1135]
Hello,

Where is extracted by default "--appimage-extract-and-run"?

Can i e.g. also specify a defined path where it should be extracted to?

PS. I think currently it is extracted to /tmp and I think that not so practical place for it.

Thanks in advance.

**Comment by TheAssassin** [comment]
IIRC the destination cannot be overwritten. You are free to extract AppImages manually into some location and then run the contents yourself.

**Comment by omexlu** [comment]
Thank you, also `appimage-extract` and then run `AppRun` by command? 🙈

**Comment by TheAssassin** [comment]
You'll be able to figure it out yourself, but you seem to be lazy:

```
my.AppImage --appimage-extract
squashfs-root/AppRun

**Comment by omexlu** [comment]
Thanks, what if I want to extract on a special folder, this works (sorry not at home for a week to test)? :
`my.AppImage --appimage-extract
/home/xxx/desktop/AppRun`

**Comment by TheAssassin** [comment]
No, it does not. But:

```sh
mkdir /what/ever/dir
cd /what/ever/dir
/some/other/dir/my.AppImage --appimage-extract
[...]
# run AppImage contents
/what/ever/dir/squashfs-root/AppRun ...

**Comment by probonopd** [comment]
Maybe we should print a message "The AppImage has been extracted to (absolute path)" at the end?
