### ISSUE TITLE
appimagetool: Support applications without icon

### ISSUE THREAD

**Issue by piegamesde** [AppImage/AppImageKit#1137]
I'm trying the tool and it forces me to have an icon: `icon entry not found in desktop file`. Some applications simply don't have an icon, please respect that.

**Comment by probonopd** [comment]
Thanks @piegamesde but the current behavior works as intended.

**Comment by piegamesde** [comment]
May you please explain the movitation behind this? Same for requiring a `.desktop` file. The `AppRun` file alone should be sufficient, no? I just tried to build an application with obviously garbage data in my `.desktop` file and it hasn't broken until now, so what is this data used for?

**Comment by TheAssassin** [comment]
It's been answered before. The AppDir standard mandates it. We inherited it from ROX Filer and just extended it. See https://docs.appimage.org/reference/appdir.html.

**Comment by piegamesde** [comment]
Thank you for the answer, I hadn't seen that.

It'd still be cool if the tool automatically inserted a placeholder dummy icon and issue a warning instead of failing. That would reduce the number of required steps to get a minimum thing running, and thus a better user experience.

**Comment by TheAssassin** [comment]
A cheap hack is `touch AppDir/myicon.svg`. The reason the icon is mandated is, I guess, to be able to show thumbnails. And almost every app has some sort of logo.

**Comment by probonopd** [comment]
> It'd still be cool if the tool automatically inserted a placeholder dummy icon and issue a warning instead of failing. That would reduce the number of required steps to get a minimum thing running, and thus a better user experience.

Well, the best user experience is achieved if we nudge the application creator into picking a suitable icon. ;-)

**Comment by TheAssassin** [comment]
Well, arguably, one could just rely on system theme icons as well. But bundling one is not the worst idea. You can never predict the contents of the system theme.
