### ISSUE TITLE
希望有个appimage应用商店

### ISSUE THREAD

**Issue by chioview** [AppImage/AppImageKit#1138]
既然appimage是跨发行版的安装包，希望有一个appimage的应用商店，毕竟渠道也很重要

**Comment by probonopd** [comment]
你好。有一个网站列出了AppImage的应用。

https://appimage.github.io/

**Comment by chioview** [comment]
谢谢


不胜感激














在 2021-05-29 02:03:55，"probonopd" ***@***.***> 写道：

你好。有一个网站列出了AppImage的应用。

https://appimage.github.io/
