### ISSUE TITLE
how to easily create AppImage?

### ISSUE THREAD

**Issue by Translate-SW** [AppImage/AppImageKit#1141]
Hello,
I would like to ask, **how do I create an AppImage?**
I have this git repository https://github.com/Translate-SW/enve-cs and I don't know how I should create appimage. **Can you please help me create an appimage?** Thank you in advance for your help.

**Comment by probonopd** [comment]
Check this out:
https://github.com/MaurycyLiebner/enve/releases/tag/continuous-linux
