### ISSUE TITLE
Porting to hobbyOS

### ISSUE THREAD

**Issue by n0p0n3** [AppImage/AppImageKit#1145]
I want to use appimage as the primary application packaging for my unixish hobby os. I was wondering what is required to use appimage, what must be implemented. I know I need squashfs support, but is there anything else that needs to be done, or is it just as simple as adding binfmt_misc like support?

**Comment by probonopd** [comment]
FUSE.

And the basic libraries listed at https://github.com/AppImage/pkg2appimage/blob/master/excludelist should be part of your base system.

**Comment by n0p0n3** [comment]
Thank you. Are the libraries required for appimage itself, or are they they required for the apps packaged inside? I plan on using appimaged or appimagelauncher to integrate and app-outlet with modified address to only connect to my curated apps, and will be custom static compiling my apps and packaging them myself.

**Comment by probonopd** [comment]
Interesting! Let me know how it goes.
