### ISSUE TITLE
Space Shows Up as \\s

### ISSUE THREAD

**Issue by elibroftw** [AppImage/AppImageKit#1148]
If I try running the Unofficial Plex Media Player AppImage, which has spaces, I always get the "would you like to install/integrate" this app. After I click yes, I see the .desktop file in the ~/local/share/applications/ folder but the path for TryExec uses \\s  instead of a space. This causes the application to not show up in the menu. Furthermore, even if the .desktop app exists, I have to manually tell the "Install Linux Application" question to stop asking me to integrate the app image.

Sorry if this is the wrong place, but it's a very annoying issue.

**Comment by elibroftw** [comment]
Found the relevant repo

**Comment by probonopd** [comment]
>  I always get the "would you like to install/integrate" this app

This is not caused by AppImageKIt.
