### ISSUE TITLE
Can appimage deal with non-desktop  applications?

### ISSUE THREAD

**Issue by flyhigao** [AppImage/AppImageKit#1157]
I have a c program that needs to be run in a very old centos5.5. The glibc version is not compatible. 
Can I package this non-desktop program with appimage ?

**Comment by probonopd** [comment]
Most likely it should be doable. May need manual work though, and a good understanding of what one is doing.

**Comment by TheAssassin** [comment]
> The glibc version is not compatible

This seems very unlikely. glibc is generally extremely good at maintaining backwards compatibility.

Without providing significantly more information, nobody can help you figure out your problem.
