### ISSUE TITLE
integrate and run window doesn't apper

### ISSUE THREAD

**Issue by Patronon** [AppImage/AppImageKit#1161]
Hi, 
I installed it as recommended and changed the settings as recommended in Order to open an FreeCad Appimage file.
When I want to open the AppImage with Appimagelaucher it just runs it and does not ask me if I want to integrate it. The Window just does not open for me.(?)
Nice program so far anyways, thanks for the effort 
I running on Linux Mint 20.2

**Comment by probonopd** [comment]
Hi @Patronon, please report AppImageLauncher issues to https://github.com/TheAssassin/AppImageLauncher/issues. Thanks!
