### ISSUE TITLE
Can not compile it from source

### ISSUE THREAD

**Issue by rubyFeedback** [AppImage/AppImageKit#1173]
I just did a git clone, then cd-ed into the directory.

Then I did:

    cmake -DCMAKE_INSTALL_PREFIX=/usr .

But it fails with:

-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at lib/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /Depot/j/AppImageKit/lib/libappimage

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:71 (include):
  include could not find requested file:

    lib/libappimage/cmake/tools.cmake

CMake Error at cmake/dependencies.cmake:5 (include):
  include could not find requested file:

    /Depot/j/AppImageKit/lib/libappimage/cmake/scripts.cmake
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)

CMake Error at cmake/dependencies.cmake:11 (import_pkgconfig_target):
  Unknown CMake command "import_pkgconfig_target".
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)

-- Configuring incomplete, errors occurred!
See also "/Depot/j/AppImageKit/CMakeFiles/CMakeOutput.log".

Not sure where the error is, but could someone fix this so we oldschool source
compilers can compile it? I can compile gcc, glibc etc... from source - 
not sure why I can not do so with AppImage. I thought app-images are
the future, but being unable to compile is a step back for me as an
oldschool linux dude. :(

**Comment by TheAssassin** [comment]
That's not a compiler error, it's a CMake error occurring long before a compiler would be used. Run `git submodule update --init --recursive` from the repo root and try again.

You might want to use the released binaries, though...
