### ISSUE TITLE
feasibility/difficulty of packaging an X11 session app like Xpra?

### ISSUE THREAD

**Issue by bdklahn** [AppImage/AppImageKit#1174]
I'm not sure if this is the best repo to attach this to, but . . .
I've been in communication with an Xpra developer. [I raised the possibility of packaging Xpra as an AppImage](https://github.com/Xpra-org/xpra/issues/3459). He seemed to think it would be problematic, saying . . .

"These subsystems are most likely to cause integration problems: [printing](https://github.com/Xpra-org/xpra/blob/master/docs/Features/Printing.md), [service](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Service.md) and [authentication](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Authentication.md), [nvenc](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/NVENC.md) (needs device access), etc"

Personally, I'd like to be able to easily run it on my (upstream-unsupported) OpenSUSE Tumbleweed desktop(s). It seems every other SUSE package bump breaks things. The OpenSUSE Xpra package maintainer says he no longer has time to keep up with that package (and asked me if I wanted to take over). But I also was wondering/hoping AppImage might reduce some of the work Xpra upstream has to do to build and test for CentOS rpm, deb, etc.
Do you think Xpra upstream is right about AppImage being challenging, in their case?

**Comment by probonopd** [comment]
Generally, an AppImage is just a self-monting filesystem that executes whatever the author has decided to put inside. So in principle I don't see why it wouldn't work. Being a disk image, the AppImage format is intended for self-standing applications. Things that need to write files all over the filesystem in order to work properly are not ideal candidates for AppImage.

Looking at https://packages.debian.org/sid/alpha/xpra/filelist, the xpra package contains files such as `/etc/dbus-1/system.d/xpra.conf`, `/etc/init.d/xpra`, `/etc/pam.d/xpra`, `/lib/systemd/system/xpra.service`, `/lib/systemd/system/xpra.socket`, `/usr/lib/cups/backend/xpraforwarder`.

Without knowing how Xpra works it looks to me like Xpra wants the system-wide D-Bus, systemd, and CUPS to know that Xpra is there. This is different from the AppImage philosophy which basically keeps applications separate from the system. To make these features work with AppImage, the AppImage would need to contain a script that would copy the respective files out of the AppImage and into the running system. This can be done, but if done wrong can quickly become a mess.

Do you even need advanced features such as D-Bus, systemd, CUPS, and nvenc?

**Comment by totaam** [comment]
Xpra maintainer here - for the record, we are not "invested in a particular packaging" and would like nothing less than to be able to devote more time to development and less time to packaging.

But until solutions like AppImage can provide the integration we need to support all the features (including printing and hardware encoders for sure) - that's not going to help and is just going to increase the (already high) packaging cost of every release.

Note: a "client-only" build (like the ones available for MacOS and MS Windows) would not need any of those pesky system files and could reasonably be packaged with a bundle format like AppImage. (but again, the need for the native RPM and DEB package remains since you need to be able to run the server somewhere)

**Comment by probonopd** [comment]
Hi @totaam, thanks for chiming in.

> Note: a "client-only" build (like the ones available for MacOS and MS Windows) would not need any of those pesky system files and could reasonably be packaged with a bundle format like AppImage.

Yes, this sounds totally reasonable to me. The Xpra server part is not an "desktop application" and hence outside the scope of AppImage. It is a service that needs to integrate relatively deeply into the host system. That is not what AppImage is all about.

The Xpra client, needing no system integration, would probably be a good candidate for AppImage packaging. In case you are looking for a way to distribute the Xpra client as a single file that can run on a multitude of Linux distributions - even those not using DEB nor RPM.

**Comment by TheAssassin** [comment]
> even those not using DEB nor RPM

Better even, you can stop worrying about the weirdnesses of those package systems, and let distros handle that.

**Comment by bdklahn** [comment]
Hello @totaam, I wondered if (hoped?) you might see the GitHub auto-reference from over there. Glad you could chime in here. Yeah . . . just covering bases, in a quest to understand a little better. I figured a direct query here might get me a better idea of anything we didn't already know about the possibilities. And I don't mean to imply specific reasoning nor intention regarding "invested". I guess the idea with that is that you already have a working workflow with that, you've already invested time in developing. No, I don't think it would make sense to do this at all, if it meant maintaining it _in addition_ to the other packages. You are already kind enough to package for more things than many do. -just querying any possibility of something like this ever replacing those as the primary supported ways for GNU/Linux. Then, maybe, just supporting like "Here are some instructions which worked to build rpm and deb, if you want to build from source".

I am, now, honestly just trying to get straight in my head the general issues, not trying to push any agenda. Because "server" and "integrated" are inherently ambiguous, and don't seem to capture it, I'm thinking in different terms. -because there are lots of "server"s which need not be integrated. -and because "integrated", is largely a matter of perspective.

So does it make sense to think about it these two ways?
1. "elevated privileges"
2. leveraging tooling which already solves some of the integration issues

Re. 1
Certain services need more permission to expose some more sensitive things. So you either (or both) do something like "sudo . . . install . . ." server programs (binaries or whatever) in a place or way which gives them rights to do more things, and/or the install process is given permission to modify configurations, etc., which give them access to use already installed binaries and systems which already have some "elevated" permission to do things. I mean . . . I guess there is big difference between saying "Hey OS, can you open a standard file dialog for me so I can give a user a familiar interface to load or same my file?", and the sorts of things Xpra is capable of doing/leveraging.

For example, Docker and Singularity, et. al., can run "services" (daemonized containers or "instances").
But with Docker you install a daemon with "elevated" capabilities, and you run the client as root.
With Singularity you "sudo . . . install . . ." the singularity binary, which restricts setguid, etc., and need root to modify any system wide config settings (restrictions, etc.). So . . . both "service" enablers still need "elevated". 

Re. 2
Packaging tools built around rpm, deb, etc., already have well established mechanisms and conventions to know, or figure out, where to install (and chmod, etc.) X and Y onto the standard Z distribution locations. So if you are doing any of that "manually" with something like AppImage, you kinda have to build your own system and set of heuristics . . . and hope they are as robust and resilient as the well-tested standard packagers.

Anyway . . . The "selling point" for AppImage is that it is one file which can do "everything". And I know that's not the _actual_ claim, in absolute terms. But we need to keep in mind that it _does_ have very real dependencies outside of itself. Otherwise it would be considered, itself, an OS. It of course depends on the Linux kernel. But not only that, it's "universality/portability" depends on a less capable (older) kernel version. It, I think, depends on glib, right? So I know that is much less than many other "package" types. But, given it already, has outside dependencies, do we really need to act under the assumption an AppImage **must** try and package every single other thing it needs? How about "Just package the things/parts which seem to be less stable or consistent, distro to distro". And I know/think folks might say that leads to a "Frankenstein" "hodgepodge" of things. But, come on, that's basically what GNU/Linux _is_ already: kernel, scheduler, _maybe_ a "consistent" init system, etc., and then a bunch of community packages. It's not like FreeBSD, with a "core" OS. It's not Mac, where it's easy to be unified if you restrict things to the same company both developing the OS _and_ the only hardware it's supported to run on. I've been doing/using software long enough to know what "stable" really means: "We haven't seen any critical issues lately, with the things the community has been doing with it." If a recent Issue reveals a 5-year-old flaw in some code  . . . it was never "stable", in a super meaningful way. I guess my point is that "integrated" isn't, in reality, the clean, pristine thing we might want to believe, and that it might not really be that meaningful or necessary to require something like AppImage to include as much as is physically possible to be "self sufficient". Because it never truly was in the first place.

**Comment by probonopd** [comment]
> It of course depends on the Linux kernel. But not only that, it's "universality/portability" depends on a less capable (older) kernel version. It, I think, depends on glib, right?

Well. You need FUSE to mount AppImages (although you can unpack them without FUSE). And you need glibc. Apart from that, what you need or don't need to run a particular AppImage depends on its _contents_. You can privately bundle _everything_, then it has no outside library dependencies, but we generally don't recommend that. The typical use case for AppImage is to be (roughly) the equivalent of an `.app` in a `.dmg` on the Mac.

**Comment by bdklahn** [comment]
Right. Yeah. I like fuse (also, an example of a kernel space-type service designed to safely run in user space :-) ). I like squashfs, as well. :-)

**Comment by totaam** [comment]
> On the Mac, you are probably also not distributing the Xpra server as an .app?

The `.app` is wrapped in a `DMG` and `PKG`.
The `PKG` has the advantage of registering URL handlers and providing hooks for running the shadow server (as this requires special permissions).

> The Xpra server is a service that needs to integrate relatively more deeply into the host system, and is hence not a good candidate for an AppImage.

Agreed.

> The Xpra client, needing no system integration, would probably be a good candidate for AppImage packaging.

The MacOS issues reminded me of some system integration that is needed for a fully featured client: does AppImage support registering URI handlers and file extension mappings?
(this currently allows users to run the xpra client directly from a web link or from a downloaded `.xpra` session file)

How about `$XDG_RUNTIME_DIR` - are there any issues with that?
As in, is it defined and fully accessible?

**Comment by TheAssassin** [comment]
libappimage supports MIME integration pretty well, both adding custom MIME definitions (for file types) as well as setting `MimeType` in desktop entries. The latter can be used to register applications as handlers for URLs: `MimeType=x-scheme-handler/<scheme>`.
