### ISSUE TITLE
Appimage cause same byte site of the image even different version of the app

### ISSUE THREAD

**Issue by slrslr** [AppImage/AppImageKit#1175]
Appimage cause same byte site of the image even different version of the app, which means unable to wget differentiate between versions:
https://github.com/mifi/lossless-cut/issues/1039#issuecomment-1048877382

I am wondering if this is necessary or you can make appimage really differentiate in site.

Or if you have please idea how to wget/curl so it can find difference in a github and local based AppImage file even it has same size?As described under the link, "wget -N" not worked

Forgive me if this is not correct place, i am not a developer.

**Comment by probonopd** [comment]
Works as intended (by wget). [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) is what contains the type of functionality you are after.
