### ISSUE TITLE
Add an option to disable check for .desktop file for appimagetool (much like the option to ignore AppStream check)

### ISSUE THREAD

**Issue by XandrosDarkstorm** [AppImage/AppImageKit#1184]
If custom AppRun is used that does not use .desktop file, appimagetool still requires .desktop file and an icon in order to even pack this thing.
This behavior is annoying and there should be a parameter like -n, which ignores checks for a .desktop file and an icon.
This is especially useful, if you pack terminal-only apps, which meant to run in pure text mode, in which linux can't work with .desktop files directly anyway.

**Comment by probonopd** [comment]
Thanks for the suggestion @XandrosDarkstorm but we don't want this because it would lead to lazy developers omitting the icon even for GUI applications, resulting in AppImages without icons, which we don't want to support. So `appimagetool` requires an icon for all AppImages, even for those that contain command line tools rather than GUI applications.

**Comment by TheAssassin** [comment]
Desktop files are also useful for CLI applications. The AppDir specification further mandates them.

**Comment by XandrosDarkstorm** [comment]
> Desktop files are also useful for CLI applications. The AppDir specification further mandates them.

They might be useful for CLI applications when used on graphical window system configuration. But what if you don't have a X11/Wayland/Whatever window system? Then .both desktop file and the icon becomes useless, since you have no native way to use them.

Also reasoning of "it might make developers lazy" sounds ridiculous. If they are lazy to make an icon for the app, then they won't be making an icon specifically for the AppImage. They might do just like me -- make a file with command "touch iconfilename".
Also .desktop file is useless when you unpack the AppImage (pretty much the same), since Exec= field will only work on full paths or executables from PATH variable, which, of course, does not get updated globally. So you have to edit this .desktop file manually. And if you need to do that, why bother adding it inside the AppImage -- user will be better off making their own.

**Comment by craynic** [comment]
Hope there could an option to generate an empty .desktop file.

I'm not lazy. My app is a pure cli program, and it's not designed to be run from a desktop menu.

**Comment by craynic** [comment]
A tip for users coming to this issue:
`appimagetool` itself is also an instance of AppImage. You can extract the .desktop file and icon from it. All you need to do is to update the Exec entry in the desktop file.
