### ISSUE TITLE
mksquashfs is killed by the system's oomkiller

### ISSUE THREAD

**Issue by lalten** [AppImage/AppImageKit#1186]
We're building AppImages with Bazel in our CI (via [rules_appimage](https://github.com/lalten/rules_appimage)). When the appimage'd program is large and the CI worker is under high memory pressure, the appimagekit invocation fails because mksquashfs is killed by the system's oomkiller.
```
ERROR: /code/path/to/package/BUILD:4:11: AppImage path/to/package/program.appimage failed: (Killed): tool failed: error executing command
```

`(Killed)` is an oom killer symptom. The reason is that `mksquashfs` seems to try and use all the available memory. See also https://gitlab.tails.boum.org/tails/tails/-/issues/16177.
mksquashfs supports a `-mem SIZE` argument: https://www.mankier.com/1/mksquashfs#-mem, which would be a great solution to this, but this isn't currently exposed in AppImageKit in https://github.com/AppImage/AppImageKit/blob/8bbf694455d00f48d835f56afaa1dabcd9178ba6/src/appimagetoolnoglib.c#L158 or https://github.com/AppImage/AppImageKit/blob/672b3d0d1bf5fd74c3465da5fd62486606025a09/src/appimagetool.c#L150-L214

It would be awesome if a new AppImageKit parameter could be made to pass this through to mksquashfs. What do you think?

**Comment by TheAssassin** [comment]
A better solution is to just allow users to add mksquashfs parameters, e.g., `--mksquashfs-param -mem --mksquashfs-param 1024`.
