### ISSUE TITLE
.mount_XXX has wrong or strange permission for sudo user

### ISSUE THREAD

**Issue by athenakia** [AppImage/AppImageKit#1191]
Operating System: Ubuntu 20.04.2 LTS
Kernel: Linux 5.4.0-107-generic
Architecture: arm64

![demo](https://user-images.githubusercontent.com/55233887/163437362-1f8f643e-ddd0-424c-aaee-b22ab1750957.jpg)

As the screenshot shows, the .mount_xxx directory has a wrong or strange permission. When using `ls` as a normal user, the permission display is all right. But when using `ls` as super user, the permission is all ??? In my situation, I want to copy a config template to a path which only super user can access, so I have to copy file in .mount_XXX with sudo but I cannot access all files in .mount_XXX. And anything I do with sudo to change its ownership or permission return "Permission denied"

**Comment by athenakia** [comment]
Besides, it's an Electron app built with electron-builder.

**Comment by probonopd** [comment]
You need to run the AppImage with `sudo` if you want root to access its contents.
Alternatively, you could use `--appimage-extract`.

This is because we are using FUSE without the `allow_root` option.

**Comment by TheAssassin** [comment]
> This is because we are using FUSE without the allow_root option.

Not... really... FUSE by default denies access to all other users on the system for security reasons. This includes `root`. For `root`, the limit can be bypassed with the option @probonopd mentioned. However, we don't use this one by default.

Consider copying your file out of the mounted AppDir first (e.g., to a temp dir), then move it into place.
