### ISSUE TITLE
Cannot mount AppImage, please check your FUSE s...

### ISSUE THREAD

**Issue by B3luga1** [AppImage/AppImageKit#1194]
this message has been appearing and I don´t know what to do
![Screenshot from 2022-05-10 16-29-03](https://user-images.githubusercontent.com/105322134/167727605-bc0b29c6-fcce-497c-8bbf-f866c95bbbd4.png)

**Comment by azubieta** [comment]
Did you check that libfuse2 is installed in your system as the message suggest ?

**Comment by simoniz0r** [comment]
Apparently Ubuntu 22.04 has switched to fuse3 and no longer has libfuse2 installed out of the box.  This is going to be an issue going forward for people new to AppImages on 22.04.

**Comment by azubieta** [comment]
@simoniz0r we have a working prototype of a fuse3 compatible runtime. Sadly this will solve the issue for newly created AppImages. Old ones will still require fuse2.

**Comment by probonopd** [comment]
Regarding Ubuntu, known upstream issue:
https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1965636

You need to instal `sudo apt-get -y install libfuse2`.

Many Ubuntu derivatives have fixed this, but unfortunately not Ubuntu itself.

> fuse3 compatible runtime

Let's discuss that in
* https://github.com/AppImage/AppImageKit/issues/877

**Comment by Moth-Tolias** [comment]
> Regarding Ubuntu, known upstream issue:
> https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1965636

ubuntu has set the bug status to wontfix.

**Comment by probonopd** [comment]
Need to `apt-get -y install libfuse2` there.
