### ISSUE TITLE
Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

### ISSUE THREAD

**Issue by SahajRana** [AppImage/AppImageKit#1195]
Hi Appimage team, thanks for providing this awesome project.

When I try installing appimage on Ubuntu 22.04 I receive following error.

```
(blup:5876): GLib-GIO-ERROR **: 15:22:44.046: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```
How to resolve this?

**Comment by TheAssassin** [comment]
First of all, AppImages are not "installed". Also, there is no "AppImage" component that needs to be installed in order for AppImages to run.

Your issue looks like a support request for a specific AppImage. You need to contact the authors of that application. We just provide support for the core AppImage project, not for third-party packaging.

**Comment by SahajRana** [comment]
@TheAssassin, thanks for the reply. I guess I misused the word "install", I would say "run" a blup.appimage file. & "Blup" is maintained by our team. While I'm trying to create appimage of blup. It works fine on Ubuntu 20 version but not on Ubuntu 22.04. 

The bug seems to be coming from GTK-3 lib ([https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1922464](https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1922464)).

Here's the recipe I'm using to create appimage.

```
 include:
    - fonts-noto-color-emoji
    - fonts-ubuntu
    - glib-networking:amd64
    - gvfs:amd64
    - language-pack-gnome-en-base
    - libasound2-data
    - libasound2-plugins:amd64
    - libcanberra-gtk3-module:amd64
    - libcom-err2:amd64
    - libgtk-3-common
    - libidn11:amd64
    - libkeyutils1:amd64
    - liblzma5:amd64
    - libmount1:amd64
    - libnss-mdns:amd64
    - libnvidia-gl-470:amd64
    - libpcre3:amd64
    - libproxy1-plugin-gsettings:amd64
    - libproxy1-plugin-networkmanager:amd64
    - libsystemd0:amd64
    - libuuid1:amd64
    - transmission-common
    - vlc-plugin-base:amd64
    - yaru-theme-gtk
    - yaru-theme-icon
    - libvlc-dev
```

This lib `libgtk-3-common` got fix of this issue in version [gtk+3.0 3.24.25-1ubuntu4](https://launchpad.net/ubuntu/+source/gtk+3.0/3.24.25-1ubuntu4). But it seems to not be available in apt-
install i.e. 
`sudo apt-get install libgtk-3-0=3.24.25-1ubuntu4`  or 
`sudo apt-get install libgtk-3-0=3.24.33-1ubuntu1` or
``sudo apt-get install libgtk-3-common=3.24.25-1ubuntu4`  or `
It says this version is not available. Is there a way to resolve this?

**Comment by TheAssassin** [comment]
Thank you for clarifying this. What method do you use to build your AppImage?

**Comment by SahajRana** [comment]
I have followed this doc [https://appimage-builder.readthedocs.io/en/latest/examples/flutter.html](https://appimage-builder.readthedocs.io/en/latest/examples/flutter.html). It creates an `AppImageBuilder.yml` file as a recipe.

**Comment by TheAssassin** [comment]
Please contact the AppImageBuilder maintainers then. This issue is not related to AppImage itself, but this third-party tool.
