### ISSUE TITLE
Crash when launchin AppImage 

### ISSUE THREAD

**Issue by RafaelLinux** [AppImage/AppImageKit#1196]
`./appimagetool-x86_64.AppImage`
Output:
```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
SOURCE is missing
```

Operating System: openSUSE Tumbleweed 20220502
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.2
Kernel Version: 5.16.4-1-default (64-bit)
Graphics Platform: X11
Memory: 15.4 GiB of RAM

**Comment by probonopd** [comment]
Why do you think it is crashing?
It clearly says `SOURCE is missing`. So works as designed...

**Comment by RafaelLinux** [comment]
Well, you have reason. Not shows a "crash", simply exits without doing nothing but showing a message. I have changed the thread title to make it correct and easier to locate the same problem for others.

Thank you
