### ISSUE TITLE
Apps not running on Arch Linux 

### ISSUE THREAD

**Issue by Jzarecta** [AppImage/AppImageKit#12]
I got an arch linux installation, download the OpenOffice, Inkscape and gPodder and none of them would start. I chmod +x and did the ./app and got:
'No such file or directory'

Could it be that is not 32/64 bits?

Regards.

**Comment by vladgolubev** [comment]
> error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory

Have same issue when on one of the latest AMI (Amazon Machine Image)

Not sure, maybe this worth mentioning in README/docs/etc.

By the way, any ideas how to overcome?

**Comment by chrisnharvey** [comment]
@vladgolubev  Do you have fuse installed? You can install by running the following command:

```
pacman -S fuse
```

Its quite uncommon for this to not be installed though.

**Comment by vladgolubev** [comment]
@chrisnharvey The tricky part is I am running LibreOffice AppImage in AWS Lambda

Is it possible at all to provide `libfuse` alongside AppImage or any other way without installing it from linux distro repos?

**Comment by probonopd** [comment]
Interesting idea, why do you run LibreOffice AppImage in an AWS Lambda function and not in a normal AWS instance? Are you sure /dev/fuse is present and accessible in AWS Lambda functions? Then you could get libfuse from the distro, unpack it on your PC, and upload it for use by AWS.

**Comment by vladgolubev** [comment]
@probonopd actually I'm running it already in a normal AWS instance but there are reasons for Lambda.

I found something useful [here](https://github.com/probonopd/AppImageKit/wiki/FUSE):

> If you don't want to install FUSE, you can either mount or extract the AppImage.

So good, we have even two options.

#### Mount
```
sudo mount -o loop LibreOffice-5.2.2-x86_64.AppImage /tmp/
```

Tried to mount on EC2 instance and got `mount: wrong fs type, bad option, bad superblock on /dev/loop0`

Ok, maybe some crazy EC2 permissions, It will be easier just to unpack, right?

#### Unpack

That's a little bit obscure. Failed to find any info on how to unpack. Stumbled upon [this issue](https://github.com/probonopd/AppImageKit/issues/173) - so good. Tried Ark, File Roller, 7z to extract AppImage - all failed. Hm, what's the recommended way to extract an AppImage?

**Comment by probonopd** [comment]
You might have a type 2 AppImage. These require you to pass `-o offset=...` to the mount command. Run the AppImage with `--appimage-offset` to find out the correct number for the offset.

**Comment by vladgolubev** [comment]
@probonopd thanks, with `offset` I was able to mount it!

But I got further errors which are [not under your responsibility](https://lists.freedesktop.org/archives/libreoffice-bugs/2015-March/261686.html) 

```
$ ./AppRun --headless --quickstart --convert-to pdf sample.txt
$ /tmp/opt/libreoffice5.2/program/oosplash: error while loading shared libraries: libXinerama.so.1: cannot open shared object file: No such file or directory
```

So thanks for the help! I will continue looking for the solution.

BTW, maybe we should update Wiki with mounting instructions you wrote above. What do you think?

**Comment by vladgolubev** [comment]
@probonopd is it possible to modify [LibreOffice AppImage Recipe](https://github.com/probonopd/AppImages/blob/master/recipes/libreoffice/Recipe) to include `libXinerama` dependency into bundle?

**Comment by probonopd** [comment]
Theoretically you can do that, but `libXinerama` is supposed to be part of every target system. It is in any desktop distribution I know of.

**Comment by probonopd** [comment]
> BTW, maybe we should update Wiki with mounting instructions you wrote above. 

Added to the FUSE wiki page.

**Comment by vladgolubev** [comment]
@probonopd 

> any **desktop** distribution

That's the case, Amazon Linux distribution is not a desktop one.

So I am ok to create my custom build for my edge case. Hope it will be my last question. How do I  add  `libXinerama` dependency in a Recipe file?

**UPD: ** I am trying now to run the latest LibreOffice recipe locally I a get `run.sh: 210: ./functions.sh: Syntax error: "(" unexpected` 

Looks like after [one of your last commits](https://github.com/probonopd/AppImages/commit/6cd0703c742b25af0401e1049035a6d4e3439074)

I modified a recipe to use older `functions.sh` and it was built!

**Comment by vladgolubev** [comment]
As I understand, the line which I search for is `find ../ -name *.deb -exec dpkg -x \{\} . \;`. So it should be enough to put a `libxinerama-dev.deb` into a folder with other LibreOffice `.deb` packages? And it will be included into AppImage bundle? Sounds very promising

**Comment by probonopd** [comment]
> That's the case, Amazon Linux distribution is not a desktop one.

Right, but why don't you install `libXinerama` and the other [stuff that we assume to be part of every target system](https://github.com/probonopd/AppImages/blob/master/excludelist) into the base system, in order to be able to run unmodified AppImages?

**Comment by probonopd** [comment]
> So it should be enough to put a libxinerama-dev.deb into a folder with other LibreOffice .deb packages? And it will be included into AppImage bundle?

Yes.

**Comment by vladgolubev** [comment]
@probonopd 

> why don't you install libXinerama into the base system

I would like to, but as far as I know, you cannot install anything into container AWS Lambda is running in. All you can do - bring .zip file with your dependencies and binaries.

Sorry, I might confuse you with my unreasonable claims. I should mention the restriction above in the very beginning, as someone can be unfamiliar with Lambda service.

**Comment by probonopd** [comment]
You can probably just put it in there and use `LD_LIBRARY_PATH`...
