### ISSUE TITLE
Assignment of build-ID against algorithm other than SHA-1 not documented

### ISSUE THREAD

**Issue by Ricky-Tigg** [AppImage/AppImageKit#1200]
**General information**
```
$ uname -ro
5.18.9-200.fc36.x86_64 GNU/Linux
```
**AppImage file properties**
```
$ file -bk AppImage
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=6092ddf6a719ff37b93e84522102c50b097b86ad, stripped\012- data
```
Hello. As it appears to be, an application beiing in _AppImage_ format of **type 2** may be assigned a build-ID, which seems to be solely defined by the **SHA-1** algorithm. Seeking to assign a decent and non-insecure algorithm – which could be represented by one of the SHA-3 or SHA-2 family – i came to notice the lack of coverage in this regard in the current [manual](https://appimage-builder.readthedocs.io/en/latest/index.html).

**Comment by probonopd** [comment]
Hi @Ricky-Tigg, I don't think `BuildID[sha1]` is an AppImage specific thing. It's probably done by the compiler or other tooling that is not under the control of the AppImage project.

**Comment by Ricky-Tigg** [comment]
It seems to me that your assumption must be correct. Otherwise either you or an other developer from the team would have known that it belongs to that project.
