### ISSUE TITLE
Signing created a "Bad signature"

### ISSUE THREAD

**Issue by Diyou** [AppImage/AppImageKit#1205]
Changes within the last month seem to have broken some update-able images due to them having "Bad signatures"

Running the appimageupdatetool results in something that looks like:
```powershell
/usr/bin/gpg2: gpg: not a detached signature
Validation error: Bad signature
Restoring original file
exited with code 1
```
This is the case with appimagetool and linuxdeploy continuous builds.

Using the appimagetool 13 still works.

**Comment by TheAssassin** [comment]
You seem to be using outdated versions of both appimagetool and AppImageUpdate. The latest versions (i.e., continuous releases) should work.

**Comment by TheAssassin** [comment]
Fixed on master, build running.
