### ISSUE TITLE
Complex idea: installable appimages

### ISSUE THREAD

**Issue by godalming123** [AppImage/AppImageKit#1210]
# Preface
I feel like appimages are the closest we have to the perfect package management format theres only one problem. Since all dependency's are  packaged they take up lots of space compared to apps. Becuase when you install multiple apps they share dependencys.
# Idea
Could appimage *maybe* allow for apps to be installed. This would install all the dependencys to `/bin/name-version-arch` before installing the package to there.
# Advantages
- Users do not have to create desktop files (yes AppimageLauncher handles this well but its rarely included in distros)
- Space is saved by applications sharing dependency's
- Uninstalling appimages could be done by right clicking the desktop file

This is only an idea I expect it will be hard to implement but I think it would fix appimages only issues. I also do not mind if probono would not like to add this

**Comment by probonopd** [comment]
One of the key features of the AppImage format is that there is no need for applications to be installed.

You can extract AppImages with `--appimage-extract`, and then they become an AppDir.

If you would like desktop integration, there are various tools available:
https://github.com/AppImage/awesome-appimage/blob/main/README.md#desktop-integration

Installing applications is considered an anti-feature. The AppImage format was specifically made that each application is just a file which you don't have to install but can double-click in the file manager. Like mp3, mp4, txt files.
