### ISSUE TITLE
unable to run appimage

### ISSUE THREAD

**Issue by jhjacobs81** [AppImage/AppImageKit#1212]
I am running Arch, a fresh install and fully up to date, with KDE. When i try to download an appimage from https://apprepo.de/ i get the following error: 
```symbol lookup error: /usr/lib/libwayland-cursor.so.0: undefined symbol: wl_proxy_marshal_flags```
since i use GLIBC 2.36 i would think it should be possible to run them. This happens on several appimages from this site. And im not sure where i should look for the solution?

**Comment by probonopd** [comment]
Please report this to whoever has created the AppImage. This is not a bug in AppImageKit. Thanks!

**Comment by jhjacobs81** [comment]
Will do! But do you have any idea what way i should look?
