### ISSUE TITLE
Sign failed

### ISSUE THREAD

**Issue by julonexus** [AppImage/AppImageKit#1218]
Hi
I got this log on a debian9:
```
[sign] signing requested
[sign] found gpgme version 1.17.1
[sign] found gcrypt version 1.10.1
[sign] calculated digest: <digest>
[sign] using engine OpenPGP (found in /usr/bin/gpg), version 2.1.18, gpgme requires at least version 1.4.0
[sign] warning: gpg 2.1.x detected, APPIMAGETOOL_FORCE_SIGN can only work with allow-loopback-entry set within the gpg-agent configuration
[sign] using key with fingerprint <fingerprint>, issuer name <issuer name>
[gpgme] FAILURE: sign 83918950
[sign] gpgme_op_sign(gpgme_ctx, gpgme_appimage_file_data, gpgme_sig_data, GPGME_SIG_MODE_DETACH): call failed: Inappropriate ioctl for device
ERROR: signing failed, continuing
```

I used this script:
```
touch dummyToSign
gpg --pinentry-mode loopback --passphrase $5 dummyToSign
rm -f dummyToSign dummyToSign.gpg
./${WORK_DIR}/AppBin/appimagetool-x86_64.AppImage ${WORK_DIR}/AppDir --sign --sign-key "blablakey"
```

Is there an external configuration to do or a missing process in appimagetool?

**Comment by TheAssassin** [comment]
I have no idea what's going on there, but my best guess is you need to `export GPG_TTY=$(tty)`. Please try that.

**Comment by julonexus** [comment]
In fact, I don't know what to do with "allow-loopback-entry set within the gpg-agent configuration" ^^
After checking commits, I used "export APPIMAGETOOL_SIGN_PASSPHRASE=$5" instead of setting myself the pass.
(That don't change the issue as expected but it si cleaner :p)

Thanks, I'll try GPG_TTY

**Comment by julonexus** [comment]
There is still an issue but with something else : 
export GPG_TTY=$(tty)
```
[gpgme] FAILURE: sign 83918929
[sign] gpgme_op_sign(gpgme_ctx, gpgme_appimage_file_data, gpgme_sig_data, GPGME_SIG_MODE_DETACH): call failed: No such file or directory
ERROR: signing failed, continuing
```

**Comment by julonexus** [comment]
Git it. I'm closing the issue.
I'll write back what I've done after cleaning up all tests.

**Comment by julonexus** [comment]
The issue comes from the environment scope variable : 
appimagetool doesn't use the environment of the caller script so we can't use an 'export' inside the script.

I resolved it by setting APPIMAGETOOL_SIGN_PASSPHRASE in the yaml of the CI and that's it.

**Comment by TheAssassin** [comment]
> appimagetool doesn't use the environment of the caller script so we can't use an 'export' inside the script

Well I'd debate that. It's not appimagetool's fault when it can't see the environment variable. Also, I haven't seen any of your scripting, so I can't provide feedback.

**Comment by julonexus** [comment]
the script is https://gitlab.linphone.org/BC/public/linphone-desktop/-/blob/master/linphone-app/tools/create_appimage.sh#L96
My observation is :
- When setting APPIMAGETOOL_SIGN_PASSPHRASE before this line, there are no mention about using passphrase in logs
- When setting GPG_TTY, the behaviour of gpg change (different error).
So, gpg takes account of what appimagetool does not then I guess they use different environment.
