### ISSUE TITLE
What is alternatives for Ubuntu 22.04

### ISSUE THREAD

**Issue by anonygituser** [AppImage/AppImageKit#1219]
I am using Ubuntu 22.04, and I want to run an Appimage file. as there is mentioned that I should not install fuse on 22.04
> Warning: Do not install the `fuse` package as of 22.04 or you may break your system

then what should to run Appimages, because I can't run that without fuse. also I am unable to run that after extracting all it
is there any alternative for this.

**Comment by TheAssassin** [comment]
https://docs.appimage.org/user-guide/troubleshooting/fuse.html#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives

**Comment by probonopd** [comment]
`sudo apt install libfuse2`.

**Comment by seltzered** [comment]
Going back to the original comment by @anonygituser about "Warning: Do not install the fuse package as of 22.04 or you may break your system" in https://github.com/AppImage/AppImageKit/wiki/FUSE , is this true or should the wiki's documentation be updated to reference https://docs.appimage.org/user-guide/troubleshooting/fuse.html#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives ?

Came into this issue after updating to 22.10.

**Comment by probonopd** [comment]
`sudo apt install libfuse2` will not break your system (`sudo apt install fuse` might).

**Comment by seltzered** [comment]
Fun times, updated to 21.10 and did 'sudo apt install fuse' yesterday and
one of the things likely made my machine no longer boot to the lock screen.
