### ISSUE TITLE
how is possible create a appimage with firefox+java+program

### ISSUE THREAD

**Issue by JavierGallego** [AppImage/AppImageKit#1222]
Hi!, I'm so new with appimages, how is possible create an appimage with firefox + java + java applet? I see the guides but only explain for create a appimage from a single application. I need help.

**Comment by probonopd** [comment]
Normally, "one app = one file".

What is your use case?

**Comment by JavierGallego** [comment]
I like create a firefox+java+applet for use with system indeendence, but I don't know how to do that

**Comment by probonopd** [comment]
You can deploy all of those into the same AppImage and make sure that they invoke each other. I assume your program, which is written in Java, shall start, and then the bundled Firefox shall open?

**Comment by JavierGallego** [comment]
Hi, no I'm not programing, I have the idea for the app, but I don't know how to do that, can help me?

**Comment by probonopd** [comment]
Hi @JavierGallego, unfortunately I can't do that, sorry. Please ping me once you have something concrete that is not working that you need help with. Thanks!
