### ISSUE TITLE
[feature request] self installable appimage using --appimage-install command

### ISSUE THREAD

**Issue by ksharindam** [AppImage/AppImageKit#1223]
I know there is AppImageLauncher for desktop integration of AppImages. 
But it will be more cool, if we don't need anything external to install it.
By providing --appimage-install command, the appimage should install itself in specific location.
That means, copy AppImage to ~/.bin or ~/.local/bin
then copy the icon to ~/.local/share/icons.
then copy desktop file to ~/.local/share/applications, (Exec line must be replaced with absolute path of appimage).
And it will also print where these files were copied.

One can just download the AppImage, mark it executable and run
./someapp.AppImage --appimage-install
to install.

**Comment by probonopd** [comment]
AppImages do not need to be installed. Just set the executable bit and run.

https://discourse.appimage.org/t/how-to-run-an-appimage/80

If you would like desktop integration, please have a look at https://github.com/AppImageCommunity/awesome-appimage#desktop-integration and/or ask the team that produces your desktop environment to support AppImages natively. Thanks!
