### ISSUE TITLE
dlopen(): error loading libfuse.so.2

### ISSUE THREAD

**Issue by clin1234** [AppImage/AppImageKit#1225]
While running this: `https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage`,

 I got this error: `dlopen(): error loading libfuse.so.2`.

**Comment by probonopd** [comment]
Please install libfuse2.

**Comment by phil294** [comment]
Would it not be possible to show a message box to the user when `libfuse2` is missing? As AppImages are often explicitly meant to just be run via double click, it's pretty discouraging UX to just fail without information to the user. I don't think everyone can be expected to use the console.

Alternatively to popup - do a `notify-send`-like popup instead?
