### ISSUE TITLE
Question how to Stop Popups

### ISSUE THREAD

**Issue by thorrrr** [AppImage/AppImageKit#1228]
Morning anybody able to help me get rid of a constant popup see below

I tried adding an App image but it failed and i started getting these every few seconds so i used Timeshift to roll back and i thought it had worked
Never saw them again but this morning they started again

I saw the App image is not good for Wayland so need to stop these issues

![image](https://user-images.githubusercontent.com/8170673/211277317-f1d90b14-f2ab-422c-8270-27b1c8ff0c05.png)
![image](https://user-images.githubusercontent.com/8170673/211277341-dc0a8480-b376-431b-b90e-f8bfb493896a.png)

**Comment by probonopd** [comment]
Please follow the link there for more information.

**Comment by TheAssassin** [comment]
The real link is https://docs.appimage.org/user-guide/troubleshooting/fuse.html. People keep vandalizing the wiki page.

The docs will be online soon again. See https://github.com/AppImage/docs.appimage.org/issues/89 for more information.
