### ISSUE TITLE
appimage.org is down

### ISSUE THREAD

**Issue by bhrutledge** [AppImage/AppImageKit#1229]
Getting `ERR_CONNECTION_REFUSED` in Chrome. And it's not just me: https://downforeveryoneorjustme.com/appimage.org

**Comment by TheAssassin** [comment]
See https://github.com/AppImage/docs.appimage.org/issues/89. Waiting for @probonopd to adjust the DNS. I have no control over this.

**Comment by TheAssassin** [comment]
Temporary mirror on https://appimage-website.assassinate-you.net/ available. @probonopd will fix the DNS setup tonight.

**Comment by probonopd** [comment]
Up and running again. Thank you very much @TheAssassin.
