### ISSUE TITLE
Dpendency mismatch in GNOME system.

### ISSUE THREAD

**Issue by thecowmilk** [AppImage/AppImageKit#1235]
AppImage required dependency `fuse` to run AppImage binaries but `GNOME` needs `fuse3` to be run the way intended. Now, when you install `fuse` the `gnome` DE will crash and you can solve this by installing `fuse3` which then later won't be able to run AppImage bins. How can I run AppImages in `gnome` DE?

**Comment by probonopd** [comment]
Install libfuse2, it can be installed alongside libfuse3. If your distribution can't do that, I'd consider it a bug of the distribution.

**Comment by thecowmilk** [comment]
Why AppImage can not be coded with libfuse3 instead? I mean if it ain't that hard..

**Comment by thecowmilk** [comment]
But it works. Thanks.

**Comment by probonopd** [comment]
> Why AppImage can not be coded with libfuse3 instead? I mean if it ain't that hard...

Because older systems don't have it. We need stable interfaces to the base system, not constantly changing ones.
