### ISSUE TITLE
Flatpak integration

### ISSUE THREAD

**Issue by orowith2os** [AppImage/AppImageKit#1251]
Some Flatpak integration would be useful to AppImage since Flatpak is cross-distro (bundling glibc and some more common libraries that a host system might not contain), provides a stable ABI in it's runtime, and has sandboxing (it also sets XDG base directory variables, so apps don't clutter the home folder). Both AppImage and Flatpak are commonly used by projects, so some Flatpak integration in AppImage would help in distribution, since packagers then have an idea of what the application would need of the package.

Features that Flatpak integration would provide are as follows:

- A stable runtime, and more cross-distro portability than before. It would also be more efficient than bundling everything with an AppImage.
- Sandboxing, so app files are separate from the home folder and don't conflict with native apps, and apps only have access to what they need.
- Easy to use, as there aren't any dependency issues on the host system. If the user has used Flatpak, AppImage will work too. 
- Space efficient, since most dependencies are contained in flatpak runtimes. Any dependencies bundled in an AppImage won't be subject to deduplication like Flatpak has, but this is a pretty decent alternative.
- Easier Flatpak packaging, as AppImages would now define what permissions they need on the end users system.

This would mean that some projects, like QT helpers for AppImage, may become obsolete as they could just use the org.kde.Platform. It would also help address some use cases Flatpak doesn't support, such as portable and runnable application binaries.

Closes #152, #171, #225, #452, #839, #992. Possibly #116 as most every Linux distribution that's not Ubuntu supports Flatpak.

**Comment by probonopd** [comment]
That approach is like running another OS (with supposedly stable APIs and ABIs) on the real OS.
