### ISSUE TITLE
Should AppImages respect LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by shoogle** [AppImage/AppImageKit#126]
An interesting dilemma came up when looking for a solution to #125; I wanted to link an AppImage application against a different version of a library to the one that was included with the AppImage to see if the library was causing the problem. However, when I originally built the AppImage I had disabled LD_LIBRARY_PATH deliberately to prevent users from linking to external libraries accidentally, so I had to rebuild the AppImage just to do this simple test.

The question is: should users be able to override the libraries included in the AppImage with their own external libraries, or is the risk of this happening accidentally too great? Here are few possibilities:

AppRun launcher script: 

``` bash
# Entirely disable LD_LIBRARY_PATH by making it point only to the internal libs
export LD_LIBRARY_PATH="${APPDIR}/usr/lib"

# Check user's LD_LIBRARY_PATH after AppImage libraries but before system cache
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"

# Check LD_LIBRARY_PATH before anything else
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/usr/lib"

# Define a new environment variable APPIMAGE_LIBRARY_PATH
# specifically for overriding AppImage libraries
export LD_LIBRARY_PATH="${APPIMAGE_LIBRARY_PATH}:${APPDIR}/usr/lib"
```

Edit: The chosen preferred version is:

``` bash
export LD_LIBRARY_PATH="${APPIMAGE_LIBRARY_PATH}:${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
```

This means `ld` will look for libraries in the following places, in the order specified:
1. `${APPIMAGE_LIBRARY_PATH}` (if set by user)
2. AppImage internal internal libraries (`${APPDIR}/usr/lib`)
3. `${LD_LIBRARY_PATH}` (if set by user)
4. System library cache (`/etc/ld.so.cache`).

**Comment by probonopd** [comment]
So far I have been in favor of `export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"` and I've never ran into situations where this was not sufficient but I am entirely open to go for a better solution if required.

Keep in mind that you can also LD_PRELOAD certain libraries which will then take precedence in any case.

**Comment by RazZziel** [comment]
Same here, I use `LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"`.

In theory `LD_LIBRARY_PATH="${APPDIR}/usr/lib"` should be enough, but in practice we usually can't include absolutely **all** the libraries needed to run a binary, specially `libGL.so.1` (because it depends on each user's particular graphics adapter), so it's good for the base system to retain some control over where those libraries can be. For instance, I think on Optimus laptops, optirun uses some kind of LD_LIBRARY_PATH or LD_PRELOAD trick in order to load Nvidia's libGL.so.1 instead of Intel's.

`"${LD_LIBRARY_PATH}:${APPDIR}/usr/lib"` is too much control, that' going to break applications on some systems, and I don't see the value of `"${APPIMAGE_LIBRARY_PATH}:${APPDIR}/usr/lib"`

**Comment by shoogle** [comment]
Right, so it seems best to have $LD_LIBRARY_PATH checked last. The value of $APPIMAGE_LIBRARY_PATH is that I can deliberately override the AppImage's internal libraries with some external ones if I really want to. It's much easier than using $LD_PRELOAD if I want to override many, e.g. to try linking against a different Qt.

**Comment by RazZziel** [comment]
Oh, that's indeed interesting then:
```
export LD_LIBRARY_PATH="${APPIMAGE_LIBRARY_PATH}:${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
```

**Comment by probonopd** [comment]
I think calling it "APPIMAGE_LIBRARY_PATH" is confusing though because these libraries are _not_ inside the AppImage. Better call it `OVERRIDE_LIBRARY_PATH` or something like that?

**Comment by RazZziel** [comment]
Indeed, better

**Comment by shoogle** [comment]
Hmm, but this is specifically for AppImages, and it is there to set the libraries that the AppImage will use. It's not actually possible to link to a file *inside* the AppImage from outside, and I can't why you would want to do that, so I doubt there would be any confusion. Happy to change it though if you still prefer OVERRIDE_LIBRARY_PATH.

**Comment by probonopd** [comment]
Correct me if I'm wrong but the libraries in the path we are discussing _override_ (take precedence over) the ones in the AppImage. Correct?

**Comment by shoogle** [comment]
That is correct, but this variable would be specifically for AppImages, it would have no value for ordinary executables. If a user saw `OVERRIDE_LIBRARY_PATH` they might think it was a pre-existing standard and not think to associate it with AppImages.

**Comment by estan** [comment]
I like `APPIMAGE_LIBRARY_PATH` best. It's analogous to `LD_LIBRARY_PATH` but specifically for AppImages. E.g. the `LD_LIBRARY_PATH` is not called `LD_OVERRIDE_LIBRARY_PATH`, yet it's purpose is to override the linker search path. I think peopler will understand the symmetry.

Could of course call it `APPIMAGE_OVERRIDE_LIBRARY_PATH`, but that's quite long. It's so common that an environment variable is used for overriding some behavior, so I don't think it needs to be part of the name in this case.

**Comment by shoogle** [comment]
FWIW, [snaps](https://developer.ubuntu.com/en/snappy/guides/security/) use `SNAP_LIBRARY_PATH`, so `APPIMAGE_LIBRARY_PATH` is good for consistency.

**Comment by probonopd** [comment]
Wouldn't all of this best be handled by a custom AppRun script? That way, only apps that need this (probably few) will be confronted with it.

**Comment by shoogle** [comment]
@probonopd that's what I was suggesting, but it makes sense if everyone who does this with an AppImage uses the same name for the environment variable.

**Comment by probonopd** [comment]
OK I see - so more a suggestion for the Wiki then?

**Comment by probonopd** [comment]
Closed since you can use a custom `AppRun` to do however you like.
