### ISSUE TITLE
execv error: Exec format error The command could not be found

### ISSUE THREAD

**Issue by coffseducation** [AppImage/AppImageKit#1267]
Hey all! I am trying to build Cantata. I have not done an appimage before.
The appimage will not launch though! 

I get execv error: 
"Exec format error " in terminal
"The command could not be found." in Dolphin.

AppRun opens Cantata if I drag it to the terminal - but not if I double click. The desktop file opens Cantata - but the appimage will not launch.

#!/bin/bash

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
EXEC="${HERE}/usr/bin/cantata"
exec "${EXEC}"

Could it be a path issue?

 Files here is anyone could help: https://nextcloud.barkingbandicoot.com/index.php/s/x7WZTRJiz9mZaHL

appimagetool 13

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-1003-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700 CPU @ 3.40GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: Dell Inc.
Product Name: Precision 5720 AIO

**Comment by FwarkTheYeti** [comment]
same issue with sonixd 0.15.5 on kubuntu 23.04 - was working a month ago, exact same - appimage file now won't run, same errors in terminal/dolphin 

https://github.com/jeffvli/sonixd/releases

Sonixd-0.15.5-linux-x86_64.AppImage 

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20 Generic
Graphics Platform: Wayland
Processors: AMD Ryzen 9 7950X
Memory: 64 GiB of RAM
Graphics Processor: AMD ATI Radeon RX 7900 XT

**Comment by probonopd** [comment]
Hi, this doesn't look like an issue in AppImageKit. Please file a bug on the tool you are using to make the AppImage (e.g., go-appimage, linuxdeploy, etc.). Thanks!
