### ISSUE TITLE
Set the original argv0 via execv

### ISSUE THREAD

**Issue by ilya-fedin** [AppImage/AppImageKit#1269]
Currently the runtime sets the original argv0 as an environment variable. But it really should provide it via execv instead of passing the path to AppRun so the application (and toolkit) can have the original argv0 without special-casing for appimage.

**Comment by probonopd** [comment]
Hello @ilya-fedin. Can you give an example? E.g., what does not work today, what would we need to make it work?

**Comment by ilya-fedin** [comment]
I'd like to be able to get the path to the appimage without special-casing for creating .desktop files, restarting the application, etc. It's also kind of standard for wrappers (and I would say the runtime is a wrapper) to preserve the original argv0.

**Comment by probonopd** [comment]
Sorry @ilya-fedin I had a long working day and I can't figure out what exactly you need.

So, can you please give a concrete example, like: I would like to use the follwowing command line:

```
...
```

As of today, __A__ happens but __B__ should happen. To make it happen, the following change would be needed in the source code:

```
...
```

**Comment by ilya-fedin** [comment]
Nevermind, looks like I've misread runtime.c source, it already works as I want it to

**Comment by probonopd** [comment]
That'ts always the best option :+1:
