### ISSUE TITLE
Vulkan support incomplete for Intel and AMD GPUs (Mesa), missing vulkan loader/vulkan drivers/headers

### ISSUE THREAD

**Issue by tuxayo** [AppImage/AppImageKit#1270]
Sorry if this isn't the right repository.
In the context of someone making an AppImage for 0ad: https://discourse.appimage.org/t/vulkan-disabled-when-running-0ad-appimage-with-intel-or-amd-chipsets/2908

Only with the NVIDIA proprietary driver Vulkan support is detected.

I’ve been told in the Mesa chat (#dri-devel@OFTC IRC) that something like this is missing: probably the vulkan loader, probably also mesa vulkan drivers and maybe also the headers to build against.

Does that make any sense?

For OpenGL support there wasn't any work necessary so the AppImage building toolchain definitely includes all the necessary stuff for OpenGL support for Mesa drivers.

**Comment by probonopd** [comment]
Maybe some additional libraries need to be bundled inside that particular AppImage. I am not sure which ones, though.

**Comment by tuxayo** [comment]
> Maybe some additional libraries need to be bundled inside that particular AppImage.

If we consider Vulkan support to be particular yes. But IMHO it should have the same kind of support as OpenGL. Any game using Vulkan can for now be expected to find itself having OpenGL working out of the box and Vulkan not. Another libre game, Veloren [1], only uses Vulkan.

The current AppImage building script of 0ad doesn't seem to have anything done to get OpenGL or audio working.
https://github.com/0ad-matters/0ad-appimage/blob/trunk/workflow.sh

>  I am not sure which ones, though.

That will be the next step I can go ask about ^^

> Most likely it is not an issue in AppImageKit. (If it is, i'm happy to reopen this issue here.)

Games are one of the software classes that has the most to benefit from shipping AppImages [2] so having Vulkan baked in the same way as OpenGL is would be great.

[1] For more mainstream ones there at least (very quick search), Doom Ethernal, No Man's Sky (2.0 update), Wolfenstein II, sure they will never get an AppImage but they were all games that in previous versions had an OpenGL renderer and now went Vulkan only.
Anyone wanting to package a Windows game in an AppImage with proton (and thus DXVK) will also be in a Vulkan only situation. That scenario would great for game devs wanting to officially support Linux for existing games/engines as an alternative to doing it via Steam.

[2] we can confidently say at least 1/3 and likely more than half Linux users have an outdated 0ad version in their repos, so they can't play together with their Windows-using friends. Which is embarrassing, libre games and Linux should work best together. And the at least a 1/3 is now, in one of the best moment in the last two years regarding schedules. Just wait two months for the next yearly 0ad release and even a month after it will be still more than 80% of users having an outdated version when only Arch, Tumbleweed and Fedora would have it packaged and available **out of the box** (even having to enable backports on Debian is questionable UX for general public game usage, and there are no backport repos on Ubuntu...). And let's not even talk about day 1 or week 1 availability. But AppImage to the rescue! :heart:

**Comment by probonopd** [comment]
Hi @tuxayo, thanks for the additional information. However, this repository only holds tools to convert AppDirs to AppImages. It holds no tools to make AppDirs, or to decide what goes into them. (Like a zip tool only converts files into the zip file format without caring what it actually is that goes inside the zip file.)

**Comment by andy5995** [comment]
@tuxayo On my laptop where the 0ad appimage failed (with Intel GPU), only the Ubuntu Focal and Bionic image failed to detect vulkan. I also tested a Jammy AppImage, and that worked. So... the problem seems to be at the "distro"-level.

**Comment by tuxayo** [comment]
So was it building on Ubuntu 22.04 or installing libvulkan-dev or both?

**Comment by tuxayo** [comment]
> However, this repository only holds tools to convert AppDirs to AppImages. It holds no tools to make AppDirs, or to decide what goes into them. (Like a zip tool only converts files into the zip file format without caring what it actually is that goes inside the zip file.)

> only the Ubuntu Focal and Bionic image failed to detect vulkan. I also tested a Jammy AppImage, and that worked. So... the problem seems to be at the "distro"-level.

Oh :open_mouth:  so the whole AppImage toolchain (not just this repo) doesn't actually have anything to do with OpenGL and audio working out of the box? It's just the distro were the AppDir is made that rules this?

**Comment by andy5995** [comment]
> Oh open_mouth so the whole AppImage toolchain (not just this repo) doesn't actually have anything to do with OpenGL and audio working out of the box? It's just the distro were the AppDir is made that rules this?

I'm not an expert, but I'd say that's a fair assessment for the most part. I actually use [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) to create the 0ad appimage:

>linuxdeploy is designed to be an AppDir maintenance tool. It provides extensive functionalities to create and bundle AppDirs for applications. It features a plugin system that allows for easy bundling of frameworks and creating output bundles such as AppImages with little effort.

In `workflow.sh' where I call `AppRun` to build the image, that's using linuxdeploy (which is [installed when I create the docker image](https://github.com/0ad-matters/0ad-appimage/blob/1e7295640277896cfb66c307653bb16e79a8d088/Dockerfile-focal#L43-L45)).

linuxdeploy seems to copy required libraries into the AppDir (you can usually see required libraries of a binary by using the `ldd` command, btw). I also use the [gtk plugin](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk) to copy files required by apps that are linked to gtk.

**Comment by probonopd** [comment]
> Oh open_mouth so the whole AppImage toolchain (not just this repo) doesn't actually have anything to do with OpenGL and audio working out of the box?

Exactly. AppImageKit is a low-level tool that just deals with the AppImage file format, not with what goes into the actual AppImages.

> It's just the distro were the AppDir is made that rules this?

The disto and the (higher-level) [tools](https://github.com/AppImageCommunity/awesome-appimage#deployment-tools-for-compiled-applications).

**Comment by tuxayo** [comment]
> AppImageKit is a low-level tool that just deals with the AppImage file format, not with what goes into the actual AppImages.

> The disto and the (higher-level) [tools](https://github.com/AppImageCommunity/awesome-appimage#deployment-tools-for-compiled-applications).

Sorry that I wasn't explicit enough. When I meant "Sorry if this isn't the right repository."  and "the whole AppImage toolchain (not just this repo)"
It was in the case that I wasn't in the right repo but that the issue still had relevance somewhere else in the AppImage usual ecosystem.

So my last message was to confirm if the issue has nothing to something to do with the AppImage ecosystem or if it's only the building distro. But it's seems it might have something to do.

IIUC, should I go to linuxdeploy and ask if that's where the stuff that make OpenGL and audio work out of the box is happening?
