### ISSUE TITLE
Continuous Blocking Notifications

### ISSUE THREAD

**Issue by dmillar-vx** [AppImage/AppImageKit#1271]
On my Fedora system, I'm getting a continuously repeating notification stating "Cannot mount AppImage, please check your FUSE setup." After dismissing the notification, a new one pops up immediately. My machine just came back on from a power outage and it's not immediately obvious what is trying to make use of the AppImage. Is there a way to silence the notifications, or a way to detect from the notification what AppImage is trying to be used?

**Comment by probonopd** [comment]
So... did you check your FUSE setup?

**Comment by dmillar-vx** [comment]
> So... did you check your FUSE setup?
> 
> https://github.com/AppImage/AppImageKit/wiki/FUSE

I checked and it appeared to be up to date and running as expected. Since I didn't know what was attempting to run, I was unable to troubleshoot further than checking the installation. I've since rebooted and no longer have the issue, but it would be useful to know how to get the information I asked about in my original post for future troubleshooting.

**Comment by probonopd** [comment]
> detect from the notification what AppImage is trying to be used

If these notifications keep popping up, then possibly you have configured your system to autostart an application that comes as an AppImage. Which one, you can likely find out by running `ps ax` in a terminal or using a process monitor.
The notification does not tell you which application your system is trying to start. But your system should be able to tell you that ;-)

>  Is there a way to silence the notifications

Only by fixing the underlying problem, which is that the FUSE setup on your system is not working. https://github.com/AppImage/AppImageKit/wiki/FUSE describes how to do that. Especially, I'd double check whether libfuse2 is present on the system.
