### ISSUE TITLE
How to work around a package needing a newer glibc version?

### ISSUE THREAD

**Issue by hwittenborn** [AppImage/AppImageKit#1274]
I've been trying to figure this out for a while, but is there any way I can work around programs in an AppImage needing a glibc version more recent than the one on the host system?

I've yet to find out any solution, but I'm thinking there's got to be one since Snaps and Flatpaks manage the backporting of glibc versions just fine. I just have no clue how I could do the same with Flatpak.

Is there any known ways to do what I'm wanting?

**Comment by hwittenborn** [comment]
I've tried linking glibc into my program, but for some reason it always leads in a segmentation fault. I'm not really sure what might be causing it, I could send over any needed info if it'd help though.

**Comment by hwittenborn** [comment]
Just did some Googling, and [this post on Stackoverflow](https://stackoverflow.com/a/851229) got me my answer. I just started my executable with the linked `ld-linux` library and it all worked fine.

I've been trying to get this all working for the past few months on and off so I can't guarantee I've reached my solution, but I'll reach out if there's any other issues I have.

**Comment by probonopd** [comment]
Check https://github.com/probonopd/go-appimage/tree/master/src/appimagetool `-s deploy` to bundle _everything_ including glibc ld-linux.

**Comment by hwittenborn** [comment]
Just found out about the linuxdeployqt tool earlier, looks like that Go tool would be a bit nicer to use though. Thanks!

**Comment by probonopd** [comment]
linuxdeployqt does not have the capability to bundle _everything_.
