### ISSUE TITLE
ArchImage: bundle Arch Linux packages for all distributions using Junest

### ISSUE THREAD

**Issue by ivan-hc** [AppImage/AppImageKit#1275]
Hi all, I'm working on a new idea to bundle the AppImages for any distro, old and young, I've named it ArchImage

https://github.com/ivan-hc/ArchImage

This is a video on how I bundle OBS Studio

https://user-images.githubusercontent.com/88724353/249807163-6335f0c4-c274-4e6c-9360-d22a24bb8594.mp4

The AppImage uses JuNest as a base

https://github.com/fsquillace/junest

# What works
The script can built the AppImage and made it work for the users that creates it, for its account

# What not works
Portability https://github.com/ivan-hc/ArchImage/issues/1 :

- If you create the AppImage without you remove /home from the AppDir, it works fine, but only for you;
- It wont work if you create a directory *.home with the same name of the AppImage;
- it wont work if you put the AppImage on another PC (I've also tried GitHub actions... no success).

All I know is that I receive always the same error in all the cases above, If I don't include an /home directory into it:

    bwrap: Can't mkdir /home/ivan: No such file or directory

I think I have to include an anvironment variable into the AppRun

More details in the issue https://github.com/ivan-hc/ArchImage/issues/1

**Comment by probonopd** [comment]
Hi @ivan-hc, thanks for sharing.

> 
it wont work if you put the AppImage on another PC (I've also tried GitHub actions... no success).

...so it's pretty much broken, isn't it?

**Comment by ivan-hc** [comment]
Hi, I've solved the issue https://github.com/ivan-hc/ArchImage/issues/1#issuecomment-1616067533

Thank you!
