### ISSUE TITLE
Is it safe to use the continous builds in production programs?

### ISSUE THREAD

**Issue by hwittenborn** [AppImage/AppImageKit#1276]
I'd like to integrate the AppImage runtime with a program I'm working on, but it looks like the last versioned release was made over 2 years ago.

Is it safe to use the continuous builds if I'm building production-targeted programs, or is there some place else I should get the runtime from?

**Comment by TheAssassin** [comment]
It's perfectly fine for the time being. Our `master` can be considered stable.

That said, we are currently discussing making releases in the future. We'll keep you updated.
