### ISSUE TITLE
Installing AppImageLauncher breaks Endless-Sky 0.10.2 AppImage

### ISSUE THREAD

**Issue by nmates** [AppImage/AppImageKit#1277]
Short description: XUbuntu 22.04 x64 box, all updates apt-gotten. AppImageLauncher installed from PPM. Endless Sky v0.10.2 from https://github.com/endless-sky/endless-sky/releases/tag/v0.10.2 was able to cmdline launch before installing AppImageLauncher . After installing AppImageLauncher, trying to launch errors with a "execv error: No such file or directory"

Longer description:
1. Have repro'd this on two boxes here.
2. Xubuntu 22.04, all updates fetched and installed. (Last checked 2023/07/10). Kernel is stock plus Nvidia 525/530 drivers installed. Also libfuse2, libfuse3 installed
3. Download Endless-Sky 0.10.2 from https://github.com/endless-sky/endless-sky/releases/tag/v0.10.2 . Using latest Firefox, but I don't think that's related to this issue.
4. From cmdline, chmod +x ~/Downloads/Endless_Sky-v0.10.2-x86_64.AppImage . Then execute "~/Downloads/Endless_Sky-v0.10.2-x86_64.AppImage". Note that the game launches to the main menu
5. Install from ppa as documented at https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian . Stable release channel is picked
6. Re-execute "~/Downloads/Endless_Sky-v0.10.2-x86_64.AppImage" . AppImageLauncher window appears. Accept ~/Applications as the dest location, pick install and run. Note that it does not launch. 
7. From cmdline, execute "~/Applications/Endless_Sky-v0.10.2-x86_64.AppImage". It errors out with a "execv error: No such file or directory"

What I've done to troubleshoot:
- Re-download the AppImage from site, diff the files in ~/Downloads , diff that against copy in ~/Applications . Identical
- Doing an apt search on AppImageLauncher shows this version: appimagelauncher/jammy,now 202211022349-stable-0f91801~ubuntu22.04.1 amd64 [installed]
- I ran "strace ./Applications/Endless_Sky..." , stderr captured. That is attached. in the .zip
- Download FreeCAD 64-bit appimage from https://wiki.freecad.org/Download . Using AppImageLauncher, it copied to ~/Applications, and launches fine
[log_err.zip](https://github.com/AppImage/AppImageKit/files/12005080/log_err.zip)

**Comment by probonopd** [comment]
Hello @nmates. Please report AppImageLauncher issues at
https://github.com/TheAssassin/AppImageLauncher/issues
