### ISSUE TITLE
Segfaults with squashfuse 0.3

### ISSUE THREAD

**Issue by Aya-Komichi** [AppImage/AppImageKit#1280]
With squashfuse version 0.3 on arch linux every appimage throws a `Segmentation Fault (cored dumped)`, rendering appimages unusable. I have no idea if this is breaking change or a bug on fuse so I am reporting this here for now.

**Comment by probonopd** [comment]
Hi. What do you mean by "with squashfuse version 0.3 on arch linux"?
You get crashes when squashfuse is installed? What happens if you uninstall squashfuse?

**Comment by Aya-Komichi** [comment]
> Hi. What do you mean by "with squashfuse version 0.3 on arch linux"? You get crashes when squashfuse is installed? What happens if you uninstall squashfuse?

Well, in my installation I am using the appimagelauncher for the appimage integration, which depends on the libappimage package which also depends on squashfuse.

I was recommended to report the issue here, but if you believe this is not the right place for this then close this issue and if possible point me the right place for my report.

**Comment by probonopd** [comment]
> appimagelauncher

Please report appimagelauncher issues over at https://github.com/TheAssassin/AppImageLauncher/issues, thanks.
