### ISSUE TITLE
Appstream generator 404s

### ISSUE THREAD

**Issue by RunningDroid** [AppImage/AppImageKit#1288]
This warning:
```
 WARNING: AppStream upstream metadata is missing, please consider creating it
          in usr/share/metainfo/example.appdata.xml
          Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
          for more information or use the generator at http://output.jsbin.com/qoqukof.
```
says to use the appstream generator at http://output.jsbin.com/qoqukof, but that presents a 404 page.
The version on Archive.org appears usable, but won't update if/when the spec changes: https://web.archive.org/web/20200917004716/https://output.jsbin.com/qoqukof

**Comment by probonopd** [comment]
Thanks for reporting. The AppStream generator has moved to 
https://docs.appimage.org/packaging-guide/optional/appstream.html
