### ISSUE TITLE
Ability to set restriction to internet and file access by user

### ISSUE THREAD

**Issue by amiyatulu** [AppImage/AppImageKit#1291]
Though there are ways to restrict internet access for an app through [commands](https://fedingo.com/how-to-restrict-internet-access-for-programs-in-linux/), one need simple ui interface to restrict the access of internet to AppImage and restrict ability to only access particular folders by AppImage. It will be a good security measure. Not sure its need to be implemented in AppImageKit or in third party apps like [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)
Users can also set the time to automatically remove app permissions after a given period. This could include disabling permissions after 5 minutes, after closing the app, after a day, or after a week.

**Comment by probonopd** [comment]
This is not in the scope of the AppImage file format. It is something that might be implemented in tools like https://github.com/probonopd/go-appimage `appimaged`.
