### ISSUE TITLE
xdg-open on Ubuntu 22.04 refuses to open links

### ISSUE THREAD

**Issue by Sytten** [AppImage/AppImageKit#1293]
Hi there!
I am scratching my head real hard on this one.
When I try to execute `xdg-open` (which in turns executes `gio`) in Ubuntu 22.04 using an URL it always return the error:
```
cannot open path of the current working directory: Permission denied
```
It doesn't do this on Ubuntu 20.04. It also doesn't do it for file paths.
I tried a bunch of ideas from https://github.com/AppImage/AppImageKit/issues/124 but they don't seem to help.
I figured I would open an issue since it likely affects of programs and I could not find anything about that issue elsewhere.
Thanks!

**Comment by Sytten** [comment]
Ok so I continued to dig into it.
It turns out it tries to open firefox in the current directory which is something like `/tmp/.mount_caido_WtV9g9/usr` in my case.
But firefox fails to open in that mount directory, so if you `cd $HOME` before it works.
I have no idea why this is a problem in Ubuntu 22.04 and not in early versions...

**Comment by probonopd** [comment]
Sounds like something that would need to be addressed in `xdg-open`?

**Comment by Sytten** [comment]
I don't know, I guess so. I just find it weird that I could not find anything on the internet about that. I dont think there is anything actionable from appimage.
