### ISSUE TITLE
Adding Github Sponsorship option

### ISSUE THREAD

**Issue by hopelessdecoy** [AppImage/AppImageKit#1296]
Is there anyway Appimages could be sponsor-able on Github? PayPal is great and all but this method would be directly connected and accessible via the repo for monthly donations. KDE does it and it's nice!

**Comment by TheAssassin** [comment]
I don't think that the project would benefit from donations at this point. For instance, I donate the resources to run the website. Other than that, we don't have any expenses, and receiving money is not a motivation (at least for me) to try and dedicate more time to this project. This is a hobby at this point.

That said, thank you for your generous offer.
