### ISSUE TITLE
[docs] Add fedora fuse-libs to the wiki

### ISSUE THREAD

**Issue by p-fruck** [AppImage/AppImageKit#1298]
The [wiki entry](https://github.com/AppImage/AppImageKit/wiki/FUSE) for fuse states that the package `fuse` should be installed on fedora. However it seems that `fuse` as well as `fuse-libs` are required. This is a common problem when using an appimage inside a distrobox running a Fedora variant (rawhide in my case).

**Comment by p-fruck** [comment]
@probonopd  I've modified my original comment (pressed enter too early :smile:). The issue is that rawhide in a distrobox ships with `fuse` preinstalled, but the `fuse-libs` package is missing. For that reason, I'd like to request the dnf install command for Fedora being changed to `dnf install fuse fuse-libs`. Unfortunately, I am not able to submit a PR for the wiki myself because of insufficient privileges

**Comment by probonopd** [comment]
So you run AppImages inside Fedora which runs inside Distrobox? And does it actually work for you after installing `dnf install fuse fuse-libs`?
