### ISSUE TITLE
Run built AppImage on Yocto

### ISSUE THREAD

**Issue by letanphuc** [AppImage/AppImageKit#1311]
Hi developers,
I'm try to run a built AppImages file (https://github.com/koreader/koreader/releases/tag/v2024.01) on my own built Linux distro based on Yocto project.
File cannot be run on QEMUx86-64, but I can run fine on my Desktop Ubuntu.

```
root@qemux86-64:/# chmod +x koreader-appimage-x86_64-linux-gnu-v2024.01.AppImage 
root@qemux86-64:/# ./koreader-appimage-x86_64-linux-gnu-v2024.01.AppImage 
-sh: ./koreader-appimage-x86_64-linux-gnu-v2024.01.AppImage: No such file or directory
```
Any package or requirement we need to run this file?

**Comment by TheAssassin** [comment]
QEMU's static binaries (via `binfmt_misc` or directly) do not like the AppImage magic bytes. You must make your AppImage a "regular binary" to be able to launch it in your setup. Please beware this is a workaround and you should NOT distribute the binary then: `dd if=/dev/zero of=koreader-appimage-x86_64-linux-gnu-v2024.01.AppImage bs=1 count=3 seek=8 conv=notrunc`

**Comment by letanphuc** [comment]
I resolved it. Problem is missing libraries in /lib64 directory. This directory is not available in Yocto Rootfs
