### ISSUE TITLE
Some Appimages stopped showing icons.

### ISSUE THREAD

**Issue by Giger22** [AppImage/AppImageKit#1314]
As in description, some AppImages in my collection stopped properly showing icons.

**Comment by probonopd** [comment]
Hi @Giger22, this is very unlikely to be an AppImageKit issue, as AppImageKit is not involved in "properly showing icons". 

Where do you see wrong icons? What icon are you seeing instead?

**Comment by Giger22** [comment]
I see this instead. [Icon](https://imgur.com/YWghKkk)
In some Appimage apps that were integrated into a system. Some stopped showing while other still show a proper icon.

$ echo $XDG_SESSION_TYPE
$ wayland

**Comment by probonopd** [comment]
Please show a full screenshot. Where do you see this icon? In your file manager? (Which one?) In your task bar?

Which Linux distribution are you running?

**Comment by Giger22** [comment]
Artix Linux, OpenRC, KDE Wayland.
[screenshoot](https://imgur.com/SYgpMv2)
I see this "icon" in Dolphin file manager and in a taskbar. Although, some Appimages that do not show their proper icons in Dolphin FM show their proper icons in a taskbar manager but some do not show in both cases. In other cases as in the screenshot I see X.11 logo on a taskbar.

**Comment by probonopd** [comment]
Which desktop integration tool created these desktop files?

**Comment by Giger22** [comment]
oh, yeah. AppImage Launcher... so it is probably its fault...

**Comment by probonopd** [comment]
> in a taskbar

> Wayland

In Wayland setting icons is broken as long as https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269 is not implemented in the Wayland compositor you are using.
