### ISSUE TITLE
Monochrome logo

### ISSUE THREAD

**Issue by AesaraB** [AppImage/AppImageKit#1315]
Hey, I created this svg of the AppImage logo for a download button on a website I'm making.

I'm not sure if the project's resources are licensed permissively, but if they are then I dedicate the following svg under the same license as ``/resources/appimagetool.svg`` in this repository.

![appimage-monochrome](https://github.com/AppImage/AppImageKit/assets/64518882/e6b489df-e704-4c06-9bd6-3773aab7d603)

**Comment by probonopd** [comment]
Thank you very much @AesaraB
