### ISSUE TITLE
Setting XDG_DATA_DIRS causes issues

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#132]
As reported [here](https://github.com/probonopd/AppImageKit/issues/124#issuecomment-205486221) setting XDG_DATA_DIRS causes issues in [AppRun.c](https://github.com/probonopd/AppImageKit/blob/21cd361e80de0f66adf666466618baa0bcc80251/AppRun.c#L44) can cause issues ( Invoking the browser from an AppImage does not work, #124). Please comment here if you run into the same issue too.

**Comment by probonopd** [comment]
The best behavior would probably be to set $XDG_DATA_DIRS to `$APPDIR/usr/share:$HOME/.local/share:/usr/local/share/:/usr/share`?

**Comment by azubieta** [comment]
No additional issues reported so far. Closing it.

**Comment by easyw** [comment]
Hi @probono
I'm having a similar issue trying to open pdf files from inside AppImages running xdg-open pdf-filename.
This instead works using the deb package.

**Comment by probonopd** [comment]
Which AppImage are you opening talking about? AppImages that allow launching other applications (external to the AppImage itself) should use an exec wrapper to avoid this sort of issues.

https://github.com/AppImage/AppImageKit/issues/396

Please file a ticket with the application that is launching external applications.
