### ISSUE TITLE
Static appimage with new runtime gives a strange error on a Pop OS! 22.04 computer 

### ISSUE THREAD

**Issue by jcelerier** [AppImage/AppImageKit#1325]
I have a very strange case with https://github.com/ossia/score/releases/download/continuous/ossia.score-master-linux-amd64.AppImage

It seems to work fine on my computer and others, but there's a specific Pop! OS 22.04 machine where it fails with "execv format error" (everything involved is x86_64 only). 

- `--appimage-extract` also does not work: it says that it's an invalid squashfs image. I thought it would be some kind of download corruption but the SHA sums matches with the ones I see on the other computers.
- libfuse2 and fuse3 are installed
- Previous versions (with the dynamically linked runtime) work fine on this computer. e.g.  this one is working : https://github.com/ossia/score/releases/download/v3.1.13/ossia.score-3.1.13-linux-amd64.AppImage 
- Same computer on another OS (Arch Linux) : the appimage works fine.

I'm a bit at loss to where to look, especially considering --appimage-extract does not work. What would be the next steps in troubleshooting this ?

**Comment by probonopd** [comment]
Interesting!

Can you run it with `strace` to see where it fails?

**Comment by probonopd** [comment]
Can you please retry with the latest https://github.com/AppImage/type2-runtime/releases/tag/continuous build?
We have changed a lot there.

If you want to try:
https://github.com/AppImage/appimagetool/releases/tag/continuous uses it.

Thanks for retesting.

**Comment by jcelerier** [comment]
hi ! since then the person who had the laptop showing this issue changed machine so I can't really try anymore... I'll close the issue as I don't think it's too useful to keep open. 
That said, I think it was the same issue than this: https://github.com/ossia/score/issues/1548  / https://github.com/probonopd/go-appimage/issues/242 ; the presence of appimagelauncher on the target computer seems to make things go bust.
