### ISSUE TITLE
LinuxDeploy+AppImage don't handle all SDL2 dependencies + glibc version mismatch

### ISSUE THREAD

**Issue by cslr** [AppImage/AppImageKit#1335]
When I build AppImage on Debian Linux trixie the software don't include all SDL2 (X11) libraries and has to installed using apt. Also glibc and glibcxx dependencies require new glibc and glibcxx and I have to update from Debian stable to Debian testing.

**Comment by probonopd** [comment]
Hello @cslr, please report linuxdeploy issues to https://github.com/linuxdeploy/linuxdeploy. Thanks.
