### ISSUE TITLE
Wiki for FUSE could mention libfuse2t64 from Ubuntu 24.04

### ISSUE THREAD

**Issue by NeroBurner** [AppImage/AppImageKit#1337]
The `FUSE` page in the wiki mentions `libfuse2` for `Ubuntu >= 22.04`: https://github.com/AppImage/AppImageKit/wiki/FUSE

Ubuntu 24.04 noble renamed the `libfuse2` package to `libfuse2t64`.

I assume the reason is mentioned in the changelog: https://changelogs.ubuntu.com/changelogs/pool/universe/f/fuse/fuse_2.9.9-8.1build1/changelog

```
fuse (2.9.9-8.1) unstable; urgency=medium

  * Non-maintainer upload.
  * Rename libraries for 64-bit time_t transition. (Closes: #1062089)
```

It would be nice if we could mention the new package name for Ubuntu 24.04 in the wiki

**Comment by probonopd** [comment]
> Ubuntu 24.04 noble renamed the libfuse2

Argh! Thanks for pointing this out @NeroBurner.

**Comment by probonopd** [comment]
Changed on https://github.com/AppImage/AppImageKit/wiki/FUSE and https://docs.appimage.org/user-guide/troubleshooting/fuse.html

cc @TheAssassin
