### ISSUE TITLE
Add to Wiki page update with instruction to fix ubuntu after installation fuse

### ISSUE THREAD

**Issue by eua1024** [AppImage/AppImageKit#1340]
### Discussed in https://github.com/orgs/AppImage/discussions/1339

<div type='discussions-op-text'>

<sup>Originally posted by **eua1024** July  6, 2024</sup>
https://github.com/AppImage/AppImageKit/wiki/FUSE

`Warning: While libfuse2 is OK, do not install the fuse package as of 22.04 or you may break your system`

If the fuse package did break your system, you can recover as follows:
1. After starting Ubuntu, enter the console by pressing **Alt+Ctrl+F1**. Then log in with your user account.
2. Or boot into the Recovery Mode (https://wiki.ubuntu.com/RecoveryMode). Then chose `network` and `root`.
3. Execute the command `sudo apt purge gdm3 && apt install gdm3 && reboot`</div>

**Comment by probonopd** [comment]
Thanks @eua1024, I linked to that page from the wiki.
