### ISSUE TITLE
KDE Wayland freezes when open an AppImage with double click

### ISSUE THREAD

**Issue by Tahinli** [AppImage/AppImageKit#1351]
Hi, I'm not sure if I 'm opening issue to right repo but here is what I have:

When I open an appimage with using my desktop environment (I mean just click to open with mouse) my system freezes but if I open appimage with terminal, it's not happening. It happens in wayland both amd and nvidia gpu. Fedora 40 KDE Plasma. In x11, I didn't see this problem. If I extract appimage, it's not happening. I tried with 3 different appimage from 3 different developer : Beekeeper Studio, RustDesk, Surrealist. It's not happening in Gnome also.

I'm not sure how to give more information about it, but I think you will encounter if you try with KDE Wayland.

**Comment by probonopd** [comment]
Cannot reproduce this. For example, here is the AppImageUpdate AppImage running on Fedora 40 KDE Wayland:

![AppImageUpdateOnWaylandKDE](https://github.com/user-attachments/assets/3ebfcd55-fbbf-4b81-b51d-d7bca38205c5)

**Comment by Tahinli** [comment]
> Cannot reproduce this. For example, here is the AppImageUpdate AppImage running on Fedora 40 KDE Wayland:
> 
> ![AppImageUpdateOnWaylandKDE](https://private-user-images.githubusercontent.com/2480569/363263413-3ebfcd55-fbbf-4b81-b51d-d7bca38205c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNjI1MjEsIm5iZiI6MTcyNTA2MjIyMSwicGF0aCI6Ii8yNDgwNTY5LzM2MzI2MzQxMy0zZWJmY2Q1NS1mYmJmLTRiODEtYjUxZC1kN2JjYTM4MjA1YzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMjM1NzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODAxOTVhMjQ0MGFhZjMwNTY2ZDAxY2EwYTUyN2U5MzhlOWFhYzViOTY0ZTliZWE5NzJmNjAzMWZkZDhiNGQ0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lPtgKl_x09T2KtxSSODp_mCH0O5IoGcqS-vCdL3q-4w)

Maybe it's about some specific use case. If you have a chance can you try an application what I've tried already ? It's happening me every time. If there is a way to debug it, I could also help.

**Comment by probonopd** [comment]
Please try with the AppImageUpdate AppImage, since I currently don't have access to Fedora 40 KDE. If it works with this but not with other AppImages, then we need to find out what they are doing differently. Can you run `--appimage-version` on the AppImages to see what AppImage runtime they are using?

**Comment by Tahinli** [comment]
It also happened in appimageupdate unfortunately

![image](https://github.com/user-attachments/assets/33af8402-11ec-48ed-93b0-5dcc7709cd12)

**Comment by valtapaz** [comment]
Can confirm (Fedora 40, KDE/Wayland, kernel 6.10.6); I also have this issue when simply double clicking an AppImage through Dolphin, although DaVinci Resolve 19.0's .run file gave a similar result. Sometimes it will unfreeze and open dozens of instances of the program (the most recent instance was with [Story Architect's setup AppImage](https://github.com/story-apps/starc/releases/download/v0.7.3/starc-setup.AppImage)). I put some lines from journalctl here; apologies for the length:


There are thousands of lines like the following:
```
Aug 23 10:29:07 fedora kwin_wayland[2319]: kf.config.core: "KConfigIni: In file /home/user/Downloads/starc-setup.AppImage, line 755:" Invalid entry (missing '=')
Aug 23 10:29:07 fedora kwin_wayland[2319]: kf.config.core: "KConfigIni: In file /home/user/Downloads/starc-setup.AppImage, line 756:" Invalid entry (missing ']')
```
Eventually I got several repeats of `Aug 23 10:29:09 fedora kwin_wayland_wrapper[2403]: Key repeat discarded, Wayland compositor doesn't seem to be processing events fast enough!`, then eventually got some systemd errors: 
```
Aug 23 10:29:10 fedora systemd[2211]: Started app-\x2fhome\x2fuser\x2fDownloads\x2fstarc\x2dsetup.AppImage@0ec1a2fa9b8b4ef58d2a4964e3884a1a.service - /home/user/Downloads/starc-setup.AppImage.
Aug 23 10:29:10 fedora kernel: process '/starc' started with executable stack
Aug 23 10:29:10 fedora systemd[2211]: Started app-\x2fhome\x2fuser\x2fDownloads\x2fstarc\x2dsetup.AppImage@164597a8c31f4c8d9fc9410e681cb9ae.service - /home/user/Downloads/starc-setup.AppImage.
Aug 23 10:29:10 fedora systemd[2211]: Started app-\x2fhome\x2fuser\x2fDownloads\x2fstarc\x2dsetup.AppImage@22267d1a5d3244949067c65958505b35.service - /home/user/Downloads/starc-setup.AppImage.
Aug 23 10:29:10 fedora systemd[2211]: Started app-\x2fhome\x2fuser\x2fDownloads\x2fstarc\x2dsetup.AppImage@2452a45e10934240a72a2ecc79c123d6.service - /home/user/Downloads/starc-setup.AppImage.
```
Unsure if this is relevant, but could be:
```
Aug 23 10:31:25 fedora rsyslogd[1300]: imjournal: journal files changed, reloading...  [v8.2312.0-1.fc40 try https://www.rsyslog.com/e/0 ]
Aug 23 10:31:28 fedora kwin_wayland[2319]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Aug 23 10:31:31 fedora kernel: usb 5-3.2: USB disconnect, device number 66
Aug 23 10:31:32 fedora kernel: usb 5-3.2: new full-speed USB device number 67 using xhci_hcd
Aug 23 10:31:32 fedora kernel: usb 5-3.2: New USB device found, idVendor=20d6, idProduct=2035, bcdDevice= 1.67
Aug 23 10:31:32 fedora kernel: usb 5-3.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Aug 23 10:31:32 fedora kernel: usb 5-3.2: Product: Xbox Series X Wired Controller Black
Aug 23 10:31:32 fedora kernel: usb 5-3.2: Manufacturer: PowerA
Aug 23 10:31:32 fedora kernel: usb 5-3.2: SerialNumber: 00008CBFE93956D8
Aug 23 10:31:32 fedora kernel: input: Generic X-Box pad as /devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb5/5-3/5-3.2/5-3.2:1.0/input/input222
Aug 23 10:31:32 fedora mtp-probe[218783]: checking bus 5, device 67: "/sys/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb5/5-3/5-3.2"
Aug 23 10:31:32 fedora mtp-probe[218783]: bus: 5, device: 67 was not an MTP device
Aug 23 10:31:32 fedora flatpak[3140]: 2024-08-23 10:31:32.773 | INFO     | src.backend.DeckManagement.DeckManager:on_connect:132 - Device /dev/bus/usb/005/067 with info: {'ID_MODEL_ID': '2035', 'ID_MODEL': 'Xbox_Series_X_Wired_Controller_Black', 'ID_MODEL_FROM_DATABASE': '', 'ID_VENDOR': 'PowerA', 'ID_VENDOR_ID': >
Aug 23 10:31:32 fedora flatpak[3141]: 2024-08-23 10:31:32.773 | INFO     | src.backend.DeckManagement.DeckManager:on_connect:132 - Device /dev/bus/usb/005/067 with info: {'ID_MODEL_ID': '2035', 'ID_MODEL': 'Xbox_Series_X_Wired_Controller_Black', 'ID_MODEL_FROM_DATABASE': '', 'ID_VENDOR': 'PowerA', 'ID_VENDOR_ID': >
Aug 23 10:31:32 fedora mtp-probe[218798]: checking bus 5, device 67: "/sys/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb5/5-3/5-3.2"
Aug 23 10:31:32 fedora mtp-probe[218798]: bus: 5, device: 67 was not an MTP device
Aug 23 10:31:33 fedora kwin_wayland[2319]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Aug 23 10:31:34 fedora NetworkManager[1617]: <info>  [1724423494.4054] device (wlp4s0): set-hw-addr: set MAC address to F6:0B:4A:EA:19:BC (scanning)
Aug 23 10:31:38 fedora kwin_wayland[2319]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Aug 23 10:31:43 fedora kwin_wayland[2319]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Aug 23 10:31:48 fedora kwin_wayland[2319]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Aug 23 10:31:53 fedora systemd-journald[791]: [🡕] Suppressed 3102076 messages from user@1000.service
Aug 23 10:31:53 fedora kwin_wayland[2319]: kf.config.core: "KConfigIni: In file /home/user/Downloads/starc-setup.AppImage, line 139403:" Invalid entry (missing '=')
```
Eventually is straightened out with multiple repeats of 
```
Aug 23 10:32:08 fedora starc-setup.AppImage[215946]: 2024.08.23 10:32:08.859 [I] Story Architect version 0.7.3, Fedora Linux 40 (Forty), x86_64
Aug 23 10:32:08 fedora starc-setup.AppImage[215946]: 2024.08.23 10:32:08.860 [I] Loading fonts [embedded]```

**Comment by probonopd** [comment]
Possibly related: `fedora systemd-journald[791]: [🡕] Suppressed 3102076 messages from user@1000.service`
I can only speculate what might be going on: Possibly output that applications write to stdout/stderr cause systemd-journald to produce too many messages? Not sure how the AppImage file format would contribute to this, What happens if you extract the AppImage and then execute the `AppRun` file by double-clicking it?

**Comment by Tahinli** [comment]
> Possibly related: What happens if you extract the AppImage and then execute the `AppRun` file by double-clicking it?

There is no problem about it, it just works.

**Comment by probonopd** [comment]
What happens if you run the AppImage in a terminal with `--appimage-mount`, and then open the mountpoint in the file manager and double-click the `AppRun` file that is mounted there?

**Comment by Tahinli** [comment]
> What happens if you run the AppImage in a terminal with `--appimage-mount`, and then open the mountpoint in the file manager and double-click the `AppRun` file that is mounted there?

I couldn't open AppRun with double click. KDE wants some application to open with, but I'm able to run it from terminal

**Comment by valtapaz** [comment]
> Not sure how the AppImage file format would contribute to this, What happens if you extract the AppImage and then execute the `AppRun` file by double-clicking it?

Just redownloaded the file; AppRun refused to export, though once I double clicked the binary itself it asked if I'll allow it to execute, then opened regularly. Oddly, this time the same thing happened with the AppImage. 

It looks like the ask for permission was significant for some reason, though: afterward, double clicking the AppImage would freeze my system for 5 seconds before the program opened, while double clicking the extracted binary opened the program instantly. Curiously, selecting the AppImage and pressing "Enter" as opposed to double clicking opened >100 instances, though this didn't happen at all for the binary; confirmed that starting the AppImage from the terminal has no lag or other discernible side effects.

**Comment by Henrik0x7F** [comment]
> > Not sure how the AppImage file format would contribute to this, What happens if you extract the AppImage and then execute the `AppRun` file by double-clicking it?
> 
> Just redownloaded the file; AppRun refused to export, though once I double clicked the binary itself it asked if I'll allow it to execute, then opened regularly. Oddly, this time the same thing happened with the AppImage.
> 
> It looks like the ask for permission was significant for some reason, though: double clicking the AppImage after that time would freeze my system for 5 seconds before the program opened, while double clicking the extracted binary opened the program instantly. Curiously, selecting the AppImage and pressing "Enter" as opposed to double clicking opened >100 instances, though this didn't happen at all for the binary. As with earlier, starting the AppImage from the terminal has no lag or other discernible side effects.

Can confirm this. Opening through the terminal works fine. Double clicking the file locks everything up for ~5 sec.
Marking the file and pressing Enter on the keyboard freezes everything for a solid minute and opens lots of instances (~30 - 40)

**Comment by probonopd** [comment]
@Henrik0x7F are you also using Fedora 40 KDE on Wayland?

**Comment by Henrik0x7F** [comment]
> @Henrik0x7F are you also using Fedora 40 KDE on Wayland?

Yes, I am

**Comment by probonopd** [comment]
Since Fedora 40 KDE on Wayland is the only distribution known to have this issue (or at least the _first_ one we are becoming aware of), I'd suggest to open a bug there, too. On the AppImage side nothing has changed that I could imagine would cause this suddenly.

**Comment by valtapaz** [comment]
That makes sense; Fedora's great and all, but at times it can get too cutting-edge for its own good

**Comment by Tahinli** [comment]
> That makes sense; Fedora's great and all, but at times it can get too cutting-edge for its own good

It's a bit out of content but if this happens because Fedora is little too much cutting edge then we should see same thing in Arch.

I'm not justifying Fedora, just wanted to talk about "cutting edge situation".

**Comment by Henrik0x7F** [comment]
Has someone already created a bug report at fedora?

**Comment by Tahinli** [comment]
If someone reported to Fedora please refer this issue to them and Fedora report link to here.

**Comment by BlauFx** [comment]
FWIW I'm also experiencing this issue. I'm on EndeavourOS, KDE Wayland.

**Comment by probonopd** [comment]
Is systemd part of what is going on? Might be another constant here?

**Comment by BlauFx** [comment]
I don't think systemd causes this issue. I just tested on KDE X11 and Hyprland on my system. Both work fine, so it seems to be a KDE Wayland specific issue.

**Comment by probonopd** [comment]
Interesting. Thanks for testing @BlauFx.

**Comment by BlauFx** [comment]
![image](https://github.com/user-attachments/assets/3b966b9d-c813-4b1a-bb3b-3b5439d0f9fc)

I primarily tested osu, standard-notes and the yubikey-manager AppImage. Running any other AppImage is affected as well.
However what I noticed the *only unaffected* AppImage is Realm Studio.

Digging further I noticed:
(Realm Studio, 117 MiB, no freeze),
(balenaEtcher, 90 MiB, 3s freeze), 
(yubikey-manager, 111 MiB, 4-5s freeze),
(osu, 142 MiB, 5-6s freeze), 
(ente, 390 MiB, 11s freeze)

Because of the correlation between file size and the amount of seconds KDE is frozen, I would speculate during decompression something causes KDE Wayland to complete freeze.

**Comment by probonopd** [comment]
Thanks. Maybe it has to do with the amount of data that needs to be decompressed when launching the application. This might explain why I didn't run into the issue with the AppImageUpdate AppImage.

**Comment by Tahinli** [comment]
I tested with gnome. There is no problem. It only happens in KDE

**Comment by probonopd** [comment]
Possibly related to this?
https://bugs.kde.org/show_bug.cgi?id=492584

**Comment by mattj518** [comment]
I've been having the same issue on KDE Neon 6.0 and I just came across this discussion.

I tried the fix listed in https://bugs.kde.org/show_bug.cgi?id=492584 and this fixes the problem so it does not appear to be a appimage problem. 

Thanks for the help.
