### ISSUE TITLE
--appimage-extract creates empty squashfs-root

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [AppImage/AppImageKit#1352]
Operating System: openSUSE Tumbleweed 20240908
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.8-1-default (64-bit)
Graphics Platform: X11

Krita appimage, https://krita.org/en/download/, https://download.kde.org/stable/krita/5.2.3/krita-5.2.3-x86_64.appimage is not extracted.

`--l` lists files correctly but `--appimage-extract` create only empty squashfs-root folder.

Latest AppImage used.

**Comment by probonopd** [comment]
Can you please share a link to the AppImage in question?

**Comment by bravequickcleverfibreyarn** [comment]
Yes of course. Posted accidentally. Soon be there.

**Comment by probonopd** [comment]
Cannot reproduce:

```
wget https://download.kde.org/stable/krita/5.2.3/krita-5.2.3-x86_64.appimage
chmod + krita-5.2.3-x86_64.appimage
chmod +x krita-5.2.3-x86_64.appimage
./krita-5.2.3-x86_64.appimage --appimage-extract
find squashfs-root/ | wc -l
52397
```

**Comment by bravequickcleverfibreyarn** [comment]
Ok, that proves everything. My steps were:

```console
wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod a+x appimagetool-x86_64.AppImage
appimagetool-x86_64.AppImage --appimage-extract krita-5.2.3-x86_64.appimage
```

It works as you said.

**Comment by probonopd** [comment]
Ah, you tried to use appimagetool to extract another AppImage. The syntax for that would be `TARGET_APPIMAGE=krita-5.2.3-x86_64.appimage ./appimagetool-x86_64.AppImage --appimage-extract`, but what I posted above is easier and also works if the different AppImages use different runtimes or compressions.
