### ISSUE TITLE
Portable mode appimages do not appear as seperate instances on the dash / taskbar

### ISSUE THREAD

**Issue by d1Bihkte** [AppImage/AppImageKit#1355]
I have set-up several ungoogled chromium appimages on ubuntu 24.04 LTS device. https://docs.appimage.org/user-guide/portable-mode.html https://github.com/ungoogled-software/ungoogled-chromium-portablelinux

Example:
/apps/a/ungoogle-chromium.AppImage
/apps/a/ungoogle-chromium.AppImage.config
/apps/a/ungoogle-chromium.AppImage.home

/apps/b/ungoogle-chromium.AppImage
/apps/b/ungoogle-chromium.AppImage.config
/apps/b/ungoogle-chromium.AppImage.home

/apps/c/ungoogle-chromium.AppImage
/apps/c/ungoogle-chromium.AppImage.config
/apps/c/ungoogle-chromium.AppImage.home

After launching two or all ungoogle-chomium appimages; They all appear under one icon on the dash (taskbar). I only see as multiple windows of one browser. If I have multiple windows opened in each browser, I can't identify each instance separately.

I don't see such problem when use snap parallel mode.
https://snapcraft.io/docs/installing-snapd
https://snapcraft.io/docs/parallel-installs
https://snapcraft.io/chromium

Example: `sudo snap install chromium`, `sudo snap install chromium_a`, `sudo snap install chromium_b`

Once they are launched, they appear separately on the dash (taskbar).

**Comment by d1Bihkte** [comment]
@probonopd but i couldn't find any other suitable repository to open an issue. https://github.com/AppImage

I can show you more examples

### Mattermost
https://snapcraft.io/mattermost-desktop
https://github.com/mattermost/desktop/releases

**appimage**
![mattermost-appimage](https://github.com/user-attachments/assets/63b5c5ad-3fa7-43ee-8314-64fc6ae34c8e)

**snap**
![mattermost-snap](https://github.com/user-attachments/assets/e4143495-9635-467c-b9b6-348327709b15)


### Figma
https://snapcraft.io/figma-linux
https://github.com/Figma-Linux/figma-linux/releases

**appimage**
![figma-appimage](https://github.com/user-attachments/assets/040a5c80-06ee-4799-b80a-4f649d4211e3)

**snap**
![figma-snap](https://github.com/user-attachments/assets/5fedbd1a-f969-48c7-824d-51ceec6ae8a5)

**Comment by d1Bihkte** [comment]
### appimage

![appimage](https://github.com/user-attachments/assets/c89f34d7-e03c-4189-8fc9-c41a4f56bf7f)


### snap
![snap](https://github.com/user-attachments/assets/dfd3591b-4572-44ff-b5d3-82b5fe1a9ae5)

**Comment by probonopd** [comment]
Possibly they don't handle icons correctly when an application is not launched by a `.desktop` file.
