### ISSUE TITLE
[desktopintegration] Handle documents properly

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#156]
Using desktopintegration right now does associate install and associate mimetypes, e.g., .sla for Scribus, but it is only halfway working at the moment.

Opening a document by double-clicking on the document icon always launches a new instance of the application's AppImage. It would probably better if launching the same AppImage twice would have the AppImage embedded runtime detect that the AppImage in question is already running and mounted, and execute from there. However, it is not trivial to keep track when to unmount. Possibly (to be tested) just mounting (again) over the same mountpoint could do the trick. To do this, the mountpoint would not be chosen randomly but would have to be deterministic per AppImage, e.g. derived from the path of the AppImage.

The folllowing is **done** by now:
When generating a local desktop file, the desktopintegration script should append `%U` to the `Exec=` key so that documents are passed to the AppImage as arguments. Similarly need to change the check for already-installed desktop files to not get confused by the %U.

Also, seemingly arguments don't get passed properly through all the way to the app when running through the wrapper script installed by desktopintegration. Need to change to

```
trap atexit EXIT
ARGS="$@"
atexit()
{
  exec $BIN "$ARGS"
}
```

**Comment by probonopd** [comment]
The optional `appimaged` daemon is recommended now. That being said, if someone wants to implement this for the `desktopintegration` bash script (or a rewrite thereof), you are welcome to do so.

**Comment by azubieta** [comment]
This seems like a job for runtime instead of appimaged.

**Comment by probonopd** [comment]
The desktopintegartion script is not supported anymore. See https://github.com/AppImage/appimaged/issues/30 for the "Document Binding" scheme outlined there which we should attempt to match in terms of its usability, in a joint successor to the at least 3 different desktop integration tools we have today.
