### ISSUE TITLE
Write GNOME thumbnailer

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#203]
Using
https://github.com/hadess/gnome-thumbnailer-skeleton
and
libarchive

**Comment by probonopd** [comment]
Pull requests welcome

**Comment by drequivalent** [comment]
Any progress on this?

**Comment by TheAssassin** [comment]
@drequivalent nope.

**Comment by azubieta** [comment]
Done, please see https://github.com/azubieta/appimage-gnome-thumbnailer
Deb packages are available at the releases tab.

![pic](https://user-images.githubusercontent.com/1138094/48751774-bcdb6f80-ec4b-11e8-969b-272b2e2bbc83.png)

**Comment by probonopd** [comment]
Wow! 👍 💯

**Comment by drequivalent** [comment]
Cool. Any way to remove the thumbnail border though?

**Comment by TheAssassin** [comment]
Can anyone please explain why this is necessary? I thought we have this XDG thumbnailing stuff that is supposed to work on GNOME.

**Comment by azubieta** [comment]
@drequivalent the thumbnails generated have no frame around it's dolphin the one who place them. Also I wasn't able to find were to turn it of.

**Comment by azubieta** [comment]
I'll close the issue as resolved. Fell free to re-open it if something else comes up.

**Comment by probonopd** [comment]
Works great, even in XFCE! :-) Thank you so much @azubieta. Do you think you could make a RPM as well? (E.g., using `cpack -V -G RPM`)?

**Comment by azubieta** [comment]
Sure, opening an issue.

**Comment by TheAssassin** [comment]
Perhaps we can integrate this project into the AppImageLauncher tool family? At least it'd be nice if we could ship it with it.

**Comment by probonopd** [comment]
In the ideal world (e.g., if appimaged/AppImageLauncher/thumbnailer/AppImageUpdate/Firejail etc. would enter Debian proper) there would be something like an appimage-desktop metapackage that would set everything up, öossibly including the files mentioned in the excludelist).
