### ISSUE TITLE
Making AppImageKit installable

### ISSUE THREAD

**Issue by thopiekar** [AppImage/AppImageKit#222]
Just wanted to install AppImageKit into an own prefix with a set of other software, but there is no 'install' target:

```
[...]
Embedding magic number 0x414901 at offset 8...
ok
Making /media/hdd/home/thopiekar/Projekte/eclipse-Ultimaker/cura-build-environment/build/AppImageKit-prefix/src/AppImageKit/AppImageExtract executable...
ok
Size: 0.625000 MB
[100%] Built target AppImageExtract
[ 81%] Performing install step for 'AppImageKit'
make[3]: *** Keine Regel, um „install“ zu erstellen.  Schluss.
```

Do you plan to make it installable? Are there good reasons why it isn't/shouldn't?

Thanks!

**Comment by probonopd** [comment]
The reason is that there is no need for it as AppImageAssistant and co. are AppImages themselves...

**Comment by thopiekar** [comment]
Hmm, ok..

**Comment by probonopd** [comment]
AppImageAssistant has been replaced by `appimagetool`. Possibly you might want to package this now.

**Comment by thopiekar** [comment]
Thank you for keeping me up-to-date.

Is appimagetool planned for version 7?
Couldn't find it in https://github.com/probonopd/AppImageKit/releases

**Comment by probonopd** [comment]
Yes, the repository is being restructured in a way that hopefully breaks as little as possible, you can currently find it in the [appimagetool/master](https://github.com/probonopd/AppImageKit/tree/appimagetool/master) branch.

**Comment by thopiekar** [comment]
Great, thanks! `appimaged` sounds very promising, too.

**Comment by thopiekar** [comment]
Hey @probonopd !

could you be so kind and tell me which executable names have changed since v6?

Thanks!

**Comment by probonopd** [comment]
Please refer to https://github.com/AppImage/AppImageKit/wiki/AppImageKit-components - if v6 still contained AppImageAssistant, then it is now an entirely different code base. `appimagetool` is now the tool used for generating AppImages.

**Comment by TheAssassin** [comment]
> No external tool is needed for this anymore.

However, appimagetool will once receive such a functionality allowing users to extract AppImages they don't want to try to execute.

**Comment by azubieta** [comment]
Closing this issue as it's no longer relevant. Please reopen it if required.
