### ISSUE TITLE
Deduplicate all AppImages using freed up and hardlinks 

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#231]
Deduplicate all AppImages by running the marvelous [freedup](http://freedup.org) tool [like shown here](https://github.com/probonopd/AppImages/blob/47661ebaec2e651bed798b838f4a07c5413d1214/recipes/qtcreator/Recipe#L117).

In the (extreme) case of the Qt Creator AppImage, this helped to reduce the AppImage size a lot because there were a lot of redundancies.

**Comment by probonopd** [comment]
I think now that we are using squashfs, duplicated files are automatically deduplicated by `mksquashfs`. To be verified!

**Comment by azubieta** [comment]
Duplicated files are handled gracefully by squashfs see https://sourceforge.net/p/squashfs/mailman/message/908840/
Closing the issue.
