### ISSUE TITLE
Cloudfare for website 

### ISSUE THREAD

**Issue by kskarthik** [AppImage/AppImageKit#245]
Better we move the website to cloud fare or any CDN. This might help to encrypt discourse too

**Comment by kskarthik** [comment]
@probonopd need your advice

**Comment by probonopd** [comment]
What would that reqiure us to do, and do you see this as a priority?

**Comment by kskarthik** [comment]
Switching to CDN we can provide encryption for discourse

**Comment by probonopd** [comment]
Where do we get the certificate from?

**Comment by kskarthik** [comment]
Cloudflare gives us a shared SSL certificate

**Comment by probonopd** [comment]
What would that reqiure us to do?

**Comment by kskarthik** [comment]
Setting up an account on cloudflare.com & a few steps to follow.

**Comment by probonopd** [comment]
Also see https://github.com/probonopd/AppImageKit/issues/110

**Comment by TheAssassin** [comment]
Related to #110

**Comment by probonopd** [comment]
Discourse now uses https. What advantage would we get from using Cloudflare, @kskarthik? GitHub has its own CDN. Would this give us https for appimage.org while still allowing us to host it on GitHub Pages?

**Comment by kskarthik** [comment]
Netlify is good now. Also, supports FOSS projects :)

**Comment by probonopd** [comment]
1 click HTTPS sounds intriguing indeed...

**Comment by TheAssassin** [comment]
Closing as the website is now hosted externally and has HTTPS support. Also, CloudFlare is evil, see https://github.com/AppImage/appimage.github.io/issues/60#issuecomment-325224040.
