### ISSUE TITLE
Executables cannot be launched by clicking them in elementary OS 0.4 Loki

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#261]
Executables cannot be launched by clicking them in elementary OS 0.4 Loki

```
$ mimetype '/isodevice/Applications/Calibre-2.68.0.glibc2.7-x86_64.AppImage' 
/isodevice/Applications/Calibre-2.68.0.glibc2.7-x86_64.AppImage: application/x-executable
```

Permissions are set to executable. File can be launched on the command line but not by double clicking it.

Is this an elementary OS bug? Where is the bugtracker?

**Comment by PHPJosh** [comment]
elementary uses a bug tracker on their PPA's https://launchpad.net/elementaryos

**Comment by probonopd** [comment]
Can someone reproduce this?

**Comment by PHPJosh** [comment]
I will install elementary in a vm later see if i can reproduce it

**Comment by probonopd** [comment]
@PHPJosh can you reproduce this?

**Comment by probonopd** [comment]
@PHPJosh ping

**Comment by PHPJosh** [comment]
did this ever get  reproduced? sorry been away for awhile and I am back working on my Distro. but if this needs to be reproduced still will try to do so within next day or so and try to verify it

**Comment by probonopd** [comment]
I couldn't so far.

**Comment by PHPJosh** [comment]
alright I will still look into at some point soon will get latest version and test unless still wanting to confirm it on this version. will post once I have verification of the bug or not

**Comment by PHPJosh** [comment]
Tested the latest iso with 0.4.1 and got Krita to work just by double clicking it.. didn't even have to set permissions lol 
![screenshot from 2017-08-23 01 33 10](https://user-images.githubusercontent.com/11535133/29596065-7797ca60-8778-11e7-9910-c680e094509b.png)

**Comment by PHPJosh** [comment]
that was via terminal but it works to double click

**Comment by PHPJosh** [comment]
will grab another screen in bit after dinner

**Comment by PHPJosh** [comment]
here is the appimage running with double click (actually single click now by default in elementary 0.4.1) so in the point release at least executables can be launched via click. 

![screenshot from 2017-08-23 04 05 49](https://user-images.githubusercontent.com/11535133/29598523-9a43b778-8786-11e7-9b93-1407277e4e54.png)

**Comment by probonopd** [comment]
Thanks for testing. Closing this ticket. Feel free to reopen if the problem persists.
