### ISSUE TITLE
Generate AppDirAssistant

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#27]
Clean up AppDirAssistant, make it multiarch, and generate it as part of the CMake process

**Comment by TheAssassin** [comment]
At a glance it looks like these issues were about AppImage type 1. This type is no longer developed and we do not recommend using it any more.

I think I can safely close this issue.

**Comment by probonopd** [comment]
AppDirAssistant and AppImageAssistant are deprecated.
