### ISSUE TITLE
[regression] build.sh now requires sudo?

### ISSUE THREAD

**Issue by lasconic** [AppImage/AppImageKit#287]
Since 12 days or so (around november 3 or 4), the master branch fails to create an AppImage for MuseScore.

See https://travis-ci.org/musescore/MuseScore/jobs/175875703#L1081

```
Making all in man
make[2]: Entering directory `/AppImageKit/inotify-tools-3.14/man'
make[3]: Entering directory `/AppImageKit/inotify-tools-3.14'
make[3]: Leaving directory `/AppImageKit/inotify-tools-3.14'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/AppImageKit/inotify-tools-3.14/man'
make[2]: Entering directory `/AppImageKit/inotify-tools-3.14'
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
make[2]: Leaving directory `/AppImageKit/inotify-tools-3.14'
make[1]: Leaving directory `/AppImageKit/inotify-tools-3.14'
+ sudo make install
/opt/rh/devtoolset-2/root/usr/bin/sudo: line 14: /usr/bin/sudo: No such file or directory
/opt/rh/devtoolset-2/root/usr/bin/sudo: line 14: exec: /usr/bin/sudo: cannot execute: No such file or directory
```

**Comment by probonopd** [comment]
Hi @lasconic, are you talking about the `master` branch of AppImageKit? I did not intentionally change something there. From the snippet it looks like you are using the (new) `appimagetool/master` branch of AppImageKit which indeed has changed in significant ways. Are you sure you need to build AppImageKit yourself on each build? I'd recommend you to consider using the (new) `appimagetool/master` branch of AppImageKit but store a "known good" version of appimagetool.AppImage which you can then use as part of your build process.

**Comment by probonopd** [comment]
Some background information about the `appimagetool/master` branch:
http://discourse.appimage.org/t/the-future-of-appimage-type-2-and-new-tools/65/5

**Comment by probonopd** [comment]
@lasconic were you able to try `appimagetool`? Let me know if it works for you please.

**Comment by lasconic** [comment]
@shoogle is looking into it.

**Comment by shoogle** [comment]
076a88a57d7ca1a8d77bdbf7d8e92f37eea03dab solves it for us. I'll put this in a Docker image and investigate `appimagetool` later.

**Comment by azubieta** [comment]
build.sh no longer requires sudo. Closing the issue
