### ISSUE TITLE
How do I add shortcuts to files inside the appdir?

### ISSUE THREAD

**Issue by flamingice** [AppImage/AppImageKit#289]
Hi, while the idea is great I find it pretty difficult to create an appimage due to unstructured, incomplete and scattered instructions. I managed to created a simple appimage that runs the executable inside. How can I access other files which are parts of the appimage (in my case a .html file) from the outside? Where can I find instructions on the possible content of the appname.desktop file?

**Comment by probonopd** [comment]
Hi @flamingice welcome to AppImage and thanks for your feedback. When you say that documentation is "unstructured, incomplete and scattered", what exactly are you looking for?

We have, among others,
* A wiki answering basic questions https://github.com/probonopd/AppImageKit/wiki
* Detailed instructions on how to create AppImages https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages
* Many [examples](https://github.com/search?utf8=✓&q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&ref=searchresults) on how to create AppImages for continuous builds on Travis CI
* Many [examples](https://github.com/probonopd/AppImages/tree/master/recipes/meta) on how to convert existing deb/ppa binaries to AppImages
* A formal [specification](https://github.com/AppImage/AppImageSpec/blob/master/draft.md) of the AppImage format
* A mailing list/forum for anything you would like to discuss http://discourse.appimage.org/

> How can I access other files which are parts of the appimage (in my case a .html file) from the outside?

What do you mean by "access"? The main application inside the AppImage can access files by opening them relative to the binary location. For example, if your application lives inside the AppImage in the `usr/bin/myapp` path and the HTML file is in `usr/share/myapp/index.html` then the application could open it by `(DIRECTORY_OF_MYSELF)/../share/myapp/index.html`. [More information on this subject](https://github.com/limbahq/binreloc).

But hey, you say "from the outside". What is the use case for this? AppImage is a format for distributing applications, not HTML files... if you really want, you can mount the AppImage and access its contents. After all, it is just a filesystem container that can be loop-mounted on Linux.

**Comment by flamingice** [comment]
Thanks for you reply, I will give more detailed feedback on the documentation later.

The application I want to make work as an appimage is an executable file ("iguana-server"), it provides an api which is utilized by a html page (index.html). 
![ca60](https://cloud.githubusercontent.com/assets/1246198/20337186/cd5ef76e-abcf-11e6-9e8a-e306c146014f.png)

The other folders in the screenshot are used by either the executable file or the html file (javascript, images, ...). The goal is to have 2 shortcuts on the desktop or in the start menu, one that starts the "iguana-server" and one that opens the html file.

**Comment by probonopd** [comment]
The best solution for that is to write a bash script `AppRun` which launches either the server, the HTML page, or both. How do you stop the server?

Note that AppImageKit is mainly targeting desktop GUI apps; as for servers solutions like Docker may be more suitable.

**Comment by probonopd** [comment]
Did this answer your question @flamingice? Did you find a solution?

**Comment by azubieta** [comment]
Closing the issue by inactivity.
