### ISSUE TITLE
Could not symlink .DirIcon

### ISSUE THREAD

**Issue by 0xbaadf00d** [AppImage/AppImageKit#296]
I can't generate appimage package. The command exit without error but the appimage package is not generated.

```
#> cat /etc/os-release
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18"
VERSION_ID="18"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
UBUNTU_CODENAME=xenial

#> uname -a
Linux zhadum 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
#> ./appimagetool-x86_64.AppImage -v test out
WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
WARNING: appstream-util is missing, please install it if you want to use AppStream metadata
Desktop file: /home/zero-x-baadf00d/test/cashless.desktop
Name: PayinTech.IO - Cashless
Icon: /usr/share/io-payintech-cashless/app
Exec: /usr/bin/io-payintech-cashless
Comment: PayinTech
Type: Application
Categories: System
File used for determining architecture: /proc/self/exe
Arch: 86_64
App name for filename: PayinTech.IO_-_Cashless
/home/zero-x-baadf00d/test should be packaged as out
Creating .DirIcon symlink based on information from desktop file
Could not symlink .DirIcon
```

**Comment by probonopd** [comment]
`Could not symlink .DirIcon` means there is some issue finding and symlinking the icon file. Please check: 
* Is there a `cashless.desktop` file in the root directory of the AppDir?
* Does this file contain an entry `Icon=cashless`?
* Is there a file `cashless.png` file in the root directory of the AppDir?

**Comment by 0xbaadf00d** [comment]
I find issue, by exemple, with `Icon=/usr/share/io-payintech-cashless/app`, appimage continue to generate a symlink to a inexisting file ==> `.DirIcon --> app.png` but the file is not copied

**Comment by probonopd** [comment]
Yes, instead of `Icon=/usr/share/io-payintech-cashless/app`please use `app` and place `app.png` at the root directory of the AppDir (next to AppRun).

**Comment by tschenkde** [comment]
Actually I have a very similar problem.
 I want to make an old Firefox-AppImage following the video for LeafPad (which works). 

- I put the firefox.desktopfile in the root folder of AppDir 
- I put firefox.png and AppRun in the AppDir root folder
- I verify in  firefox.desktopfile : Icon=firefox
 
Run 
./AppImageAssistant  Firefox.AppDir  OldFirefox.AppImage

and I read the following line 

xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/.DirIcon'='/usr/share/icons/hicolor/48x48/apps/firefox.png'

I donnot want to take files from /usr/share ... (AppImage should be independent from host ?)
The icon is in the rootfolder as is the .desktop -file, which defines   Icon=firefox, 
so why is it not taken.

running ./OldFirefox.AppImage fails as one would expect : 
Cannot open /tmp/.mount_m0Nyss/.DirIcon

**Comment by tschenkde** [comment]
Same problem with Firefox-Dev Recipe: 

- wget -O Firefox52 https://raw.githubusercontent.com/probonopd/AppImages/master/recipes/firefox-dev/Recipe
- sh Firefox52 
- ./out/Firefox-Dev-52.0a2.en.glibc2.3.4-x86_64.AppImage

ends with Error:
Cannot open /tmp/.mount_GxEjSo/.DirIcon
....

**Comment by azubieta** [comment]
We have been working on fixing symlinks issues this week. Would you mind to re-tests?

**Comment by azubieta** [comment]
Closing the issue as solved.

**Comment by probonopd** [comment]
@0xbaadf00d please comment here if the problem persists, then we will reopen it.

**Comment by charterchap** [comment]
In case this helps anyone else, I hit this as I was mounting a shared folder inside my vm which was creating a simple permissions issue. Try creating a symlink in your appdir by hand and see what happens.
