### ISSUE TITLE
[32-bit] deb does not get built

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#310]
Since we have [32-bit builds](https://github.com/probonopd/AppImageKit/pull/307), it would be good if the 32-bit appimaged deb would also get created. Apparently it is not.

**Comment by TheAssassin** [comment]
Trying to find out the reason for this. We might be able to drop equivs-build, though, and use CMake's CPack to build the `.deb`s directly. That's what @azubieta uses for Nitrux, for example.

**Comment by azubieta** [comment]
At nitrux we only ship 64 bits binaries but if you are building it in a 32 bit system that 32 bits binaries should be created.

**Comment by TheAssassin** [comment]
@azubieta how are you calling CPack? I can't figure out why it won't work on my system.

**Comment by azubieta** [comment]
Just cpak nothing additional.
