### ISSUE TITLE
Usability: Provide clear appstreamcli error message

### ISSUE THREAD

**Issue by JonasT** [AppImage/AppImageKit#313]
The error message "Failed to validate AppStream information with appstreamcli" is extremely unhelpful, at the very least you should add the wrong or missing tag and the line of the XML file to it.

For someone coming from this guide https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages this tool isn't even mentioned at any point, so you can't reasonably expect the user to know about appstreamcli, nor is it a useful use of anyone's time to read the man page on that external tool as a next step just to find out how to get an actually useful error message.

**Comment by probonopd** [comment]
Thanks for your report @JonasT. For now you can use the `-n, --no-appstream: Do not check AppStream metadata` option of `appimagetool`.

We are not bundling `appstreamcli` though, so it would be really interesting to see why it fails on your system when invoked by `appimagetool` but not when you run it manually... can you run `appimagetool` with maximum verbosity please?

**Comment by azubieta** [comment]
@JonasT we suspect that this is no longer an issue, please let us know if it's still valid.
We will close the issue due inactivity. Please feel free to reopen it if needed.

**Comment by spoorun** [comment]
I'm getting the same issue, appstream data validates with appstreamcli, but fails with appimagetool and have to bypass it by using the -n, --no-appstream: Do not check AppStream metadata option
