### ISSUE TITLE
appimagetool for macOs

### ISSUE THREAD

**Issue by develar** [AppImage/AppImageKit#322]
Is it possible to provide appimagetool for macOs?

I am investigating this issue for now, these packages are required to build project on macOs:

```
brew install md5sha1sum libtool gnu-sed fuse
brew install Caskroom/cask/osxfuse
```

`libtoolize` must be replaced to `glibtoolize` and `sed` to `gsed` in the `build.sh`.

now I get error `../runtime.c:47:10: fatal error: 'wait.h' file not found`

**Comment by develar** [comment]
Ouch, it seems runtime is embedded into appimagetool so, it is not possible. Probably direct usage of `mksquashfs` will be a solution :)

**Comment by probonopd** [comment]
Wow, never thought of actually porting `appimagetool` to macOS. Hold on, are you actually saying you have (almost) ported over AppImageKit to macOS? (Could it run AppImages?)

It would be easy to change appimagetool to use an external runtime file. Actually this has been requested before for cross-architecture AppImage builds.

However, the AppImage format intentionally is made very easy: Just concatenate the runtime with a squashfs file. No offset, just append (e.g., using `cat runtime > the.AppImage && cat some.squashfs >> the.AppImage`).

**Comment by develar** [comment]
> are you actually saying you have (almost) ported over AppImageKit to macOS

No. I just need to build AppImage on macOS :) But in general — I think it will pretty easy to port AppImage to macOs (but no need and will be not user friendly (addition brew packages are required)).

> However, the AppImage format intentionally is made very easy

I am trying to reuse official tool to build. So, I will try to reuse linux runtime instead of build new one on macOS.

> Let me know if you want to go this route and need this feature.

This feature will be cool because otherwise I have to use 3 different builds of appimagetool (ia32, x64, arm (not yet sure)).

**Comment by probonopd** [comment]
Did you take detailed notes that would allow me to build on macOS on Travis CI?

**Comment by develar** [comment]
@probonopd I will try to send PR (~2 days).

**Comment by probonopd** [comment]
Hi @develar did you ever succeed in doing this?

**Comment by develar** [comment]
@probonopd No. I think I will use `mksquashfs` directly.

**Comment by azubieta** [comment]
@develar let's close the issue due inactivity, please feel free to reopen it if something else comes up.
