### ISSUE TITLE
Arch Linux support, please.

### ISSUE THREAD

**Issue by aasgit** [AppImage/AppImageKit#324]
Install dependencies for Arch Linux                                           
if [ -e /usr/bin/pacman ] ; then                                                
  echo "Please submit a pull request if you would like to see Arch Linux support."
  exit 1                                                                        
fi
ps: I'm trying to make a PKGBUILD to install the binaries, since someone has created an AUR for git (but it fails miserably) and AUR rules are pretty strict on no duplicating packages. I'll comment here if I manage to get something useful.

**Comment by probonopd** [comment]
Just for clarification, you are aware that you should be able to use the appimaged-x86_64.AppImage and appimagetool-x86_64.AppImage files from https://github.com/probonopd/AppImageKit/releases to run them on Arch Linux?

If you really have a need for native Arch Linux packaging, [here](https://github.com/probonopd/AppImageKit/issues/320#issuecomment-269775788) is a comment with regard to RPM packaging; I guess it would work similarly for Arch Linux.

The first step is that you would need to find out how the dependencies are named in Arch Linux, and change 

```
if [ -e /usr/bin/pacman ] ; then
echo "Please submit a pull request if you would like to see Arch Linux support."
exit 1
```

to something that actually installs the dependencies.

**Comment by aasgit** [comment]
hi, apologies for the very late reply. 

thank you very much for the precious comment. I'll try to make a native pkgbuild based on your suggestion and contribute to this. At the minute I'll be satisfied with AUR pkg here https://aur.archlinux.org/packages/appimage-git/

**Comment by probonopd** [comment]
If that one still has AppImageAssistant, then it is way outdated by now...

**Comment by aasgit** [comment]
d'oh! I'll fix it in the next days. thank you for the hint!

**Comment by probonopd** [comment]
Thanks @aasgit looks like `git clone https://aur.archlinux.org/appimage-git.git` now contains `appimaged` and `appimagetool`. Thanks!

__Please note:__ It is __not__ recommended to compile binaries on rolling release distributions like Arch Linux for use with __appimagetool__, For this purpose, please use the oldest still-supported distributions like CentOS 6.x, debian oldstable, Ubuntu LTS, or openSUSE Leap. The reason is explained in https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-portable-appimages.

**Comment by justinmoon** [comment]
[Seems ^^ is no longer maintained](https://aur.archlinux.org/packages/appimage-git/#comment-755366)
