### ISSUE TITLE
[appimaged] ISO9660 icons get extracted with zero bytes

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#328]
Some files (e.g., icons) are extracted from type 1 (ISO9660) AppImages with length 0, i.e., the file gets created but no bytes are copied into it. This happens, for example, when using wxHexEditor-0.23-x86_64.AppImage on xubuntu-16.04.1-desktop-amd64.iso; `/home/me/.local/share/icons/hicolor/48x48/apps/appimagekit_9422f875d4247597961ed0b56edc869b_wxHexEditor.png` then has zero bytes.

I suspect the error to be somewhere around [here](https://github.com/probonopd/AppImageKit/blob/16a81267489d8a5950317ae84c9a37075b840112/shared.c#L643-L655).

See https://github.com/libarchive/libarchive/issues/811, similar to libarchive minitar.

**Comment by probonopd** [comment]
PRs welcome that implement https://github.com/libarchive/libarchive/issues/811#issuecomment-272774216

**Comment by yjwudi** [comment]
hi,
@probonopd I'm looking at how to solve the bug. I did not download a wxHexEditor*.deb from the official website, so I use "apt-get install wxhexeditor" to install and copied the wxhexeditor_0.23+repack-2ubuntu1_amd64.deb from /var/cache/apt/archives/ to the work directory, then I use dpkg to extract it. These commands are finished on ubuntu-16.04-desktop-amd64.iso. After I extract the deb, i did not find the icons/ folder in /home/wxhexeditor.AppDir/usr/share/, then I compressed the AppDir using "./appimagetool-x86_64.AppImage wxhexeditor.AppDir/", and I got the wxHexEditor-x86_64.AppImage. I still not found the icon folder after I installed the AppImage. Why I did not have the icon folder? Did I get the wrong  wxhexeditor_0.23+repack-2ubuntu1_amd64.deb file?

**Comment by probonopd** [comment]
Hi @yjwudi thanks for looking into this. Let me point out that the issue is a bug in `appimaged` when trying to extract files from ISO0660. Sorry if this was not clear from the original description.

So if you take the file [wxHexEditor-0.23-x86_64.AppImage](https://bintray.com/probono/AppImages/download_file?file_path=wxHexEditor-0.23-x86_64.AppImage) and loop-mount it like so:
```
sudo mount -o loop wxHexEditor-0.23-x86_64.AppImage /mnt
```
then you will be able to see the icons in `/mnt/usr/share/icons` subdirectories. But when you use `appimaged`, then these icons are not properly extracted (using libarchive) due to some bug. I think that https://github.com/libarchive/libarchive/issues/811#issuecomment-272774216 shows how it would have to be done correctly, but so far I have not found what I am doing wrong in https://github.com/probonopd/AppImageKit/blob/16a81267489d8a5950317ae84c9a37075b840112/shared.c.

**Comment by TheAssassin** [comment]
My best guess is that it's the variables not being initialized. They contain whatever was stored on the assigned memory address before. https://github.com/probonopd/AppImageKit/blob/16a81267489d8a5950317ae84c9a37075b840112/shared.c#L639 ff.

Example:

```#include <stdio.h>
#include <stdint.h>
 
int main() {
  int64_t test;
  printf("%d", test);
  return 0;
}```

**Comment by probonopd** [comment]
Seems to be the same in the minitar example of libarchive; besides, I would have no clue what to initialize them with. 0?

**Comment by azubieta** [comment]
As far as I can remember I fix a similar issue related to icons extraction in AppImages type 1. I will close the issue, if the error persist please feel free to reopen it.
