### ISSUE TITLE
zsync file does not get generated

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#338]
Seems like there should be an -o somewhere?

> sprintf (command, "%s %s -u %s", zsyncmake_path, destination, basename(destination));

Workaround:

```
./appimagetool-x86_64.AppImage -v -u "zsync|$APPIMAGEFILENAME" /$APP.AppDir /appimage/$APPIMAGEFILENAME
zsyncmake -o /appimage/$APPIMAGEFILENAME.zsync /appimage/$APPIMAGEFILENAME
```

**Comment by probonopd** [comment]
This seems to work for me:
```
appimagetool ./Some.AppDir -u "zsync|http://foo.bar"
# and
appimagetool ./Some.AppDir Some.AppImage -u "zsync|http://foo.bar"
```
@ScarlettGatelyClark can you provide additional information?

**Comment by TheAssassin** [comment]
@ScarlettGatelyClark if you should encounter this problem again feel free to reopen the issue.
