### ISSUE TITLE
Change order of zenity and kdialog in desktop integration script

### ISSUE THREAD

**Issue by phoerious** [AppImage/AppImageKit#340]
The desktop integration script looks for the availability of zenity, kdialog and Xdialog in this order for displaying its prompts.

Having Xdialog as the last fallback appears to be a sensible decision, but kdialog should come before zenity as it is specific to the KDE platform, therefore likely to be only installed when KDE is installed and in that case also the preferred choice.

On my system (Arch Linux), zenity comes as a mandatory dependency for steam, although I run KDE. The desktop integration plugin therefore always uses zenity which doesn't integrate too well with the rest of the desktop. It would be great if kdialog would have higher priority.

**Comment by probonopd** [comment]
Not sure about the status of kdialog - it seems to be missing even from KDE-centric distributions like KDE neon, because it has not been ported to KF5. At least that was the status when I last asked. So I think it is more or less a legacy fallback?

**Comment by phoerious** [comment]
I have it on my system and would much prefer it over clunky zenity. I don't think it would be an issue to check for it first. Of course, the success rate of matching the more generic options is always higher, but then you also want to reach a certain amount of platform integration and should therefore match the more specific options first (IMHO).

**Comment by probonopd** [comment]
Perhaps we could make use of `$SESSIONTYPE` to determine the order? So, if KDE and kdialog available, use it as the first choice?

```
$ echo $SESSIONTYPE
gnome-session
```

**Comment by phoerious** [comment]
I don't think that variable exists everywhere. At least on my system, it isn't defined.

**Comment by probonopd** [comment]
Check all of the envs mentioned above, I updated the post above.

**Comment by phoerious** [comment]
I updated mine, too. :-)

Additionally to those mentioned above I also have
```
DESKTOP_SESSION=/usr/share/xsessions/plasma
```

**Comment by probonopd** [comment]
Perhaps `if [ env | grep KDE_ ] ; then ...`?

**Comment by phoerious** [comment]
You can test if the command exists anywhere in the $PATH with
```
command -v kdialog > /dev/null
```
Returns non-zero exit code when it isn't.

`env | grep KDE` is quite unsafe I think, but it may work.

**Comment by probonopd** [comment]
Will think about it; in the meantime feel free to change the desktopintegration script for your AppImage.

**Comment by phoerious** [comment]
Thanks!
I don't think the issue is very critical, by it would be nicer to have a more native dialog.

**Comment by darealshinji** [comment]
Writing your own tiny dialog programs instead of relying on zenity & co being present might be an option. A fallback dialog tool using FLTK might also be a solution (as I suggested [here](https://github.com/probonopd/AppImages/issues/116#issuecomment-261769849)).
For better KDE detection you could take a look at screenFetch or similar tools. But I think checking for the environment variable `KDE_FULL_SESSION` should normally be enough.

**Comment by probonopd** [comment]
Would accept a PR if it would come fully tested on KDE, GNOME, XFCE, Mate, Elementary, etc.

**Comment by azubieta** [comment]
Desktop integration scripts are no longer used. The issue will be closed, please reopen it if something else comes up.
