### ISSUE TITLE
Tray icon issues with Ubuntu Unity

### ISSUE THREAD

**Issue by phoerious** [AppImage/AppImageKit#351]
In our application we require a tray icon which we resolve with
```
QIcon icon = QIcon::fromTheme(name);
```
`name` is a relative icon name, not an absolute path (in our case just `"keepassxc"`).

Within the AppImage, multiple resolutions of this icon are located in `./usr/share/icons/hicolor/*/apps`.
According to `QIcon::themeSearchPaths()`, Qt looks in the following locations when resolving relative paths:
```
/tmp/.mount_TaLj1p/usr/share/icons
/usr/share/icons
/usr/share/pixmaps
:/icons
```
`/tmp/.mount_TaLj1p` is the runtime mount location of our AppImage, so Qt will find the icon in `/tmp/.mount_TaLj1p/usr/share/icons/hicolor/*/apps`. The fact that Qt really did find it, is checked with `icon.isNull()`. I also painted it onto a QWidget to make sure it actually is the correct icon, which it is.

Further down in the code, we use this icon as a tray icon:
```
m_trayIcon = new QSystemTrayIcon(this);

// ...

m_trayIcon->setIcon(icon);
```

This works fine on all platforms when I launch our binary directly. However, as soon as I package it as an AppImage, it stops working in Ubuntu Unity (and some other GTK-based DEs). The same problem also appears when I change into the source AppDir and start the `AppRun` binary. Even though Qt found the icon, Unity can't, when I pass it the icon object.

The only way to make it work on Ubuntu, is to add absolute paths to the icon object:
```
// for every resolution
icon.addFile(filename);
```
An alternative solution is to copy the icons to `$HOME/.local/share/icons/hicolor/*/apps`, but that defeats the purpose of an AppImage.

This problem does not occur in KDE Plasma 5.

**Comment by phoerious** [comment]
After some more research, I found that unsetting the `XDG_DATA_DIRS` environment variable before launching the AppImage also works. What does not work, however, is appending `/absolute/path/to/appimage/mountlocation/usr/share`.

**Comment by probonopd** [comment]
Does unsetting XDG_DATA_DIRS and then setting it to `/absolute/path/to/appimage/mount/location/usr/share` work?

**Comment by phoerious** [comment]
Yes, it does, but so does `/bla/blub/i/do/not/exist`
`AppRun`'s working directory seems to be `/path/to/mount/location/usr`, so I added this to my startup script:
```
export XDG_DATA_DIRS="\$(pwd)/share"
```
This results in `/tmp/.mount_1CrMtL/usr/share` and works, but so does a simple `unset XDG_DATA_DIRS`. Adding the following line instead, does not work, however:
```
export XDG_DATA_DIRS="\$(pwd)/share:\$XDG_DATA_DIRS"
```
Thee result is `/tmp/.mount_1CrMtL/usr/share:./share/:/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop` and a missing tray icon.

Maybe it would also work to have the `/tmp/.mount_1CrMtL` instead of ``/tmp/.mount_1CrMtL/usr` as working directory, but that breaks library loading.

**Comment by probonopd** [comment]
So, normally icons are in `/usr/share`, and we want them to also be picked up from the `./usr/share` inside the AppDir = mounted AppImage. That is what the export XDG_DATA_DIRS stuff is supposed to do. If I get this ticket right, it is actually doing the exact opposite?

**Comment by phoerious** [comment]
It seems so. At least on Ubuntu. On KDE I haven't had any tray icon issues.

**Comment by phoerious** [comment]
`AppRun` adds `./share` to the paths, so I thought maybe this relative path among all those absolute paths triggers some Ubuntu bug. But unfortunately, the same behavior stays when I kick it out:
```
export XDG_DATA_DIRS="\$(pwd)/share:/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
```

**Comment by probonopd** [comment]
AppRun should not put a relative path there...
https://github.com/probonopd/AppImageKit/blob/cc5513754e6cc9e6c4f2677a2afc211c7e08acc3/AppRun.c#L128-L130 and https://github.com/probonopd/AppImageKit/blob/cc5513754e6cc9e6c4f2677a2afc211c7e08acc3/AppRun.c#L52

**Comment by phoerious** [comment]
Apparently it does. But it doesn't seem to matter, since it's not working anyway.

**Comment by probonopd** [comment]
Can this issue be reproduced with other apps?

**Comment by phoerious** [comment]
I don't know. Can you come up with any other (Qt) apps that use tray icons? I don't want to try all of them.

**Comment by probonopd** [comment]
https://github.com/fathomssen/redtimer, they also have an AppImage...

**Comment by phoerious** [comment]
Seems to work there. But that app has some other serious rendering issues (dragging windows causes some serious eye injury).
But maybe they also use absolute paths and don't try to resolve via QIcon::fromTheme()?

**Comment by probonopd** [comment]
See [here](https://github.com/fathomssen/redtimer/search?utf8=%E2%9C%93&q=QSystemTrayIcon).

**Comment by phoerious** [comment]
I just found it myself. :-)
https://github.com/codestation/qcma/blob/b710981e6ef0a52346e458f0e942620beabebcbc/gui/qtrayicon.cpp#L101
So this is a bad app to compare with.

**Comment by probonopd** [comment]
@phoerious is this still an issue and may it be related to https://github.com/probonopd/QtQuickApp/issues/2?

**Comment by phoerious** [comment]
I think it is. We have unset XDG_DATA_DIRS in our startup script though, so it works for us.
But we are also having similar issues with our Snap package which we haven't yet solved. I suppose this is a general problem with Ubuntu and self-contained app containers.

**Comment by kskarthik** [comment]
Unity is no more for next LTS.

**Comment by probonopd** [comment]
We don't know if there will be something like a community-based Unibuntu...

**Comment by phoerious** [comment]
It's quite possible that a similar bug exists in Gnome or other GTK-based DEs (but I haven't tried).

**Comment by probonopd** [comment]
Solved in https://github.com/probonopd/QtQuickApp/issues/2#issuecomment-290944466

**Comment by probonopd** [comment]
Please leave a comment if you think that this should be reopened.
