### ISSUE TITLE
[appimaged] Replace libarchive by leaner ISO9660 extraction code

### ISSUE THREAD

**Issue by darealshinji** [AppImage/AppImageKit#353]
Linking libarchive statically should work around the issue with the different library names (and resolve https://github.com/probonopd/AppImageKit/issues/343). There shouldn't be any license issues, as libarchive is using a [BSD-style license](https://github.com/libarchive/libarchive/blob/master/COPYING).

**Comment by probonopd** [comment]
A better option would be to remove `libarchive´ by some (tiny) ISO9660 processing routines, e.g., CmgUtil from https://github.com/probonopd/klik/tree/master/trunk/client/trunk/libCmgUtl/src if it could be MIT licensed. Or isolate the ISO9660 functionality from libarchive.

**Comment by probonopd** [comment]
Statically linking libarchive for now.
