### ISSUE TITLE
Broken symlink in AppDirAssistant.AppDir/usr/bin/AppImageKit/bin/strace

### ISSUE THREAD

**Issue by RazZziel** [AppImage/AppImageKit#36]
```
lrwxrwxrwx 1 raziel raziel 76 Mar 20  2015 AppDirAssistant.AppDir/usr/bin/AppImageKit/bin/strace -> /home/liveuser/Desktop/AppDirAssistant 0.3.2p1.AppDir/usr/bin/strace_private
```

Shouldn't we include the proper strace binary?

**Comment by probonopd** [comment]
See https://github.com/probonopd/AppImageKit/blob/master/AppDirAssistant.AppDir/usr/bin/profileapp.py#L72 - we use  aprivate copy of strace since otherwise there is a permissions error when strace is run from within the AppImage. Did you find a way around that?

**Comment by probonopd** [comment]
Is this still an issue @RazZziel?

**Comment by RazZziel** [comment]
Not really an issue, but an _ugly_, as it'll only work on a system where `/home/liveuser/Desktop/AppDirAssistant 0.3.2p1.AppDir/usr/bin/strace_private` exists. There's no alternative solution?

**Comment by TheAssassin** [comment]
At a glance it looks like this issue is about AppImage type 1. This type is no longer developed and we do not recommend using it any more.

I think I can safely close this issue.

**Comment by probonopd** [comment]
AppDirAssistant and AppImageAssistant are deprecated.
