### ISSUE TITLE
Get rid of the glib dependency

### ISSUE THREAD

**Issue by RazZziel** [AppImage/AppImageKit#4]
While glib is commonplace in most systems, it's not always available in many minimalistic systems, like TinyCoreLinux, and this dependency should be avoided in a truly portable package format.

Currently glib is used for:
- isofs.c
  *\* g_hash_*
  *\* g_strdup, g_strsplit, g_strconcat, g_strfreev, g_free, g_return_val_if_fail
- runtime.c
  *\* g_build_filename, g_strdup

Possible solutions:
- Link glib statically
  *\* Pros: No source code change needed
  *\* Cons: +300Kb in the runtime binary (28K -> 328K)
- Modify isofs.c to remove glib dependency
  *\* Pros: likely smaller
  *\* Cons: lots of work

Regarding the first solution, linking glib (and zlib) statically is managed with [this patch](http://pastebin.com/GJJ3qjxM).

Regarding the second solution, the g_hash functions could be replaced by some alternative hash implementation in C ([example](http://stackoverflow.com/questions/1138742/looking-for-a-good-hash-table-implementation-in-c)), and the string manipulation functions should be pretty trivial to implement with string.h

**Comment by TheAssassin** [comment]
@RazZziel please note that pastebin links in an issue report are a bad idea, as they usually disappear quickly. Your links no longer work.

At a glance it looks like these issues were about AppImage type 1. This type is no longer developed and we do not recommend using it any more.

I think I can safely close this issue.
