### ISSUE TITLE
Attempt to install an AppImage file but nothing happens

### ISSUE THREAD

**Issue by chiefolaf** [AppImage/AppImageKit#404]
Hi there, trying to install Etcher and was suggested by their dev team to raise this with yourselves.

Summary:
Unable to install the Etcher.appImage either by double-clicking or from command line.  With and without root in both cases.  
Distro: Mint 18
Kernel: 4.4.0-21-generic

I followed [this suggestion](https://askubuntu.com/questions/774490/what-is-an-appimage-how-do-i-install-it).  the chmod seemed to work but executing gave me a permission denied error:

`$ sudo chmod a+x Etcher-1.0.0-linux-x64.AppImage`
`$ sudo ./Etcher-1.0.0-linux-x64.AppImage`
`sudo: unable to execute ./Etcher-1.0.0-linux-x64.AppImage: Permission denied`

After guidance from the nice Etcher devs, I checked the [required dependencies](https://github.com/resin-io/etcher/blob/master/scripts/build/debian/config.json#L12) were installed (sorry for the great, ugly pasting!  TL;DR - they were/are):

`$ dpkg-query -l gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk2.0-0 liblzma5 libnspr4 libnss3 libpango1.0-0 libstdc++6 libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 policykit-1-gnome`
> Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  gconf-service                     3.2.6-3ubuntu6        amd64                 GNOME configuration database system (D-Bus service)
ii  libasound2:amd64                  1.1.0-0ubuntu1        amd64                 shared library for ALSA applications
ii  libasound2:i386                   1.1.0-0ubuntu1        i386                  shared library for ALSA applications
ii  libatk1.0-0:amd64                 2.18.0-1              amd64                 ATK accessibility toolkit
ii  libatk1.0-0:i386                  2.18.0-1              i386                  ATK accessibility toolkit
ii  libc6:amd64                       2.23-0ubuntu7         amd64                 GNU C Library: Shared libraries
ii  libc6:i386                        2.23-0ubuntu7         i386                  GNU C Library: Shared libraries
ii  libcairo2:amd64                   1.14.6-1              amd64                 Cairo 2D vector graphics library
ii  libcairo2:i386                    1.14.6-1              i386                  Cairo 2D vector graphics library
ii  libcups2:amd64                    2.1.3-4               amd64                 Common UNIX Printing System(tm) - Core library
ii  libcups2:i386                     2.1.3-4               i386                  Common UNIX Printing System(tm) - Core library
ii  libdbus-1-3:amd64                 1.10.6-1ubuntu3       amd64                 simple interprocess messaging system (library)
ii  libdbus-1-3:i386                  1.10.6-1ubuntu3       i386                  simple interprocess messaging system (library)
ii  libexpat1:amd64                   2.1.0-7ubuntu0.16.04. amd64                 XML parsing C library - runtime library
ii  libexpat1:i386                    2.1.0-7ubuntu0.16.04. i386                  XML parsing C library - runtime library
ii  libfontconfig1:amd64              2.11.94-0ubuntu1.1    amd64                 generic font configuration library - runtime
ii  libfontconfig1:i386               2.11.94-0ubuntu1.1    i386                  generic font configuration library - runtime
ii  libfreetype6:amd64                2.6.1-0.1ubuntu2.3    amd64                 FreeType 2 font engine, shared library files
ii  libfreetype6:i386                 2.6.1-0.1ubuntu2.3    i386                  FreeType 2 font engine, shared library files
ii  libgcc1:amd64                     1:6.0.1-0ubuntu1      amd64                 GCC support library
ii  libgcc1:i386                      1:6.0.1-0ubuntu1      i386                  GCC support library
ii  libgconf-2-4:amd64                3.2.6-3ubuntu6        amd64                 GNOME configuration database system (shared libraries)
ii  libgconf-2-4:i386                 3.2.6-3ubuntu6        i386                  GNOME configuration database system (shared libraries)
ii  libgdk-pixbuf2.0-0:amd64          2.32.2-1ubuntu1.2     amd64                 GDK Pixbuf library
ii  libgdk-pixbuf2.0-0:i386           2.32.2-1ubuntu1.2     i386                  GDK Pixbuf library
ii  libglib2.0-0:amd64                2.48.2-0ubuntu1       amd64                 GLib library of C routines
ii  libglib2.0-0:i386                 2.48.2-0ubuntu1       i386                  GLib library of C routines
ii  libgtk2.0-0:amd64                 2.24.30-1ubuntu1      amd64                 GTK+ graphical user interface library
ii  libgtk2.0-0:i386                  2.24.30-1ubuntu1      i386                  GTK+ graphical user interface library
ii  liblzma5:amd64                    5.1.1alpha+20120614-2 amd64                 XZ-format compression library
ii  liblzma5:i386                     5.1.1alpha+20120614-2 i386                  XZ-format compression library
ii  libnspr4:amd64                    2:4.13.1-0ubuntu0.16. amd64                 NetScape Portable Runtime Library
ii  libnspr4:i386                     2:4.13.1-0ubuntu0.16. i386                  NetScape Portable Runtime Library
ii  libnss3:amd64                     2:3.28.4-0ubuntu0.16. amd64                 Network Security Service libraries
ii  libnss3:i386                      2:3.28.4-0ubuntu0.16. i386                  Network Security Service libraries
ii  libpango1.0-0:amd64               1.38.1-1              amd64                 Layout and rendering of internationalized text (transitional package)
ii  libpango1.0-0:i386                1.38.1-1              i386                  Layout and rendering of internationalized text (transitional package)
ii  libstdc++6:amd64                  5.4.0-6ubuntu1~16.04. amd64                 GNU Standard C++ Library v3
ii  libstdc++6:i386                   5.4.0-6ubuntu1~16.04. i386                  GNU Standard C++ Library v3
ii  libx11-6:amd64                    2:1.6.3-1ubuntu2      amd64                 X11 client-side library
ii  libx11-6:i386                     2:1.6.3-1ubuntu2      i386                  X11 client-side library
ii  libxcomposite1:amd64              1:0.4.4-1             amd64                 X11 Composite extension library
ii  libxcomposite1:i386               1:0.4.4-1             i386                  X11 Composite extension library
ii  libxcursor1:amd64                 1:1.1.14-1            amd64                 X cursor management library
ii  libxcursor1:i386                  1:1.1.14-1            i386                  X cursor management library
ii  libxdamage1:amd64                 1:1.1.4-2             amd64                 X11 damaged region extension library
ii  libxdamage1:i386                  1:1.1.4-2             i386                  X11 damaged region extension library
ii  libxext6:amd64                    2:1.3.3-1             amd64                 X11 miscellaneous extension library
ii  libxext6:i386                     2:1.3.3-1             i386                  X11 miscellaneous extension library
ii  libxfixes3:amd64                  1:5.0.1-2             amd64                 X11 miscellaneous 'fixes' extension library
ii  libxfixes3:i386                   1:5.0.1-2             i386                  X11 miscellaneous 'fixes' extension library
ii  libxi6:amd64                      2:1.7.6-1             amd64                 X11 Input extension library
ii  libxi6:i386                       2:1.7.6-1             i386                  X11 Input extension library
ii  libxrandr2:amd64                  2:1.5.0-1             amd64                 X11 RandR extension library
ii  libxrandr2:i386                   2:1.5.0-1             i386                  X11 RandR extension library
ii  libxrender1:amd64                 1:0.9.9-0ubuntu1      amd64                 X Rendering Extension client library
ii  libxrender1:i386                  1:0.9.9-0ubuntu1      i386                  X Rendering Extension client library
ii  libxss1:amd64                     1:1.2.2-1             amd64                 X11 Screen Saver extension library
ii  libxss1:i386                      1:1.2.2-1             i386                  X11 Screen Saver extension library
ii  libxtst6:amd64                    2:1.2.2-1             amd64                 X11 Testing -- Record extension library
ii  libxtst6:i386                     2:1.2.2-1             i386                  X11 Testing -- Record extension library
ii  policykit-1-gnome                 0.105-2ubuntu2        amd64                 GNOME authentication agent for PolicyKit-1

Any suggestions what else I could try to get it working?

**Comment by probonopd** [comment]
What happens if you run without sudo?

**Comment by chiefolaf** [comment]
Hi probonopd - I tried that first with the same result.
However I found the problem (after a couple of random stabs in the dark basically):

I had the .appImage file saved to:
> /media/<2nd HDD>/Downloads/

Shifting it to, say:
> /home/me/Documents/

and it works no problem.  My laptop HDD is small so had added a second.
Didn't think that should be an issue though? I'm a Linux rookie though so not much is too clear right now!

**Comment by probonopd** [comment]
Type `mount`. Do you see `noexec` in the line with `/media/<2nd HDD>/`?

**Comment by chiefolaf** [comment]
I do indeed!  Thanks.  Have noticed I need root to unmount it now too, which I didn't have to do before.  Not sure if that's related.  I didn't intentionally change anything but I guess something's been altered.

**Comment by probonopd** [comment]
Maybe check your `/etc/fstab` file and remove `noexec` (please be sure what you are doing!)
