### ISSUE TITLE
update runtime inside of appimage file

### ISSUE THREAD

**Issue by Kodiman** [AppImage/AppImageKit#417]
Hi, Your AppImage software is excellent quality. The best "portable apps" for linux.

Please implement a command or script that updates the runtime of the appimages.  Such as for example:

appimagetool --update-runtime  APPIMAGE-FILENAME
appimagetool --update-runtime --recursive APPIMAGES-FOLDERNAME

Please test that it works for upgrade to your new portable runtime (that uses .home and .config folders).

https://github.com/AppImage/AppImageKit/commit/d17fdefadcb98befa66c29137ce25731256f8f2a

This would be similar to the VMware ThinApp portables tool "Relink.exe -Recursive foldername".

Please status update. Much appreciated. Thanks!

**Comment by probonopd** [comment]
Thanks for this suggestion Kodiman.

Until someone implements this, you can do the following:
* Launch the AppImages in question
* While they are running, do:

```
find "/tmp" -maxdepth 1 -name '.mount_*' -type d -exec appimagetool -n {} \;
```

This will produce a new AppImage with the new runtime for each running AppImage.

**Comment by probonopd** [comment]
Please let me know if this is sufficient for you.

**Comment by Kodiman** [comment]
Hi, That is a good start. Your work is appreciated. Best regards. Thanks.

**Comment by TheAssassin** [comment]
The problem with being able to update the runtime inside the AppImage is the fact that the runtime won't have the exact same size as before. Thus, one would have to create another file, insert the new runtime in the beginning and append the old squashfs or something like that. I don't know whether this use case is that common, so I'm not sure if it's worth implementing this at all, considering that it's rather easy to repackage an existing AppImage with the current toolchain. (You could just `--appimage-extract` as well.)

**Comment by Kodiman** [comment]
Hi, You can batch update the runtime of the appimages by making new appimages from the old files.  You can automatically rename the old appimage files to "filename.old" or such. This should be an automated command or script. Similar to the professional quality VMware ThinApp portables tool "Relink -Recursive foldername". That would be excellent. Thanks.

**Comment by probonopd** [comment]
Generally we just produce new AppImages rather than rework old ones. But I have given a semi-automatic solution above that should be sufficient for most needs. If this is not sufficient, then please help us working toward an implementation.

**Comment by Kodiman** [comment]
Some of the AppImages apps on the download pages have old dates. Does that indicate those have old versions of runtimes? Any plans to produce updates of those with the current runtime? Thanks.

**Comment by probonopd** [comment]
Yes. They will be updated whenever new versions of the AppImages get built. Are there ones you would be especially interested in? Then I can trigger a rebuild for these manually.

**Comment by Kodiman** [comment]
The AppImages apps such as here https://bintray.com/probono/AppImages

Please consider updating (rebuild) all the AppImages to the current runtime. (That will provide the benefits of new runtime features such as portable home folders.) Greatly appreciated. Thanks.

**Comment by TheAssassin** [comment]
@Kodiman we can do that, but we need a list of apps to be updated. If you want this to happen soon, how about compiling a list of old AppImages? You could automate that I guess. You can get the AppImage type in a bash script by calling them with `--appimage-version` (see https://github.com/AppImage/AppImageKit/#command-line-arguments) and check its return value.

**Comment by Kodiman** [comment]
Hi, As per your message, please try to update these to your best new runtime. With the portable home feature. The list is in random order. Perhaps start with the most popular apps, as you have time. Your efforts are appreciated. Thanks.

AppImageKit
AppImageUpdate
Audacity
AvahiDiscover
Aseprite
Atom
BlueGriffon
Boostnote
Calibre
Clementine
Corebird
Chromium
Darktable
Demonsaw
Dia
EncryptPad
Engauge
Etcher
FBReader
FeedReader
Firefox
Firefox_Developer_Edition
Flowblade_Movie_Editor
FontForge
Fotoxx
FreeMind
GIMP
Go_For_It
GoogleEarth
Gqrx
Graphmonkey
Gnu_PSPP
Hugin
Hydrogen
Inkscape
Instant_Lyrics
Iridium
Kadu
Krita
LMMS
LeoCAD
LibreCAD
kodi
Leafpad
LibreOffice
LibreOfficeDev
Linphone
MediaInfo
MediathekView
Meld
Mumble
Natron
Otter
Pandoc
Notes
OBS
OpenNX_client
OpenSCAD
Peek
PowerShell
Qcad
Quassel
Quod_Libet
Ramme
Remmina
RetroShare06
Ricochet
SMTube
SciLab
ScreenCloud
Scribus
Shotcut
Sigil
SimpleScreenRecorder
Slack
SolveSpace
Stellarium
Sublime
Synergy
Terminix
Transmission
Trojita
Typora
VSXu
WMail
Wavebox
WebTorrent
Wire
Wireshark
X2Go_Client
XChat
XChat_IRC
Xara_Xtreme
XnView_MP
Yout
ZeroNet
Zim_Desktop_Wiki
easyMP3Gain
gPodder
ghostwriter
mpv_Media_Player
ocenaudio
puddletag
qBittorrent
qTox
vokoscreen
wxHexEditor
xdgurl
Syncthing_GTK
Thunderbird
Vivaldi
VLC

**Comment by probonopd** [comment]
@Kodiman I have triggered rebuilds for most of them (Travis CI now hates me). Please keep in mind that my example AppImages on Bintray are just for demonstration, and only made so that upstream application projects can test them. If you want proper AppImages, please ask the upstream application authors to provide an AppImage.

**Comment by Kodiman** [comment]
Hi, Thanks for your time and effort. AppImage is excellent. You are the best. Much appreciated. Thanks.

**Comment by Kodiman** [comment]
Hi, The build dates on bintray etc have not updated. Did the triggered rebuilds fail? Is their an ETA? Thanks.

**Comment by probonopd** [comment]
Many have, some haven't. 

Please keep in mind that my example AppImages on Bintray are just for demonstration, and only made so that upstream application projects can test them. If you want proper AppImages, please ask the upstream application authors to provide an AppImage.

This means that __for example, if you would like to see a Firefox AppImage, please ask the Firefox team, and so on.__

**Comment by Kodiman** [comment]
Hi, Some of the rebuilds failed? Technical problems? Can it be fixed? Thanks

**Comment by probonopd** [comment]
If you want proper AppImages, please ask the upstream application authors to provide an AppImage.

**Comment by Kodiman** [comment]
Hi, It has been fixed? Can trigger the rebuilds to do more? Please. Thanks.
