### ISSUE TITLE
can't copy anything under ubuntu mate

### ISSUE THREAD

**Issue by Matrix-Zhang** [AppImage/AppImageKit#421]
i am use mongobooster AppImage Version at ubuntu mate, but the clipboard not work, it should paste text from mate, but can not copy text to paste to some where

**Comment by TheAssassin** [comment]
The AppImage project cannot provide support for AppImages packaged by third parties. Please ask the upstream authors of the software for help. If you can prove that a bug in AppImageKit software is causing the problem, feel free to reopen this issue.

Beware that you need to provide more information when posting an issue somewhere in general. A link to the actual AppImage and the exact version of your operating system will help the other team, and they won't have to ask you first and await a reply.

**Comment by probonopd** [comment]
That being said, we are happy to support the developers of mongobooster in optimizing their AppImage.

**Comment by TheAssassin** [comment]
Yes, of course.
