### ISSUE TITLE
binreloc.c still needed?

### ISSUE THREAD

**Issue by darealshinji** [AppImage/AppImageKit#431]
Are `binreloc.c` and `binreloc.h` still needed? `appimagetool.c` only uses the `br_strcat()` function which could be replaced with `strcat()` or something else. `appimagetoolnoglib.c` also uses `br_find_exe_dir()` but this version of appimagetool is not used anymore I think.

**Comment by probonopd** [comment]
Define "needed". I want to have it around so that the functions it provides can be used whenever needed.

**Comment by TheAssassin** [comment]
Well, if someone came up with a PR removing the dependency that doesn't break the builds, I guess we would happily merge it.

**Comment by probonopd** [comment]
Well, I'm not strictly against removing it, but I don't see a big advantage either.

**Comment by TheAssassin** [comment]
Smaller binaries perhaps? Also it's another dependency we don't have to stay compatible to any more.
