### ISSUE TITLE
functions.sh generate_appimage GLIBC_NEEDED set after first use

### ISSUE THREAD

**Issue by schuhschuh** [AppImage/AppImageKit#432]
`generate_appimage ` in `https://raw.githubusercontent.com/AppImage/AppImages/master/functions.sh` sets `GLIBC_NEEDED` before first use (`rm` old output):

```bash
rm ../out/$APP"-"$VERSION".glibc"$GLIBC_NEEDED"-"$ARCH".AppImage" 2>/dev/null || true
GLIBC_NEEDED=${GLIBC_NEEDED:=$(glibc_needed)}
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION".glibc"$GLIBC_NEEDED"-"$ARCH".AppImage"
```

**Comment by TheAssassin** [comment]
Please note that `functions.sh` and its friends in the AppImages repository merely serve as examples how to use appimagetool manually. They are somewhat considered deprecated, and we prepare to get rid of them entirely.

We recommend the usage of linuxdeployqt for all packaging. Don't get confused by the name, it is just written in Qt but can be used to package any application. Using it has several advantages, e.g. it provides real solutions for most hacks and workarounds in `functions.sh`.

Please consider a switch to linuxdeployqt.

**Comment by TheAssassin** [comment]
That said, we're in the wrong issue tracker anyway, for discussions about `functions.sh` this one should be used: https://github.com/AppImage/AppImages/issues

Please reopen the issue there, because I consider it a valid problem that should be looked at further.
