### ISSUE TITLE
Beginner friendly instructions

### ISSUE THREAD

**Issue by elhanan** [AppImage/AppImageKit#439]
Please change the instructions on the How to Run an AppImage section of the appimage.org homepage to account for the following. 

If you ever wonder what the following commands do, type the first command word following by " --help" and press enter, or type "man " followed by the first command word and press enter.

The $ symbol before a command means you do not need root/administrator's permission to run the command. The # symbol before a command means you do. The $ and # symbols usually indicate a command if not talking about Twitter hashtags or money.

If a command says "command not found" after you hit enter on it, you first need to install another package that will let you use that command. Try googling what package contains the command and install that first.

1. Download a file that has .AppImage at the ending of its name with either a web browser or wget.
2. Open a command line interface (CLI)/command prompt/terminal window and type
$ cd ~/Downloads
Press enter.
The "cd " command navigates through directories/folders in the terminal as opposed to in a GUI (Graphical User Interface).
3. If you haven't downloaded the .AppImage file yet and want to use wget in the terminal, type
$ wget URL-of-the-.AppImage-file
Press enter.
URL is the web address you would type in a web browser (such as Firefox, Chrome, Opera, etcetera)'s address bar. The acronym means Uniform Resource Locator. Replace "URL-of-the-.AppImage-file" with the download link you would find in the address bar of a web browser when it starts to download.
4. Use the list (ls) command to see if you have the file in the Downloads folder.
$ ls
Press enter.
5. If the file .AppImage file is there, type (without "TheFirstPartOfTheName", substituting the name of the file you found with the ls command in there without a space between the name and the ".AppImage" file extension)
$ chmod a+x "TheFirstPartOfTheName".AppImage
Press enter.
It is now installed.
6. Everytime you want to run the app, either type
$ ./"TheFirstPartOfTheName".AppImage
Or double click on the file, and you're all set!

**Comment by probonopd** [comment]
Thanks @elhanan but why would we want to teach people the command line? I'd shorten the instructions to this:

1. Go to the download page of the application your are interested in, e.g., https://krita.org/en/download/krita-desktop/
2. Download the AppImage for the architecture of your computer (most likely Intel 64-bit a.k.a. x86_64)
3. Open your file manager and browse to the location of the AppImage
4. Right-click on the AppImage and click the ‘Properties’ entry
5. Switch to the Permissions tab and
6. Click the ‘Allow executing file as program’ checkbox if you are using a Nautilus-based file manager (Files, Nemo, Caja), or click the ‘Is executable’ checkbox if you are using Dolphin, or change the ‘Execute’ drop down list to ‘Anyone’ if you are using PCManFM
7. Close the dialog
8. Double-click on the AppImage file to run

![](https://cdn-standard4.discourse.org/uploads/appimage/optimized/1X/a4889c5cb8711d6845b58135080787d2f370af35_1_500x500.gif)

http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80

**Comment by probonopd** [comment]
If you want to skip steps 3 to 8, then you can install the optional `appimaged` daemon. It will do this automatically for you, and it will put a launcher entry in the applications menu for you automatically.

https://discourse.appimage.org/t/new-appimaged-optional-daemon-that-registers-appimages-with-the-system/87

**Comment by elhanan** [comment]
Cool, thanks.
