### ISSUE TITLE
Wrong Icon in Unity Dock

### ISSUE THREAD

**Issue by IvanX507** [AppImage/AppImageKit#443]
Hello, I’m recently installed the daemon appimaged because i wanted to have my appimages integrated in my system, and its working really well except for one little thing.
Despite the fact that in the Unity dash the apps appears well with this respective icons, in the Unity dock appears a folder icon instead of the normal icon of the app.
I don't know if I’m doing something wrong or is a bug.

Example:
http://imgur.com/a/kQ9HX

Thanks for the Help.

**Comment by probonopd** [comment]
Does this happen with other AppImages too?

**Comment by IvanX507** [comment]
Yes

**Comment by probonopd** [comment]
Which ones?

**Comment by IvanX507** [comment]
Krita and Kdevelop, i have a clean Ubuntu installation so thats the only appimages that i have for now

**Comment by probonopd** [comment]
So it's a bug but not a high priority one since Unity is going to go away soon anyway.

**Comment by TheAssassin** [comment]
Due to Unity being shut down, and no updates in the last months, I'll close the issue. Feel free to reopen if the error persists.
