### ISSUE TITLE
Switch back to upstream squashfs-tools repository

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#446]
The [upstream repository](https://github.com/plougher/squashfs-tools/) seems to have been reactivated by the original author. I think we might want to change our submodule to the official mirror again. The patch has been merged, and our fork does, except for README, not differ from the upstream project.

@probonopd any reasons that would block us from doing so?

**Comment by probonopd** [comment]
Great to see the patches were merged upstream.

Other than "it works for us as it is now" I see no reason not to switch back.
