### ISSUE TITLE
appdata.xml validation is too strict, rejects perfectly valid files

### ISSUE THREAD

**Issue by JonasT** [AppImage/AppImageKit#449]
The appdata.xml validation is too strict, rejects perfectly good-looking files for minor reasons like:

- the description paragraph is considered too short
- there is no screenshot (what if it's a command line tool?)
- the person writing it has no good place to host a screenshot and therefore can't provide an URL
- the screenshot arbitrary doesn't load today because the webserver happens to be down and the URL isn't reachable right now (this breaks automated builds, people! why would you enforce this??)
- there are no translation info tags
- the project license is specified as `Proprietary` (newsflash: we still have proprietary software. should people not be allowed to package it?)
- ..

None of which IMHO are a valid reason to reject such a file. This makes file unbuildable for completely nonsense reasons like:

1. there wasn't that much to write about in the description because it's a simple tool (punishing perfectly good terse descriptions)
2. the author doesn't have a good webhoster for screenshots (punishing people who can't upload files to a good world-reachable location)
3. I want to package an application which has a Proprietary license (pushing people not to package useful applications that don't happen to be available as free software yet)
4. I don't know foreign languages and therefore didn't add any translation info (punishing English speakers)
5. my webhost is down and suddenly I can't package up my application anymore (punishing people without solid infrastructure and risking to break automated builds with unexpected failures which aren't actually directly blocking the build process at all)

This is completely overreaching and makes packaging with AppImage a pain. Therefore, please convert such reasonable things to warnings, print them out and *proceed anyway*. Thanks.

Edit: the appstream-util version I used is 0.7.1 as shipped with Fedora 26

**Comment by JonasT** [comment]
For what it's worth, I used `appstream-util validate` assuming that is also what appimagetool uses since appimagetool just printed out this with zero detail info:
```
AppStream upstream metadata found in usr/share/metainfo/simplehorror.appdata.xml
Validation of files failed
Failed to validate AppStream information with appstream-util
```
If appimagetool actually uses something else that doesn't enforce all the above things, then this issue is probably invalid

**Comment by JonasT** [comment]
Yup it seems appimagetool doesn't actually use the regular `appstream-util validate` so this is all wrong and the ticket is invalid, sorry about that! Closing this

**Comment by probonopd** [comment]
> The appdata.xml validation is too strict

cc @ximion

**Comment by ximion** [comment]
`appstream-util` is not my tool, but hughsie's (for some reason, I can't highlight him here...)
That tool validates more than just style and fails if the style isn't 100% okay.

The `appstreamcli` tool will always only fail if there are issues with the file that make it completely unfit for use (errors) or that are serious enough and should get fixed as soon as possible (warnings) and does the style hints as infos or pedantic issues which don't make the file fail validation, but still show up in the output.

I guess using the `validate-relax` command on appstream-util helps, as well as giving users an option to skip validation with appstream-util. Using appstreamcli should always be safe (if its version is high enough), if there are issues with that, let me know.

**Comment by probonopd** [comment]
cc @hughsie

**Comment by probonopd** [comment]
> I guess using the `validate-relax` command on appstream-util helps

Yes, `appimagetool` and [AppImageHub](https://github.com/AppImage/AppImageHub) are using that 

> as well as giving users an option to skip validation with appstream-util

`appimagetool -n, --no-appstream          Do not check AppStream metadata`

**Comment by hughsie** [comment]
> This makes file unbuildable for completely nonsense reasons like:

Not nonsense, and I actually find that quite insulting -- I'm not making up random rules to make everyone's life more difficult.

> there is no screenshot

If it's a CLI application then you shouldn't be using `type=desktop`.

> there wasn't that much to write about in the description because it's a simple tool (punishing perfectly good terse descriptions)

Can you give me an example? The style checker deliberately checks for the length of the description as it wants upstream to provide a description that matches in style to all the other applications. The front-end to the data cannot possibly look good when one application is providing a few words and another is providing 10 paragraphs.

> the author doesn't have a good webhoster for screenshots

Then the author should sign up to one of the free image-hosting resources, or just check in the screenshot to git and use a link to github.

> I want to package an application which has a Proprietary license

Which is fine, you just have to use `LicenseRef-proprietary` rather than something nonstandard.

> I don't know foreign languages and therefore didn't add any translation info

You don't have to speak non-English languages to be able to accept translations... If you really can't then you can just do `<translation/>`

> and risking to break automated builds with unexpected failures

Well, is it better to allow the build to complete and then have no screenshots in the end-user application like gnome-software? I'd say knowing about the failure at build time is better than knowing about it at user-searching-for-app-time.

**Comment by JonasT** [comment]
> Not nonsense, and I actually find that quite insulting -- I'm not making up random rules to make everyone's life more difficult.

@hughsie sorry, I was under the completely false impression that I needed to fix all those issues to be able to include it into an AppImage. (which would have been bad IMHO and did frustrate me a bit) As non-enforced style remarks, it's of course something completely different and it seems much more reasonable. Sorry for the ranting!

Some hopefully constructive suggestions for improvement:

"LicenseRef-Proprietary": this is really hard to find when searching the web for the proper value, e.g. npm seems to have used "Unlicensed" at some point. Could you maybe make the tool check "Proprietary" as a special value and then output an error that specifically remarks that the correct value is "LicenseRef-Proprietary" instead of just a generic error that the value is not a known SPDX value?

Also, if `validate` is meant to be enforced e.g. for gnome-software I suggest not reporting screenshot download as a failure leading to exit code != 0 but rather as a warning, since otherwise automated checks might break just because the image hoster happens to be temporarily down.

**Comment by TheAssassin** [comment]
As @probono mentioned, there are several appstream specification issues that have had to be addressed for AppImage and its ecosystem. I agree that the wording of the first comment was unnecessarily aggressive, albeit there are several valid points in it.

The workarounds @hughsie posted are just that, workarounds. The `<translation>` tag for example, I totally agree that it is not a hard requirement, or the verification of the image links, even GitHub is down at times. Also, in terms of web security, it is considered a bad mistake to link to unverified images on random servers and make people embed these into other applications, I guess we are all aware of the fact that libjpeg etc. have their security flaws.

I will post a more detailed analysis later.

**Comment by probonopd** [comment]
I understand that `<translation/>` is the way to say "there are no translations". I'd say that's fine, as long as it's very clearly documented in the [quickstart example](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) which @ximion told me I should point people to.

It would be _very beneficial_ to AppStream if both (as I call them) "AppStream lint tools" (by @ximion and @hughsie) including earlier versions thereof would accept at least the __4.1.2. Example file__ without complaining about anything; in other words the quickstart example should be written in such a way.
