### ISSUE TITLE
appdata.xml files that fail validation during AppImage build with appimagetool will simply print out an error that it failed, with zero info on what exactly is the problem

### ISSUE THREAD

**Issue by JonasT** [AppImage/AppImageKit#450]
appdata.xml files that fail validation during AppImage build with appimagetool will simply print out an error that it failed, with zero info on what exactly is the problem:

```
AppStream upstream metadata found in usr/share/metainfo/simplehorror.appdata.xml
Validation of files failed
Failed to validate AppStream information with appstream-util
```

This means I need to find out it uses appstream-util manually and then use `appstream-util validate` hoping this is also what AppImageKit would have used (or is it `appstream-util validate-relax`? I don't even know) and then find out myself what is the actual problem with it.

Therefore, to make fixing appdata.xml files easier and to prevent people from digging up "errors" with appstream-util that wouldn't actually stop appimagetool itself, please change the error to provide actual details.

appimagetool version:
```shell
 ./appimagetool-x86_64.AppImage --version
Version: continuous-1-g2c0e50c
```
Operating system: Fedora 26 x64

**Comment by probonopd** [comment]
Thanks for pointing this out, this is clearly not ideal. We are currently using 

```
sprintf (command, "%s validate-relax %s", g_find_program_in_path ("appstream-util"), appdata_path);
int ret = system(command);
```

https://github.com/AppImage/AppImageKit/blob/cfa96e0b1c87fbd29e54fdcfae10ed2b88404359/appimagetool.c#L525

I was assuming that the `system()` call would pass through all messages to stdout and stderr. Apparently I was wrong. Can you propose how to do this better? Thanks.

**Comment by JonasT** [comment]
Urghs, I investigated some more and I ran the command inside python in a way that `stderr` shows up but `stdout` doesn't... sorry. With that fixed, it shows up nicely!

I kinda feel like I filed a similar ticket too when I tried AppImage many months ago 😕 silly me, I guess I should learn how to leave stdout/stderr alone properly

**Comment by TheAssassin** [comment]
Never mind. Every ticket that is solved this quickly is a good one. It usually means someone increased their knowledge. I don't see a problem with this at all. It's a lot better than people getting dissatisfied of using a software because of lack of knowledge. Feel free to open more tickets, or even better, visit our IRC channel: #appimage on Freenode. If you're unexperienced with IRC, please read [this very good guide](https://workaround.org/getting-help-on-irc/).
