### ISSUE TITLE
Help with two programs

### ISSUE THREAD

**Issue by NewUserLinux** [AppImage/AppImageKit#455]
Please build Aegisub and MKVToolnixGUI in AppImage. Not working lastest version in Ubuntu 14.04.

**Comment by TheAssassin** [comment]
You're in the wrong repo for that, please see https://github.com/AppImage/AppImages. You need to create an issue there, maybe someone will find time to help you.

Also, think about improving your style of asking a question. You aren't providing any real information. The minimum would be a few links to the projects, what you have tried (a *lot* more detailedly than you did) with logs, where you had trouble and so on. No one will be able to help you, and no one will be willing to search for all the missing details themselves. You should always provide more information than what you think is right, devs can pick the essentials out of it easily, but get annoyed when some pieces are missing.

**Comment by probonopd** [comment]
Please ask the Aegisub and MKVToolnixGUI projects for AppImages. We are happy to help the Aegisub and MKVToolnixGUI developers to make AppImages, but we do not make AppImages for them.
