### ISSUE TITLE
cp: cannot create regular file '/usr/lib/unknown-linux-gnu/pkgconfig/': No such file or directory

### ISSUE THREAD

**Issue by uwehermann** [AppImage/AppImageKit#456]
When doing ```bash -ex build.sh``` in AppImageKit there are errors on at least two different OSes.

This is tested with e.g. 9df35eb12138df3404bf8647043c06d3faf52eb3.

Debian unstable, x86_64:
```
$ bash -ex build.sh
++ sudo cp resources/liblz4.pc /usr/lib/unknown-linux-gnu/pkgconfig/
cp: cannot create regular file '/usr/lib/unknown-linux-gnu/pkgconfig/': No such file or directory
$ uname -m
x86_64
$ uname -p
unknown
```

The correct directory would be ```/usr/lib/x86_64-linux-gnu/pkgconfig```, right?

On Ubuntu Trusty i386 I got a similar error, there it was ```/usr/lib/athlon-linux-gnu/pkgconfig/``` that doesn't exist (```uname -m``` is ```i686``` there, ```uname -p``` is ```athlon```).

The correct directory would probably be ```/usr/lib/i386-linux-gnu/pkgconfig```, which does exist (there's no ```/usr/lib/i686-linux-gnu/pkgconfig``` either btw).

**Comment by probonopd** [comment]
Frankly, as it stands now, this (barely) builds on our CentOS 6 container that we are using in our Travis CI based build pipeline, and on my local Ubuntu 16.04 machine.

Generally we recommend users to use the binaries that we provide, unless you absolutely must build your own for some reason. Our builds give you compatibility with older systems and are generally well tested.

Furthermore, the openSUSE Build Service has their own builds of the tools in AppImageKit, but the openSUSE team really did all the work to re-engineer the build scripts for their needs.

I am no expert in these things and am very reluctant to make any changes so as to not break our current working build pipeline. That being said, I know that @TheAssassin has a better build system somewhere on his long TODO list, albeit not at the top.

**Comment by azubieta** [comment]
The `build.sh` script has been already rewritten therefore this issue should be gone. Closing the issue if it shows up please reopen.
