### ISSUE TITLE
**Not Urgent** Symlink issue?

### ISSUE THREAD

**Issue by Tvs-Frank** [AppImage/AppImageKit#459]
OS: Ubuntu 16.04.
Appimage = Krita.
Tested by logoff/logon.

I have two computers with custom setups, both with SSD's and hard drives.

On computer "A," the /home, /var and /tmp folders are on their own partitions on the hard drive and the Krita icon shows in my "Applications" folder (which I created in Home just for Appimages) and also appears when searching for apps.

On computer "B," the /home, /var and /tmp folders are symlinks from the hard drive. The Krita icon shows "a" default icon (again Home->Applications) and does not appear when searching for apps.

This is solely an icon issue. The app runs fine.

Perhaps this is an issue with Krita’s packing (the paths they use), as MuseScore’s appimage does provide icons when I use the “install” option. Krita, unfortunately, does not offer that option.

Any ideas?

Thank you so much. I love appimages!

**Comment by TheAssassin** [comment]
Can you link to the specific AppImage you use? Or perhaps upload it on https://transfer.sh or elsewhere?

**Comment by Tvs-Frank** [comment]
https://download.kde.org/stable/krita/3.2.1/krita-3.2.1-x86_64.appimage

**Comment by probonopd** [comment]
Do you have the optional `appimaged` daemon installed on your machine?

**Comment by TheAssassin** [comment]
@probonopd his issues arise from the desktop integration script. He's trying to "install" the AppImage, i.e., install the desktop file. So, I doubt he's using appimaged.

**Comment by probonopd** [comment]
I see. That script needs to go, and needs to be replaced by something "proper", e.g., a stripped down `appimaged` sans the `d` and sans inotify.

**Comment by probonopd** [comment]
But as a workaround, @Tvs-Frank could try with the optional `appimaged` daemon and see whether it works for him when using it.

**Comment by Tvs-Frank** [comment]
not running appimaged on either machine

**Comment by Tvs-Frank** [comment]
Tried appimaged on symlinked setup and got this when using the -v option:

"appimaged: error while loading shared libraries: libarchive.so.14: cannot open shared object file: No such file or directory"

**Comment by Tvs-Frank** [comment]
I did a symlinked 14 to 13, the one my system, and it installed. I supposed i need to move my appimages to one of the folders it searches

**Comment by Tvs-Frank** [comment]
Created a $HOME/bin folder, moved my appimages there, logged out/in again and it's working.

**Comment by probonopd** [comment]
> I did a symlink from libarchive.so.14 to libarchive.so.13 (the current one on my symlinked system) and it installed

...and this all the while libarchive is always version 3 in fact. This is a major annoyance which will probably lead us to drop libarchive entirely if they cannot get this fixed. Optionally, we could try to `dlopen()` just whatever version of libachive the distribution provides, since despite the different names they are not all that different in the end, as long as they provide the (few) functions that we need.

References:
* https://github.com/libarchive/libarchive/issues/817
* https://github.com/AppImage/AppImageKit/issues/445#issuecomment-322041452
* https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues#library-filenames
