### ISSUE TITLE
appimaged double .desktop file

### ISSUE THREAD

**Issue by corppneq** [AppImage/AppImageKit#460]
I am using appimaged version: continuous-1-gd35c990
and Wire: wire-2.12.2729-x86_64.AppImage
The Wire AppImage asks me if I want to create a .desktop file.
AppImageD already created one. If AppImageD is used an AppImage should not ask if I want to create a .desktop file.
![appimage-bug](https://user-images.githubusercontent.com/4342880/29979780-2bef8158-8f47-11e7-84b2-8b41144ce579.png)

Also I am not shure if they are related:
```
./AppImageUpdate-443.g69bf471-x86_64.AppImage wire-2.12.2729-x86_64.AppImage 

** (appimageupdategui:12877): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-DwGN8tjmDX: Verbindungsaufbau abgelehnt
Could not load application icon: Datei »appimageupdate« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden

(appimageupdategui:12877): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(appimageupdategui:12877): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
appimageupdate wire-2.12.2729-x86_64.AppImage      Cannot update this file
You need to an updater that can handle      
```

**Comment by probonopd** [comment]
> The Wire AppImage asks me if I want to create a .desktop file.

The Wire AppImage, or any AppImage, should __not__ ask you to integrate itself into the system _while_ the `appimaged` daemon is running. If it does, it is a bug of the Wire AppImage and should be reported there.

> ./AppImageUpdate-443.g69bf471-x86_64.AppImage wire-2.12.2729-x86_64.AppImage 
> Cannot update this file

This means that the Wire AppImage does not contain the required update information for AppImageUpdate, which is optional (some AppImages have it, but not all). This would be a feature request for the Wire AppImage.
