### ISSUE TITLE
Bundle wget in AppImage?

### ISSUE THREAD

**Issue by simoniz0r** [AppImage/AppImageKit#462]
I have a few scripts that I would like to bundle in AppImages, and they use wget for some key parts.  I'd like to be able to bundle an AppImage that just works (some people don't have wget), and I was wondering if it would be feasible to bundle wget in an AppImage.  If so, which libs should I bundle with it?  I've tried a couple of different builds with some of the libs and one with all of the libs required by wget, but a user on CentOS 7 had issues running the builds.

I'm currently just manually copying files that are listed as being installed for wget and its libs, and then running apimagetool to generate the AppImage.  Maybe I'm doing something wrong here?  I think I'm doing everything correctly as the AppImage runs on my system.

The AppImages with wget bundled in run fine on my system, so maybe I need to build the AppImage from an older distro (currently doing it from Ubuntu 16.04)?  Any help is appreciated.

**Comment by simoniz0r** [comment]
Disregard, I think I have this figured out.

**Comment by probonopd** [comment]
Please see
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by simoniz0r** [comment]
Yeah, I had read that.  It was still a little confusing to figure out which libs I should bundle and which ones I shouldn't.  Kinda just kept plugging libs in there until it worked.

**Comment by probonopd** [comment]
As a general rule of thumb, bundle all libraries __except__ those listed on https://github.com/AppImage/AppImages/blob/master/excludelist
