### ISSUE TITLE
Create AppImage on OSX

### ISSUE THREAD

**Issue by teras** [AppImage/AppImageKit#463]
Is it possible to create an AppImage of an application using an OS X system?
I know that you are targeting mainly automatic tools, but I am extremely new to AppImage and an old school developer, who prefers to build everything locally under my supervisor.

**Comment by probonopd** [comment]
It probably can be done, but we are not providing the tools for it at the moment. Where do the binaries that go inside the AppImage come from? Wouldn't you need a Linux system to build them, anyway?

**Comment by teras** [comment]
No, it is a java application (I am the developer of Jubler, a subtitle editor), and no actual linux libraries are required. I have created a thin native application (in the older days was just a script) which manages to properly launch the application.

I am experimenting with other ways to distribute my application and AppImage finds me 100% compatible with its ideology. Thus I was thinking that, instead of creating once more with a lot of pain a dpkg file, this time to be more modern and use AppImage instead.

**Comment by probonopd** [comment]
https://github.com/AppImage/AppImageKit/issues/322 is about building `appimagetool` for macOS, @develar had started looking into it.

If you are really determined, you could do it by just using `mksquashfs` and `dd`. Let me know if you are interested in going down that route.

**Comment by teras** [comment]
I am sorry, I didn't dig out this post!
I am also interested on creating proper AppImages on OSX, which would run on Linux. 
Like cross-platform build tools.

I can see that mksquashfs seems to work fine (I hope).
So if I understand correctly, if I attach a specific header to a squashfs FS I am ready?

I'd be interested though to support all features, if possible, including digital signatures. These little creatures are becoming more and more required these days. I am not afraid  o doing a little of hocus pocus.

**Comment by probonopd** [comment]
Yes, essentially you take the compiled form of AppImageKit `runtime.c`, and append a squashfs filesystem to the end of it, done. Now, if you also want to have signatures and update information, you would need to write them to the correct offsets. All of that can be done manually no doubt, but why not use the tool that does all of that for you, `appimagetool`. We "just" need to get it to build on macOS...

**Comment by teras** [comment]
1) Is there any precompiled version available? AFAIK your version is built on an old machine, which makes it perfect stable candidate instead of my creating my own.

2) I did a quick clone of AppImageKit and I have the feeling that inotify does not exist in OSX. I might be interested in porting it to OSX, but for sure I might need a lot of help with that.

It looks interesting though

**Comment by probonopd** [comment]
I would start by just compiling appimagetool, nothing else - iirc, that doesn't require inotify. inotify is used by runtime.c, which you could use a precompiled version of, from a real linux machine...

**Comment by teras** [comment]
Do you provide any means of compiling only the appimagetool?

**Comment by probonopd** [comment]
Please study  the relevant section of `build.sh`, it shows the exact steps.

**Comment by teras** [comment]
That's what I am doing, but it is quite compicated for anyone who hasn't writted this script, in contrast to anyone who knows any keystroke with it :)

I've pinned down to this command:

`gcc -DVERSION_NUMBER=\"$(git describe --tags --always --abbrev=7)\" -D_FILE_OFFSET_BITS=64 -Isquashfuse/     $(pkg-config --cflags glib-2.0) -g -Os getsection.c  -c appimagetool.c -I squashfs-tools/`

After some poking around and adding various missing include files, I came thus far:

```
appimagetool.c:646:20:` error: cannot take the address of an rvalue of type 'int'
                if(WEXITSTATUS(pclose(fp)) != 0)
                   ^           ~~~~~~~~~~
/usr/include/sys/wait.h:144:26: note: expanded from macro 'WEXITSTATUS'
#define WEXITSTATUS(x)  ((_W_INT(x) >> 8) & 0x000000ff)
                          ^      ~
/usr/include/sys/wait.h:131:28: note: expanded from macro '_W_INT'
#define _W_INT(w)       (*(int *)&(w))  /* convert union wait to int */
                                 ^ ~
appimagetool.c:654:20: error: cannot take the address of an rvalue of type 'int'
                if(WEXITSTATUS(pclose(fp)) != 0) { 
                   ^           ~~~~~~~~~~
/usr/include/sys/wait.h:144:26: note: expanded from macro 'WEXITSTATUS'
#define WEXITSTATUS(x)  ((_W_INT(x) >> 8) & 0x000000ff)
                          ^      ~
/usr/include/sys/wait.h:131:28: note: expanded from macro '_W_INT'
#define _W_INT(w)       (*(int *)&(w))  /* convert union wait to int */
                                 ^ ~
2 errors generated.
```

**Comment by probonopd** [comment]
> Is there any precompiled version available

The compiled `runtime.c` is at the beginning of each AppImage, before the squashfs image starts. You can extract it using `dd`.

For example:
```
wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage 
./appimagetool-x86_64.AppImage  --appimage-offset # returns 97112 which is the offset at which the squashfs begins
dd if=./appimagetool-x86_64.AppImage bs=1 count=97112 of=runtime
chmod a+x runtime 
./runtime
```

Next, you would have to find the correct offsets for the signature and the update information. Shouldn't be too hard using a hex editor or;

```
objdump -h ./runtime 
 27 .upd_info     00000400  0000000000000000  0000000000000000  00016a77  2**0
                  CONTENTS, READONLY
 28 .sha256_sig   00000400  0000000000000000  0000000000000000  00016e77  2**0
                  CONTENTS, READONLY
```

So, update information starts at 0x16a77 = 92791 and signature at 0x16e77 = 93815. They are 1024 bytes long each.

```
HEXOFFSET=$(objdump -h runtime | grep .upd_info | awk '{print $6}')
HEXLENGTH=$(objdump -h runtime | grep .upd_info | awk '{print $3}')
dd bs=1 if=runtime skip=$(($(echo 0x$HEXOFFSET)+0)) count=$(($(echo 0x$HEXLENGTH)+0)) | xxd

HEXOFFSET=$(objdump -h runtime | grep .sha256_sig | awk '{print $6}')
HEXLENGTH=$(objdump -h runtime | grep .sha256_sig | awk '{print $3}')
dd bs=1 if=runtime skip=$(($(echo 0x$HEXOFFSET)+0)) count=$(($(echo 0x$HEXLENGTH)+0)) | xxd
```

Overwrite these with 1024 `0x00`s if you don't use them.

Beware though, all offsets can change with each build.

**Comment by probonopd** [comment]
About the `error: cannot take the address of an rvalue of type 'int'`, I don't know. Maybe Google has a solution...

**Comment by teras** [comment]
Indeed this information is retrievable the  brew command "gobjdump" from the binutils package.

Is it also possible to get the size of the header, with a similar trick?
Or, if it is not possible, maybe also append it in a separate section, like the other two options?
Remember that on a system other than Linux, it is not possible to run this application.

**Comment by probonopd** [comment]
There is [C code that determines the end of the ELF binary](https://github.com/AppImage/AppImageKit/blob/appimagetool/master/elf.h).
I don't know if this can be made compile on macOS.

**Comment by teras** [comment]
Oh right... I saw that part of the code while I am experimenting on making compile the appimagetool. 

Right now I just managed to compile it! (Still needs linking though).
Made some changes of course, hopefully not too intrusive.

I'll let you know if linking worked too.

**Comment by teras** [comment]
I think I am very close on compiling appimagetool, I have only one issue up to now.
It can't find external references _binary_runtime_start and _binary_runtime_end 

I also have a question: where is the binary mksquashfs used? In appimagetool or somewhere else?
The reason is that, to compile it, a patch should be applied , which is applied on top of version 4.3, and (as usual) doesn't properly apply.

**Comment by probonopd** [comment]
Great to hear @teras. :+1: Please join #AppImage on irc.freenode.net, where the developers meet.

**Comment by probonopd** [comment]
This part we will have to rewrite.

Currently we are using the runtime that is embedded in the `linuxdeployqt` executable using http://stupefydeveloper.blogspot.de/2008/08/cc-embed-binary-data-into-elf.html for the AppImage to be generated. This is not going to work if your `linuxdeployqt` executable is not an ELF Linux executable. Instead, we should make `linuxdeployqt` read the `runtime` from a plain file, and use that instead.

Essentially https://github.com/AppImage/AppImageKit/issues/304#issuecomment-264278615 needs to be implemented. PR welcome!

**Comment by th-otto** [comment]
> About the error: cannot take the address of an rvalue of type 'int', I don't know. Maybe Google has a solution...

WEXITSTATUS is a macro that is supposed to work with either union wait or int. Just assigning the return value of pclose() to an int variable first should do the trick.

**Comment by TheAssassin** [comment]
@probonopd please review and close, if possible.

**Comment by probonopd** [comment]
Thanks for confirming and closing @teras
