### ISSUE TITLE
Ask user to provide ARCH=... instead of guessing it from /proc/self/exe

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#467]
Guessing the architecture from the currently running system is flawed logic, since it is all about the architecture of the _target_ system, not the host system `appimagetool` itself is running on.

https://github.com/AppImage/AppImageKit/blob/55e43015c616e8eaa8ec9ddbdad103aa22b2ec04/appimagetool.c#L401-L405

We should ask the user to provide `ARCH=... appimagetool ...` instead of guessing it from `/proc/self/exe`, which fails on macOS anyway.

Thanks @teras for pointing this out.

**Comment by probonopd** [comment]
Ideally, we should
1. search for .so as we do now,
2. if none are found, search for executable files
3. inspect all of them for architectures until we have found one
4. if all else fails, present the user a message telling him to set `$ARCH=...

**Comment by probonopd** [comment]
Something along the lines of `find my.AppDir/ -type f -perm -+x -or -iname '*.so' `

**Comment by Martchus** [comment]
Since this came up on my OBS pull request: https://github.com/openSUSE/obs-build/pull/429

I'm wondering what points of this issue are already implemented and which are still missing:

`2.` Although @TheAssassin claims in the PR this is already done, when looking at the code I doubt that. But maybe I miss something.
`4.` That's already implemented and the reason for my PR.

**Comment by TheAssassin** [comment]
@Martchus our issue tracker isn't always perfectly up to date. We have a very small team but way too many issues.

**Comment by Martchus** [comment]
I've already supposed the issue isn't up-to-date. That's why I was asking for an update :-)

**Comment by probonopd** [comment]
Since I had originally opened this issue, the determination of the architecture has entirely changed, e.g., in 

https://github.com/AppImage/AppImageKit/commit/5a9ebc986f4cfd54866cc0946a7f554c07963bb2

So I think we can close this issue here. Please comment if you think it needs to be reopened. Thanks.
