### ISSUE TITLE
kdialog invoked with invalid arguments

### ISSUE THREAD

**Issue by th-otto** [AppImage/AppImageKit#469]
In the desktopintegration script, kdialog is invoked with invalid options. --caption is not known at all, and -yesno is interpreted as 5 single one-letter options. Result:

$ kdialog --caption "" --title Install -yesno "Would you like to integrate..."
Unknown options: caption, y, e, s, n, o.

**Comment by TheAssassin** [comment]
Mind to tell about your system (OS) and your kdialog version?

Also, since the desktop integration is going to be replaced as soon as possible anyway (see PR #433) I wouldn't put too much effort into this any more. But we'd accept a PR of course.

**Comment by th-otto** [comment]
Ah sorry, OS is openSUSE tumbleweed, with kernel 4.11.8. kdialog version is kdialog-17.04.3 (according to rpm, kdialog --version just prints 1.0). The problem arises only because zenity is not installed by default, hence the fallback to kdialog.

I dont have a forked repo, so a PR will be difficult, but attached is a small patch.

PS.: not related to this, but while trying to build my first AppImage, i found another small problem: i used generate_type2_appimage() from functions.sh. I tries to generate a *.zsync file from the just written *.AppImage (using the bundled zsyncmake from appimagetool). But after appimagetool finishes, the *.AppImage is moved to a different folder. That sometimes seems to cause the zsyncmake command to fail, but all i see then is "open: no such file or directory" (without any filename). Could it be that appimagetool does not wait for the zsyncmake to finish? I could solve it by adding a sleep command after appimagetool finishes.


[desktopintegration.patch.zip](https://github.com/AppImage/AppImageKit/files/1285330/desktopintegration.patch.zip)

**Comment by probonopd** [comment]
That script must die... and be replaced with something better. Merging your patch nevertheless.

**Comment by probonopd** [comment]
> PS.: not related to this

Please open a new issue for this, and please describe how to reproduce (so that we have a way to know whether we could fix it).
