### ISSUE TITLE
Change embedding of runtime to platform agnostic way

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#470]
*Thanks @teras for bringing up the idea, and working out this proposal.*

The way the runtime is embedded at the moment apparently works on Linux only. As appimagetool is prepared to run on other platforms as well (see #466), we need to change this to a more platform agnostic way.

The idea is to basically *encode* the freshly built runtime into C source code (using `xxd -i` for instance), and compile and link this file into the appimagetool binary. The effect is the same, the pre-built binary is inside the built application and can be written out. The big advantage compared to now is that this method does not rely on any ELF magic, and could even run on other platforms such as Windows.

Implementing this in the build workflow shouldn't be too hard either, at least on Linux. Problems could arise on other platforms, as we need to cross-compile `runtime.c` to a Linux target before embedding it (a binary blob in the repository so that this could be avoided is a no-go). Cross-compilation of the runtime itself is not problematic at all due to the presence of `clang` on macOS, but we will have to do this for all the dependencies as well.

This issue is by the way the perfect chance to switch over completely to CMake. As the compilation of the runtime now has to be changed anyway, we should avoid doing it in both places again.

**Comment by teras** [comment]
Just to confirm that xxd -i works perfectly under osx.

**Comment by probonopd** [comment]
As said before, I'd also support just using plain old files, and no embedding trickery.

**Comment by probonopd** [comment]
Also see https://github.com/AppImage/AppImageKit/issues/304.

**Comment by TheAssassin** [comment]
@probonopd nobody plans to remove the runtime parameter.

**Comment by azubieta** [comment]
@TheAssassin are you still on this? Can it be closed?

**Comment by TheAssassin** [comment]
No. There was a PR for that (#471), but it was never merged. Closing until further notice.

**Comment by probonopd** [comment]
* Being worked on -> no
* Resolved -> no
* Good idea -> yes

So why close it? Closing things just because they are not resolved yet is never a good rationale...

**Comment by TheAssassin** [comment]
We decided not to embed runtimes in binaries on macOS etc. We don't need that feature any more, but can use what we have now.

**Comment by TheAssassin** [comment]
The idea was to ship the runtime separately for those platforms.
