### ISSUE TITLE
relocation error related to glibc

### ISSUE THREAD

**Issue by philippgille** [AppImage/AppImageKit#480]
I created an AppImage of my own app with *appimagetool* version 9. When trying to execute the AppImage the following error occurs:

`hello-netcoreapp: relocation error: hello-netcoreapp: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

`hello-netcoreapp` is the app. I've got `libglib2.0-0` installed. I use *appimagetool* not as AppImage, but I extract it first and then use its `AppRun` to create the AppImage of my app.

This worked in the past (with the same *appimagetool* version) and I'm not sure if my build script or build environment broke this. But maybe someone here has heard of the error already, or otherwise if I find out what's wrong I'll post an update here for future reference.

**Comment by TheAssassin** [comment]
I haven't seen this issue yet. Please try to find out what has changed about your build environment. Also, please provide sufficient information about your environment.

Also, have you tried the latest version of appimagetool (the "continuous" one)?

**Comment by probonopd** [comment]
Hi @philippgille it seems like the libstdc++ you are using for building is "too new". Can we see your build script, including how you set up your build system?

**Comment by philippgille** [comment]
The error occurs when building on a VM running *Ubuntu 14.04.5*, as well as when building using Docker (image *microsoft/dotnet:1.1-sdk*). I don't remember installing anything fancy on the VM, but to make sure the build environment is the same just go the Docker way.

The regular build script is `scripts/build.sh` in https://github.com/philippgille/hello-netcoreapp/tree/1ad6a4635231077588bf83f43bdaa62a6518c418.

To build within a Docker container, just use `scripts/build-with-docker.sh`. It mounts the root directory of the repository as volume, so it has access to all the files and can write into the `artifacts` directory. It also installs `libglib2.0-0` to be able to extract the *appimagetool*. After the script (or rather the `scripts/build.sh` script that's run within the Docker container) is finished there's `artifacts/hello-netcoreapp_v0.1.0_ubuntu.16.04-x64.AppImage`.

Trying to execute that AppImage leads to the above mentioned error.

Please note: I only tried executing the AppImage on the *same machine* (build machine / Docker host, not Docker container because of FUSE), so I'm not sure if the error comes from the build or maybe the execution environment.

**Comment by probonopd** [comment]
The error is about libstdc++, this has nothing to do with glibc. For whatever reason your binary seems to require a newer/different version of it than is available in your execution environment.

**Comment by philippgille** [comment]
I got it working! My application was built for Ubuntu 16.04, but I tried to run it on Ubuntu 14.04. **This has nothing to do with AppImage**, but instead with how the *.NET Core SDK 1.1* builds its *self-contained deployments*. When building for Ubuntu 16.04, it's not compatible to Ubuntu 14.04.

The same goes for the other way around. When building a .NET Core app for Ubuntu 14.04, it's not compatible to Ubuntu 16.04 (error is "*Failed to initialize CoreCLR, HRESULT: 0x80131500*").

Info for .NET Core developers: This can probably be solved with the "portable RIDs" that were introduced in .NET Core *2.0*, where you can build for generic platforms like `linux-x64`. See [.NET Core RID catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids).

**Comment by probonopd** [comment]
While it is to be expected that an a pplication was built for Ubuntu 16.04 will fail to on earlier versions like 14.04, the other way around should work. If it doesn't, I'd consider it a bug in the application and/or its dependencies/libraries/frameworks that needs to be fixed.
