### ISSUE TITLE
Remote l10n assets

### ISSUE THREAD

**Issue by Elv13** [AppImage/AppImageKit#482]
Hello,

I was discussing this with @TheAssassin on IRC. What would be the generally good practice to handle translation assets. For my application and all the libraries it uses, even compressed, it gets quite heavy. Some applications like Firefox (all platforms) and LibreOffice (Windows and macOS installers) simply ship multiple archives/installers for each locals. Some other, like most current liveCDs ship a basic translation packages for download the full one once Internet is available[1].

In what direction do you think generic appimages should go? Should you provide runtime support for on-demand assets, favor multiple files or use a third party solution within the appimage?

[1] https://launchpad.net/ubuntu/+source/language-pack-fr https://launchpad.net/ubuntu/+source/language-pack-fr-base

**Comment by probonopd** [comment]
Simply bundle all locales inside the same AppImage. macOS does the same.

**Comment by Calinou** [comment]
> Simply bundle all locales inside the same AppImage. macOS does the same.

Some applications, for file size reasons (LibreOffice, Firefox, Thunderbird, …) create a build for each language. However, I don't think this is needed for most apps.

**Comment by azubieta** [comment]
This issue fall mostly on the developers side as they can make the apps to download the required translations files to a writable XDG_DATA_DIR and load them from there.

Closing the issue. Please reopen it if required.
