### ISSUE TITLE
Errors are printed to standard output

### ISSUE THREAD

**Issue by jakub-bochenski** [AppImage/AppImageKit#483]
Running the powershell appimage on centos (no x-window installed) results in the following extra messages:
```
    ./PowerShell-6.0.0-beta.7-x86_64.AppImage
    which: no desktop-file-validate in (/tmp/.mount_ZfbAnL/usr/bin/:/home/acme:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/acme/.local/bin:/home/acme/bin)
    desktop-file-validate is missing. Skipping /tmp/.mount_ZfbAnL/usr/bin/powershell.wrapper.
    PowerShell v6.0.0-beta.7
    Copyright (C) Microsoft Corporation. All rights reserved.
    The specified drive root "net:[4026532497]" either does not exist, or it is not a folder.
```

Running it with stderr redirected to `/dev/null` still leaves `desktop-file-validate is missing. Skipping /tmp/.mount_R39YOm/usr/bin/powershell.wrapper.` in the output.
```                                                                                                                             
    [acme@iq-jenkins-dockerbuilder-2 ~]$ ./PowerShell-6.0.0-beta.7-x86_64.AppImage 2>/dev/null
    desktop-file-validate is missing. Skipping /tmp/.mount_R39YOm/usr/bin/powershell.wrapper.
    PowerShell v6.0.0-beta.7
    Copyright (C) Microsoft Corporation. All rights reserved.
```

It should go to stderr instead.

**Comment by probonopd** [comment]
Please report this to the PowerShell project as it seems unrelated to AppImageKit, thanks.

**Comment by probonopd** [comment]
Seems to be a bug in the desktopintegration bash script. Needs to be fixed here, and then needs to be updated in the PowerShell project.

**Comment by TheAssassin** [comment]
@probonopd we should rather attempt to merge #433.

**Comment by jakub-bochenski** [comment]
@probonopd @TheAssassin can you give me some idea when this will be fixed?
It's rather annoying to have to filter out the output on each invocation of powershell. Moving output from stdout to stderr seems like an easy fix.

**Comment by TheAssassin** [comment]
@jakub-bochenski I opened a pull request (https://github.com/AppImage/AppImageKit/pull/490). We will have to test whether the version in there works with the PowerShell AppImage.

However, the build in there is failing, for some totally unrelated reason. @probonopd will have to merge it, as I can't fix this issue.

**Comment by jakub-bochenski** [comment]
@TheAssassin I see the PR is merged to develop. 
Do you think I should try the continuous build of AppImage with Powershell?

**Comment by probonopd** [comment]
The PowerShell team would need to carry the changes over, it's just a couple of changes in a bash script. The PowerShell team is not automatically fetching the latest master from this project.

**Comment by TheAssassin** [comment]
I agree. I fixed the upstream issue, but we can't trigger updates for other projects who would potentially benefit from the fix. Please step up to them and ask them to update the tools they use.
