### ISSUE TITLE
Support AppImage in linuxbrew

### ISSUE THREAD

**Issue by emanresusername** [AppImage/AppImageKit#484]
hoping to get some advice/ideas from similar projects on [this issue](https://github.com/Linuxbrew/homebrew-core/issues/4357)

(please excuse the copypasta 😅 thought this'd be the best combo of efficiency, related-github-repo-synnergy and visibility/discoverability for the relevant communities/contributers/etc)

**Comment by probonopd** [comment]
Maybe start with the build steps in https://github.com/probonopd/linuxdeployqt/blob/master/README.md#using-linuxdeployqt-with-travis-ci and convert these to the linuxbrew equivalent. Since I have never used linuxbrew, I don't know how to do that though.

**Comment by emanresusername** [comment]
😮  i wasn't even thinking about also building the `AppImage` that's an interesting idea 🤔 
is there any way to do that without needing root (i think one of the things that draws people (at least me and a handful of folks i've encountered 😅) to linuxbrew is being able to use it without being a `sudo`er)?

**Comment by probonopd** [comment]
Ah, it's "just" about installing already-existing AppImages, that should be rather easy to do. An AppImage is just an ELF executable like any other Linux application. So they should be totally able to do it.
