### ISSUE TITLE
appimaged memory leak

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#492]
It appears to me like we have a memory leak somewhere in appimaged. See the following screenshot:

![screenshot_2017-10-17_13-41-36](https://user-images.githubusercontent.com/4503202/31666572-fea82c5c-b34c-11e7-8996-e36e32ec996b.png)

I had to kill the process and start a new instance to fix my memory issues. We'll have to run appimaged with the memory sanitizer or something alike.

**Comment by probonopd** [comment]
Thanks for the observation. I had run it through valgrind some time ago but forgot how it works. So would be glad if someone could help.

**Comment by TheAssassin** [comment]
Has to be verified in a long time test under realistic circumstances (i.e., let's all run the new version, and check the RAM usage occasionally). Also should be analyzed with ASan as soon as #568 is done.

**Comment by TheAssassin** [comment]
Looks good to me. ASan doesn't find any more memory leaks on my system. I'll try to merge #576 asap.
