### ISSUE TITLE
Desktop integration does not work anymore

### ISSUE THREAD

**Issue by knapsu** [AppImage/AppImageKit#493]
Commit 09a48ee8bf5644fd6505588662efc390fb910d4f breaks the desktop integration.
Check for command existence is invalid as it always returns empty string (line 151).
It would be better to check it with `[ -x "$(command -v $DEP)" ]`

**Comment by TheAssassin** [comment]
As stated below your comment there, would you be willing to send a fix in a PR?

**Comment by knapsu** [comment]
Yes, I will do it.

**Comment by TheAssassin** [comment]
Thanks!

**Comment by probonopd** [comment]
...perhaps we should just retire that bash script altogether and ask people to use the appimaged daemon instead.

**Comment by TheAssassin** [comment]
Apart from being totally off topic: Wouldn't that remove some of the self containment which we praise AppImages for usually?

**Comment by knapsu** [comment]
Sticked with `which` as some older shells does not have the `command`.
Wanted to do a one liner
```
check_dep()
{
  which $1 &>/dev/null || { echo "$1 is missing. Skipping ${THIS}."; exit }
}
```
It works in bash, zsh, ash but **not** in busybox. So I went for a longer version which works in all mentioned shells.

**Comment by TheAssassin** [comment]
GitHub didn't close it automatically, therefore I'll close it manually.
