### ISSUE TITLE
appimaged not working linuxmint 18.2

### ISSUE THREAD

**Issue by Lvaskz** [AppImage/AppImageKit#495]
hi, appimaged was installed in linuxmint 18.2 but appimages located in downloads not appears in the system

**Comment by probonopd** [comment]
Please run appimaged from the command line and watch for output there. If in doubt, please paste the log here. Thanks.

**Comment by probonopd** [comment]
Are you sure appimaged is even running? `ps ax` should tell you.

**Comment by hideout** [comment]
i dont think that appimaged is running thats the problem

**Comment by probonopd** [comment]
Please run it from the command line by typing `appimaged <enter>`, then try again and watch the command line for output.

**Comment by Lvaskz** [comment]
hi, i installed from deb system:
wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimaged_1.0_amd64.deb"
sudo dpkg -i appimaged_*.deb
systemctl --user enable appimaged
systemctl --user start appimaged
 now is working
