### ISSUE TITLE
webcamoid , Scribus 1.5.3 and stacer aren't recognized by appimaged 

### ISSUE THREAD

**Issue by Lvaskz** [AppImage/AppImageKit#500]
hi, i already installed appimaged , and i have several appimaged located in bin folder, all recognized except stacer, webcamoid, and scribus.

**Comment by probonopd** [comment]
If you run appimaged from the command line, do you see any suspicious output regarding these AppImages?

**Comment by Lvaskz** [comment]
can you tell me how ?

**Comment by TheAssassin** [comment]
You download the appimaged AppImage [here](https://github.com/AppImage/AppImageKit/releases), open a terminal, make the AppImage executable and run it.

**Comment by probonopd** [comment]
Please let us know if you are running into any questions/issues @Lvaskz - we are interested in making this as easy as possible and would like to know what people struggle with.

**Comment by Lvaskz** [comment]
Hi, i opened a terminal and i typed: "appimaged". many appimages appear, stacer and web camoid inclusive, but without icon. Scribus not appear definitely.Weird, some appimages icons not appear like synfig and openshot, but if a locate i some other place( not bin folder) and run it ( openshot) a pop up window appear asking me a instalation and the icon appear after that.
i gonna send terminal report later

**Comment by Lvaskz** [comment]
hi, i decided download again stacer, scribus and webcamoid appimages. i erased the old ones and i puted the new ones to bin folder. I typed appimaged in the terminal and now all appimages appear in the menu aplication list. Webcamoid icon is missing, but applicatión is in the list applicatión menu.
Something weird that a noted is that many appimages appear twice and in differente places from the applications menu and in some cases without  icon, at least in linuxmint 18.2.
Perhaps  i must to report to webcamoid developer that add icon to webcamoid.

**Comment by Lvaskz** [comment]
Do  you now why appimages appear several times in the ?

**Comment by TheAssassin** [comment]
@Lvaskz that usually happens either because you have multiple copies of the AppImage in your downloads directory (e.g., first download is called `something.AppImage` and the second download is then `something (1).AppImage`).
Unfortunately, you can't identify which one is which because both contain the same desktop file and therefore create the exact same launcher in your app menu.

(An edge case that I experienced with Xfce 4 once was a caching issue where applications didn't show up, showed up without an icon, then showed up, so that might cause issues, too, but it's really unlike).

**Comment by Lvaskz** [comment]
"(An edge case that I experienced with Xfce 4 once was a caching issue
where applications didn't show up, showed up without an icon, then showed
up, so that might cause issues, too, but it's really unlike)."

I think this is what is happen in cinnamon( my desktop).

"@Lvaskz <https://github.com/lvaskz> that usually happens either because
you have multiple copies of the AppImage in your downloads directory (e.g.,
first download is called something.AppImage and the second download is
then something
(1).AppImage).
Unfortunately, you can't identify which one is which because both contain
the same desktop file and therefore create the exact same launcher in your
app menu."

Well, i must to say that i have a one openshot.appimage, but it appears
twice, the same thing with scribus.appimage.One appimage twice in the app
menu.
Yes i have 2 appimages;  stable and develop version, by the way freecad,
but they do not appear 2 times( stable and develop), but 3 times( stable,
develop, stable). It is easy to eliminate the duplicated, but it becomes
some annoying

2017-11-02 9:07 GMT-06:00 TheAssassin <notifications@github.com>:

**Comment by probonopd** [comment]
That's strange. `.desktop` files are generated based on the string of the full path to the AppImage, and since there cannot(?) be 2 AppImages with the same path there should not be more than one `.desktop` file, and hence, menu entry. Can anyone else reproduce duplicate menu entries?

**Comment by Lvaskz** [comment]
I noted some thing, every time i run appimaged on terminal, the appimages duplicate in the app menu.
and some others disappear like stacer.
what exactly appimaged command does? 

$ appimaged
_________________________

-> REGISTER /home/amiel/Downloads/scribus-1.5.3-linux-x86_64.AppImage
ISO9660 based type 1 AppImage
Got root desktop: scribus.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/Downloads/SynfigStudio-1.3.4-64bit-linux-testing-17.08.09-9fecd.appimage
ISO9660 based type 1 AppImage
Got root desktop: synfigstudio.desktop
Installing desktop file
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_splash_screen.png has nonstandard size w = 300, h = 400; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_set_fill_color.png has nonstandard size w = 200, h = 200; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_show_grid_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_snap_grid_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_show_guideline_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_snap_guideline_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_utils_chain_link_on_icon.png has nonstandard size w = 128, h = 256; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_utils_chain_link_off_icon.png has nonstandard size w = 128, h = 256; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_utils_timetrack_align_icon.png has nonstandard size w = 1, h = 128; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_installer_logo_osx.png has nonstandard size w = 420, h = 420; please fix it
/tmp/appimagekit_399d3e403b96c5b75643063d3ea78649_set_outline_color.png has nonstandard size w = 200, h = 200; please fix it
_________________________

-> REGISTER /home/amiel/bin/scribus-1.5.3-linux-x86_64.AppImage
ISO9660 based type 1 AppImage
Got root desktop: scribus.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/KeePassXC-2.2.0-x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: keepassxc.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/webcamoid-8.1.0-x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: webcamoid.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/gimp-2.9.5-20170202.glibc2.15-x86_64.AppImage
ISO9660 based type 1 AppImage
Got root desktop: gimp.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/OpenToonz-1.1.3-mypaint-2017.06.15-linux-64bit.appimage
ISO9660 based type 1 AppImage
Got root desktop: opentoonz.desktop
Installing desktop file
/tmp/appimagekit_e8405ff36d80dc0872104c8230af7fbc_opentoonz.png has nonstandard size w = 180, h = 180; please fix it
_________________________

-> REGISTER /home/amiel/bin/PapagayoNG-1.4.1-2017.06.01-d72ac-linux-64bit.appimage
ISO9660 based type 1 AppImage
Got root desktop: papagayong.desktop
Installing desktop file
/tmp/appimagekit_c286d8eff34fd3b8dbb92b4ea87e2650_papagayong.png.png has nonstandard size w = 320, h = 320; please fix it
_________________________

-> REGISTER /home/amiel/bin/VLC-2.2.6.AppImage
squashfs based type 2 AppImage
Got root desktop: vlc.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/digikam-5.7.0-01-x86-64.appimage
ISO9660 based type 1 AppImage
Got root desktop: digikam.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/FreeCAD-0.16.6710.glibc2.17-x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: freecad.desktop
Installing desktop file
XPM size parsing not yet implemented
/tmp/appimagekit_55085f77f1fc539ce17399ff37cd3b7a_pstree16.xpm has nonstandard size w = 0, h = 0; please fix it
XPM size parsing not yet implemented
/tmp/appimagekit_55085f77f1fc539ce17399ff37cd3b7a_pstree32.xpm has nonstandard size w = 0, h = 0; please fix it
XPM size parsing not yet implemented
/tmp/appimagekit_55085f77f1fc539ce17399ff37cd3b7a_python2.7.xpm has nonstandard size w = 0, h = 0; please fix it
_________________________

-> REGISTER /home/amiel/bin/SynfigStudio-1.2.1-64bit.appimage
ISO9660 based type 1 AppImage
Got root desktop: synfigstudio.desktop
Installing desktop file
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_splash_screen.png has nonstandard size w = 300, h = 400; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_set_fill_color.png has nonstandard size w = 200, h = 200; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_show_grid_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_snap_grid_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_show_guideline_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_snap_guideline_icon.png has nonstandard size w = 120, h = 120; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_utils_chain_link_on_icon.png has nonstandard size w = 128, h = 256; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_utils_chain_link_off_icon.png has nonstandard size w = 128, h = 256; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_utils_timetrack_align_icon.png has nonstandard size w = 1, h = 128; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_installer_logo_osx.png has nonstandard size w = 420, h = 420; please fix it
/tmp/appimagekit_b672a1011e8760c861c4fa8194ccaed8_set_outline_color.png has nonstandard size w = 200, h = 200; please fix it
_________________________

-> REGISTER /home/amiel/bin/krita-3.3.1-x86_64.appimage
ISO9660 based type 1 AppImage
Got root desktop: krita.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/Stacer-x64.AppImage
squashfs based type 2 AppImage
Got root desktop: stacer.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/kdenlive-17.08.1-x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: kdenlive.desktop
Installing desktop file
_________________________

-> REGISTER /home/amiel/bin/FreeCAD-0.17.9747.glibc2.17-oce17.1-ng.x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: freecad-daily.desktop
Installing desktop file
Got root desktop: freecad.desktop
Installing desktop file
XPM size parsing not yet implemented
/tmp/appimagekit_a9d87c46dc7cc172f7444a7243215f11_pstree16.xpm has nonstandard size w = 0, h = 0; please fix it
XPM size parsing not yet implemented
/tmp/appimagekit_a9d87c46dc7cc172f7444a7243215f11_pstree32.xpm has nonstandard size w = 0, h = 0; please fix it
XPM size parsing not yet implemented
/tmp/appimagekit_a9d87c46dc7cc172f7444a7243215f11_python2.7.xpm has nonstandard size w = 0, h = 0; please fix it
_________________________
Blindly assuming AppImage type 1
The author of this AppImage should embed the magic bytes, see https://github.com/AppImage/AppImageSpec

-> REGISTER /home/amiel/bin/OpenShot-v2.4.0-x86_64.AppImage
ISO9660 based type 1 AppImage
Got root desktop: openshot-qt.desktop
Installing desktop file

**Comment by Lvaskz** [comment]
![captura de pantalla 2017-11-02 23-09-35](https://user-images.githubusercontent.com/29207169/32361136-93c0b598-c022-11e7-99b7-1f6898d4c856.png)
![captura de pantalla de 2017-11-02 23-08-31](https://user-images.githubusercontent.com/29207169/32361138-95281cc8-c022-11e7-9930-3f1032ced731.png)

**Comment by Lvaskz** [comment]
Do you note scribus repeated?

**Comment by probonopd** [comment]
You need for the appimaged process to completely finish. At https://github.com/AppImage/AppImageKit#appimaged-usage it is described what this process does.

**Comment by Lvaskz** [comment]
![captura de pantalla 2017-11-02 23-09-35](https://user-images.githubusercontent.com/29207169/32399971-5e2bb7c2-c0c0-11e7-8726-0869ae1c495c.png)
![captura de pantalla de 2017-11-02 23-08-31](https://user-images.githubusercontent.com/29207169/32400000-c4877736-c0c0-11e7-8914-45d248869243.png)

**Comment by Lvaskz** [comment]
"@Lvaskz that usually happens either because you have multiple copies of the AppImage in your downloads directory (e.g., first download is called something.AppImage and the second download is then something (1).AppImage)."  @TheAssassin  you right, in some other place i had scribus. appimage, sorry. And i know why papagayo,vlc and freecad are duplicated, they have a script asking instalation in the system, thats is why appear duplicated.

**Comment by probonopd** [comment]
> And i know why papagayo,vlc and freecad are duplicated, they have a script asking instalation in the system, thats is why appear duplicated.

This script should __not__ run if it detects that `appimaged` is already running. Or did you have these AppImages _before_ you installed `appimaged`? In this case, duplication is unavoidable at the moment. (This is what makes me consider to drop that script altogether and just tell people to use `appimaged`).

**Comment by hideout** [comment]
i had the same problem and yes the problem was the script where running
cause it did not detects that appimaged was already running

2017-11-05 11:41 GMT+01:00 probonopd <notifications@github.com>:

**Comment by probonopd** [comment]
> i had the same problem and yes the problem was the script where running cause it did not detects that appimaged was already running

Please post the exact download URL of the AppImage having this issue.

**Comment by hideout** [comment]
ok will have a look on it

2017-11-05 14:43 GMT+01:00 probonopd <notifications@github.com>:

**Comment by Lvaskz** [comment]
here some ones:
http://github.com/OpenShot/openshot-qt/releases/download/v2.4.0/OpenShot-v2.4.0-x86_64.AppImage
https://github.com/darealshinji/vlc-AppImage/releases/download/continuous/VLC-2.2.6.glibc2.16-x86_64.AppImage
https://github.com/FreeCAD/FreeCAD/releases/download/0.17_pre/FreeCAD-0.17.9747.glibc2.17-oce17.1-ng.x86_64.AppImage

**Comment by probonopd** [comment]
To make analyzing this issue easier, please post, for each affected AppImage, the output of this command:

```
xxd ./PapagayoNG-1.4.2-2017.07.31-65704-linux-64bit.appimage | head -n 1
00000000: 7f45 4c46 0201 0100 4149 0100 0000 0000  .ELF....AI......
```

**Comment by TheAssassin** [comment]
@probonopd @Lvaskz you can use [appimageupdatetool](https://github.com/AppImage/AppImageUpdate/releases/tag/continuous) to show some information about AppImages. Just call like `./appimageupdatetool*.AppImage -d my.AppImage`. It displays a nice summary about relevant information that you can just copy and paste into GitHub comments etc.

**Comment by Lvaskz** [comment]
tusk and proton mail have problems to run when i use appimaged. The apps not work properly

**Comment by probonopd** [comment]
Please report to the authors of the respective AppImages. Thanks!

**Comment by Lvaskz** [comment]
[](url)
