### ISSUE TITLE
Make AppRun more flexible

### ISSUE THREAD

**Issue by simoniz0r** [AppImage/AppImageKit#502]
For some applications, setting every environment variable can cause issues (see https://github.com/AppImage/AppImageKit/issues/501 for example).  It would be nice if there could be a config file that users could drop in the base AppDir that would allow them to toggle the use of AppRun's environment variables and maybe even allow them to add paths to the environment variables.

**Comment by TheAssassin** [comment]
PRs welcome.

**Comment by simoniz0r** [comment]
I'm not very familiar with any other languages, so [here](https://u.teknik.io/kiddX.txt) is a bash script concept that I've come up with:

```bash
#!/bin/bash
# Provide options for loading environment variables in AppRun.conf rather than loading them all by default

# Create AppRun variable defaults in case config file is not present
APPRUN_SET_PATH="TRUE"
APPRUN_SET_LD_LIBRARY_PATH="TRUE"
APPRUN_SET_PYTHONPATH="TRUE"
APPRUN_SET_XDG_DATA_DIRS="TRUE"
APPRUN_SET_PERLLIB="TRUE"
APPRUN_SET_GSETTINGS_SCHEMA_DIR="TRUE"
APPRUN_SET_QT_PLUGIN_PATH="TRUE"

# Get AppRun running directory
RUNNING_DIR="$(dirname "$(readlink -f "$0")")"

# Load config file if present
[ -f "$RUNNING_DIR/AppRun.conf" ] && . "$RUNNING_DIR/AppRun.conf"

# Set AppRun environment variables based on config settings
[ "$APPRUN_SET_PATH" = "TRUE" ] && export PATH="$RUNNING_DIR"/usr/bin/:"$RUNNING_DIR"/usr/sbin/:"$RUNNING_DIR"/usr/games/:"$RUNNING_DIR"/bin/:"$RUNNING_DIR"/sbin/:"$PATH"
[ "$APPRUN_SET_LD_LIBRARY_PATH" = "TRUE" ] && export LD_LIBRARY_PATH="$RUNNING_DIR"/usr/lib/:"$RUNNING_DIR"/usr/lib/i386-linux-gnu/:"$RUNNING_DIR"/usr/lib/x86_64-linux-gnu/:"$RUNNING_DIR"/usr/lib32/:"$RUNNING_DIR"/usr/lib64/:"$RUNNING_DIR"/lib/:"$RUNNING_DIR"/lib/i386-linux-gnu/:"$RUNNING_DIR"/lib/x86_64-linux-gnu/:"$RUNNING_DIR"/lib32/:"$RUNNING_DIR"/lib64/:"${LD_LIBRARY_PATH}"
[ "$APPRUN_SET_PYTHONPATH" = "TRUE" ] && export PYTHONPATH="$RUNNING_DIR"/usr/share/pyshared/:"$PYTHONPATH"
[ "$APPRUN_SET_XDG_DATA_DIRS" = "TRUE" ] && export XDG_DATA_DIRS="$RUNNING_DIR"/usr/share/:"$XDG_DATA_DIRS"
[ "$APPRUN_SET_PERLLIB" = "TRUE" ] && export PERLLIB="$RUNNING_DIR"/usr/share/perl5/:"$RUNNING_DIR"/usr/lib/perl5/:"$PERLLIB"
[ "$APPRUN_SET_GSETTINGS_SCHEMA_DIR" = "TRUE" ] && export GSETTINGS_SCHEMA_DIR="$RUNNING_DIR"/usr/share/glib-2.0/schemas/:"$GSETTINGS_SCHEMA_DIR"
[ "$APPRUN_SET_QT_PLUGIN_PATH" = "TRUE" ] && export QT_PLUGIN_PATH="$RUNNING_DIR"/usr/lib/qt4/plugins/:"$RUNNING_DIR"/usr/lib/i386-linux-gnu/qt4/plugins/:"$RUNNING_DIR"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"$RUNNING_DIR"/usr/lib32/qt4/plugins/:"$RUNNING_DIR"/usr/lib64/qt4/plugins/:"$RUNNING_DIR"/usr/lib/qt5/plugins/:"$RUNNING_DIR"/usr/lib/i386-linux-gnu/qt5/plugins/:"$RUNNING_DIR"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"$RUNNING_DIR"/usr/lib32/qt5/plugins/:"$RUNNING_DIR"/usr/lib64/qt5/plugins/:"$QT_PLUGIN_PATH"

# Use APPRUN_EXEC variable if it is set otherwise attempt to find .desktop file and Exec line from .desktop file in RUNNING_DIR
if [ -z "$APPRUN_EXEC" ]; then
    DESKTOP_FILE="$(dir -C -w 1 "$RUNNING_DIR/" | grep -m1 '.desktop')"
    if [ ! -z "$DESKTOP_FILE" ]; then
        APPRUN_EXEC="$(grep -m1 'Exec=.*' "$RUNNING_DIR"/"$DESKTOP_FILE" | cut -f2 -d"=" | cut -f1 -d" ")"
        if [ -z "$APPRUN_EXEC" ]; then
            echo "Failed to find Exec line in $DESKTOP_FILE and APPRUN_EXEC variable is not set; exiting..."
            exit 1
    else
        echo "Failed to find .desktop file in $RUNNING_DIR and APPRUN_EXEC variable is not set; exiting..."
        exit 1
    fi
fi
cd "$RUNNING_DIR"
exec "$APPRUN_EXEC" "$@"
```

The `AppRun.conf` file in the AppDir would look like this:
```
APPRUN_SET_PATH="TRUE"
APPRUN_SET_LD_LIBRARY_PATH="TRUE"
APPRUN_SET_PYTHONPATH="FALSE"
APPRUN_SET_XDG_DATA_DIRS="FALSE"
APPRUN_SET_PERLLIB="FALSE"
APPRUN_SET_GSETTINGS_SCHEMA_DIR="FALSE"
APPRUN_SET_QT_PLUGIN_PATH="FALSE"
APPRUN_EXEC="./usr/bin/program"
```

**Comment by TheAssassin** [comment]
You've requested us to implement new features you needed a few times, but most of them are really not a priority for us, so if you need the feature, please do it right in C and send a PR. Thanks.

**Comment by simoniz0r** [comment]
As I stated above, I do not know C.  I am simply making suggestions for things that I would like to have happen; if suggestions are not welcome, then I will refrain from creating further issues here.  I don't really have the time to learn C so that I can create a proper PR for this issue... sorry :-\

**Comment by TheAssassin** [comment]
Never mind, thanks for the example, I'm sure the person implementing this feature will appreciate your mock-up.

**Comment by probonopd** [comment]
`AppRun.c` is meant as a baseline default implementation that is as straigtforward as possible. For applications that need more functionality, it is possible to use a custom AppRun script such as yours @simoniz0r. The person putting together is not limited to the default one.

**Comment by simoniz0r** [comment]
>We don't want to support config files for AppImage. If an application wants to store configuration, it should do so in the application's config files.

>AppImage is all about simplicity, "it just works", without giving the user the burden of dealing with configuring it first.

I think you may be confused here?  By setting the default variables for the AppRun and checking to see if it exists before attempting to load it, the config file is made entirely optional.  Without the config file, the functionality of AppRun is the same as what you have in the /resources dir here.

**Comment by simoniz0r** [comment]
>AppImage is all about simplicity, "it just works", without giving the user the burden of dealing with configuring it first.

That's the thing, though... it doesn't "just work" for some applications with all of the environment variables that AppRun provides by default.  What I'm asking for would give users more flexibility when using the AppRun provided here without having to resort to creating their own solutions.

**Comment by probonopd** [comment]
We want the person who creates an AppImage put in the work, so that for the user it "just works".

**Comment by simoniz0r** [comment]
The config file is not for the user.  It is inside of the AppImage and put there by the person who creates the AppImage.

**Comment by probonopd** [comment]
OK, sorry I misundestood. That's better - but then, the the person who creates the AppImage could just as well use a custom AppRun script.

**Comment by simoniz0r** [comment]
I mean, I think it would be nice if the default AppRun could provide these options, but I guess I'll just use the script that I posted above.  It's working in the AppImages that I was having problems with the default AppRun provided here.  I thought it'd be nice if other AppImage creators didn't have to put in extra work to have the correct environment variables set also, but I guess not.

**Comment by probonopd** [comment]
I think your case is a very special edge case not many others will run into. By the way, did you check out the appimage-exec-wrapper library?

According to https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#environment-variables, by default, AppRun sets some variables such as `LD_LIBRARY_PATH` before executing the payload application. While this is sufficient in most cases, it may lead to issues if the payload application launches other applications that reside in the base system, that is, outside of the AppImage. KDevelop is an example of such an application. In these cases, the [appimage-exec-wrapper](https://quickgit.kde.org/?p=scratch%2Fbrauch%2Fappimage-exec-wrapper.git&a=tree) library can be used together with the AppImage distribution mechanism. Place the library somewhere in your AppImage and point `LD_PRELOAD` to it before launching your application. Whenever your application invokes a child process through `execv()` or `execve()`, this wrapper will intercept the call and see if the child process lies outside of the bundled appdir. If it does, the wrapper will attempt to undo any changes done to environment variables before launching the process, since you probably did not intend to launch it with e.g. the `LD_LIBRARY_PATH` you previously set for your application.

**Comment by probonopd** [comment]
Typically you are running into this issue if an application inside an AppImage launches applications on the host system, which is generally discouraged as you should not assume certain applications to be present on the host system (apart from very basic ones that are installed in the default installation of every distribution). This is a general rule-of-thumb but there may well be specific use cases (such as yours, or KDevelop), where the application inside the AppImage needs to launch applications from the base system.

**Comment by simoniz0r** [comment]
>I think your case is a very special edge case not many others will run into.

I don't *really* think it's special case; if anyone wants to create an AppImage of a terminal emulator or an application that runs a terminal emulator inside of it, and they try to execute a python command inside of that application, it's going to fail with the default AppRun.

I think providing a flexible AppRun could help people who are new to creating AppImages a lot.  I think it would be nice if people didn't have to dig around for info like that and could just use the config file to toggle environment variables and perhaps even customize the paths in them.

>By the way, did you check out the appimage-exec-wrapper library?

Honestly, I've read though all of the documentation here a couple of times, and I'm just starting to grasp things really.  It's kind of hard to figure out what to trust in the documentation when some of it is extremely old and not at all relevant, but that's a topic of another issue (https://github.com/AppImage/AppImageKit/issues/488).

**Comment by probonopd** [comment]
You are correct. Terminal applications packaged as an AppImage are one of the special cases, for which I think the appimage-exec-wrapper library is very useful.

**Comment by simoniz0r** [comment]
Just looking at that library kinda confuses me.  I don't really see info that would help me jumping out right away.  I don't really think that something like that library is very helpful to people who are new to creating AppImages; I think it might just scare them away.

**Comment by probonopd** [comment]
AppImageKit is a _developer_ tool and _developers_ will know what to do with this.

**Comment by simoniz0r** [comment]
Alrighty then... noted.  I dunno why you're so against something like this that would be a simple improvement, but whatever.  Not exactly the friendliest interactions I've had on Github...
