### ISSUE TITLE
Is it possible to run an appimage game with firejail and save the game data?

### ISSUE THREAD

**Issue by JulianLai** [AppImage/AppImageKit#507]
`firejail --private --appimage game.appimage` can play the game without problem, but the game data will be gone if I exit the game.

**Comment by TheAssassin** [comment]
See #506, you need to provide more information.

As far as I know, it is not possible to run AppImages with firejail's default profile and have it have access to the file system.

However, we are not responsible for that functionality, **please contact Firejail with your question**.
