### ISSUE TITLE
error: Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#511]
Cannot build on Ubuntu 14.04.5 LTS:

```
++ sudo cp resources/liblz4.pc /usr/lib/x86_64-linux-gnu/pkgconfig/
++ '[' -e /usr/bin/yum ']'
++ '[' -e /usr/bin/pacman ']'
+ git submodule init
+ git submodule update
error: Server does not allow request for unadvertised object 5be5d61e5e5a93911256b5f2106e50da0ca81e8d
Fetched in submodule path 'squashfs-tools', but it did not contain 5be5d61e5e5a93911256b5f2106e50da0ca81e8d. Direct fetching of that commit failed.
```

Does not help: 
* `git reset --hard`
* `git submodule foreach git reset --hard`

**Comment by probonopd** [comment]
`git submodule sync` worked for me.

**Comment by native-api** [comment]
https://superuser.com/questions/1240216/what-does-the-git-error-message-server-does-not-allow-request-for-unadvertised

**Comment by gnzlbg** [comment]
@probonopd I am having this same issue, but `git submodule sync` does not fix it. What exactly did you do?

**Comment by probonopd** [comment]
I think I just ran `git submodule sync` in the directory in question and it worked for me, but I really don't remember any specifics, sorry.

**Comment by nickdesaulniers** [comment]
As a note for future travelers.  If you set your depth too shallow, the git server may be configured not to advertise each individual commit, IIUC.  We weren't seeing this issue in travis ci since it clones with depth 50, but local checkouts were broken.

```sh
$ git submodule update --depth 50
```

fixed this for me.

**Comment by zsq978663747** [comment]
both don't fix it for me.Any other operate

**Comment by TheAssassin** [comment]
@zsq978663747 your use case is most likely very different from this one. Here, a branch in a submodule was used that got lost, so the repository was updated by committing a new commit ID for it, and after pulling updating the submodules, all users could use it again.

The error is not bound to a specific scenario, it is quite generic, actually.

**Comment by SharbelWired** [comment]
@probonopd suggestion (git submodule sync) worked for me.  I executed the sync, then the submodule update command worked as expected.   Thanks @probonopd  !
