### ISSUE TITLE
appimaged + xubuntu -- apparent caching issue causes menu to not show icon until re-login

### ISSUE THREAD

**Issue by JoshuaD84** [AppImage/AppImageKit#522]
On XFCE / Ubuntu (probably all XFCE?): 
Step 1: Put an appimage that contains an icon in ~/bin
Step 2: Run appimaged
Step 3: look at menu - your program is on the menu, but has no icon
Step 4: log out
Step 5: log back in
Step 6: look at menu - you program is on the menu and has an icon

**Comment by TheAssassin** [comment]
Hitting that bug regularly, too. Fixes itself after some minutes (no exact measurements, but > 10 I'd say).

**Comment by JoshuaD84** [comment]
It did not fix itself on my system in minutes. I think I let it sit for ~12 hours with no resolution before doing a logout/login.

**Comment by TheAssassin** [comment]
Downloaded the new release of Cura yesterday, just checked, the icon is shown now. So yes, it can fix itself, but the times can range from a few minutes to several days.

**Comment by probonopd** [comment]
Hypothesis: I think you have to log out and log in once. Reason: When new directories get created beneath `share/icons`, the desktop only considers these after a logout.

**Comment by JoshuaD84** [comment]
Can confirm that a single log-out then log back in solves the problem.

**Comment by probonopd** [comment]
So I don't think this is a bug in AppImageKit, hence closing. Feel free to reopen if you think that we can improve the situation.
