### ISSUE TITLE
[Cosmetic Change] Make output of `--appimage-help` a bit more terse

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#532]
Currently, *`"--appimage-help"`* will print this output:

<pre>AppImage Options:

--appimage-help                 Prints this help
--appimage-offset               Prints the offset at which the embedded filesystem image starts, and then exits
--appimage-extract              Extracts the contents from the embedded filesystem image, then exit
--appimage-mount                Mounts the embedded filesystem image and prints the mount point, then waits until it is killed
--appimage-version              Prints the version of AppImageKit, then exits
--appimage-updateinformation    Prints the update information embedded into the AppImage, then exits
--appimage-signature            Prints the digital signature embedded into the AppImage, then exits
</pre>

I think, this output should be a little bit more terse:
<pre>AppImage Options:

--appimage-help         Print this help
--appimage-offset       Print byte offset of start of embedded filesystem image, then exit
--appimage-extract      Extract contents from embedded filesystem image, then exit
--appimage-mount        Mount embedded filesystem image, print mount point, then wait until kill
--appimage-version      Print version of AppImageKit, then exit
--appimage-updateinfo   Print update information embedded in AppImage, then exit
--appimage-signature    Print digital signature embedded in AppImage, then exit
</pre>

**Comment by probonopd** [comment]
Agree, can you send a PR please?

**Comment by KurtPfeifle** [comment]
The "short" version of the option could still be added in a backward-compatible way:

      --appimage-updateinfo[formation]   Print update info embedded in AppImage, then exit

<sub>(You know I'm not yet comfortable with PRs; however, this one seems "easy", so I MIGHT try...)</sub>

**Comment by probonopd** [comment]
If you know me, I am always for KISS and against too many options. Maybe you'd like to use a ~/.bash_completion file?

**Comment by KurtPfeifle** [comment]
Maybe even the *`"then kill"`*-parts could be skipped?

Maybe only when mounting, this additional info should be printed?

    --appimage-mount        Mount embedded filesystem image, print mount point, then wait for kill

**Comment by probonopd** [comment]
People might think it crashed or might just leave it running forever, so I think kill should be mentioned. Or Ctrl-D.

**Comment by probonopd** [comment]
As for the PR: Just go to https://github.com/AppImage/AppImageKit/blob/appimagetool/master/runtime.c and click the pencil (edit) button, make your changes, click the green button at the end of the page. Then fill out a summary on the next page and click the green button again, done.

**Comment by KurtPfeifle** [comment]
> *" I am always for KISS and against too many options. Maybe you'd like to use a ~/.bash_completion file?"*

IMHO, to create a dependency to a ~/.bash_completion file isn't KISS compatible just for getting the shorter `--appimage-updateinfo` work as well. 

Many people do not use Bash completion. And what about ZSH users? (I don't even know how this could be made to also work for ZSH...)

**Comment by probonopd** [comment]
Closed in https://github.com/AppImage/AppImageKit/commit/f4c1a28f9bc787058eee3b20c31ac46167d113ce
