### ISSUE TITLE
Improve libappimage

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#536]
CC @azubieta 

I looked a bit more into libappimage, and think we should improve it to follow the code style and structure (or, at least provide a compatible API) established in [libappimageupdate](https://github.com/AppImage/AppImageUpdate/blob/rewrite/include/appimage/update.h).

First of all, I established the `appimage::` namespace. We could put the utility functions into a `::util` or `::misc` namespace, like AppImageUpdate's `Updater` class is available as `appimage::update::Updater`.

Furthermore, looking at the main header, the include guard seems awkward, and should either be changed to something more standard like `LIBAPPIMAGE_H`, or replaced by the modern `#pragma once`.

Also, the CMake configuration hardcodes a _lot_ of paths that depend on `build.sh` results, and I couldn't really figure out the reason for `AppImageConfig.cmake.in` (especially the `foo` and `bar` stuff looks like @azubieta forgot it in the code), and the "deployment" code doesn't seem to make too much sense to me either. I think that could be thinned out, and we could avoid generating `AppImageConfig.cmake` at all, especially when using modern CMake functions like the `target_*` settings.

**Comment by probonopd** [comment]
Thanks @azubieta and thanks @TheAssassin. It would be good if a discussion on this could take place early on, before others are starting to consume this API, which would complicate changes manyfold. Would appreciate your thoughts @azubieta.

**Comment by azubieta** [comment]
That's why unsaid that I will require a little bit more code.
About the fixed paths, foo and bar I almost have it fixed I'll send a Pr
today.

Name space, well I guess that appimage:deployment because that is what the
functions in there do
Utils seems too wide
Furthermore we would need other name spaces for extracting stuff like icons
or other files that allows a better integration with the system.
I would recommend to keep the names as concrete as possible.

**Comment by TheAssassin** [comment]
@azubieta I just wanted to discuss any changes with you before taking any actions to make sure that I don't break your use of the library.

I have quite a few things to move here from AppImageUpdate (although they will receive a different namespace, as they shouldn't have dependencies on the SquashFS code and therefore need to be put in their own library). Therefore I wanted to discuss the future architecture of the modules before integrating my code.

If you can provide a link where you consume the library, I'll have a look and refactor the module so the config files etc. won't be necessary any more.

**Comment by llelectronics** [comment]
LibAppImage needs also more clear instructions on how to package it up. 
The build.sh script does not create the necessary files for building up stuff based on libappimage.

**Comment by TheAssassin** [comment]
@llelectronics libappimage can be considered alpha and is not meant to be used yet at the moment. Sprint 4 is mostly about improving AppImageKit and especially libappimage, so you should wait for its end and check again. The plan is to move most build code to CMake.

**Comment by TheAssassin** [comment]
We've been working on libappimage, and it is mostly ready to use for external projects. Please don't expect ABI compatibility yet, though, as this is still pre-beta software.

**Comment by probonopd** [comment]
> We've been working on libappimage, and it is mostly ready to use for external projects. 

:+1:  Do we already have preliminary documentation on it in the wiki or a `.md` file?

**Comment by probonopd** [comment]
We should clarify that libappimage is something for applications that _deal with_ AppImages (e.g., to generate, manage AppImages) but not something that _every_ AppImage will need.

**Comment by TheAssassin** [comment]
> We should clarify that libappimage is something for applications that deal with AppImages (e.g., to generate, manage AppImages) but not something that every AppImage will need.

That *is* clear, and we've discussed that already yesterday... The only thing that caused problems was the desktop integration, which you once said you'd like to get rid of anyway...
