### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by notklaatu** [AppImage/AppImageKit#538]
I'm packaging up a Python application, and get this error when I try to run my AppImage:

    bash-4.3$ ./StopGo-x86_64.AppImage 
    ImportError: No module named site

The ``site`` module is pretty basic Python so it does exist on my local file system.

If I run my app with ``--appimage-extract`` and run ./stopgo.wrapper from the expanded dir, the app launches successfully.

I'd like to avoid packaging Python itself (which is where the site module comes from), because I don't know of a Linux system that would not have it already installed.

Any ideas?

**Comment by TheAssassin** [comment]
> I'd like to avoid packaging Python itself (which is where the site module comes from), because I don't know of a Linux system that would not have it already installed.

Well, the problem with Python is that it is highly version dependent. You can't trust on Linux distributions to ship Python at all. There's a remarkable amount of old distro releases that don't have a newer Python 3.x and won't ever get it, and there's a few that don't have Python 2 any more.

It's cleaner and way easier to control for you if you bundle Python.

The problems you have is that your Python installation is most likely not relocatable, i.e., the modules hardcode paths which are (obviously) not available relative to the mounted AppImage contents etc.

You should bundle Python. I'd suggest trying miniconda, with which I've set up an [AppImage](https://github.com/Pext/Pext/pull/31) for [Pext](https://pext.hackerchick.me/). Works well, many dependencies are available for installation using the `conda` command, and some are even relocatable without issues.

Rule of thumb: When trying to bundle Python, you will experience problems. When bundling e.g., pygit2, we've had a lot of issues with its dependency libgit2 etc. It is not the best language to make AppImages with.

Other AppImages that successfully bundle Python are e.g., Cura, or Krita. You might take theirs as inspiration, too.

**Comment by notklaatu** [comment]
It used to work without bundling Python. I guess the switch from ISO to squashfs must affect it?

I'll try bundling Python. Thanks for the tip about miniconda; I'll check it out.

**Comment by TheAssassin** [comment]
@notklaatu please look at my Pext scripts for inspiration. I had a hard time (took me > 5 days to figure out) bundling Python using miniconda, and hope you can avoid the issues I experienced by making use of my existing code.
