### ISSUE TITLE
Pull AppImage build scripts from rawgit.com

### ISSUE THREAD

**Issue by bubnikv** [AppImage/AppImageKit#548]
AppImageKit seems to download its modules from git.com/.../raw
It seems that pulling the raw data from rawgit.com will improve performance and reliability.

By the way, the Slic3r Prusa Edition fails to download the AppImages Recepie. Is it a github reliability issue? Or has some file been moved to a new location?

converted 'https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe' (ISO-8859-1) -> 'https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe' (UTF-8)
--2017-11-26 12:10:43--  https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/AppImage/AppImages/raw/master/recipes/meta/Recipe [following]
converted 'https://github.com/AppImage/AppImages/raw/master/recipes/meta/Recipe' (ISO-8859-1) -> 'https://github.com/AppImage/AppImages/raw/master/recipes/meta/Recipe' (UTF-8)
--2017-11-26 12:10:44--  https://github.com/AppImage/AppImages/raw/master/recipes/meta/Recipe
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2017-11-26 12:10:44 ERROR 404: Not Found.

**Comment by TheAssassin** [comment]
I don't think it is a good idea to use such a 3rd party service. Thanks for the hint, but it's more reliable to use GitHub directly.

See https://github.com/rgrove/rawgit/blob/master/FAQ.md#i-need-guaranteed-100-uptime-should-i-use-cdnrawgitcom, rawgit.com themselves tell you not to use their service as they can't guarantee any uptime.

P.S.: I'll look into the download issue.

**Comment by probonopd** [comment]
@bubnikv please see https://github.com/AppImage/AppImages#warning-important-notice

**Comment by bubnikv** [comment]
@probonopd thanks Simon, that seems to cure my problem.
