### ISSUE TITLE
AppImage recipe functions.sh helper script should allow embedding of update information

### ISSUE THREAD

**Issue by phoerious** [AppImage/AppImageKit#549]
The `functions.sh` script which is used for generating AppImages via recipe scripts does not support embedding of update information for AppImageUpdate.

My workaround is to add the following line to my recipe:

    sed -i 's/"\$appimagetool" /"$appimagetool" $@ /' ./functions.sh

and then call `generate_type2_appimage()` like this:

    generate_type2_appimage -u "gh-releases-zsync|keepassxreboot|keepassxc|latest|KeePassXC-*-${ARCH}.AppImage.zsync"

It would be nice if this could be implemented upstream. This generic approach would also allow for other useful parameter overrides, such as embedding signatures.

**Comment by TheAssassin** [comment]
We don't really recommend using these data any more, there are several security concerns, and a bunch of other problems. Especially not for third-party AppImage builds. Instead, you should think about switching to linuxdeployqt, which is even able to "guess" the right upload information if building on Travis CI.

However, if you want to implement the feature, feel free to send a PR.

**Comment by phoerious** [comment]
Moving to linuxdeployqt would require some refactoring and last time we tried this, linuxdeployqt didn't quite do what it was supposed to do. Perhaps we'll do that for a next feature release.

**Comment by probonopd** [comment]
While I agree that in many cases `linuxdeployqt` is preferable I still think having this functionality here would be an advantage.

**Comment by jamessan** [comment]
This was fixed by https://github.com/AppImage/AppImages/commit/c13e496cd1f47f2598811e6fe2c702ba55b4ab50, wasn't it?

**Comment by TheAssassin** [comment]
I think so, @jamessan, thanks for the hint. Closing.
