### ISSUE TITLE
[desktopintegration] Integrate GNOME Search provider metadata

### ISSUE THREAD

**Issue by chrisnharvey** [AppImage/AppImageKit#55]
Hey, I just have a few quick questions. If anyone could give me some advice then that would be great. Just figured it would be a lot easier to ask, rather than tinkering for hours, trying to achieve something that someone else might have already achieved.
1. Just wondering if its possible to set AppImages as "default" apps in GNOME?

I have converted Epiphany (GNOME Web Browser) into an AppImage, and it works perfectly. However, there seems to be no way for me to set the AppImage as the default app for opening websites.
1. The Epiphany AppImage also doesn't add the "Search Provider" to GNOME. Could this potentially be something that is integrated into AppImageMonitor? Or is this too distro/desktop-environment specific?

**Comment by chrisnharvey** [comment]
Sorry, forgot to mention. Is this the right place to be posting questions like this? Or is there a forum?

**Comment by probonopd** [comment]
I think you need to install a `.desktop` file that has the AppImage as the value for the `Exec=` key. For this, you could extract the `.desktop` file from the AppImage and rewrite the value of its `Exec=` key to point to the AppImage itself. `appimaged` did this if I remember correctly.

**Comment by chrisnharvey** [comment]
Looks like the "Categories" or "MimeType" keys need to be there for GNOME to pick it up as a default app.

AppImageMonitor doesn't seem to copy these over.

Is there a reason that AppIamgeMonitor creates its own .desktop file instead of using the one out of the AppImage?

**Comment by chrisnharvey** [comment]
Any ideas on how to get the GNOME "Search Providers" working?

**Comment by probonopd** [comment]
I can't tell about AppImageMonitor, I think @RazZziel didn't have this in mind when he wrote it. To achieve what you intend, have a look at the `appimaged` code and then re-implement it in a nice, clean way using `vala` and bindings to the appropriate libraries like `libarchive` for extracting the .desktop file from the AppImage.

**Comment by RazZziel** [comment]
> Is there a reason that AppIamgeMonitor creates its own .desktop file instead of using the one out of the AppImage?
Not really, other than the Exec, Icon need to be different, and I'd like the Name to be different as well, because different versions of the same AppImage may have the same name, but I think it makes more sense to have them under different names in the menu, although that's very debatable

Incidentally, I ran into this problem a few days ago, before reading this issue, and implemented MimeType copying in 3eae15e6a80fd646bf3f574de5e46a399ed74762. Works well for my needs.

Anyway, we could actually copy the whole .desktop and change only the Exec, the Icon and maybe the Name (like `appimaged` seems to have done, I can't recall)

Regarding the implementation in Vala or whatever other platform, that's probably a bigger task that should be started once the bash prototype has been around a while longer as pilot test, and we understand better that's needed (i.e. in other issue we're discussing maybe we want web/bittorrent seed integration)

> The Epiphany AppImage also doesn't add the "Search Provider" to GNOME. Could this potentially be something that is integrated into AppImageMonitor? Or is this too distro/desktop-environment specific?

It's probably DE specific but there's no reason why it shouldn't be added. Do you know how to script adding a Search Provider? Is that related to https://github.com/probonopd/AppImageKit/issues/58?

**Comment by probonopd** [comment]
> Anyway, we could actually copy the whole .desktop and change only the Exec, the Icon and maybe the Name (like appimaged seems to have done, I can't recall)

Have a look at [this](https://github.com/probonopd/AppImageKit/blob/010268a504ee73ded07dbc0fd1e67db947ff6211/desktopintegration#L191-L196)

**Comment by chrisnharvey** [comment]
@probonopd I think I'll use your example from desktopintegration to install the desktop file based on the one from the AppImage. I'll submit a PR when I'm done.

@RazZziel The GNOME search provider is a way of integrating application search into the GNOME shell. For example, if we had a music app as an AppImage, when searching for a song in GNOME shell, it will show results from our AppImage (if the search provider is installed). Similar to Spotlight on OS X and search on the "Dash" in Unity.

**Comment by chrisnharvey** [comment]
https://developer.gnome.org/SearchProvider/

**Comment by probonopd** [comment]
@chrisnharvey, about installing the desktop file, I am not sure whether the distribution or the AppImage should do that. Right now no distribution does anything, so we'd probably be better off id the AppImages themselves took care of this, like my Leafpad example on
https://bintray.com/probono/AppImages/Leafpad/0.8.17/view#files

What do you think?

**Comment by chrisnharvey** [comment]
@probonopd I think you're right and the AppImage should take care of it. I'm just not sure how we'd remove the desktop file if the AppImage is deleted?

**Comment by probonopd** [comment]
`TryExec=` in the `.desktop` file is supposed to not show the menu entry if the file is no longer there. From time ti time a cleanup script could delete desktop files with TryExec statements with missing associated files.

**Comment by probonopd** [comment]
>  I'm just not sure how we'd remove the desktop file if the AppImage is deleted?

`àppimaged` takes care of that.

**Comment by probonopd** [comment]
With `appimaged` I can type "Music" into the launcher and Spotify.AppImage appears. Like it should be.

**Comment by TheAssassin** [comment]
Can't we close this issue by now then?

**Comment by probonopd** [comment]
@chrisnharvey?

**Comment by probonopd** [comment]
I think so.
