### ISSUE TITLE
Broken automatic filenames since version detection implementation

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#553]
While trying to put together an AppImage for OBS Studio. At first, linuxdeployqt did create a version dependent filename when using `-appimage` flag, but I needed to insert my own AppRun, hence I called linuxdeployqt, and then appimagetool manually. This yielded a broken file name: `OBS--x86_64.AppImage`. Note the double dash.

I'm pretty certain this is a bug since the automagic filename version detection thingy has been implemented. It is pretty obvious that the second dash should only be added to the filename when there's a version to add.

By the way, I have a line `export VERSION` that seems to work only when using linuxdeployqt. Maybe without such a line the bug won't occur. Should look into that, too.

**Comment by TheAssassin** [comment]
@probonopd could you please have a look here?

**Comment by probonopd** [comment]
What happens if you run `VERSION=foobar appimagetool some/AppDir`?

**Comment by TheAssassin** [comment]
`OBS-foobar-x86_64.AppImage`. Seems to work when passed explicitly.

**Comment by probonopd** [comment]
That is strange.

What happens if you do `VERSION=$VERSION appimagetool some/AppDir` within the script in which it is currently failing for you?

**Comment by TheAssassin** [comment]
I don't think that this makes any change, technically spoken. I assume the bug has probably been resolved in the past months (the issue is pretty old, actually). I'll re-run a build as-is with `VERSION` being the current commit hash on my workstation, and we'll see if it works this time. If it does, I'll close the issue as resolved.

**Comment by TheAssassin** [comment]
I found the issue, the variable was accidentally set to an empty string, appimagetool is behaving correctly. Closing.
