### ISSUE TITLE
How do you make an AppImage of a Java Jar?

### ISSUE THREAD

**Issue by jbwyatt4** [AppImage/AppImageKit#562]
Hello AppImage devs,

Clicking on the Bundling Java Runtime Environment link in the wiki leads to a single line directing me to a dead url, so I thought I should ask here.

My Java Jar is called JavaFXApplication1.jar. It's dependency is the Java 8 Runtime. It is in the AppDir/usr/bin folder.

I am using appimagetool-x86_64.AppImage wget from the github repo.

I am using the example AppRun and a slightly modified desktop file

```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${PYTHONPATH}"
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
exec "${EXEC}" "$@"
```
```
[Desktop Entry]
Type=Application
Name=JavaFXTest
Exec=JavaFXApplication1.jar
Comment=A test
Icon=appimagetool
Categories=Development;
Terminal=false
```
I get the following error with command: ARCH=x86_64 ./appimagetool-x86_64.AppImage -n MyApp.AppDir

```
WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
Using architecture x86_64
/home/user/app_dist/MyApp.AppDir should be packaged as appimagetool-x86_64.AppImage
AppStream upstream metadata found in usr/share/metainfo/myapp.appdata.xml
/home/user/app_dist/MyApp.AppDir/usr/share/metainfo/myapp.appdata.xml: 
(appstream-util:31011): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Failed to validate AppStream information with appstream-util
```

I add the ARCH flag as appimagetool complains about not finding the arch of my jar.

Some googling and I tried to add the -n flag and got this error

```
Using architecture x86_64
/home/user/app_dist/MyApp.AppDir should be packaged as appimagetool-x86_64.AppImage
Generating squashfs...
Could not open regular file for writing as destination: Text file busy
Embedding ELF...
Not able to open the AppImage for writing, aborting
```

Does anyone have any advice on how to solve this?

**Comment by probonopd** [comment]
> I add the ARCH flag as appimagetool complains about not finding the arch of my jar.

Are you sure you are bundling the required JRE inside the AppImage?

> Could not open regular file for writing as destination: Text file busy
> Embedding ELF...
> Not able to open the AppImage for writing, aborting

That is the real error here. Could it be that you have a pre-existing AppImage there, which is open from another process? Delete it and try again.

Which filesystem, operating system and version is your build system?

**Comment by jbwyatt4** [comment]
Hi probonopd

> Are you sure you are bundling the required JRE inside the AppImage?

The link for bundling the JRE with the AppImage is broken. How do you bundle the JRE? (I get this error on both Ubuntu 16.04 and Manjaro.)

> That is the real error here. Could it be that you have a pre-existing AppImage there, which is open from another process? Delete it and try again.

There was no AppImage generated in the App folder. A symlink to the icon was made. Deleted it.

Was using Manjaro, switched to Ubuntu and I got a different error. (I should have tested on Ubuntu first, but there the link to how to bundle JRE was broken so I expected that to be the issue.)

/home/user/app_dist/MyApp.AppDir should be packaged as JavaFXTest-x86_64.AppImage
AppStream upstream metadata found in usr/share/metainfo/myapp.appdata.xml
I - myapp.appdata.xml:myapp.desktop
    First 'description/p' paragraph might be too short.

E - myapp.appdata.xml:myapp.desktop
    Component metadata refers to a non-existing .desktop file.

Validation failed.
Failed to validate AppStream information with appstreamcli

(I changed the name in .desktop to JavaFXTest)

> Which filesystem, operating system and version is your build system?

Ubuntu 16.04 HWE x64, Ext4

**Comment by probonopd** [comment]
You need to bundle a JRE. Need to find some working download link.

You can use `-n` if you don't care about AppStream.

**Comment by jbwyatt4** [comment]
Good to know.

With -n it generates an AppImage. I get an execv error from running the AppImage which I assume is due to a lack of a JRE.

execv error: Permission denied

**Comment by probonopd** [comment]
Yes, need a JRE.

**Comment by jbwyatt4** [comment]
Hi probonopd,

Any updates?

**Comment by TheAssassin** [comment]
`execv error: Permission denied` _always_ means that the executable bit is missing for a file. Ensure that `AppRun` has the executable bit set.

**Comment by jbwyatt4** [comment]
I am not sure how to do that. There is no guide for setting up an AppImage with a Jar. If you would write out instructions here; that would be appreciated.

**Comment by TheAssassin** [comment]
There are no general instructions other than https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-Runtime-Environment. I just saw your error, and showed you what has to be done to fix it. Please refer to the Wiki document. Feel free to improve it.

**Comment by jbwyatt4** [comment]
That pycharm wiki link was broken when I opened this issue. Glad to see it was fixed.

**Comment by TheAssassin** [comment]
I just fixed it. However, the PyCharm recipe is not really suited for you, as PyCharm comes bundled with its own JRE. You'll most likely have to figure out the details of bundling an entire JRE yourself.

**Comment by jbwyatt4** [comment]
> However, the PyCharm recipe is not really suited for you, as PyCharm comes bundled with its own JRE. You'll most likely have to figure out the details of bundling an entire JRE yourself.

That is too much to expect of a new user of AppImage. If you want people to use AppImage we need more help then that. I honestly I have no idea of where to begin with this guide. (Oracle download link is broken btw.)

**Comment by probonopd** [comment]
Where can JavaFXApplication1 be downloaded and what does it do? Are you the author of it?

**Comment by jbwyatt4** [comment]
Yes, it is either one of the NetBeans JavaFX examples or based off it (can't remember). 

I have attached it (as a .zip since Github does not like jars).

Make sure to have the JavaFX package installed on your distribution or you will get a class error. Both Ubuntu and Manjaro separate JavaFX. With Ubuntu it is called openjfx .
[JavaFXApplication1.zip](https://github.com/AppImage/AppImageKit/files/1545467/JavaFXApplication1.zip)

**Comment by probonopd** [comment]
openjfx does not seem to exist in Ubuntu 14.04 (the oldest still-supported LTS), what can we do there?

**Comment by jbwyatt4** [comment]
We would have to use the Oracle binaries. I believe it uses functionality from FX 8 which may have came out after Ubuntu 14.04 feature freeze.

**Comment by probonopd** [comment]
Which URL can the Oracle binaries be downloaded from?

**Comment by jbwyatt4** [comment]
This script seems to be an updated version of the wget command PyCharm tries to use. I just tested it. It works. (It is the JDK, instead of the JRE, it is also Java 9.)

https://gist.githubusercontent.com/P7h/9741922/raw/6c0b812ebb97c0b6633b76bc4c2f293714837064/jdk_download.sh

**Comment by probonopd** [comment]
Isn't JDK "bloated" in the sense that it is much larger than the minimum needed to run this application?

**Comment by jbwyatt4** [comment]
Well, it is the development libraries and tools. You would have to use this URL then:
http://www.oracle.com/technetwork/java/javase/downloads/jre9-downloads-3848532.html

Or use Ubuntu's 16.04 libraries.

**Comment by probonopd** [comment]
OK. You need to write a bash script called "AppRun" that launches your jar using the unpacked jre9. Do you need help on that or is it clear to you how to do this?

**Comment by jbwyatt4** [comment]
I would need help with that.

**Comment by probonopd** [comment]
Something along the lines of:

```
mkdir -p usr/lib/jvm/ ; tar xf ../jre* -C usr/lib/jvm/
( cd usr/bin ; ln -s ../lib/jvm/jre*/bin/java . )
tar xf ../mule_*
mv mule/data/lib*so mule/data/lib/lib* usr/lib/
mkdir -p usr/share/javafxapplication1
mv mule/data/*jar usr/share/javafxapplication1
cat > javafxapplication1.desktop <<\EOF
[Desktop Entry]
Type=Application
Name=JavaFXApplication1
Exec=javafxapplication1
Icon=javafxapplication1
Categories=Utilities;
EOF
convert mule/data/icon.gif javafxapplication1.png
cat > usr/bin/javafxapplication1 <<\EOF
java -Xms64m -Xmx256m -jar ./share/javafxapplication1/data.jar
EOF
chmod a+x usr/bin/javafxapplication1
```

**Comment by jbwyatt4** [comment]
Had to make a lot of edits. mule/data/icon.gif didn't work. Still getting the execv error

mkdir -p usr/lib/jvm/ ; mkdir -p usr/bin/ ; tar xf ../jre* -C usr/lib/jvm/
( cd usr/bin ; ln -s ../lib/jvm/jre*/bin/java . )
mkdir -p usr/share/javafxapplication1
cp ../JavaFXApplication1.jar usr/share/javafxapplication1
cat > javafxapplication1.desktop <<\EOF
[Desktop Entry]
Type=Application
Name=JavaFXApplication1
Exec=javafxapplication1
Icon=javafxapplication1
Categories=Development;
Comment=A test
EOF
convert ../freepik.jpg javafxapplication1.png
cat > usr/bin/javafxapplication1 <<\EOF
java -Xms64m -Xmx256m -jar ./share/javafxapplication1/javafxapplication1.jar
EOF
chmod a+x usr/bin/javafxapplication1

**Comment by probonopd** [comment]
Do you have an AppRun file? What is the output when you run it? Do you have a proper AppDir?

You really need to learn a bit about how this all works by looking at the examples... and by dissecting some of the existing example AppImages...

**Comment by crazyaccess** [comment]
I am having the same problem
