### ISSUE TITLE
Building libappimage unclear

### ISSUE THREAD

**Issue by llelectronics** [AppImage/AppImageKit#564]
LibAppImage is a dependency for some applications like nx-software-center to build. 
Running build.sh from appimagetool/master does not seem to create/ship the necessary CMake files or includes for creating that libappimage which is necessary. (Missing appimage.h for example)

**Comment by TheAssassin** [comment]
@llelectronics see my comment https://github.com/AppImage/AppImageKit/issues/536#issuecomment-348921757. Please avoid creating further issues for libappimage, it is really premature, and we're going to work out the details in the current sprint. See also https://github.com/AppImage/AppImageKit/issues/536.

We're going to post instructions here once this all works.

**Comment by probonopd** [comment]
See https://github.com/probonopd/nx-software-center/blob/patch-1/.travis.yml for where to get a deb of it in the meantime...

**Comment by TheAssassin** [comment]
AppImageKit now is just another CMake based project. If you want to build it, simply `add_subdirectory(my/path/to/AppImageKitSubmodule)`. You'll get a target called `libappimage`, which you can pass to `target_link_libraries` etc.

**Comment by probonopd** [comment]
Now we need to document it :+1:

**Comment by TheAssassin** [comment]
The "official" way _is_ documented, and always was. See the README. If you want to, we can add a note that this is just another CMake project, but that's pretty obvious, considering there's a `cmake` directory and a `CMakeLists.txt`.
