### ISSUE TITLE
Disable System Integration dialogue with env var

### ISSUE THREAD

**Issue by achingbrain** [AppImage/AppImageKit#569]
Is there a way to prevent the 'Would you like to integrate $FOO with your System' dialogue opening without installing any extra software or mutating the global system?

I'm trying to run automated UI tests on an `.AppImage` in a immutable CI environment so can't install `appimaged` or create a file at `$HOME/.local/share/appimagekit/no_desktopintegration`.

What would be ideal is if I could start the app with an env var like `APPIMAGE_NO_DESKTOP_INTEGRATION` or pass a flag or something to suppress the popup.

Is this possible?

**Comment by TheAssassin** [comment]
Check out https://raw.githubusercontent.com/AppImage/AppImageKit/master/desktopintegration. Try `export DESKTOPINTEGRATION=no`.

**Comment by achingbrain** [comment]
That's fantastic, thank you!
