### ISSUE TITLE
Investigate getlantern/autoupdate

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#57]
While https://github.com/probonopd/AppImageKit/tree/master/AppImageUpdate.AppDir does mostly what we need, we should check out

https://github.com/getlantern/autoupdate

which seems to follow a similar pattern.

**Comment by TheAssassin** [comment]
Since we have concrete plans with AppImageUpdate, is that still of any interest?

**Comment by probonopd** [comment]
Merely out of curiosity, but I don't see any concrete TODOs.
