### ISSUE TITLE
Error in 'appimaged': munmap_chunk(): invalid pointer: 0x00000000004307d2

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#583]
```
Error in 'appimaged': munmap_chunk(): invalid pointer: 0x00000000004307d2
```

Suspected cause: https://github.com/AppImage/AppImageKit/pull/575
PR in the works to fix this: https://github.com/AppImage/AppImageKit/pull/582

**Comment by TheAssassin** [comment]
Should have been resolved.

**Comment by KurtPfeifle** [comment]
@TheAssassin wrote (unprecisely):

> *"Should have been resolved."*

So... is it resolved or is it not?

**Comment by probonopd** [comment]
I don't get it anymore in recent builds :+1:
