### ISSUE TITLE
Dead link in wiki page about bundling KDE apps

### ISSUE THREAD

**Issue by d1vanov** [AppImage/AppImageKit#589]
[This wiki page](https://github.com/AppImage/AppImageKit/wiki/Bundling-KDE-apps) contains [the dead link](https://github.com/probonopd/imagewriter/blob/master/.travis.yml) to usage example.

**Comment by d1vanov** [comment]
The referenced project is called [imagewriter-1](https://github.com/probonopd/imagewriter-1), not `imagewriter`.

**Comment by probonopd** [comment]
Thanks for noticing this. The correct link is
https://github.com/KDE/isoimagewriter/blob/master/.travis.yml

Updated.
