### ISSUE TITLE
Define additional metadata in .desktop file

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#59]
The topmost `.desktop`file in the root directory of the AppDir/AppImage should be enriched with additional lightweight metadata related to the AppImage. 

http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s11.html

PortableLinuxGames apparently already has defined some.
- `X-AppImage-Name`: Name of the application (e.g., `Krita`)
- `X-AppImage-Version`: Version of the application that is contained in the AppImage (e.g., `1.3.1`)
- `X-AppImage-Arch`: Architecture of the AppImage (e.g., `x86_64`)
- `X-AppImage-Release`: Version or timestamp of the AppImage itself (added at AppImage creation time)
  ...

However. let's try not to be redundant to [AppStream](http://www.freedesktop.org/software/appstream/docs/) information. So let's not include the license, the URL, etc.

**Comment by probonopd** [comment]
`X-AppImage-Version` might be misleading since it is not evident that this is about the payload app

**Comment by TheAssassin** [comment]
I think we can close this, since there's support for AppStream, which we propose in a lot of places, including AppImageHub. As far as I know, it has support for a lot of default types, and also allows auxiliary information.

**Comment by probonopd** [comment]
But it is optional and cumbersome whereas adding the version  of the application should be easy/automatic...

**Comment by azubieta** [comment]
I guess that this should be solved by the conclusions of this discussion: https://github.com/AppImage/appimaged/issues/30 therefore I'll close the issue.

Re-open it if you think otherwise :)

**Comment by probonopd** [comment]
https://github.com/AppImage/appimaged/issues/30 names some metadata which currently is not in desktop files yet (but may be required for the proper functioning of the concepts outlined in https://github.com/AppImage/appimaged/issues/30). At this point it is unclear whether an extension of the current desktop file format is the way to go, or a switch to something like JSON or YAML (which would allow for plist-style data structures like arrays etc.)

**Comment by probonopd** [comment]
Let's close this only after we have documented this stuff somewhere.

**Comment by probonopd** [comment]
`X-AppImage-Version` is currently undocumented, isn't it? (Where is it documented/specified?)

**Comment by probonopd** [comment]
Same for the architecture?

**Comment by probonopd** [comment]
Reference: https://github.com/AppImage/AppImageKit/issues/662

**Comment by TheAssassin** [comment]
Many features are undocumented right now. Please open an issue in the docs repository.

**Comment by probonopd** [comment]
Thank you for documenting them. Should we also add them to the AppImageSpec?

**Comment by TheAssassin** [comment]
If you like. I'm not entirely sure which are even supported, so I stayed a bit vague. After all, I only know for sure `X-AppImage-Version` is actively used.

I don't think that stuff needs to go in the spec necessarily, but if you like, you can put it in as a recommendation (*SHOULD*). That's probably more motivation for anyone than the docs to implement this in their tools.
