### ISSUE TITLE
Find replacement for file command

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#590]
On `deepin-15.5-amd64.iso`:

```
sh: 1: /usr/bin/file: not found
```

**Comment by TheAssassin** [comment]
What is it used for?

**Comment by probonopd** [comment]
Figuring out the architecture of the binaries inside the AppDir, and hence, picking the correct matching runtime architecture,

**Comment by TheAssassin** [comment]
I assume you could easily copy the few magic numbers required for detecting the architecture of the binaries, and write some detection code yourself. That'd eliminate this dependency as a whole.

**Comment by probonopd** [comment]
Yes.

**Comment by TheAssassin** [comment]
https://github.com/threatstack/libmagic/blob/master/magic/Magdir/elf

We could either link to libmagic and bundle this file (and the library), or write some C code hardcoding the values (a custom parser would be overkill in my opinion). The `libmagic.a` artifact included in Ubuntu 16.04 has a size of 232k, which is fairly acceptable in my opinion. I could imagine that if we build our own, we might save some space.

**Comment by probonopd** [comment]
We don't need to recognize any file format known to libmagic, but really only ELF executables and libraries. Should be able to shrink its size significantly.

**Comment by TheAssassin** [comment]
`file` uses libmagic internally, hence the idea of using it to avoid writing duplicate code and have someone else maintain it.

The size of `libmagic.a` won't decrease when deactivating any format. The `magic` data is laying in files in the same format which I linked to, as far as I can see.

**Comment by develar** [comment]
#691 latest build (from master) blindly requires `file` command, but actually it is not required at all if `ARCH` env is defined (as electron-builder does).

**Comment by TheAssassin** [comment]
@develar what's your point here?

**Comment by develar** [comment]
@TheAssassin This check https://github.com/AppImage/AppImageKit/blob/appimagetool/master/src/appimagetool.c#L514 must be only performed if  `ARCH` is not defined.

**Comment by TheAssassin** [comment]
I see, seems right. Could you send a PR, please?

**Comment by develar** [comment]
@TheAssassin Well, I decided instead use mksquashfs directly, sorry. https://github.com/develar/app-builder/commit/5353f2642cbfac8039e0469e765116a24a318b99 (in any case I am on macOS and it is not easy to build and test fix).

**Comment by azubieta** [comment]
Getting the target architecture of the binaries application can be performed by reading the `e_machine` entry in the elf header. Therefore we can drop file.

**Comment by TheAssassin** [comment]
Closing as resolved.
