### ISSUE TITLE
libappimage must not be a runtime dependency for each AppImage

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#611]
libappimage must not be a runtime dependency for each Appimage. As of today, Scribus nightly builds from http://impagina.org/download/ are broken:

```
me@host:~/Downloads$ ./Scribus-git4553fa9-glibc2.14.glibc2.14-x86_64.AppImage --appimage-extract
scribus.wrapper: error while loading shared libraries: libappimage.so: cannot open shared object file: No such file or directory
```

How did this happen? We should never introduce additional dependencies into what had been working before, thus breaking all 3rd party AppImages without prior discussion and announcement, giving developers plenty of time to prepare.

**Comment by TheAssassin** [comment]
You reported the same error yesterday. And it's pretty obvious. The last line says something `*.wrapper: `. It's the desktop integration script.

The issue has been fixed already, they have to rebuild their AppImage. Also, they have the glib version twice in their filename, it doesn't look like they have updated their build scripts in a while, however they're pulling in the latest `functions.sh` for every build. Maybe they should review their build infrastructure
