### ISSUE TITLE
Improve IMPORTED CMake targets

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#614]
At the moment, we're generating a CMake module and install it on the system, which can be used to use a system wide shared library.

We should, however, make it a little easier to work with this module. At the moment, we're using a pretty outdated pattern where variables are created for every kind of information one needs to build and link to it (namely include directories and library locations). Similar to the `FindPNG` module which comes with CMake, I'd like to create so-called `IMPORTED` targets, which can be used with the well-known CMake function `<target_>link_libraries`. Using that target will then configure CMake to link to all the dependencies (for the static version), and include the right directories, without having to make these calls manually.

See e.g., https://cmake.org/cmake/help/v3.6/module/FindPNG.html#imported-targets:

```cmake
find_package(PNG REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main ${PNG_LIBRARIES})
target_include_directories(main ${PNG_INCLUDE_DIRS})
target_compile_definitions(main ${PNG_DEFINITIONS})
```

vs.

```cmake
find_package(PNG REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PNG::PNG)

**Comment by azubieta** [comment]
We do have make an imported target already. Please check the installed file: usr/lib/cmake/AppImageKit/AppImageKitTargets.cmake

**Comment by TheAssassin** [comment]
I see. And I see some potential for improvements. Thanks for the hint, I'll be working on that then. And thanks for your initial work.

**Comment by azubieta** [comment]
Now we have libappimage and there is an issue there that actually deals with this topic. https://github.com/AppImage/libappimage/issues/18
Closing this.
