### ISSUE TITLE
Restore env variables modified by AppRun when running processes outside of the AppImage

### ISSUE THREAD

**Issue by pamarcos** [AppImage/AppImageKit#616]
I found this issue testing https://github.com/darealshinji/AppImageKit-checkrt/issues/9. It's kind of related, but it affects the original AppImageKit, not only the checkrt flavour.

I did the following:

- Created AppImage (without the checkrt flavour or embedding any libstdc++) of an app that eventually opens a URL with Ubuntu 14.04. This works just fine in Ubuntu 14.04.
- Opened the AppImage with Ubuntu 17.10. It runs, but when trying to open the browser I get the following and the browser doesn't get opened:

```

XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func
Couldn't load XPCOM.
```

I solve the issue by clearing `LD_LIBRARY_PATH` internally in my app so that every process opened afterwards doesn't inherit that value. Hence, the question: should we restore original values for all env variables AppRun modifies when running external processes? Is there any reason not to do it? 

In case affirmative, the only way that I find we can restore the values without asking every app to do that themselves (removing the `APPDIR` parts of the env variables) is by hijacking the `exec` calls as in https://github.com/AppImage/AppImageKit/issues/396. However, not every config supports injecting through `LD_PRELOAD`, nor it is a very elegant of doing it.

**Comment by probonopd** [comment]
What is causing this? `hb_` points to HarfBuzz. Are any harfbuzz-related libraries bundled in your AppImgae and what happens if you delete them from the AppImage?

**Comment by pamarcos** [comment]
There is nothing regarding to HarfBuzz as far as I can tell:

```
Collabshot => bin/Collabshot (interpreter => /lib64/ld-linux-x86-64.so.2)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1
            libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6
            libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
                libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0
                    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libQt5Widgets.so.5 => bin/../lib/libQt5Widgets.so.5
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    libQt5Multimedia.so.5 => bin/../lib/libQt5Multimedia.so.5
        libpulse.so.0 => bin/../lib/libpulse.so.0
            libjson-c.so.2 => bin/../lib/libjson-c.so.2
            libpulsecommon-4.0.so => bin/../lib/libpulsecommon-4.0.so
                libwrap.so.0 => bin/../lib/libwrap.so.0
                    libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1
                libsndfile.so.1 => bin/../lib/libsndfile.so.1
                    libFLAC.so.8 => bin/../lib/libFLAC.so.8
                    libvorbisenc.so.2 => bin/../lib/libvorbisenc.so.2
                    libvorbis.so.0 => bin/../lib/libvorbis.so.0
                    libogg.so.0 => bin/../lib/libogg.so.0
                libasyncns.so.0 => bin/../lib/libasyncns.so.0
                    libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2
            libdbus-1.so.3 => bin/../lib/libdbus-1.so.3
    libQt5Gui.so.5 => bin/../lib/libQt5Gui.so.5
    libQt5Network.so.5 => bin/../lib/libQt5Network.so.5
    libQt5Core.so.5 => bin/../lib/libQt5Core.so.5
        libicui18n.so.52 => bin/../lib/libicui18n.so.52
        libicuuc.so.52 => bin/../lib/libicuuc.so.52
            libicudata.so.52 => bin/../lib/libicudata.so.52
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0
            libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by TheAssassin** [comment]
Well, obviously it *is* used by something in your app, because the error is harfbuzz-related, as @probonopd pointed out. Did you call `ldd` on all the libraries in your `lib` directory? I could imagine something that is `dlopen()`ed using them, probably a Qt plugin.

**Comment by pamarcos** [comment]
Found it. I am not asking linuxdeployqt skip Qt plugins on purpose. This is where it's taken from:

```
Log: Using ldd:
Log:  inspecting "/home/pablo/qt_5.9_debian_sound/plugins/platformthemes/libqgtk3.so"
...
Log:  dylib.binaryPath "/usr/lib/x86_64-linux-gnu/libgtk-3.so.0"
...
Log: Using ldd:
Log:  inspecting "/usr/lib/x86_64-linux-gnu/libgtk-3.so.0"
...
Log:  dylib.binaryPath "/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0"
```

So it seems since one of Qt plugins ends up needing libharfbuzz, which is why linuxdeployqt is including it in my lib folder. So, since AppRun is prepending this lib before the original LD_LIBRARY_PATH, any external process will end up using those versions for everything.

I know an AppImage is not sandboxed, but it seems to me that using the internal versions of shared libs for processes outside of the bundle is going to be trouble at some point.

**Comment by TheAssassin** [comment]
Only if you rely on system tools which need to be installed system wide. Can't you perhaps bundle that app you need to call as well? That'd make your app more self contained, too.

**Comment by pamarcos** [comment]
Can't really embed this one. Well, I could but it would be a big mistake. I'm actually asking the OS to open a URL with the default browser. In my case it's Firefox, which seems to depend on something else I embed within my AppImage.

Anyway, I think the point here is: how many other external applications may clash with what's embedded into AppImages? What's the harm in removing what AppRun added to env variables for those external apps so they can run just as they would normally do?

**Comment by TheAssassin** [comment]
@pamarcos how are you opening up that URL, if I may ask? There's a lot of system independent ways to do so. It might be worth checking what Python's `webbrowser` module does: https://docs.python.org/2/library/webbrowser.html

The problem is, when bundling additional executables which are also bundled in the AppImage, they definitely need the relevant libraries (example: linuxdeployqt's `-executable` option). We'd need a detection whether the subprocess is bundled in the AppImage or is a system one, and only in the latter case restore the original environment.

**Comment by pamarcos** [comment]
I'm using http://doc.qt.io/qt-5/qdesktopservices.html#openUrl. I haven't checked how Qt does it, but I image it's done the proper way.

**Comment by TheAssassin** [comment]
That thing will most likely not call your browser directly, it looks more like the Python approach (or what `xdg-open` does), and have the system call the appropriate software through an API.

**Comment by pamarcos** [comment]
It tries different approaches. The first one being `xdg-open` while the last attempt is literally trying to find the typical browsers in your system and calling them with the URL as a parameter: https://github.com/qt/qtbase/blob/3fe74b76fd0eaf39d4c6681e2edca5adbf107883/src/platformsupport/services/genericunix/qgenericunixservices.cpp#L135-L137

In any case, how's that affecting this issue? At some point, there's a call to open a browser. Presumably, by calling "browser [url]". Whether the caller is `xdg-open` or `gnome-open` is not that relevant IMO. The thing is that whoever is calling the browser (or even if the browser is called directly) it will inherit the env variables from AppImage, leading to a possible clash.

I don't think this is more likely to happen with browsers or anything. There are probably lots of cases that may happen when calling external processes.

**Comment by TheAssassin** [comment]
I'm asking myself whether `xdg-open` does inherit the environment when spawning new processes... But yes, you're right, I was just curious about your use case, and maybe whether it's possible to quick fix it by changing the method. It is not.

**Comment by pamarcos** [comment]
Surprising enough, it turns out `xdg-open` is just a script: https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-open.in. It does seem to inherit the whole environment and depending on some values the logic is different. 

In any case, to fix https://github.com/darealshinji/AppImageKit-checkrt/issues/9 we need to remove the `optional` part from `LD_LIBRARY_PATH`. I think this issue actually supersedes the other one and we'd have fewer problems if we remove the `APPDIR` part of the env variables. However, I'm surprised that this has not raised issues before.

**Comment by TheAssassin** [comment]
@probonopd should make that decision.

**Comment by probonopd** [comment]
Correct, ideally the environment variables set by AppRun (such as `LD_LIBRARY_PATH`) would be unset before anything outside the AppImage gets called. 

This is exactly what the exec wrapper used by Kdevelop does.

This is mostly an issue for applications inside an AppImage that invoke other applications outside the AppImage (like Kdevelop does).
