### ISSUE TITLE
Do not cause systemd to relaunch appimaged immediately after a crash

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#619]
We should not have systemd restart `appimaged` immediately after it crashes all the time. I think systemd has a facility to slow down subsequent launches, we should use it.

Example:
https://github.com/AppImage/AppImageKit/issues/617

**Comment by TheAssassin** [comment]
The instruction you are probably looking for is `RestartSec`. Add it like this:

```
Restart=always
RestartSeconds=30
```

I couldn't figure out where the systemd file is defined, so I'd ask you to send a PR for that.

**Comment by probonopd** [comment]
Here:
https://github.com/AppImage/AppImageKit/blob/b50a73e9fe34f6e0337a4aa4985d47010de5ef1d/appimaged.ctl#L29

According to https://www.freedesktop.org/software/systemd/man/systemd.service.html the key seems to be named `RestartSec` - which is correct?

**Comment by probonopd** [comment]
I`d assume that we`d have to use something like

```
RestartSec=30s
```

or even more seconds.

**Comment by probonopd** [comment]
Do we also need 

> StartLimitIntervalSec=interval, StartLimitBurst=burst

? I find the documentation hard to understand and can't wrap my head around it right now.

**Comment by TheAssassin** [comment]
I don't think so.

**Comment by probonopd** [comment]
How can one tell systemd to try starting a service for three times, and then give up and no longer restart it?

**Comment by TheAssassin** [comment]
Well, in that case, you can set e.g.,

```
RestartSec=30
StartLimitIntervalSec=300
StartLimitBurst=3
```

This tells systemd to wait 30 seconds, restart the process, then retry. It allows the process to do so 3 times in 300 seconds.

**Comment by probonopd** [comment]
Thanks, that was the simple explanation that I was missing in the official documentation :-)

**Comment by TheAssassin** [comment]
The `s` is optional, as it takes seconds as default unit. But, as usual, explicit is better than implicit (source: PEP20). You could also write `1m` etc.
For `StartLimitIntervalSec`, it seems like you have to specify an integer without any suffixes. See https://www.freedesktop.org/software/systemd/man/systemd.unit.html.

**Comment by probonopd** [comment]
OK, so it's not just me... ;-)
