### ISSUE TITLE
[desktopintegration] Root = system wide install does not work

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#62]
[desktopintegration] Root = system wide install does not work

**Comment by RazZziel** [comment]
[`SYSTEM_WIDE="--mode system"`](https://github.com/probonopd/AppImageKit/blob/010268a504ee73ded07dbc0fd1e67db947ff6211/desktopintegration#L159) doesn't seem to be correct, because according to [the doc](http://manpages.ubuntu.com/manpages/precise/man1/desktop-file-edit.1.html):

       -m, --mode=MODE
              Set the permissions of the destination files to MODE.

**Comment by probonopd** [comment]
Ouch. That's why it hasn't been working so far... Needs to be fixed indeed.

**Comment by TheAssassin** [comment]
@probonopd is this still relevant?

**Comment by probonopd** [comment]
I think it is still an issue but I don't develop the old `desktopintegration` script further. So keeping this issue open for others to pick up if someone thinks this needs to be fixed.

**Comment by TheAssassin** [comment]
Closing as outdated.
