### ISSUE TITLE
Shell output of `--appimage-updateinfo` is padded with NUL byte

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#621]
I noticed that all AppImages released by the AppImageKit project pad the string printed for *`--appimage-updateinfo`* to fill up to 1024 characters with NUL bytes. It doesn't normally show in the terminal, but it is revealed as a series of *`@@@@@@@@@@...`* if you run, for example:

    ./appimagetool-x86_64.AppImage --appimage-updateinfo | less

For what reason are these NUL bytes required in the *output* (when printing the updatestring *AS INFO* into the terminal, as response to a command line argument requesting it)?

Can't these bytes be suppressed before they arrive in the shell? They only make using the *`--appimage-updateinfo`* output harder to post-process in scripts and logs...

**Comment by TheAssassin** [comment]
When those bytes are interpreted in the runtime code as a C string, the null bytes are terminating the string in there, and we can work with it normally. I am pretty sure that, when asked for the update info with said flag, the runtime doesn't interpret the data at all, but just "forwards" it to stdout.

I think we can just trim the null characters without breaking software in other places.

**Comment by probonopd** [comment]
> I think we can just trim the null characters without breaking software in other places.

Yes, we should trim them away. They are in the ELF so that the ELF section always has a known amount of space available, so that the content of this section can be changed after compilation. When outputting, we would truncate the string before the first occurence of `0x00`.

**Comment by TheAssassin** [comment]
I sent a PR, see #632. @KurtPfeifle could you please check whether AppImages built using the appimagetool from that PR behave correctly?
