### ISSUE TITLE
Consider having appimagetool include desktopintegration automatically

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#63]
[desktopintegration] Consider having AppImageAssistant/package do this automatically

**Comment by azubieta** [comment]
appimagetool including desktop integration ? Please elaborate or close.

**Comment by probonopd** [comment]
The idea was to have appimagetool put something like the old `desktopintegration` script (but possibly based on libappimage as of today) into each produced AppImage; but I guess we are not going down that path, since proper desktop integration needs some infrastructure on the system. We might reconsider if XDG or something like it implements the core concepts from  https://github.com/AppImage/appimaged/issues/30
