### ISSUE TITLE
[appimaged] Some icons are extracted with 0 KB from type-1 AppImages

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#630]
For whatever reason, the icon does not get extracted correctly by `appimaged`, resulting in a 0 KB file:

```
# The original inside the AppImage
me@host:~$ ls -lh /tmp/.mount_OqtGsV/usr/share/icons/default/512x512/apps/protonmail-desktop.png 
-rw-rw-r-- 1 root 2000 433K Jan 14 22:11 /tmp/.mount_OqtGsV/usr/share/icons/default/512x512/apps/protonmail-desktop.png

# The one extracted by appimaged
me@host:~$ ls -lh .local/share/icons/default/512x512/apps/appimagekit_003d3e803b7e43a5f4ee559be432eb4c_protonmail-desktop.png 
-rw-r--r-- 1 me me 0 Jan 20 11:04 .local/share/icons/default/512x512/apps/appimagekit_003d3e803b7e43a5f4ee559be432eb4c_protonmail-desktop.png
```

Possibly related to the fact that the icon is in `/usr/share/icons/default` rather than in `/usr/share/icons/hicolor`.

Reference:
https://github.com/protonmail-desktop/application/issues/162

**Comment by probonopd** [comment]
I am wondering why the extracted icon lands in `default` rather than in `hicolor` given this:

https://github.com/AppImage/AppImageKit/blob/29ecf870526694db47f849aba41b3624d13e1713/src/shared.c#L174

**Comment by probonopd** [comment]
Example AppImage:

https://github.com/protonmail-desktop/application/releases/download/v0.5.4/protonmail-desktop-0.5.4-x86_64.AppImage

**Comment by azubieta** [comment]
If I recall this issue was related to a broken implementation of file extraction following symlinks which was already fixed.
Closing the issue, please reopen if required.
