### ISSUE TITLE
Permalinks for appimageupdatetool, AppImageUpdate and zsync{,make}2?

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#635]
Tools + utilities provided by the AppImage project use generic names for their downloadable binaries on the respective GitHub "releases" page(s): *appimaged*, *appimagetool*, *linuxdeployqt* (even if it isn't under the umbrella of "AppImage").

However, for *appimageupdatetool*, *AppImageUpdate*, *zsync2* and *zsyncmake2* this is not the case. For these you need to use a "versioned" filename/downloadlink.

Couldn't these tools provide a copy of their releases under a non-versioned name, so their automatic/scripted downloads could use a permalink without having to resort to sed/grep/awk hackery to find the newest *'href='* link from *`curl`*'s HTML output?

**Comment by TheAssassin** [comment]
@probonopd decided that it makes sense to put this information in the filename, too, for tools which don't have to be downloaded in automated ways (e.g., CI builds). I agree to this. Also, this is the wrong place to discuss naming changes, if you insist, you are free to open issues in the actual repositories of these projects.

**Comment by probonopd** [comment]
@KurtPfeifle do you know the GitHub API? It can be used to make the parsing a bit easier.
