### ISSUE TITLE
All tools released as AppImages stopped providing meaningful '--appimage-version' info

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#638]
None of the tools + utilities provided by the AppImage project no longer print useful info for the *`--appimage-version`* flag:

```
for i in appimaged appimagetool appimageupdatetool AppImageUpdate linuxdeployqt zsync2 zsyncmake2 ; do
    printf "%60s" "./$i*.AppImage" ;
    $i*.AppImage --appimage-version ;
done
                           ./appimaged-x86_64.AppImage :  Version: 
                        ./appimagetool-x86_64.AppImage :  Version: 
      ./appimageupdatetool-189-6e634ca-x86_64.AppImage :  Version: 
          ./AppImageUpdate-189-6e634ca-x86_64.AppImage :  Version: 
            ./linuxdeployqt-continuous-x86_64.AppImage :  Version: 
                  ./zsync2-109-781a47f-x86_64.AppImage :  Version: 
              ./zsyncmake2-109-781a47f-x86_64.AppImage :  Version: 
```

A few days ago, this still used to work, as testing with previous versions amply demonstrates which I've still kept around:

```
      ./appimageupdatetool-185-1c72f3b-x86_64.AppImage :  Version: continuous-4-g7c68361
          ./AppImageUpdate-185-1c72f3b-x86_64.AppImage :  Version: continuous-4-g7c68361
          ./AppImageUpdate-181-1615ff8-x86_64.AppImage :  Version: continuous-46-gb50a73e
          ./AppImageUpdate-183-236e0c5-x86_64.AppImage :  Version: continuous-46-gb50a73e
                      ./AppImageUpdate-x86_64.AppImage :  Version: continuous-46-gb50a73e
                  ./zsync2-105-7fd1caa-x86_64.AppImage :  Version: continuous-6-ge68586d
              ./zsyncmake2-105-7fd1caa-x86_64.AppImage :  Version: continuous-6-ge68586d
                  ./zsync2-106-817978a-x86_64.AppImage :  Version: continuous-1-g8a471fc
              ./zsyncmake2-106-817978a-x86_64.AppImage :  Version: continuous-1-g8a471fc
```

**Comment by TheAssassin** [comment]
Could you please try to find out which of the tools' versions was the first one which didn't work as intended? (In case you still have the intermediate versions, too.) Otherwise, someone'll have to `git bisect`.

**Comment by KurtPfeifle** [comment]
Sorry.

What you see above is all info I can provide. I don't have any other versions, otherwise I'd have tested these too.

So "someone" who as changed code in that context would have to dig herself...

**Comment by TheAssassin** [comment]
No problem, thanks for notifying us. I'll try to debug it within the range of commits you provided.

**Comment by KurtPfeifle** [comment]
Another thing I noticed, which changed over the course of the last releases. The following table provides a list of current `--appimage-offset` values:

```
 ================================
    Running check_offsets:
 ================================
             appimaged :  146768
        AppImageUpdate :  146768
    appimageupdatetool :  146768
          appimagetool :  146768
         linuxdeployqt :  146768
                zsync2 :  146768
            zsyncmake2 :  146768
```

A few releases ago, these were not as uniform as they now are:

```
 ================================
    Running check_offsets:
 ================================
        ./appimageupdatetool-185-1c72f3b-x86_64.AppImage :  116144
            ./AppImageUpdate-181-1615ff8-x86_64.AppImage :  116144
            ./AppImageUpdate-183-236e0c5-x86_64.AppImage :  116144
            ./AppImageUpdate-185-1c72f3b-x86_64.AppImage :  116144
                    ./zsync2-105-7fd1caa-x86_64.AppImage :  100024
                    ./zsync2-106-817978a-x86_64.AppImage :  116144
                    ./zsync2-108-fb06578-x86_64.AppImage :  146768
                ./zsyncmake2-105-7fd1caa-x86_64.AppImage :  100024
                ./zsyncmake2-106-817978a-x86_64.AppImage :  116144
```

I guess this little details has very little practical relevance, as long as all the functionality of the tools is there. However, it may be a pointer or indicator for something else...

**Comment by TheAssassin** [comment]
Whenever the runtime changes, these numbers change as well. I recently changed said runtime in order to close #632. This change seems harmless.

By the way, do you want to share your test script? Maybe it's worth running some of your checks automatically on Travis.

**Comment by KurtPfeifle** [comment]
> *"do you want to share your test script?"*

Yes, I want. When it's ready and time for it -- that is once *everything* works as I intend it to...

----

<sup>(Meanwhile you could follow what Travis builds are successful here: https://travis-ci.org/KurtPfeifle/AppImageKit-Toolbox/builds , then download the generated *`appimagekit-toolbox-continuous-x86_64.AppImage`* from transfer.sh and run it with '--help' to find your way around; lastly run it with '--runscript selftests.sh' parameters.)</sup>

**Comment by probonopd** [comment]
> appimagekit-toolbox-continuous-x86_64.AppImage

w00t - something cool is brewing. Talk about eating our dogfood ;-)

**Comment by KurtPfeifle** [comment]
Thanks.

FYI: my *'selftests.sh'* script now starts to enumerate *`'--appimage-version'`* info again:

````
 ================================
    Running check_appimageversions:
 ================================
             appimaged :  Version: continuous-2-g879de57
        AppImageUpdate :  Version: 
    appimageupdatetool :  Version: 
          appimagetool :  Version: continuous-2-g879de57
         linuxdeployqt :  Version: 
                zsync2 :  Version: 
            zsyncmake2 :  Version: 
      appimage-toolkit :  Version: continuous-2-g879de57
````

The current releases of utilities from the AppImageUpdate, zsync2 and linuxdeployqt repos are not yet doing it -- I guess after they are re-built they also will. I'll watch out...

So the only "irregularity" standing out from this set of selftests are the facts that...

* *'zsyncmake2'* does not yet support *`'--version'`* (see [issue #17](https://github.com/AppImage/zsync2/issues/17) over there) -- who cares about additional commas or not?
* *'linuxdeployqt'* reports a *`'build <local dev build>'`* string...

````
 ================================
    Running check_versions:
 ================================
             appimaged :  appimaged, continuous build (commit continuous-2-g879de57), build 1448 built on 2018-02-02 09:57:36 UTC
        AppImageUpdate :  AppImageUpdate version 1-alpha (commit 6e634ca), build 189 built on 2018-01-25 07:00:57 UTC
    appimageupdatetool :  appimageupdatetool version 1-alpha (commit 6e634ca), build 189 built on 2018-01-25 07:00:57 UTC
          appimagetool :  appimagetool, continuous build (commit continuous-2-g879de57), build 1448 built on 2018-02-02 09:57:36 UTC
         linuxdeployqt :  linuxdeployqt 4 (commit 002059c), build <local dev build> built on 2018-01-29 14:08:24 UTC
                zsync2 :  zsync2 version 2.0.0-alpha-1 (commit 781a47f), build 109 built on 2018-01-26 07:08:11 UTC
            zsyncmake2 :  Flag could not be matched: version
   appimagekit-toolbox :  appimagekit-toolbox, version 1-alpha (commit 7816165), build 98 on Fri Feb  2 10:06:22 UTC 2018
````

**Comment by TheAssassin** [comment]
I'll trigger rebuilds for all the remaining tools.

**Comment by TheAssassin** [comment]
> 'linuxdeployqt' reports a 'build <local dev build>' string...

Hm, I'll try to find the cause and fix it. Related issue: https://github.com/probonopd/linuxdeployqt/issues/232

**Comment by TheAssassin** [comment]
@KurtPfeifle issue resolved, also retriggered builds for the other projects. You may re-run your tests now, they should succeed this time.
