### ISSUE TITLE
[desktopintegration] Xdialog window does not scale

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#64]
[desktopintegration] Xdialog window does not scale when the text to be displayed is long

**Comment by TheAssassin** [comment]
Please elaborate. It doesn't get clear what this issue refers to. Is that still a problem?

**Comment by probonopd** [comment]
One of three tools that are tried to display the desktopintegration dialogs is `Xdialog`. However, when it is used to display long texts, then the text is cut off. This is a placeholder in case anyone experiences issues with text being cut off.

**Comment by azubieta** [comment]
desktop integration dialogs? Where?
 I'm working on fixing old bugs. It seems that this is no longer an issue. Can we close it?

**Comment by TheAssassin** [comment]
@azubieta check the master branch (we are on `appimagetool/master` right now). There's a script `desktopintegration`.

The branch is no longer maintained. We can close this as wontfix.
