### ISSUE TITLE
Qt - Open file dialog

### ISSUE THREAD

**Issue by milohr** [AppImage/AppImageKit#640]
I'm getting this errors dialogs windows after creating the AppImage and launching the app open file dialog:

URL cannot be listed
file://
->
Malformed URL
->
URL cannot be listed
file://

And then the open file dialog shows up but not folders are displayed.

If it is of any use this is the console repetitive output:

kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "file"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "ftp"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "trash"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "gdrive"

This is the AppImage:
https://drive.google.com/open?id=1EbLpnBKp20_Vbuw_qzgXHpO4mdmL4F7S

Right before the AppImage is created everything works just fine.
I also create a new simple application with just a button and a open file dialog and the same thing happened when I created its Appimage.

For Qt this is the line I'm using to display the open file dialog:
QString url = QFileDialog::getExistingDirectory(this,"Select folder...");

I'm using Qt 5.10
and this is the lines I'm using to create the AppImage
./linuxdeployqt.AppImage /home/camilo/Coding/qt5/babe/org.kde.babe.desktop -bundle-non-qt-libs -verbose=1
./linuxdeployqt.AppImage /home/camilo/Coding/qt5/babe/org.kde.babe.desktop -appimage

It also happened with an AppImage qith Qt Quick Controls 2:
https://drive.google.com/open?id=1xx3KcCSJ5NOQ2Rg_eZ6QOjy5QP7PMZjP

Except the error dialog. The open file dialog shows up but cannot see any folder being displayed

Any idea why is this happening?
Let me know if you need any more information.

**Comment by TheAssassin** [comment]
This appears like a linuxdeployqt issue. Could you post the issue there, please? Thanks.

**Comment by milohr** [comment]
I will, thank you.

**Comment by probonopd** [comment]
https://github.com/probonopd/linuxdeployqt/issues/229
