### ISSUE TITLE
Consider using Retpoline to mitigate the Spectre security risk on x86_64

### ISSUE THREAD

**Issue by Chaz6** [AppImage/AppImageKit#648]
Retpoline is a software solution to protect against branch-target-injection attacks which is quicker than the proper hardware fix. As this is a binary modification, this can be applied to any packaged application built using AppImageKit. More info: https://support.google.com/faqs/answer/7625886

**Comment by TheAssassin** [comment]
Do you suggest to apply those patches to our tools? Or do you suggest we should encourage users to apply them to their AppImages (maybe we can even integrate that into appimagetool)?

**Comment by Chaz6** [comment]
I was thinking this could applied by appimagetool to the packaged application as a proactive measure.

**Comment by TheAssassin** [comment]
I don't think that's a feasible option. The problem is, those patches and changes to software aren't fully free of side effects, there's performance problems (more or less bad, depending on the use cases of the software).

**Comment by azubieta** [comment]
This kind of solution should be performed by the software developer by themselves otherwise we will be blamed by the side effects of such patches.

Closing issue as wontfix. Please reopen if required.

**Comment by probonopd** [comment]
Let's think of AppImage as a self-mounting filesystem image. What goes inside is not really our business...
