### ISSUE TITLE
[desktopintegration] When installed systemwide, then do not ask user

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#65]
[desktopintegration] When installed systemwide, then do not ask user

**Comment by TheAssassin** [comment]
Please elaborate on this issue so people can actually work on it. Is it even up to date?

**Comment by probonopd** [comment]
I am not sure whether this is still an issue. When you run the AppImage e.g., from /opt as root, then it could/should install the desktop integration system-wide for all users.

But I am focusing on `appimaged` instead these days.

**Comment by probonopd** [comment]
I am not sure whether my original request was really what we need, it seems from https://github.com/AppImage/appimaged/issues/30 that per-user desktop integration is also sufficient for those applications that are available system-wide. Hence, closing.
