### ISSUE TITLE
build.sh failed,  when retry, it do everything from beginning, waste a lot of time

### ISSUE THREAD

**Issue by tidatida** [AppImage/AppImageKit#655]
I git clone the source on centos 7 x64 , and run build.sh , it do some work include download, compile , but it failed somewhere , error: #  **no zsyncmake ,**  then failed. So I retry it, it do everything from the beginning , re-downloading everything, re-compiling, ... 

It sucks.  And I download binary version then do installing, but  failed again.  So , it not work on Centos7 ?

**Comment by TheAssassin** [comment]
The script is primarily meant to be used by our CI system.

AppImageKit is a CMake project, so if you have CMake on your system, build it like any other CMake project:

```
git clone https://github.com/AppImage/AppImageKit
cd AppImageKit
mkdir build
cd build
cmake ..
make -j$(nproc)

**Comment by tidatida** [comment]
Thanks @TheAssassin  ,  I have finihshed compiling successfully,  now I'll read how to use it. You can close this issue now.

**Comment by TheAssassin** [comment]
Actually, I need to recommend you to use the official binaries provided on our [download page](https://github.com/AppImage/AppImageKit/releases). Compiling yourself is, as the README says, nothing the average user needs to be able to do.
