### ISSUE TITLE
Move appimaged to separate repository

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#656]
Now that we have libappimage, we could move appimaged to a separate repository.

That'd reduce the build times of this repository a little, and allows us to build e.g., packages for Debian and other systems with CMake or other tools without cluttering the release page of AppImageKit.

Another reason might be that AppImageKit is meant to be the implementation of the AppImage specification version 2, however, appimaged is just an auxiliary tool, and nothing required to build AppImages.

I could also imagine something like a "daemon" repository, serving as the future home of other daemons we're planning, like appimageupdated.

**Comment by probonopd** [comment]
I fear extra work with little extra benefit... Die

**Comment by TheAssassin** [comment]
How much more extra work would you expect?

In fact, we'd just have to set up some CMake script pulling in AppImageKit via ExternalProject and then build `appimaged.c` against that code. Building against libappimage instead of pulling in `shared.c` etc. is also easier to reflect in system packaging, they prefer to build packages for libraries and binaries separately. That said, we could do the same in the AppImageKit repository.

**Comment by probonopd** [comment]
I'd prefer to keep everything in one place, in order to have far less administrative work to do.

**Comment by TheAssassin** [comment]
Another important argument for extracting appimaged is that AppImageKit contains the developer tools (SDK), whereas appimaged is, like AppImageUpdate, a user oriented program. I was recently informed that some users have difficulties to understand where to find which application, and they don't understand why appimaged can be found in the AppImageKit repository.

Soon, we'll be working on improving libappimage. Then, we should be able to easily extract appimaged, and link it statically to libappimage. Development wise and also technically, it's a mandatory step.

**Comment by probonopd** [comment]
Another argument against is that the build artifacts are probably linked/used in scripts in a gazillion different places and would break or lead to outdated versions...

**Comment by TheAssassin** [comment]
@probonopd I can't see any chance that appimaged's artifacts are used in any scripts or places...

**Comment by star-buck** [comment]
+1 for sorting things from a users perspective.

I personally was really confused where to look for appimaged and thought until very recently that AppImageKit was purely for developers doing their own appimage building...

**Comment by probonopd** [comment]
> @probonopd I can't see any chance that appimaged's artifacts are used in any scripts or places...

Stuff like this...

https://github.com/probonopd/SystemImageKit/blob/379dcc5157f58e61fb38d3906a4f434c6b3a403a/boot/bin/generate-appimaged-extension#L47

> +1 for sorting things from a users perspective.
> I personally was really confused where to look for appimaged and thought until very recently that AppImageKit was purely for developers doing their own appimage building...

If it tuns out that this is a common misconception, that could either mean that we need to improve the description/documentation and/or may be a reason to split the GitHub projects indeed (splitting generates additional work which I would like to avoid unless there is _clear_ benefit).

**Comment by TheAssassin** [comment]
Well, I don't have to tell you that the way how appimaged is built and linked to the rest of the code is really, really dirty. A mandatory step in improving appimaged and libappimage is to actually add all the necessary functionality we need for appimaged to it, and then properly link appimaged to libappimage. This helps in adding some structure to AppImageKit. Also, in terms of software architecture, loosely coupled code should be preferred.

These mammoth files called `shared.c` are really a pain to maintain...

**Comment by azubieta** [comment]
I also support the idea of splitting up all the appimage development tools
from the client side applications. Maintenance is the main reason from my
point of view. Every single tool in this repo has a different purpose so
they will evelove eventually in they own way. There is no need to limit
that evolution because a restriction in another component.
For libappimage users having to build all those tools is expensive and
non-required.
As an alternative to split each tool and to keep them together at the same
time we can use for submodules. In order to keep this as the main appimage
kit repository and reference properly every component.

**Comment by KurtPfeifle** [comment]
@probonopd 

> [...] may be a reason to split the GitHub projects indeed (splitting generates additional work which I would like to avoid unless there is clear benefit).

You mean just like the split of *probonopd/linuxdeployqt* from the rest of *appimage/$stuff* on Github?  😜

**Comment by TheAssassin** [comment]
> You mean just like the split of probonopd/linuxdeployqt from the rest of appimage/$stuff on Github? ￼

There's a bunch of reasons to do this. Also, linuxdeployqt is not linked to any AppImage code. It uses appimagetool via subprocesses.

> As an alternative to split each tool and to keep them together at the same time we can use for submodules. In order to keep this as the main appimage kit repository and reference properly every component.

That doesn't make sense. appimaged is a tool that uses AppImage (i.e. libappimage) code. If there is any kind of submodule, it's AppImageKit being a submodule of appimaged, to build libappimage and link appimaged to it.

**Comment by probonopd** [comment]
Since everybody seems to agree that it is a good idea to do the split I will agree to do this _if_
* Someone volunteers to do it (@TheAssassin is that you?)
* A new [AppImage/appimaged](https://github.com/AppImage/appimaged) repo is set up and made fully working (including downloadable continuous releases and documentation) _before_ appimaged is removed from this repo

In other words, once the [AppImage/appimaged](https://github.com/AppImage/appimaged) repo is fully functional, we can remove appimaged from this repo.

Questions:
* Where do we want to handle isses? Here or in the [AppImage/appimaged](https://github.com/AppImage/appimaged) repo?
* Which wiki do we want to use? The one here or a new one in the [AppImage/appimaged](https://github.com/AppImage/appimaged) repo?

**Comment by TheAssassin** [comment]
I am going to perform the migration sometime in the next weeks. At the moment, I am working on some refactorings in the AppImageKit code, to improve libappimage. Once I'm done, the extraction should be fairly easy to do.

> Which wiki do we want to use? The one here or a new one in the AppImage/appimaged repo?

You once said you'd want to use the AppImageKit wiki for everything, so, I'd keep doing so. We need to improve that wiki anyway. I doubt we'll be able to use the unstructured GitHub wiki for a long time anyway. I'll be working on a _real_ docs system or wiki one day...

> Where do we want to handle isses? Here or in the AppImage/appimaged repo?

I would migrate the issues there, then. AppImageUpdate's issues are dealt with in AppImageUpdate's repository as well.

**Comment by probonopd** [comment]
> You once said you'd want to use the AppImageKit wiki for everything, so, I'd keep doing so. 

Agreed, I prefer to have everything in one place and not scattered around in multiple places.

> I'll be working on a real docs system or wiki one day...

The GitHub wiki has the great advantage that it is _easy_, does not need us to set up and maintain additional infrastructure, and everyone can participate. Compared to it every other solution would be more complicated imho (but that's a different topic not related to this issue).

**Comment by TheAssassin** [comment]
Well, just because it's easy to use doesn't mean it satisfies all our needs. We have so much information in the wiki that most people can't find easily, and a majority of the information is outdated. Also, there's _zero_ structure, all documents are on the same level.
So, even though GitHub provides it directly, that won't help us in getting some *good* documentation of AppImage and its ecosystem. And we really need to provide this asap, in order to help spread the word about AppImage.

Also, The docs I suggest will definitely be managed in a Git repository (put it on GitHub and everyone can contribute pretty much as easy as at the moment), and for rendering there's external services (even I could host it on my infrastructure without much effort). But yes, that's a topic for another day to discuss.

**Comment by probonopd** [comment]
> But yes, that's a topic for another day to discuss.

Agree. Note to self (for _that_ day): Wiki != "structured documentation"

**Comment by TheAssassin** [comment]
> Note to self (for that day): Wiki != "structured documentation"

I tend to disagree. Documentation and Wiki are similar concepts. A wiki is just adding a web editor and some user system to the concept. But they don't need to lack structure.

[DokuWiki](https://www.dokuwiki.org/dokuwiki) (one of my favorite systems) for example supports a hierarchical layout of pages. See [this template](https://www.dokuwiki.org/template:bootstrap3) for example: `template` is the page's "directory" (filesystem terminology, DokuWiki calls it a "namespace"). You can even configure it to use slashes instead of colons for namespacing.

My point is: The GitHub wiki engine [Gollum](https://github.com/gollum/gollum) is perfectly suited for small wikis. But it's quite limited, and doesn't scale well. See the [wiki page "Known limitations"](https://github.com/gollum/gollum/wiki/Known-limitations):

> ### MISCELLANEOUS
>
>...
>
> 2. Pages can link/include one another with filenames but there is only a single namespace for pages, so all page filenames should be globally unique.

**Comment by probonopd** [comment]
It was really meant as a 

> Note to self (for that day)

**Comment by KurtPfeifle** [comment]
>> You mean just like the split of probonopd/linuxdeployqt from the rest of appimage/$stuff on Github? ￼
>>
> There's a bunch of reasons to do this.

Which ones? I'm probably too stupid to find even one.

There are more reasons to put it into the appimage/$stuff realm:

* It regularly mentioned and recommended on IRC when it comes to building AppImages.
* It is quite often mentioned in the AppImage wikis.
* Users get likewise confused and *"have difficulties to understand where to find which application"*

> Also, linuxdeployqt is not linked to any AppImage code. It uses appimagetool via subprocesses.

The fact that it isn't linked to any AppImage code isn't such a reason. Admittedly, the fact that it uses appimagetool via subprocesses in itself isn't one either -- but the fact that it seems to be promoted as one core tool to generated sane AppDirs (and hence, AppImages) is one.

**Comment by TheAssassin** [comment]
WIP in #780. Unfortunately I have to remove appimaged from AppImageKit first before I am able to publish appimaged in its new location. This is due to a CMake target naming conflict (having an appimaged target in both AppImageKit and appimaged's new repository). But I will finish the other Git repository and push it as soon as possible after merging #780.

**Comment by TheAssassin** [comment]
appimaged can now be found here: https://github.com/AppImage/appimaged/

I changed the AppImageKit README already. Please change the links to appimaged's page if you find outdated ones.
