### ISSUE TITLE
`--appimage-extract` recently stopped to work reliably

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#659]
I noticed that recently the *`--appimage-extract`* parameter stopped to work reliably for an AppImage I'm building from time to time for testing purposes.

Here are two (only temporarily available) versions of the AppImage:

*  **No longer working:** https://transfer.sh/cbnt9/appimagekit-toolbox-continuous-103-20180215-git.d553c1c-x86_64.AppImage (***Travis build no. 103*** from last night)
* **Still working:** https://transfer.sh/DoUaM/appimagekit-toolbox-continuous-102-20180210-git.6e7bff6-x86_64.AppImage (***Travis build no. 102*** from 5 days ago)

For build 103 with *`--appimage-extract`* I only get 2 files in *`squashfs/usr/bin/`*. When I do *`"--appimage-mount"`* or run *`"appimagetool -l [...] | grep usr/bin/"`* I can count 34 different files in there.

For build 102 this problem isn't there.

Another problem I noticed when I run these AppImages with parameter *`--scriptrun selftests.sh`*:

* Build 102 works as expected:

    ```
     ================================
        Running check_versions:
     ================================
              appimaged :  appimaged, continuous build (commit continuous-4-g06f10fa), build 1452 built on 2018-02-10 10:23:13 UTC
         AppImageUpdate :  AppImageUpdate version 1-alpha (commit 6e634ca), build 195 built on 2018-02-08 22:36:06 UTC
     appimageupdatetool :  appimageupdatetool version 1-alpha (commit 6e634ca), build 195 built on 2018-02-08 22:36:06 UTC
           appimagetool :  appimagetool, continuous build (commit continuous-4-g06f10fa), build 1452 built on 2018-02-10 10:23:13 UTC
          linuxdeployqt :  linuxdeployqt 4 (commit e915ad0), build 485 built on 2018-02-10 11:35:15 UTC
                 zsync2 :  zsync2 version 2.0.0-alpha-1 (commit 781a47f), build 109 built on 2018-01-26 07:08:11 UTC
             zsyncmake2 :  Flag could not be matched: version
   appimagekit-toolbox :  appimagekit-toolbox, version 1-alpha (commit 6e7bff6), build 102 on Sat Feb 10 20:37:40 UTC 2018

    ```

* For Build 103 I get this output:

    ```
     ================================
        Running check_versions:
     ================================
              appimaged :  appimaged, continuous build (commit continuous-4-g06f10fa), build 1452 built on 2018-02-10 10:23:13 UTC
         AppImageUpdate :  AppImageUpdate version 1-alpha (commit 012801f), build 208 built on 2018-02-15 21:55:43 UTC
      AppImageUpdate-Qt :  /tmp/.mount_appimaEWUWDq/usr/bin/AppImageUpdate-Qt: error while loading shared libraries: /tmp/.mount_AppImaqyqK5T/usr/bin/../lib/libQt5Core.so.5: cannot read file data: Error 103
     appimageupdatetool :  ./usr/share/tests/check_versions: line 10: ./AppRun: Transport endpoint is not connected
           appimagetool :  ./usr/share/tests/check_versions: line 10: ./AppRun: Transport endpoint is not connected
          linuxdeployqt :  ./usr/share/tests/check_versions: line 10: ./AppRun: Transport endpoint is not connected
                 zsync2 :  ./usr/share/tests/check_versions: line 10: ./AppRun: Transport endpoint is not connected
             zsyncmake2 :  ./usr/share/tests/check_versions: line 10: ./AppRun: Transport endpoint is not connected
   appimagekit-toolbox :  ./usr/share/tests/check_versions: line 10: ./AppRun: Transport endpoint is not connected

    bash: ./usr/share/tests/check_offsets: Transport endpoint is not connected
    bash: ./usr/share/tests/check_appimageversions: Transport endpoint is not connected
    bash: ./usr/share/tests/check_updateinfo: Transport endpoint is not connected
    bash: ./usr/share/tests/check_updatedescribe: Transport endpoint is not connected
    bash: ./usr/share/tests/check_help: Transport endpoint is not connected
    bash: ./usr/share/tests/check_appimagehelp: Transport endpoint is not connected
    bash: ./usr/share/tests/check_lists: Transport endpoint is not connected
```

**Comment by TheAssassin** [comment]
```
> ./appimagekit-toolbox-continuous-102-20180210-git.6e7bff6-x86_64.AppImage --appimage-version
Version: continuous-4-g06f10fa
> ./appimagekit-toolbox-continuous-103-20180215-git.d553c1c-x86_64.AppImage --appimage-version
Version: continuous-4-g06f10fa
```

Same runtime in both AppImages. Makes sense, as the last release has been published 6 days ago.
Extraction works fine on my computer. Did you try it on another computer and check whether the issue persists? Seems like a "doesn't work for me" (opposite of "works for me") situation.

"Transport endpoint is not connected" looks like a FUSE issue I know it [in relation to SSHFS](https://stackoverflow.com/questions/24966676/transport-endpoint-is-not-connected), when a connection is interrupted (when the internet connection is lost for instance). Could also be a temporary hiccup. The list of potential causes is long.

I can assure you it's not an issue in AppImageKit (neither appimagetool nor the runtime).

I'd suggest you to reboot your computer in order to reset FUSE. Maybe it's also that you have too many AppImages running or something like that (i.e., have too many FUSE endpoints running in parallel, might exceed some limit).

I would say we can close this issue as it's not an AppImage issue.

**Comment by KurtPfeifle** [comment]
Thanks for looking into this.

I've arrived at build no. 105 now and the issue is gone. Will look later what the exact differences were (other than having included the new AppImage for *AppImageUpdate-Qt* into it since build 103).

**Comment by TheAssassin** [comment]
JFYI: Please beware AppImageUpdate-Qt might be removed in the future.

**Comment by KurtPfeifle** [comment]
@TheAssassin:

> *"[...] beware AppImageUpdate-Qt might be removed in the future."*

Thanks for the hint.

If it happens, I'll notice it and adapt my meta-AppImage accordingly.
