### ISSUE TITLE
Show the version of the application

### ISSUE THREAD

**Issue by boudewijnrempt** [AppImage/AppImageKit#662]
We got this report from someone who has appimaged and lots of different krita appimages: https://twitter.com/AdmiralTofu/status/965374714448351233 , and have https://bugs.kde.org/show_bug.cgi?id=390624 . It would be good to be able to show the version of the application in that dialog.

Maybe something like "if there is an X-AppImageKit-Version=xxx entry in Desktop file, append it to the app name"

**Comment by TheAssassin** [comment]
I know the problem, and I'd like to have such a feature, too. It shouldn't be too hard to implement this, we read the Desktop file already anyway.

**Comment by probonopd** [comment]
This is what appimaged does if there is an `X-AppImage-Version=` eky in the desktop file:

![versions](https://user-images.githubusercontent.com/2480569/48967494-23a8b200-efd9-11e8-8378-228e2048bbea.png)

Can we close this @boudewijnrempt?

(Larger story: https://github.com/AppImage/appimaged/issues/30)

**Comment by TheAssassin** [comment]
`X-AppImage-Version` is the way to go.

**Comment by probonopd** [comment]
@boudewijnrempt the desktop file in `krita-4.2.0-preview-x86_64.appimage` currently has `X-Krita-Version=28` when it should have `X-AppImage-Version=4.2.0-preview` for this to work.

(The XDG standards should really specify an official way to communicate application versions, without the need for `X-...`, see the [larger story](https://github.com/AppImage/appimaged/issues/30)).
