### ISSUE TITLE
munmap() calls missing in getsection.c

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#669]
In `getsection.c`, a couple of `mmap()` calls are made. The file descriptors which are mapped are properly closed, but the memory is never unmapped. This means they're not cleaned up properly.

We should add the corresponding `munmap()` calls, and while we're at it look for more `mmap()` calls which aren't cleaned up properly either.

**Comment by probonopd** [comment]
Thank you for noticing this.
