### ISSUE TITLE
[desktopintegration] Not all windows grouped correctly in docks

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#68]
Not all windows grouped correctly in docks, e.g., in Elementary OS or Unity with Krita when Krita is launched from an icon that is "pinned" into the dock.

Possibly setting `StartupWMClass=` in the `.desktop` file helps. Use `xprop WM_CLASS` and click on the window in question to find out the value to be used.

**Comment by TheAssassin** [comment]
Is this still an issue after more than a year in Elementary OS?

**Comment by probonopd** [comment]
I think that setting `StartupWMClass=` in the `.desktop` file helped in my cases. Use `xprop WM_CLASS` and click on the window in question to find out the value to be used.
