### ISSUE TITLE
[website] Collection of quotes

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#689]
> The AppImage thing won me over because I don't have to do anything

Matt Heartley, Freedom Penguin

https://youtu.be/ZE2Dcr9QD10?t=51m48s

**Comment by probonopd** [comment]
> I'm more and more in love with AppImages all the time

Bryan Lunduke, The Lunduke Show

https://youtu.be/ZE2Dcr9QD10?t=52m28s

**Comment by skrzyp** [comment]
Both videos are "private" now.

**Comment by TheAssassin** [comment]
I guess we can close this then.

**Comment by probonopd** [comment]
Argh. Why is @BryanLunduke apparently taking his YouTube videos private?

Maybe we can link to the equivalents on LBRY (which is cool btw, and has an AppImage client).

**Comment by TheAssassin** [comment]
None of these videos have ever been linked to. Nothing to do here.

**Comment by probonopd** [comment]
The idea was to put them into the testimonials section (once we have some time to do it)...
