### ISSUE TITLE
testappimage: no free loop device

### ISSUE THREAD

**Issue by shoogle** [AppImage/AppImageKit#71]
When I use testappimage on Ubuntu it works great the first few times, but then it fails after about the 4th or 5th time with the message "mount: could not find any free loop device". It seems that something doesn't get unmounted properly somewhere in the script, so the system eventually runs out of loop devices.

I have been unable to find a solution to this, but I have submitted a workaround in the form of <a href="https://github.com/probonopd/AppImageKit/pull/70#issuecomment-172215798">PR #70</a> which, among other things, allows the same chroot to be used for multiple tests.

**Comment by probonopd** [comment]
By default the kernel supports only a low number of loop-mounts. I am using `max_loop=256` as a kernel argument and never ran into any those issues anymore. A cleaner solution would of course be preferred. Check `mount` to see if extraneous loop-mounts are still mounted.

**Comment by shoogle** [comment]
I see. If there's no way to tell the system "I'm done using this loop-mount, please let me use another" then raising the maximum number is the way to go. That would appear to make my '-p' option redundant on home systems (if people are willing to play with kernel arguments), but it still might be handy on remote build systems where you can't make changes to the kernel.

**Comment by probonopd** [comment]
I wasn't aware that loop devices don't get free'd up automatically. I have been using `max_loop=256` simply to have more loop devices _at the same time_.

**Comment by probonopd** [comment]
Check `/dev/loop-control`, http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=770fe30a46a12b6fb6b63fbe1737654d28e84844
