### ISSUE TITLE
appimaged fails to move icon

### ISSUE THREAD

**Issue by overheadhunter** [AppImage/AppImageKit#732]
Investigating why my icon didn't show up in the desktop environment, I ran appimaged with the `--verbose` flag and noticed it didn't succeed to move the icon (which it previously extracted to `/tmp`) to the target directory `~/.local/share/icons/hicolor/512x512/apps`.

I got a "no such file or directory" error, because the `apps` dir inside `~/.local/share/icons/hicolor/512x512` did not exist. After manually creating this directory, everything works as expected.

Using appimaged version: continuous-1-g6f3138f on Ubuntu 18.04 nightly minimal.

**Comment by TheAssassin** [comment]
Can you provide a link to the AppImage you were testing this with?

**Comment by overheadhunter** [comment]
Sure: [cryptomator-continuous-amd64.AppImage](https://bintray.com/cryptomator/cryptomator/download_file?file_path=cryptomator-continuous-amd64.AppImage). It might update any time, though.

**Comment by TheAssassin** [comment]
@overheadhunter general tip for bug reports: when asked to provide a link, you should make sure it's a link to the exact same AppImage.

Anyway, I uploaded it to transfer.sh to archive it for this bug report: https://transfer.sh/hRA47/cryptomator-continuous-amd64.AppImage

Inspecting your AppImage, I noticed the lack of `usr/share/icons`. appimaged copies these locations recursively to `~/.local/share/...`. When there's icons in there, they'll get deployed. But appimaged does not have the capabilities to analyze the "root icon", and therefore can't auto-deploy it to the right directory. You will have to create `AppDir/usr/share/icons/hicolor/512x512/` and put your icon in there, then appimaged can deploy it properly.

**Comment by overheadhunter** [comment]
> you should make sure it's a link to the exact same AppImage

Sorry 🙈 We don't have any stable release yet, as we just started experimenting with AppImages. It is still the same that I used before - I wrote that hint about the updates to make sure, people stumbling over this issue in a month don't rely on it.

> You will have to create AppDir/usr/share/icons/hicolor/512x512/ and put your icon in there, then appimaged can deploy it properly.

Good to know, thank you! :-) So this is also the correct location if I want to register any mime type associations, I suppose?

Can you point me to a reference directory structure? In the wiki I only found some minimal skeletons.

---

Anyhow: In my opinion appimaged should not rely on this directory to exist during the aforementioned move operation, since `AppDir/usr/share/icons/hicolor/512x512/apps` is not a mandatory directory.

**Comment by TheAssassin** [comment]
@overheadhunter appimaged does not register any MIME types, at least not yet.

We know about the lack of proper documentation. If something isn't automated properly, it should at least be documented properly, right? We are going to start a real documentation of our tools later this year.

**Comment by overheadhunter** [comment]
Looking forward to it! I might be contributing a guide on creating AppImages from self-contained Java applications built with [javapackager](https://docs.oracle.com/javase/9/tools/javapackager.htm).

Feel free to close this issue, if you keep track of lacking documentation somewhere else. I consider my problem solved for now.

**Comment by TheAssassin** [comment]
@overheadhunter you can put it into our wiki next to the other "Bundling [...]" pages.

**Comment by probonopd** [comment]
Thanks @overheadhunter - I have added a section for it at https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps#option-1-using-jlink
