### ISSUE TITLE
--appimage-extract and other runtime options don't work when using external runtime

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#743]
I noticed that some runtime functionalities like `--appimage-extract` don't work as intended with an external runtime.

The use case of using a custom, separate runtime to run existing AppImages isn't very well tested and needs to be improved. Otherwise, users of [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) cannot extract AppImages.

**Comment by probonopd** [comment]
Why does AppImageLauncher need an external runtime?

**Comment by TheAssassin** [comment]
@probonopd you should maybe bookmark this link: https://github.com/TheAssassin/AppImageLauncher/blob/master/src/main.cpp#L75-L80

**Comment by TheAssassin** [comment]
Going to work on this next.
