### ISSUE TITLE
Error when running appimaged

### ISSUE THREAD

**Issue by Silicomancer** [AppImage/AppImageKit#748]
I just downloaded `appimaged-x86_64.AppImage` and tried to run it on KDE Neon the very first time. This is what I get:

```
$ ./appimaged-x86_64.AppImage
appimaged: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_option_group_unref
```

Any ideas?

**Comment by TheAssassin** [comment]
@Silicomancer could you please check whether glib is installed? It is a runtime dependency, and one of the "base libs" the AppImage project considers installed everywhere already, hence it isn't bundled in the AppImage.

**Comment by Silicomancer** [comment]
Which package name would that be exactly? 
Is there a list in the web containing all runtime dependencies for AppImage?

**Comment by Silicomancer** [comment]
Yes, Neon is Ubuntu based. I just checked with apt and found the following package installed:
`libglib2.0-0/xenial-updates,now 2.48.2-0ubuntu1 amd64`

**Comment by TheAssassin** [comment]
I use Ubuntu Xenial myself, and never had any such issues. I even have the exactly same version of libglib installed. It must be an issue on your end...

Can you please call `sha256sum /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0`? Should look like this:
```
6b6d75caf92851f101e7898e1ebce5813c42b704d97a20c804f607cd80dfc495  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

**Comment by TheAssassin** [comment]
Please upload this exact file (if you don't know where to, try https://transfer.sh), and please tell us where you got this file.

**Comment by TheAssassin** [comment]
Nevermind, I found the issue.

The bug has been introduced in #745, which introduces bundling of glib for a very specific reason. Unfortunately, it happens that GLib's dependencies, mainly GObject, are not bundled.

I will fix this asap. Sorry for the inconvenience.

**Comment by Silicomancer** [comment]
Ok, happy you found it. Thanks for the fast and kind support!

**Comment by TheAssassin** [comment]
We're not done yet, but thanks for the kind words. I need you to test the AppImages built by the PR #749 later. I'll post a link here asap.

**Comment by TheAssassin** [comment]
Please try https://transfer.sh/AKHuv/appimaged-x86_64.AppImage. Freshly built on Travis CI.

**Comment by TheAssassin** [comment]
Tested it. It worked fine. Therefore merged the PR. Feel free to reopen this issue if you encounter the bug with the new official release.
