### ISSUE TITLE
AppRun fails to parse .desktop file with non-latin characters

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#75]
wget -q "https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob_plain/HEAD:/release/freedesktop/blender.desktop"

causes Segmentation fault when running AppRun

**Comment by Sod-Almighty** [comment]
I'll take a look

**Comment by probonopd** [comment]
Why?

**Comment by azubieta** [comment]
Sorry, I confused AppRun with appimaged.

**Comment by probonopd** [comment]
@Sod-Almighty still on it? :)

**Comment by TheAssassin** [comment]
We can close that as outdated.
