### ISSUE TITLE
Create and use IMPORTED targets for external dependencies

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#751]
The `UTILITY` targets that are created by `ExternalProject_Add` can't be linked to like other normal library targets, used by most other projects. This leads to issues when using AppImageKit as a submodule with other projects that define a `gtest` target as well.

To avoid conflicts, we need to check whether targets for the ones we want to create ourselves exist already. This can be done by `if(TARGET gtest)`, for example. We should add a `message(WARNING "Target XYZ exists, using it instead of building our own")` to inform the user about the fact we're re-using the existing target.

As a side effect, by creating _one_ proper `IMPORTED` target per library allows for removing all the boilerplate linking code we have in all our files. This allows us to replace large parts of our CMake scripts, and makes our code much nicer to read.

As this issue is blocking my further development, I am going to work on fixing this asap.

CC @azubieta

**Comment by azubieta** [comment]
Have you tried checking if gtest already exists before calling ExternalProject_Add ?

**Comment by TheAssassin** [comment]
@azubieta the problem is that CMake is, due to the order of dependencies, instructing the external project (which _has_ that check) to `target_link_libraries` the `ExternalProject` version, which breaks, as it's not a "normal" library target.

But yes, the same check will be put as a guard around our own library creation code. If e.g., `gtest` is available already, the existing target should be used, instead of hacking our own. It would totally be possible to work around duplications (by generating the library target name dynamically or other hacks), but it feels wrong to do so, and might lead to annoying bugs like `duplicate symbol` etc., which can be avoided totally by re-using existing libraries. And by adding proper messaging, we help users of libappimage to debug any collision issues.
