### ISSUE TITLE
appimaged: implement appimage_shall_not_be_integrated

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#754]
CC @probonopd 

appimaged should respect the new `X-AppImage-Integrate=false` key that has been implemented by #750.

**Comment by TheAssassin** [comment]
@probonopd I would still like to know whether you want this in appimaged or not. It's a small patch, but it changes the way appimaged works, therefore I ask you first.

**Comment by probonopd** [comment]
Yes, I'd like this in `appimaged`. Overall, I'd like `appimaged` and similar solutions to share as much code and behavior as possible. If we can't entirely merge them.

**Comment by TheAssassin** [comment]
Want to give this a try? It's a very small patch, and it'd provide you a first level view on our API design.

**Comment by probonopd** [comment]
I'd highly appreciate a PR @TheAssassin

**Comment by probonopd** [comment]
I'd highly appreciate a PR @TheAssassin

**Comment by TheAssassin** [comment]
Please don't expect me to do it anytime soon. I have tons of other things to do at the moment.

**Comment by TheAssassin** [comment]
Migrated to https://github.com/AppImage/appimaged/issues/20.
