### ISSUE TITLE
Build Error: XZ linking not working on multi-thread builds

### ISSUE THREAD

**Issue by azubieta** [AppImage/AppImageKit#757]
Building inside a ubuntu:bionic docker whit the following configuration which was already working until now.
Build configuration: https://github.com/nomad-desktop/nxos-third-party-build/tree/libappimage
see .travis.yml and build.sh files

Build log: https://travis-ci.org/nomad-desktop/nxos-third-party-build/builds/370692771#L3064

**Comment by TheAssassin** [comment]
@azubieta I've got some time today. Were you able to fix this issue yourself?

**Comment by azubieta** [comment]
Not yet, I suspect that it's a build order problem, at least according to my build logs.
squashfuse is being built before xz
I think that we are missing and `add_dependency` cmake instruction

**Comment by azubieta** [comment]
Confirmed, that was the error. I just removed the `-j2` from my build script and it moved forward.

**Comment by TheAssassin** [comment]
@azubieta @AIIX please check whether the changes in the PR fix the issue.

**Comment by Taz8du29** [comment]
[ 74%] Building C object src/CMakeFiles/appimagetool.dir/binreloc.c.o
    [ 75%] Building C object src/CMakeFiles/appimagetool.dir/elf.c.o
    [ 76%] Linking C executable appimagetool
    ../squashfuse-EXTERNAL-prefix/src/squashfuse-EXTERNAL/.lib /libsquashfuse.a(libsquashfuse_la-decompress.o): In function `sqfs_decompressor_zlib':
    ~/Source/cura/AppImageKit_tmp/build/squashfuse-EXTERNAL-prefix/src/squashfuse-EXTERNAL/decompress.c:42: undefined reference to `uncompress'
    collect2: error: ld returned 1 exit status
    src/CMakeFiles/appimagetool.dir/build.make:188: recipe for target 'src/appimagetool' failed
    make[2]: *** [src/appimagetool] Error 1
    CMakeFiles/Makefile2:1445: recipe for target 'src/CMakeFiles/appimagetool.dir/all' failed
    make[1]: *** [src/CMakeFiles/appimagetool.dir/all] Error 2
    Makefile:162: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by TheAssassin** [comment]
Should be fixed now.
