### ISSUE TITLE
Inaccuracy on Wiki page "Similar projects"

### ISSUE THREAD

**Issue by mwleeds** [AppImage/AppImageKit#760]
On [this](https://github.com/AppImage/AppImageKit/wiki/Similar-projects) wiki page it says Flatpak can't package Terminal CLI tools, which isn't true. For example, [here's one](https://flathub.org/apps/details/org.vim.Vim) on Flathub. I would recommend the text "Yes (with app ID aliases if you edit PATH)[[1](https://github.com/flatpak/flatpak/releases/tag/0.10.2)]".

**Comment by probonopd** [comment]
@mwleeds I think that https://github.com/flatpak/flatpak/issues/17 may still be a showstopper for "out of the box", at least for Live (=stateless) systems.

**Comment by mwleeds** [comment]
@probonopd it says CentOS 7 a few lines above that

**Comment by mwleeds** [comment]
@probonopd I'll download an ISO and try

**Comment by mwleeds** [comment]
I ran out of space trying to install a runtime (well technically it was a "read-only file system" error but I think no space was the root cause), so it's hard to say definitively, but presumably that wouldn't have happened if it wasn't a live system. Anyway the live system limitation is documented separately on that wiki page.

**Comment by probonopd** [comment]
Thanks for testing. Since all I ever run is Live systems (yes - I never install a system), it looks like I still cannot use it. But you are right, it is separately mentioned on the page.
