### ISSUE TITLE
appimaged floods stderr with underscores

### ISSUE THREAD

**Issue by mithrandi** [AppImage/AppImageKit#762]
When I start appimaged, it outputs a seemingly unlimited number of lines containing only `_________________________`; these end up in the journal when autostarted normally which is rather frustrating, although most of them do get collapsed fortunately.

My system info:

```
mithrandi@lorien ~> appimaged --version
appimaged, continuous build (commit 485198d), build 1697 built on 2018-04-26 18:10:12 UTC
mithrandi@lorien ~> lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux unstable (sid)
Release:        unstable
Codename:       sid
mithrandi@lorien ~> uname -a
Linux lorien 4.15.0-3-amd64 #1 SMP Debian 4.15.17-1 (2018-04-19) x86_64 GNU/Linux
```

Let me know if there's any extra debugging I can do or information I should provide.

**Comment by mithrandi** [comment]
Ah, I have tens of thousands of files in my Downloads directory, so that probably explains the volume of output. I think it would probably be better not to output "debug level" messages by default, or at least when not attached to a terminal.

**Comment by probonopd** [comment]
Should probably use https://linux.die.net/man/3/isatty and not output anything except errors if `isatty(STDOUT_FILENO) == 0`

**Comment by TheAssassin** [comment]
You could as well just use an environment variable. That way, systemd users could switch it on in the systemd settings as well.

**Comment by probonopd** [comment]
Like, only output debug messages, if the environment variable `$DEBUG` is not empty?

**Comment by TheAssassin** [comment]
Something like that, yes. That's a lot more explicit than some TTY checks.

**Comment by TheAssassin** [comment]
Migrated to https://github.com/AppImage/appimaged/issues/18.
