### ISSUE TITLE
Overwrite process name when using TARGET_APPIMAGE using setproctitle()

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#763]
It's a bit annoying to see the path to the runtime binary when using `$TARGET_APPIMAGE`. I think we should overwrite the process name that shows up in tools like `ps`, `htop` etc. with `prctl`'s `PR_SET_NAME`.

See http://man7.org/linux/man-pages/man2/prctl.2.html.

**Comment by TheAssassin** [comment]
How is that an argument against faking the runtime? The point is, at the moment, you can't see which AppImage is run by such a runtime. "Faking" the path in the process name would fix that, and allow users to see which processes are executed.

If you have an alternative to using a custom runtime and `$TARGET_APPIMAGE` for me, let me know! But be assured AppImageLauncher treats all AppImages types separately. Using an external runtime won't become an issue, as long as the AppImage spec won't suddenly change.

**Comment by probonopd** [comment]
All I am saying is that there may be a type-3 AppImage one day, and a runtime that only can run those. Just something to keep in mind.

**Comment by TheAssassin** [comment]
Sure. But applications which use this feature are aware of this problem. You can just check the AppImage type, and treat the different AppImages accordingly.
