### ISSUE TITLE
How to provide plug-ins for programs that are distributed as AppImages

### ISSUE THREAD

**Issue by aferrero2707** [AppImage/AppImageKit#772]
At least in the GIMP AppImage case, I am facing the problem of how to provide compatible plug-ins in the for of shared object files. Such plug-ins need to be compiled with the same environment (base system, compiler and libraries) as the AppImage itself, otherwise they will likely give rise to library conflicts.

At the moment I see two solutions:
1. bundle all possible plugins in the main AppImage package
2. provide the GIMP AppImage build environment as a Docker container, so that binary plug-ins can be separately compiled and still be compatible with the main executable

I tend to prefer option 2. because it is much more flexible.

Did anyone else already faced and solved a similar problem?
Notice that this issue seems not to be related to AppImages, but also affect other bundling mechanisms like Flatpak...

**Comment by probonopd** [comment]
> Notice that this issue seems not to be related to AppImages, but also affect other bundling mechanisms like Flatpak...

Agree that #2 seems like a good idea, if plugins get loaded from somewhere within `$HOME`.

**Comment by TheAssassin** [comment]
I'd bundle a set of plugins you consider useful, and load the rest from the home directory.

**Comment by aferrero2707** [comment]
@TheAssassin the point is exactly how to provide the plug-ins that are not bundled, but installed separately in the home directory.
They need to be compiled with the same environment as the GIMP executable in the AppImage, and one should provide an "as easy as possible" build procedure for third-party providers.
The idea of the Docker container is the best I could imagine so far...

**Comment by TheAssassin** [comment]
@aferrero2707 I see.

It highly depends on how the plugin system is designed. Most software that uses shared libraries for plugins define a well designed interface, with API/ABI versioning, etc., so that depending on the API version they use, the library can be loaded without issues by the main software. I assume GIMP plugins work like that. Other software may not take that much care when building plugin systems, or simply work differently.

In my opinion, there is no definitive answer to this question. One can only give a definite reply for a specific program.

Just for the record: I didn't have an actual look at GIMP's plugin system. The above are just assumptions .

**Comment by probonopd** [comment]
As a general rule of thumb I'd say proceed with the plugins like for the GIMP for macOS (a.k.a. "OS X") download.

**Comment by probonopd** [comment]
Is this a sufficient answer so that we can close this @aferrero2707?

**Comment by aferrero2707** [comment]
I am currently putting together a sort of framework for packaging plug-ins to be used with the GIMP appimage, so I close this for the moment and I will eventually re-open it to announce the code when ready.

Thanks for the suggestions!

**Comment by probonopd** [comment]
Thanks @aferrero2707 but please keep in mind our "one app = one file" philosophy.

**Comment by aferrero2707** [comment]
> please keep in mind our "one app = one file" philosophy

How do you propose to apply this to applications that support external plug-ins, like GIMP?

In the GIMP case, from one side the developers are requesting a package that only provides the main application, and on the other it is not really practical to bundle all existing plug-ins...

**Comment by probonopd** [comment]
Applications can always load additional plug-ins from somewhere inside the user's `$HOME`.

**Comment by probonopd** [comment]
> So, it seems to me that the packager of the AppImage should also provide a suitable build environment for external plug-ins. What do you think? 

Yes, that sounds reasonable. Preferably on Docker, I'd guess.

> Would there be an easier solution?

Unless the GIMP gets a stable interface that does not require plug-ins to be compiled with the same toolchain as the main application, I can't think of one.
