### ISSUE TITLE
Dependency issues since #770

### ISSUE THREAD

**Issue by Optiligence** [AppImage/AppImageKit#773]
>appimagetool: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

while running `appimagetool . --verbose --no-appstream`

**Comment by TheAssassin** [comment]
You should just install the missing library. The package is `libselinux1`.

**Comment by Optiligence** [comment]
where is this dependency mentioned?

i thought the point was that this is rather freestanding

and as far as i can tell this only changed a few days ago

**Comment by Optiligence** [comment]
what log are you thinking of? 

you can have the travis links
>appimagetool, continuous build (commit 1490dc4), build 1706 built on 2018-05-02 20:44:01 UTC

https://travis-ci.org/knossos-project/knossos/builds/375255665
worked, 2.5 days ago

https://travis-ci.org/knossos-project/knossos/builds/375981033
didn’t, 5.5h ago

**Comment by TheAssassin** [comment]
I see. The library is requested by `libgio-2.0.so.0` as a direct link dependency. https://github.com/AppImage/AppImages/blob/master/excludelist#L95 suggests it should not be excluded. Therefore, we must have made a change that causes this to fail.

As we recently changed some code in the build system (resp. #770), this bug might have been introduced there. I'll re-check the code, and will try to fix the issues.

**Comment by Optiligence** [comment]
ok, this isn’t really the travis Ubuntu, but an Arch Linux docker image

**Comment by TheAssassin** [comment]
... okay well that's a completely different situation. Arch Linux is the least distribution for bundling AppImages anyway, unless you know what you're doing. Your AppImage will not be compatible with any distro except for Arch.

I just checked the old binaries, and it seems that #770 introduced a link dependency on `libgio`, which wasn't there before (although we copy the library, which is actually unnecessary). I'll fix the issue ASAP.

**Comment by TheAssassin** [comment]
Confirming that the issue has been introduced by #770. I checked the linker command line:

```
gcc [...] -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz
```

**Comment by Optiligence** [comment]
>Arch Linux is the least distribution for bundling AppImages anyway, unless you know what you're doing. Your AppImage will not be compatible with any distro except for Arch.

we know. we patch it together by deleting some too new libs which we expect to be present and test it on distros where we want it to work
it’s just a workaround for not having to drag around and babysit outdated build boxes (we tried that before)

sorry i missed the Arch part first and thx for fixing

**Comment by TheAssassin** [comment]
@Optiligence you're welcome. If you encounter further issues, please reopen this issue or open new ones.
