### ISSUE TITLE
Migrate to a GitHub Organization

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#78]
Should we migrate this project to https://github.com/AppImage?
Everywhere you have a migrated repository cloned needs to run this simple command: `git remote set-url origin git@github.com:ORGANIZATION/REPO.git`

**Comment by hideout** [comment]
hey!

i think thats a good point we should migrate the project to
https://github.com/AppImage
that was on my todo list too.

and it think its not a big deal to migrate it.
Anybody has a vote against it?

cheers

2016-01-23 13:21 GMT+01:00 probonopd <notifications@github.com>:

**Comment by chrisnharvey** [comment]
Sounds like a good idea.

Would this be for SystemImageKit too?

If so, should the organisation be called something other than AppImage?

**Comment by RazZziel** [comment]
AppImage sounds fine to me :+1:

**Comment by hideout** [comment]
to me too! [image: :+1:] ;) #Appimage

2016-01-23 14:46 GMT+01:00 Ismael Barros² <notifications@github.com>:

**Comment by shoogle** [comment]
Or maybe AppImages (with an "s")?

**Comment by probonopd** [comment]
AppImage is the overall name of the project, AppImageKit is the toolkit, the format is called "AppImage" and the files are "AppImages"...

**Comment by kskarthik** [comment]
Let's move @probonopd I could see lot of volunteers involvement in this project. Organization is a better place. I too like the "AppImage" name for the org :+1:

**Comment by probonopd** [comment]
Yes. Only I'm a bit afraid that links might break. Let's not do it during a traffic spike (as we have right now).

**Comment by kskarthik** [comment]
Okay, Do it later. Also migration needs some time. Lot of change to wiki, website, etc. So, it's not a quick job..

**Comment by RazZziel** [comment]
Is it a good time now to move to an organization? Looks like GitHub even has [repository redirects](https://github.com/blog/1508-repository-redirects-are-here) to avoid us some pain on these cases.

Git clone/pull/push get redirected, git pages don't but that shouldn't be an issue; what **could** be an issue and is not 100% clearly specified is wget access to download scripts and releases, which are used in some external scripts, but [here](https://help.github.com/articles/transferring-a-repository/) they say

> **In addition to redirecting web traffic**, all git clone, git fetch, or git push operations targeting the previous location will continue to function _blah blah blah_

so it **should** be a painless migration.

**Comment by probonopd** [comment]
Agree that we should do it at some point, I'm just a bit undecided when to do it since I have never done such a migration in a live project that has 900 stars, some high-profile actual users and is just about to getting traction... probably the answer is "the sooner the better", I know. But in any case, let's do it with some planning (prior announcement with enough time and let's make sure I am around a PC at that weekend).

**Comment by shoogle** [comment]
I don't anticipate that this will cause you to lose any users. After all, the kit is only really used by developers at the moment, and developers are more than capable of following a link to a new page, especially if the redirect is automatic.

If I were you I'd go ahead and reserve the AppImage organisation name (if you haven't already) to stop someone else using it, and add a notice that a move is about to take place to the description and top-level README for this repo. No need to give more than a month's notice.

**Comment by brauliobo** [comment]
Github have this migration (personal to organization) so nothing breaks. See settings

**Comment by probonopd** [comment]
Also should at some point move historic components out of this repo and reduce repo size, https://github.com/CodeBlastr/SYSTEM/wiki/Git-Reduce-Repo-Size

**Comment by probonopd** [comment]
As a first step, imported https://github.com/probonopd/appimagetool into this repository like this:

```
git clone https://github.com/probonopd/AppImageKit.git
cd AppImageKit/
git remote add appimagetool https://github.com/probonopd/appimagetool.git
git fetch appimagetool
git branch -r
git checkout -b appimagetool/master
git push --set-upstream origin appimagetool/master
```

**Comment by probonopd** [comment]
As next steps, I plan to:

- [ ] Move this repository to the AppImage organization - will it break Travis CI builds? Do I have to set the secret variables (e.g., for Bintray) again? Will it break anything for downstreams?
- [ ] Delete the old `master` branch, its content is now in `stable/v1.0` - Will it break anything for downstreams
- [ ] Create a new `master` branch based on the current `appimagetool/master` branch

**Comment by probonopd** [comment]
Also see #103

**Comment by kskarthik** [comment]
Status?

**Comment by probonopd** [comment]
I am afraid of breaking things for users...

**Comment by hideout** [comment]
good point

2017-03-12 19:18 GMT+01:00 probonopd <notifications@github.com>:

**Comment by chrisnharvey** [comment]
I'm almost certain that Github well setup redirects from the old repo to the new one when migrating to an organisation.


Maybe we could test this with a test repo to see if everything still works after migrating to an organisation?




Get Outlook for Android









On Sun, Mar 12, 2017 at 6:48 PM +0000, "Ferdinand" <notifications@github.com> wrote:










good point



2017-03-12 19:18 GMT+01:00 probonopd <notifications@github.com>:

**Comment by probonopd** [comment]
Yes, what about Travis CI integrations, the secret tokens I have set up as environment variables in Travis CI, etc.

**Comment by TheAssassin** [comment]
GitHub would set up redirections, and after hitting `[sync]` in your Travis profile, everything should be updated.
I would suggest moving AppImageKit, AppImages and related work to the organisation.

**Comment by probonopd** [comment]
Needs to be updated:
* webhook
* yml

Unclear:
* Variables exported in the Travis CI settings

**Comment by TheAssassin** [comment]
Shouldn't bee too much work to to backup (copy-paste) them and put them back in place if they should be missing.
But anyway, I'd suggest test forking the AppImage repository, and executing the transfer there to get a real life experience.

**Comment by TheAssassin** [comment]
Move has been performed!

**Comment by TheAssassin** [comment]
Reopening as not all the steps from https://github.com/AppImage/AppImageKit/issues/78#issuecomment-258615898 have been implemented yet.

**Comment by azubieta** [comment]
@probonopd I guess that we can close this issue already.

**Comment by probonopd** [comment]
Yes, we have done this a long time ago. Thanks everyone!
