### ISSUE TITLE
Ship libappimage with an .a file

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#785]
Ship libappimage with an `.a` file so that we can link it statically if needed.
`libappimageupdate.a` already exists.

**Comment by TheAssassin** [comment]
I don't really want to maintain e.g., a pkg-config file, listing all the dependencies... with shared libraries, this works fine. Also, with the shared library, we can embed our own versions of squashfuse etc. (which we patch) in the library. With static linking, we'd have to ship these static archives as well.

Please list a few use cases in which a static library would be advantageous.

**Comment by probonopd** [comment]
User story: "I want to ship a GNOME Software plugin that has no weird dependencies on software that is not packaged in all distros". Prio not super high at the moment, as I need to write the plugin first ;-)

**Comment by TheAssassin** [comment]
@probonopd so, your use case is that you need to link everything statically so the plugin can be shipped as a shared object? Your user story isn't really providing any details on what you want to do _technically_. I mean, you can always ship a shared object with another one, i.e., ship the plugin with the libappimageupdate library...

**Comment by probonopd** [comment]
The plugin itself is a shared object, but running ldd on it should not show dependencies on anything that is not e.g., in Ubuntu or Fedora by default. I think that would make deployment easier. But as I said, it's not that urgent atm.

**Comment by TheAssassin** [comment]
We already build a static library. Consider using CMake in your project, use a submodule to include AppImageKit, use it via `add_subdirectory(...)`, and then link your binary to `libappimage_static`. We don't need to install this symbol, though. And when using the library this way, CMake will take care of the dependency management, and will link your binary to all the other static libraries.

**Comment by TheAssassin** [comment]
Closing as wontfix. We already build a static library, which can be used through CMake. We don't need to ship it in our CPack packages.
