### ISSUE TITLE
Integration of AppImage fails: Invalid cross-device link

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#790]
While trying to integrate the latest Cura AppImage (3.3.0), I found a bug in the libappimage integration code in `archive_copy_icons_recursively_to_destination()`, where libappimage tries to read the data from the ISO9660 image using libarchive, and then create the file in the corresponding location and write the data using `fwrite()`.

We need to make sure that we don't just "copy" hardlinks but either create the files normally, or create the hardlink using the right API, but not with `fwrite()`. Alternatively, we need to touch the type 1 code and make sure that while creating the ISO9660 image all hardlinks are converted to normal files.

Someone should tell Cura to finally switch to type 2... https://github.com/Ultimaker/cura-build/issues/136

CC @azubieta

**Comment by TheAssassin** [comment]
Found the issue: the existing `fwrite()` call's arguments were passed in the wrong order. When calling `fwrite()`, it returns the number of chunks with a given size that were written successfully. This value can be compared to the expected size, and if it is not equal, an error must have occurred. In this case, the size and number of elements arguments were in the wrong order, causing the error check to yield false positives. By fixing the order, the error check works as expected.

**Comment by probonopd** [comment]
Thank you.
