### ISSUE TITLE
how is ././ different from plain old ./

### ISSUE THREAD

**Issue by bdantas** [AppImage/AppImageKit#793]
I've been hacking on GNU/Linux for a long time, so obviously I'm familiar with `./` to mean "here" and I use it often. However, in the AppImage how-to it is recommended to use `././` instead of `./` (see the _No hard-coded paths_ section [here](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages)).

Please, what's the difference between `././` and the more traditional `./`? Why wouldn't a simple `./` suffice when patching binaries to eliminate hard-coded paths?

**Comment by TheAssassin** [comment]
It doesn't suggest you to use `././` other than for binary patching. In many existing binaries, paths are harcoded with the prefix `/usr`. When trying to replace those paths with a relative one, the new path and the old path need to have the same length. Therefore, it is possible to replace `/usr/abc` with `././/abc` for instance. If your AppRun then changes the working directory to `$APPDIR/usr`, the relative paths can be resolved, and it should work (`$APPDIR` is the mounted AppImage's location).

Please don't hesitate to ask further questions.

**Comment by bdantas** [comment]
Thank you. Why is it important that the new path and old path have the same length?

**Comment by TheAssassin** [comment]
Well, let's assume they're not.

Best case: replacement is shorter than original string -> path would be broken (example: `/usr/test` -> replacing `/usr` with `./` -> `./sr/test`)

Worst case: replacement is longer than the original string -> at least path is broken, maybe even the binary, as the new string would exceed the old string's place, therefore replacing parts of the binary code as well (example: `/usr` replace with `./whatever` -> boom)

**Comment by bdantas** [comment]
Aha! I got it. Thank you for the clear explanation. I've been building AppImages for a long time and never quite grasped this. A long-time mystery solved :)

**Comment by TheAssassin** [comment]
If you want to help others in the same situation, please consider sending a PR/editing the wiki to fix our docs.

**Comment by probonopd** [comment]
> I've been manually building AppImages (for myself and family/friends) for a long time

Hi @bdantas have you thought about contacting the authors of those applications and suggesting them to offer official AppImages for download? Maybe you can even contribute your AppImage packaging work to them. Would be highly appreciated. Thanks!

**Comment by bdantas** [comment]
> have you thought about contacting the authors of those applications and suggesting them to offer official AppImages for download?

Absolutely! I've done so for all the applications I've needed AppImages for (lftp, mpv, firefox). Closest I came to getting the authors on board was lftp. Other AppImages I create are custom.

> Best case: replacement is shorter than original string -> path would be broken (example: /usr/test -> replacing /usr with ./ -> ./sr/test)

I tried `sed -i 's_/usr_./_g' somebinary` and there were no extraneous characters after patching: using `strings | grep` proves that the binary started with `/usr/bin/foo` and ended up with `.//bin/foo`, not `./sr/bin/foo`. (This is not surprising, `sed`'s `s` command deletes all of the matched pattern before substituting.)

> Worst case: replacement is longer than the original string -> at least path is broken, maybe even the binary, as the new string would exceed the old string's place, therefore replacing parts of the binary code as well (example: /usr replace with ./whatever -> boom)

I tried `sed -i 's_/usr_/whateverwhateverwhatever_g' somebinary` and, as expected, the filesize of the binary increased to accommodate the extra characters, suggesting that none of the binary data needed to be overwritten.

Can you pitch in, Simon? I've wondered about why the binary is patched with `././` instead of `./` for several years at this point, and am no closer to understanding it.

**Comment by bdantas** [comment]
I can confirm that patching with `sed -i 's_/usr_././_g' somebinary` creates a working AppImage, while patching same binary with `sed -i 's_/usr_._g' somebinary` creates an AppImage that segfaults. Why, oh why?

**Comment by TheAssassin** [comment]
> Best case: replacement is shorter than original string -> path would be broken (example: /usr/test -> replacing /usr with ./ -> ./sr/test)
> 
> Worst case: replacement is longer than the original string -> at least path is broken, maybe even the binary, as the new string would exceed the old string's place, therefore replacing parts of the binary code as well (example: /usr replace with ./whatever -> boom)

**Comment by probonopd** [comment]
Search for the string `/usr` and replace it with `././`.

**Comment by bdantas** [comment]
Thank you, probonopd. Yes, I've discovered that if the strings are not the same size then the AppImage crashes. I started this thread because I'm trying to understand why the crash happens. TheAssasin says that replacing `/usr` with a shorter string breaks the path by leaving behind extraneous characters, but `sed` does not leave behind extraneous characters (see my long post above). Replacing with a shorter string must be causing a crash for some other reason.

**Comment by TheAssassin** [comment]
@bdantas build the binary with debug information and use a debugger. You can never say how the replacement is performed. It is only an assumption that only the path is broken. Also the app might segfault just because of that as well. There's no "rule of thumb" that can tell you what side effects this hack has.

**Comment by bdantas** [comment]
@TheAssassin Thanks, I'll try that when I get a chance. In the meantime, I'll chalk it up to subtle side effect(s) that changing the length of the path has/have on the binary. I can live with that :)

**Comment by probonopd** [comment]
If you do replacements in binaries with different sizes, then the addresses in the binary don't stay the same. The length of the binary changes. This causes it to crash because the content is no more at the expected locations.

**Comment by bdantas** [comment]
Very interesting. I didn't realize that binaries have internal addresses and expect things to be in certain locations. If that's the case, it completely makes sense why replacing a string with one of a different length wreaks havoc. 

Thank you both very much for your patience. Call me strange but I can't help but ponder about such things. I'll keep spreading the word about AppImage--IMHO it is one of the best things to ever happen to GNU/Linux.

Happy hacking!

**Comment by TheAssassin** [comment]
Ah, right, @probonopd, of course. `sed` is a text editor, and doesn't just overwrite the existing stream (like calling `strcpy` on a char array) but replace it.
