### ISSUE TITLE
Consider to move appimage.org to gh-pages

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#794]
Now that GitHub supports HTTPS, are there still great reasons to host appimage.org on our own infrastructure?

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by TheAssassin** [comment]
Why have GitHub tracking on that homepage?

And yes, there's plenty. We have the translation system that'd require to push a lot of commits to that branch containing compiled files, which is the last thing you should do.

**Comment by probonopd** [comment]
OK, so there are still great reasons to not doing it currently.

**Comment by TheAssassin** [comment]
I personally found appimage.org to be quite reliable by the way. And you always say, never change a running system, right?

**Comment by probonopd** [comment]
Right! :100:
