### ISSUE TITLE
xz's tarball hash sums changed upstream

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#797]
It appears to me like xz changed their tarball once again, the hash sum doesn't apply any more (see e.g., https://travis-ci.org/probonopd/gs-plugin-appimage/builds/386336986#L3245). This is _highly_ annoying.

Our own mirror still has the original file with the right hash, which we used for a while during a similar situation. I think we need to switch to that once again. Maybe we should keep using it permanently.

**Comment by TheAssassin** [comment]
It appears that the upstream sources have been updated (see https://tukaani.org/xz/). I don't know why that broke the old tarballs.
The sourceforge mirror seems to be working. I'll send a PR using the Netcologne mirror URL (https://netcologne.dl.sourceforge.net/project/lzmautils/xz-5.2.3.tar.gz).

**Comment by probonopd** [comment]
> I don't know why that broke the old tarballs.

Strange! NSA? ;-)
