### ISSUE TITLE
Appimaged does not find Exec key in desktop file

### ISSUE THREAD

**Issue by jdevera** [AppImage/AppImageKit#806]
When appimaged is processing the Digikam appimage, it complains about the lack of Exec key in the found desktop file:

```
Jun 15 23:47:24 nexon appimaged[15311]: -> REGISTER /home/jdevera/.local/bin/digikam-5.9.0-01-x86-64.appimage
Jun 15 23:47:24 nexon appimaged[15311]: squashfs based type 2 AppImage
Jun 15 23:47:24 nexon appimaged[15311]: Got root desktop: digikam.desktop
Jun 15 23:47:24 nexon appimaged[15311]: TODO: Implement inode.base.inode_type 9
Jun 15 23:47:24 nexon appimaged[15311]: Desktop file has no Exec key
```

However, the `digikam.desktop` file inside the appimage contains the following line:

```
Exec=digikam.wrapper -qwindowtitle %c
```

The result is that no desktop entry is registered for Digikam

**Comment by probonopd** [comment]
Thanks for reporting. appimaged was recently moved to its own repository, so I have opened an [issue](https://github.com/AppImage/appimaged/issues/13) there.
