### ISSUE TITLE
Missing dependencies when running AppImage on Ubuntu Server

### ISSUE THREAD

**Issue by edgarfauquier** [AppImage/AppImageKit#808]
Hello!

I have created an AppImage, which runs perfectly on different Ubuntu Desktop versions. However, when I try to run it on a Ubuntu Server 14.04, it complains about missing dependencies.

After some investigation, I have found that **libfontconfig.so.1** is required and not present on the system.

(The file is explicitly excluded, as i can see it on https://github.com/AppImage/AppImages/blob/master/excludelist)

Any suggestions?

Thanks!

**Comment by probonopd** [comment]
The excludelist is put together by looking at what can be expected to come as part of each _desktop_ target system (distribution). If you would like to run AppImages on a server (not a default desktop installation), then you need to install the libraries mentioned in the excludelist through your distribution's package manager first.

**Comment by TheAssassin** [comment]
Please don't try to bundle the library despite it's in the excludelist. Your app might become incompatible with most other OSes then.
