### ISSUE TITLE
architecture detection broken with recent »file« releases

### ISSUE THREAD

**Issue by Optiligence** [AppImage/AppImageKit#810]
>Unable to guess the architecture of the AppDir source directory "."

https://github.com/AppImage/AppImageKit/blob/5b5ca1a70cd84966d9084a9efb70115aa4b9fdb2/src/appimagetool.c#L357 breaks because there is no comma before the arch

>~> file -L -N -b /usr/lib/libc-2.27.so 
ELF 64-bit LSB pie executable x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /usr/lib/ld-linux-x86-64.so.2, BuildID[sha1]=0c1ecb7b0e67918d1d1991e0e7793f814bfa1ec2, for GNU/Linux 3.2.0, not stripped

using file-5.33

**Comment by probonopd** [comment]
I am getting

```
me@host:~$  file -L -N -b /usr/lib/liblilv-0.so.0
ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=544dc36f9301a8430783950fcb13334feee83488, stripped
```

I don't think we can handle `ELF 64-bit LSB pie executable x86-64`, whatever that is.

**Comment by Optiligence** [comment]
it’s the default output for libraries on Arch Linux
may be a `file` issue too
what’s your file version?

**Comment by probonopd** [comment]
```
me@host:~$ file --version
file-5.32
magic file from /etc/magic:/usr/share/misc/magic
```

**Comment by probonopd** [comment]
Please be aware of https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

**Comment by probonopd** [comment]
Uh, that's interesting. So possibly a bug should be reported against `file` since sudden changes in its output format will upset many tools that are relying on it.

**Comment by TheAssassin** [comment]
@Optiligence can you try `file --mime`, please? This should yield a MIME type instead of a textual description, which is probably a more consistent output, and easier to parse, too.

**Comment by Optiligence** [comment]
file-5.33
>~> file --mime /usr/lib/libc-2.27.so
/usr/lib/libc-2.27.so: application/x-pie-executable; charset=binary

**Comment by TheAssassin** [comment]
That'd be better, yes. See https://github.com/AppImage/AppImageKit/blob/appimagetool/master/src/elf.c#L135.

**Comment by Optiligence** [comment]
the relevant file commits, for reference: 
introduction: https://github.com/file/file/commit/6876ebadcdf27224b3ffa9dfa4343127aa97c9b2
fix: https://github.com/file/file/commit/defcf7e39943780dd19ca002c478e52ec9ee5cbc
so its 5.33 only

**Comment by TheAssassin** [comment]
@Optiligence the best solution would be to get rid of file or any sort of magic database for detecting ELF files. We can just replicate this in our source code, the ELF format is very well defined, there's magic bytes, e.g.,

```
> xxd /bin/bash | head -n1
00000000: 7f45 4c46 0201 0100 0000 0000 0000 0000  .ELF............
```

Furthermore, there's a flag defining the architecture which can simply be read, our ELF code is even capable of this. See https://github.com/AppImage/AppImageKit/blob/appimagetool/master/src/elf.c#L135

**Comment by Optiligence** [comment]
Sure. but since it also seemed like a `file` bug, i wanted to check that out, but their bug tracker and mailing list links were down, so i sifted through the commits. 

It’s just a confirmation that it is, indeed, a bug, and that it’s also fixed already. 

For the time being i’ll set the environment variable `ARCH=x86_64`as the appimage output helpfully suggested.

**Comment by TheAssassin** [comment]
Adding this issue to my current TODO list.

**Comment by probonopd** [comment]
> introduction: file/file@6876eba
> fix: file/file@defcf7e
> so it’s 5.33 only

So a bug in `file` has been introduced, and has already been fixed. Unless 5.33 happens to land in, say, a Ubuntu LTS release I'd say we can safely ignore this.

**Comment by TheAssassin** [comment]
But why bother using `file` at all? This subprocessing stuff can be kicked out entirely, making appimagetool faster and less error prone.

**Comment by probonopd** [comment]
> But why bother using file at all?

Because it is working (besides one bug in one version of it that already has been fixed by them)? I prefer not to touch what we already have working, and focus on the things that we either don't have yet or are not working properly yet (e.g., `appimaged` is still placing desktop files into the filesystem one after each other rather than all at once, and so on - there our time _makes a difference_).
