### ISSUE TITLE
conda: relocateable paths

### ISSUE THREAD

**Issue by looooo** [AppImage/AppImageKit#813]
I tried to create an appimage from conda-packages but it doesn't work because I think there are hard-coded paths. Conda sets these paths during installation of a package. 
I wonder if it is possible to set the paths during installation in a way appimage could use them. Or if there are any other ways to remove hard-coded paths.

**Comment by TheAssassin** [comment]
This [example script](https://github.com/Pext/Pext/blob/master/travis/build-appimage.sh#L31) showcases how to use miniconda to build an AppImage.

Otherwhise, this is not an issue, but a question. Closing therefore. Feel free to join our IRC chat (#AppImage on Freenode) or use our Forum (https://discourse.appimage.org) to get further assistance. You can also ask further questions here.

**Comment by probonopd** [comment]
Which hard-coded paths are you referring to? And could these be overridden by setting, e.g., `$PYTHONPATH`?

**Comment by looooo** [comment]
first I tried to launch my application via activating the conda-environment and running the executeable. But conda uses absolute-paths in the activation script.
Pext is using a different approach and launch the executeable directly. This also works with freecad, but still I have problems with some libraries: fontconfig, opengl/coin (crash on scene creation). Maybe something sounds familiar to you and you give some hints.

**Comment by TheAssassin** [comment]
@looooo without your code this is impossible to get right. I can't see what you're doing right now. I can tell you that bundling Pext took me several weekends in ~8 months to get right. Please join our IRC chat, and we'll try to figure out how to do it properly.

**Comment by looooo** [comment]
@TheAssassin I will do... btw.: here is the repo which contains the recipe for the appimage:
https://github.com/looooo/freecad_conda_appimage

**Comment by looooo** [comment]
@TheAssassin @probonopd 
in case you have some time to test this:
here is a first FreeCAD-appimage based on conda which works for me:
https://github.com/looooo/freecad_conda_appimage/releases
If you have any ideas how to improve this, or it is not working, please give some feedback.

**Comment by TheAssassin** [comment]
I recommend you to test it in a set of VMs running the most popular distros' live ISOs (Ubuntu, Debian, openSUSE, etc.), that covers most of the users' environments.

**Comment by probonopd** [comment]
@looooo a `.travis.yml` file would be cool that would produce and upload the AppImage...

**Comment by looooo** [comment]
yes, good ideas. I think I will test the appimage on different machine before trying to setup the creation of the appimage with travis. There are still some libraries missing.. Also there is a qt5.6 problem on newer distros (ubuntu18.04) https://stackoverflow.com/questions/50555973/qgtkstyle-could-not-resolve-gtk, but this is more related to the qt-build. But in general I think it's definetly possible to use conda-packages for appimages. Only a few environment-variables have to be set, and some files have to be removed.
