### ISSUE TITLE
Can we get rid of appimagetoolnoglib.c?

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#817]
@probonopd we still have that file https://github.com/AppImage/AppImageKit/blob/appimagetool/master/src/appimagetoolnoglib.c in our source code that isn't used in the real world.

Since we maintain only the GLib version, we should consider removing the non-GLIB file.

**Comment by probonopd** [comment]
Please don't remove it. It's meant as a minimal working example implementation for those users who can't accept a dependency on GLib. Originally it was geared to, e.g., electron-builder. It's not broken so why remove it.

**Comment by TheAssassin** [comment]
I don't think it's built by our build system, that's why I asked. We could've moved it to a branch or something like that.
But okay, then we'll leave it in the source code.
