### ISSUE TITLE
Localization support for X-AppImage-Version

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#820]
Whenever a desktop file contains a localized `Name` entry, it takes precedence over the non-localized version. Therefore, the `X-AppImage-Version` content must be appended to localized versions as well. 

See https://github.com/AppImage/AppImageKit/blob/07100fbc512c42bc5fef1fd0fbc53da62937dfc9/src/shared.c#L582-L584.

Unfortunately, we can't get a list for which locales a translated `Name` entry is available using the GLib API, therefore we'll probably have to check the full list of locales (probably hardcoded, but maybe there's a way to get a list from the distro) using the GLib functions.

**Comment by probonopd** [comment]
I am not sure whether having localized names is even a good idea. I mean, Firefox is Firefox. Application names should be brand names that work regardless of language. 

Now prove me wrong ;-)

**Comment by TheAssassin** [comment]
Of course that's a silly idea for pure names. For instance, Cura has two entries, `Name=Cura` and `Name[de]=Cura`. That's total nonsense.

But think of e.g., `Firefox web browser` and `Firefox-Webbrowser`. Or of languages which use non-latin letters, that are used by a large share of the human population.

The point is, we can't control what users put in their desktop files, and we shouldn't simply remove localized names. If we append the version, we must do it for _all_ possible entries, that's my point.

I thought about this by the way, and I think I'm going to implement a minimalistic "locale detection" algorithm that will look for all entries matching `Name(\[[^\s]+\])?=` and parse the locales.

**Comment by probonopd** [comment]
In my opinion, the product name is "Firefox" and this is an international brand name. "web browser" would better go to `GenericName` or `Comment` where localization makes a lot of sense.

That being said, one area where localizing `Name` actually might make sense is non-Latin character sets, such as Chinese, Japanese, or Korean.
