### ISSUE TITLE
"Portable mode": Get rid of .config directory

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#832]
We should get rid of this `my.AppImage.config` directory for the so-called "portable mode". If an AppImage is supposed to be run in the "portable mode", then it should just work by creating the `my.AppImage.home` directory. The more configuration options, the less understandable the feature is.

Instead of simply removing it, we should just create a `.config` directory in the `.home` and export the environment vars accordingly. This way, only a single step is required to use this feature.

**Comment by probonopd** [comment]
No, these are either-or. Not to be combined. If you are fine with home, just use that and don’t care about config.

**Comment by TheAssassin** [comment]
@probonopd would you like to explain at least? This is something totally non-obvious to users.

**Comment by probonopd** [comment]
Again, it seems like you are happy to use `$HOME` and redefine the whole home directory. In this case, you don't need `.config`.  (Someone only needs `.config` who wants the XDG configuration directory to be redirected but not the whole `$HOME`). Maybe we should clarify in the docs that `.home` is probably what most users will want to use, and that the two are mutually exclusive.

**Comment by TheAssassin** [comment]
@probonopd how are they mutually exclusive? I don't see why that should be the case.

The problem is the fact nobody really uses the XDG environment variables, but we mention it in the docs. As an unexperienced user, I cannot understand what this is, what I need it for, and why, as you claim, those options were mutually exclusive, etc.

I guess your point is that if the app supports the `$XDG_CONFIG_HOME` variable, you could make your AppImage use the "bundled" configs in the current home directory. This logic is flawed though, due to the reasons above. If I need my app to be portable, and I forget to create e.g. the `.config` directory and have the var set in my current environment to `/home/user/.config`, the configs might be stored there. This is totally non-obvious, and creates problems here and there. When talking about a "portable" mode, measures should be taken that if it is enabled, everything's stored next to the AppImage and not on the system. The current functionality doesn't provide this, in fact, it allows for many situations in which data, configs etc. might be stored by software both in the portable dirs and on the system.

It's in my opinion necessary to make this a lot easier and understandable, copying basically the idea of https://portableapps.com. If an app is "portable", everything is set up so the app will store its data in the "portable home", and not on the system. If not, it shall use the system directories. This is easy, understandable, and _expected_ behavior.

What we have _now_ is in my opinion a total mess, that should be resolved by only providing one way for "portable" AppImages.

**Comment by TheAssassin** [comment]
@probonopd the thing is, I've seen some systems where those variables are indeed set (IIRC some openSUSE or so). The FreeDesktop standard doesn't even forbid that. I just want to avoid such situations in which people rely on the data to be contained in the directory (e.g., when they don't want to "leave traces").

I know we don't guarantee any form of isolation of data, but this is the impression people get when reading about the portable mode. I want to add some notes about that to our docs.

**Comment by probonopd** [comment]
Maybe we should only call "portable HOME" = "portable mode" and refer to the other option as "portable configuration".

**Comment by TheAssassin** [comment]
... and explicitly state that `.config` isn't reliable at all, and people should use both together anyway?

**Comment by probonopd** [comment]
> ... and explicitly state that .config isn't reliable at all

The feature is reliable, just not all applications support the XDG standard, which should be reported as bugs to the respective applications.

> people should use both together anyway?

You probably mean __not__ together?

**Comment by TheAssassin** [comment]
@probonopd perhaps we should discuss that on IRC.
