### ISSUE TITLE
Issue with libfontconfig and FT_Done_MM_Var symbol

### ISSUE THREAD

**Issue by mardy** [AppImage/AppImageKit#836]
Hi there!
  A user has [reported](https://discuss.pixls.us/t/phototeleport-a-new-photo-uploader/8243/18) a problem when running PhotoTeleport's AppImage in Linux Manjaro:

    ./PhotoTeleport_0.6-8.AppImage: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

Searching for it in the internet, I found similar issues with other AppImage files:

 - [Digikam](http://digikam.1695700.n4.nabble.com/digiKam-users-DK-doesn-t-start-td4705721.html)
 - [Streamio](https://gist.github.com/nemanjan00/dca98f1eb26414327e32452185916ec8), includes a workaround

**Comment by TheAssassin** [comment]
Rebuilding the AppImages should fix the issue. libfreetype (`FT_*`) has been added to our blacklist.

**Comment by mardy** [comment]
It does, thanks!
