### ISSUE TITLE
continuous build of AppRun-amd64 does not exist

### ISSUE THREAD

**Issue by mbunkus** [AppImage/AppImageKit#837]
The canonical way to use `functions.sh` from the `AppImages` repository is to download a copy from github. Unfortunately, that file [hardcodes the location](https://github.com/AppImage/AppImages/blob/master/functions.sh#L86) to the `AppRun-amd64` binary to point to the contiuous build in this repository — and that file [doesn't exist]() at the moment, only `AppRun-i686`.

**Comment by TheAssassin** [comment]
I will retrigger the build to see if that fixes the issue.

Please beware we do not recommend to use this `functions.sh` file, and it may be removed in the future. You might want to switch to better, more modern tools. https://github.com/linuxdeploy/linuxdeploy

**Comment by ddennedy** [comment]
Today, AppRun-x86_64 does not exist:
```
+ wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 -O AppRun
--2018-08-11 08:23:31--  https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
...
HTTP request sent, awaiting response... 404 Not Found
2018-08-11 08:23:32 ERROR 404: Not Found.
```
I do not know anything about `functions.sh` as I simply do:
```
	wget -N https://raw.githubusercontent.com/probonopd/AppImages/master/pkg2appimage
	bash -ex pkg2appimage appimage/appimage.yml
```

**Comment by TheAssassin** [comment]
@ddennedy it seems like it was a GitHub issue. I hit the edit button on the release page, and GitHub requested me to upload the file again. Actually, the file was uploaded yesterday by the Travis build, but it seems like GitHub lost the file somehow. I manually uploaded the file from our backup artifacts repository now. I hope that fixes the issue permanently.

Please reopen if *GitHub strikes again*.

**Comment by ddennedy** [comment]
Got it now! thank you

**Comment by probonopd** [comment]
Wow, GitHub is losing files now? Have they started migrating on Microsoft tools?

**Comment by hideout** [comment]
looks like ;)

2018-08-12 19:04 GMT+02:00 probonopd <notifications@github.com>:
