### ISSUE TITLE
--appimage-extract-and-run

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#841]
Docker is a very popular environment for building software, and also AppImages.

Due to our use of FUSE, AppImages don't directly run in Docker, which requires a simple but annoying workaround for every AppImage: the AppImage is called with `--appimage-extract`, and then, instead of the AppImage, `squashfs-root/AppRun` is called. This is normally just another line that needs to be added, but can get quite complex the more AppImages are involved, because then the `squashfs-root` directories need to be renamed, etc.

This is something that could be automated by us by adding a new option to the AppImage runtime: `--appimage-extract-and-run`. When this flag is used, the AppImage's contents should be extracted into a temporary directory with a predictable name (i.e., some value that depends on the AppImage file), the `AppRun` entry point should be called with the other parameters passed, and then the files should be cleaned up again.
In order to avoid having to re-extract all files on subsequent runs, we should introduce an environment variable `NO_CLEANUP` that, if set, should prevent the cleanup code from running. This is also what the predictable directory names are needed for.

This flag wouldn't only help our users, but also help us in our own Docker based build scripts.

**Comment by probonopd** [comment]
In an effort to keep the number of options and the complexity low I'd say `./some.AppImage --appimage-extract && ./squashfs-root/AppRun` is preferable imho.

**Comment by TheAssassin** [comment]
@probonopd as pointed out above, this doesn't work in _many_ cases. This doesn't add any noteworthy complexity, rather it forces us to refactor the runtime a bit, and greatly improve its code quality and structure.

The alternative is to provide some sort of shell script that automates this. But that doesn't make _any_ sense. Aren't we user oriented? Users request this feature, after all.

**Comment by probonopd** [comment]
I think your main point is that instead of `squashfs-root` we should use something that reflects the name of the AppImage and thus would prevent collissions. Right?

**Comment by TheAssassin** [comment]
No. The point is that we should provide an _easy_, automated and reliable way to execute AppImages in Docker containers _without_ needing the user to understand the problem and solve it using some script magic.

**Comment by TheAssassin** [comment]
Okay, well, I think that if you explicitly state it should only be used in case FUSE doesn't work, it could also be included in the help text. But in any case, I'll start working on this then. I already started to improve the code flow in the runtime a bit, but I'm still struggling to understand some `if`s in the extraction code. But I will figure it out, I guess.

**Comment by TheAssassin** [comment]
So, I finally understand what that "extra parameter" in `--appimage-extract` did: It was some sort of "pattern" that one could pass to extract parts of an AppImage only.

My question is: do we _really_ need that? In my opinion, it'd make more sense to allow overriding the default `squashfs-root` output directory.

**Comment by probonopd** [comment]
> My question is: do we really need that? 

Sure! Do you _really_ want to extract the whole AppImage just to get e.g., the desktop file(s)?

**Comment by TheAssassin** [comment]
I will restore the original behavior then.

**Comment by TheAssassin** [comment]
I'm finally done with this feature. It was a bit more work than expected, but I could fix some things in the runtime and other parts of our source code.

Also, I found a nice and working (verified) MD5 implementation which I included into our repository. This will allow us to remove the dependency on OpenSSL in libappimage (used for MD5 calculations during desktop integration).

Pattern matching has been restored. I actually _documented_ this now, to avoid further confusion about the feature.

We're getting closer to a point where we could unit test the runtime.

**Comment by probonopd** [comment]
Great job, thank you very much @TheAssassin

**Comment by ChristianCiach** [comment]
It looks like `--appimage-extract-and-run` is not advertised by `--appimage-help`. Is this by design?

**Comment by TheAssassin** [comment]
@ChristianCiach https://github.com/AppImage/AppImageKit/issues/841#issuecomment-413342158.

**Comment by ahmedtds** [comment]
Not advertising it is a bad idea, stop being a nanny. I had to google for like 1 hour to find this solution. Why I had to do that? You should mention about it if FUSE fails or don't exist.

**Comment by probonopd** [comment]
@ahmedtds are you running in a Docker container? Or what else is the reason you cannot use FUSE?

**Comment by TheAssassin** [comment]
How is this relevant? The issue is that the option isn't documented anywhere outside this issue tracker, mostly because of your opposition in the comments here.

Simply adding this option to the help text and, more importantly, https://docs.appimage.org will resolve @ahmedtds's concerns.

**Comment by probonopd** [comment]
Btw, I am not against documenting it on docs.appimage.org if it is clearly explained that this is for Docker, Podman etc. and is not the genereally recommended "normal" way for running AppImages on (broken) desktops. Personally I am not using Docker, Podman etc. but it seems like people have issues using `appimagetool.AppImage` there, and need `--appimage-extract-and-run` as we never implemented container autodetection to make it "just work".

**Comment by soredake** [comment]
@probonopd not only docker, but also flatpak.

**Comment by suy** [comment]
FWIW, this is now documented, with both the command line argument and the environment variable. It's on the troubleshooting section: https://docs.appimage.org/user-guide/troubleshooting/fuse.html#fallback-if-fuse-can-t-be-made-working

This issue appears much sooner in a DDG search, though, so I hope the link is useful. ;)

**Comment by adelin-b** [comment]
I just found this option, its been weeks I had problem because some extension I use need to patch the appImage on runtime. 
It is not documented: 
```
 myappimage --appimage-help
AppImage options:

  --appimage-extract [<pattern>]  Extract content from embedded filesystem image
                                  If pattern is passed, only extract matching files
  --appimage-help                 Print this help
  --appimage-mount                Mount embedded filesystem image and print
                                  mount point and wait for kill with Ctrl-C
  --appimage-offset               Print byte offset to start of embedded
                                  filesystem image
  --appimage-portable-home        Create a portable home folder to use as $HOME
  --appimage-portable-config      Create a portable config folder to use as
                                  $XDG_CONFIG_HOME
  --appimage-signature            Print digital signature embedded in AppImage
  --appimage-updateinfo[rmation]  Print update info embedded in AppImage
  --appimage-version              Print version of AppImageKit

Portable home:

  If you would like the application contained inside this AppImage to store its
  data alongside this AppImage rather than in your home directory, then you can
  place a directory named

  /opt/cursor-bin/cursor-bin.AppImage.home

  Or you can invoke this AppImage with the --appimage-portable-home option,
  which will create this directory for you. As long as the directory exists
  and is neither moved nor renamed, the application contained inside this
  AppImage to store its data in this directory rather than in your home```

**Comment by TheAssassin** [comment]
Please open an issue in the new repository: https://github.com/AppImage/type2-runtime

**Comment by probonopd** [comment]
https://github.com/AppImage/type2-runtime/issues/64

**Comment by charlag** [comment]
I'm sorry for necroposting but I have noticed that it uses a predictable name (md5 hash) in `/tmp` which is probably not very good:
https://systemd.io/TEMPORARY_DIRECTORIES/
wouldn't at least [mkdtemp](https://man7.org/linux/man-pages/man3/mkdtemp.3.html) be a bit more secure?

**Comment by TheAssassin** [comment]
It works well when using `NO_CACHE`. That was a design decision. I don't recall the detaills.

**Comment by charlag** [comment]
I'm sorry, what is `NO_CACHE`? i couldn't find any mention so I can't tell if it's alleviating the security concerns I've mentioned
