### ISSUE TITLE
AppStream validation fails with symbol lookup error

### ISSUE THREAD

**Issue by phoerious** [AppImage/AppImageKit#856]
When I run appimagetool on my AppDir without `--no-appstream`, I get the following error:

```
AppStream upstream metadata found in usr/share/metainfo/org.keepassxc.KeePassXC.appdata.xml
Trying to validate AppStream information with the appstreamcli tool
In case of issues, please refer to https://github.com/ximion/appstream
/bin/appstreamcli: symbol lookup error: /usr/lib/libappstream.so.4: undefined symbol: g_strv_contains
Failed to validate AppStream information with appstreamcli
```

This seems to be a glib incompatibility. appstreamcli is not bundled with the AppImage, so both the CLI tool as well as the the failing lib are from my system, but it works when I use it without the appimagetool libs in my library load path.

I'm on Arch Linux.

**Comment by probonopd** [comment]
Agree, we should do that.

**Comment by TheAssassin** [comment]
We seem to use some shell script that indeed sets `LD_LIBRARY_PATH`. I guess we should consider using linuxdeploy to make appimagetool AppImages.

**Comment by probonopd** [comment]
Agree, we should do that. Or use patchelf manually.

**Comment by TheAssassin** [comment]
... which is kind of counterproductive, as we know linuxdeploy works perfectly fine, and it's tested in a variety of places.

**Comment by probonopd** [comment]
As we have heard from many third-party projects, some insist on building the AppImage stuff themselves, and they generally appreciate as few build-time dependencies as possible.

**Comment by xsnrg** [comment]
This is on Fedora. 
```
[appimage/stderr] AppStream upstream metadata found in usr/share/metainfo/org.kde.kstars.appdata.xml
[appimage/stderr] /usr/bin/appstreamcli: symbol lookup error: /lib64/libappstream.so.4: undefined symbol: g_ptr_array_steal_index_fast
[appimage/stderr] Failed to validate AppStream information with appstreamcli
ERROR: Failed to run plugin: appimage 
DEBUG: Exited with return code: 1 
```

**Comment by probonopd** [comment]
This seems to indicate that `appstreamcli` was built on a newer system than the one you are trying to run it on. Where did you get it from? Which version of Fedora are you running?

Besides, `ERROR: Failed to run plugin: appimage` seems to indicate that this is an issue that belongs to https://github.com/linuxdeploy/, because AppImageKit does not use "plugins".

**Comment by xsnrg** [comment]
This is Fedora 31 x86_64 with all the most recent updates.
base package repo @System:

```
Installed Packages
Name         : appstream
Version      : 0.12.7
Release      : 2.fc31
Architecture : x86_64
Size         : 1.1 M
Source       : appstream-0.12.7-2.fc31.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Utilities to generate, maintain and access the AppStream database
URL          : https://github.com/ximion/appstream
License      : GPLv2+ and LGPLv2+
Description  : AppStream makes it easy to access application information from the
             : AppStream database over a nice GObject-based interface.

```

You are correct in that this was with linuxdeploy. I will open a ticket over there.  Thank you.

**Comment by TheAssassin** [comment]
@probonopd that's not remotely a linuxdeploy issue, if any it'd be an _appimage_ plugin issue... as linuxdeploy-plugin-appimage internally only bundles appimagetool and appimagetool crashes here, this bug report is exactly right here.

Please do not direct people to the wrong bug tracker, it's annoying work to then redirect everything in the right repository first, then redirect them back here where the issue belongs...

**Comment by probonopd** [comment]
Sorry!

**Comment by xsnrg** [comment]
So, for fun I upgraded to Fedora 32 last night to give it a try there.

```
[appimage/stderr] AppStream upstream metadata found in usr/share/metainfo/org.kde.kstars.appdata.xml
[appimage/stdout] /home/jhoward/projects/kstars-appimage should be packaged as KStars-x86_64.AppImage
[appimage/stdout] Trying to validate AppStream information with the appstreamcli tool
[appimage/stdout] In case of issues, please refer to https://github.com/ximion/appstream
[appimage/stderr] /usr/bin/appstreamcli: symbol lookup error: /lib64/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
[appimage/stderr] Failed to validate AppStream information with appstreamcli
ERROR: Failed to run plugin: appimage 
DEBUG: Exited with return code: 1 

```
```
Installed Packages
Name         : appstream
Version      : 0.12.10
Release      : 1.fc32
Architecture : x86_64
Size         : 1.4 M
Source       : appstream-0.12.10-1.fc32.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Utilities to generate, maintain and access the AppStream database
URL          : https://github.com/ximion/appstream
License      : GPLv2+ and LGPLv2+
Description  : AppStream makes it easy to access application information from the
             : AppStream database over a nice GObject-based interface.

```

It sounds like folks know what the problem might be from the above conversation, but if there is any other information I can provide that would be helpful, just ask.

**Comment by probonopd** [comment]
The way I read this (@TheAssassin do you read it the same way?) `/usr/bin/appstreamcli` (which comes from the system, not from here) crashes because it needs `/lib64/libsoup-2.4.so.1` (which also comes from the system) which does not find the symbol `g_file_info_get_modification_date_time` anywhere. Hy hypothesis is that our AppImage is bundling a library to which `g_file_info_get_modification_date_time` was added in a later version (version higher than what we are bundling). So the "outside world" (outside of the AppImage) may need `g_file_info_get_modification_date_time` while our bundled version does not have it.

Are we still using LD_LIBRARY_PATH somewhere? If we could move away from it, then the outside tool  `/usr/bin/appstreamcli` should not use any of the privately bundled libraries, and hence be able to find `g_file_info_get_modification_date_time`.

(But any of this begs the question: Why run our tools on a recent Fedora when the point is to make binary-compatible AppImages. Our suggestion is to run on something like CentOS 6 or Ubuntu xenial...)

**Comment by TheAssassin** [comment]
@probonopd well, do we ship `AppRun.c`? If yes... sigh... this thing should just go into the wastebin, it's always causing way more issues than it solves...

**Comment by probonopd** [comment]
We might not need to use `AppRun.c` for `appimagetool.AppImage`... in fact, the currently-experimental successor won't use it.

**Comment by TheAssassin** [comment]
We should just bundle appimagetool with the known-stable linuxdeploy, then build the AppImage with appimagetool itself, I guess.

**Comment by probonopd** [comment]
We should remove, not add, dependencies of non-core outside projects.

**Comment by TheAssassin** [comment]
Given the existing dependency mess, the fact that appimagetool has a successor in preparation _and_ the fact this tool is known-stable and pretty bug-free and maintained by me, there is no real argument not to do it, especially if that fixes such issues permanently.

**Comment by TheAssassin** [comment]
I recently see an increase in problems related to this issue. The pattern of using `$LD_LIBRARY_PATH` for all applications in an AppImage is still in  widespread use (see e.g., https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/4). We really need to document that this is an antipattern, fix our AppImages and discard `AppRun.c`.

To fix this problem quickly, I just came up with one idea: If you don't like using linuxdeploy (which, I think, should be the way to go), how about simply patching `$LD_LIBRARY_PATH` in appimagetool again? We could probably split the env var into separate paths, look for any path containing `$APPDIR`, remove it, reassemble the value and set `$LD_LIBRARY_PATH` again. However, this is a very bad hack, and should be the last resort.

**Comment by azubieta** [comment]
The usage of `$LD_LIBRARY_PATH` is a key factor in the AppImages created with appimage-builder. It's required first to toggle the usage of the embed libc version and second to reduce the build time by not having to patch every single binary (patching the java runtime libs takes about 30minutes in my laptop). 

I've seen this error too in appimage-builder. There appimagetool is executed as without any LD_LIBRARY_PATH set. So it's no something unique of the use case where the developer set LD_LIBRARY_PATH when running linuxdeploy.

**Comment by TheAssassin** [comment]
> The usage of $LD_LIBRARY_PATH is a key factor in the AppImages created with appimage-builder.

That might be the case, but still, it's got severe drawbacks and I would consider it an antipattern. Using `DT_RUNPATH` eliminates all the issues and should therefore be used wherever possible. Your case might be considered an edge case and therefore be acceptable (your libc is also relatively new normally, which should mitigate the issues a bit, too).

I'm not a fan of any kind of libc bundling generally...

**Comment by ba32107** [comment]
Hi, I also came across this issue today, wrote up some detailed reproduction steps in https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/issues/16 in case it's any help. Looking forward to seeing if this can be solved soon. Thanks for your time looking into this!
