### ISSUE TITLE
Quote on 'Similar Projects' is no longer accurate

### ISSUE THREAD

**Issue by popey** [AppImage/AppImageKit#860]
The following section is on the [Similar Projects](https://github.com/AppImage/AppImageKit/wiki/Similar-projects) wiki page. I have a couple of issues with it.

1) At 2 years old, it's by no means 'recent' :)
2) While snapd used to require a login to Ubuntu One to install snaps via GNOME Software, this was a [bug](https://pad.lv/1736232), [fixed](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1736232/comments/14) nearly a *year* ago. 

I appreciate this is an appimage project page, and the suggestion is that anyone can fix it, but nobody did, for nearly a year. It's not your competitors responsibility to fix your errors in your marketing. The fact that you've got misinformation about another project at the very top of the page is very disappointing. 

"In a recent episode of the German podcast RadioTux Magazin November 2016 the differences were summarized around 22:00:

>     AppImage: Relatively simple - click, runs.
> 
>     Snap: You have to install something, you have to login somehow to Ubuntu One, but then you can install something, runs.
> 
>     Flatpak: I need to get Flatpak first, then I have to add the repositories there, then I have to get the GPG keys, then I have to download Runtimes, and then I can somehow get the Flats out of there, install and start the programs.
> 
>     So to say, ordered according to difficulty.
"

**Comment by azubieta** [comment]
You are totally right. We should take care of that wiki in general.
 But if you have some spare time, feel free to send your modifications.

**Comment by TheAssassin** [comment]
@popey if you want to, please send a PR with a new wording that is more accurate.

**Comment by probonopd** [comment]
Thanks for your correction. Good to hear that a login is no longer required. 

The section section in question is a quote from a third-party podcast, so instead of changing the quote we should add a note that as of today, the login is no longer required.

**Comment by popey** [comment]
Saying "as of today, the login is no longer required" is not satisfactory in my opinion. It's not 'today', it was nearly a year ago. It was a bug, which was fixed. Stating it on this page and having a sub-note that it's "no longer required" makes the implication that it was _intended_ to be required, but now isn't. That's not the case. It wasn't intended to work like that, and the fact that it did was just a bug, which was fixed. Having a bug highlighted at the very top of your page being used as a stick to beat the other options is a slippery slope. I'm sure you wouldn't like any bugs in appimage to he highlighted as features that "today" are "no longer required"?

**Comment by probonopd** [comment]
Thanks for the clarification @popey. How about this?

> NOTE: Logging into Ubuntu One is no longer required (and has not been for a while); apparently this was a bug at the time of the review.

**Comment by popey** [comment]
Awesome, I fixed the date on it too. Thanks.
