### ISSUE TITLE
AppImage and Ubuntu Snap

### ISSUE THREAD

**Issue by 1995parham** [AppImage/AppImageKit#861]
I installed Neovim by its AppImage binary when I called Go which is installed by the snap from Neovim it returns snap application itself instead of Go. Is there any solution for this?

**Comment by probonopd** [comment]
Can you please post the exact comments you have used? From your description it is not clear to me what exactly you're doing and what is happening. Thank you.

**Comment by 1995parham** [comment]
In Neovim as in vim, you can run system commands. When I run `!go` to run go it runs `snap` package manager instead of Go.
I installed Go with the snap package manager, It created a symbolic link `/snap/bin/go -> /usr/bin/sanp` for go and this link runs without any problem but when it runs from Neovim that is installed using AppImage it runs snap.

**Comment by probonopd** [comment]
On the command line of your system, please enter: `which go` and `readlink -f $(which go)` - what does it say?

**Comment by 1995parham** [comment]
`which go`: `/snap/bin/go`
`readlink -f $(which go)`: `/usr/bin/snap`

**Comment by 1995parham** [comment]
Thanks for your help, I will create an issue there.

**Comment by zyga** [comment]
Hey @1995parham - can you please open an issue on the snapcraft forum (forum.snapcraft.io) or on launchpad (bugs.launchpad.net/snapd) - or just hop onto #snappy on freenode and chat with us!

**Comment by 1995parham** [comment]
I corrected this issue by sourcing my default bashrc in zshrc last week. If you want I can create this issue in snapcraft forum.

**Comment by zyga** [comment]
Thanks, this is fine, we know about the zsh issue and (eventually) it will get fixed.
