### ISSUE TITLE
Svg Icons don't show up in AppImage

### ISSUE THREAD

**Issue by DamirPorobic** [AppImage/AppImageKit#868]
Do you have any idea what could be causing that svg icons don't show up in my AppImage? Previously I was using png and everything worked fine, today I just replaced the pngs with svgs and now when the CI builds the AppImage, no icons show up. When I build from source locally everything seems to be working fine. Icons are loaded via Qt Resource file. 

![image](https://user-images.githubusercontent.com/12796236/46919525-ce907e00-cfe0-11e8-80a8-1540b0df3b79.png)

![image](https://user-images.githubusercontent.com/12796236/46919521-c1738f00-cfe0-11e8-844f-f89a96196d94.png)

**Comment by TheAssassin** [comment]
How did you create the AppImage? Most likely using a Qt deployment tool.
Please open an issue in linuxdeployqt's/linuxdeploy-plugin-qt's repository.

To make sure it's not an AppImage issue, please extract and run the AppImage (shortcut: `--appimage-extract-and-run`, not meant for production). If that works fine, then it's a deployment and not an AppImage issue.

**Comment by DamirPorobic** [comment]
When I run it with `--appimage-extract-and-run` I see the same issue. 
Sure, will open a issue under linuxdeployqt.

**Comment by probonopd** [comment]
Discussion continues in https://github.com/probonopd/linuxdeployqt/issues/325
