### ISSUE TITLE
Install appimagetool resources from cmake

### ISSUE THREAD

**Issue by azubieta** [AppImage/AppImageKit#869]
Currently, the appimagetool resources are being installed using a [build-appdir.sh](https://github.com/AppImage/AppImageKit/blob/9f0eeb61f070a6c74d2f9c9e5a114c1396c98097/build-appdir.sh) the same could be achieved by using CMake. With the gain that we will be able to use cpack to produce bundles.

**Comment by probonopd** [comment]
This CMake thing seems to be like a Tamagochi. Wants to be fed al the time, but why?

**Comment by TheAssassin** [comment]
It's moving functionality from shell script into CMake, reducing the overall amount of code.

**Comment by azubieta** [comment]
Done in #870
Closing this issue.
