### ISSUE TITLE
Relocating ancient libs to avoid a false 'not found' exec error

### ISSUE THREAD

**Issue by joelmaxuel** [AppImage/AppImageKit#879]
Hi,

This is not a problem with AppImageKit as I am still in the AppDir phase, however it seems relevant enough to Issue #361.

I am making an attempt to create an AppImage (for personal use) of a proprietary application some 20 years old, which makes use of libc5 and some X libs incompatible with today.  Also factor in running the old i386 software on amd64 hardware (and OS).

My challenge is upon calling the binary on Debian 9 (when it worked for Debian 3) - when the application is called on, it cannot be "found".  My current AppRun file:

```
#!/bin/sh
HERE=$(dirname $(readlink -f "$0"))
export LD_LIBRARY_PATH="$HERE"/lib:"$HERE"/usr/lib:"$HERE"/usr/X11R6/lib:"$HERE"/usr/486-linuxlibc1/lib
cd $HERE/opt/product/bin/
#ls -l
ldd "$HERE"/opt/product/bin/executable
exec "$HERE"/opt/product/bin/executable "$@"
#./executable
```

...to which I have ensured that I am hitting the right file.  The initial ldd revealed:

> 	linux-gate.so.1 (0xf77cf000)
> 	libXt.so.6 => /home/shared/Drop/appimage/AppDir//usr/X11R6/lib/libXt.so.6 (0xf7781000)
> 	libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xf75f2000)
> 	libXpm.so.4 => /home/shared/Drop/appimage/AppDir//usr/X11R6/lib/libXpm.so.4 (0xf75e3000)
> 	libm.so.5 => /home/shared/Drop/appimage/AppDir//lib/libm.so.5 (0xf75da000)
> 	libc.so.5 => /home/shared/Drop/appimage/AppDir//lib/libc.so.5 (0xf751c000)
> 	libSM.so.6 => /home/shared/Drop/appimage/AppDir//usr/X11R6/lib/libSM.so.6 (0xf7514000)
> 	libICE.so.6 => /usr/lib/i386-linux-gnu/libICE.so.6 (0xf74f7000)
> 	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7340000)
> 	libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xf7314000)
> 	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf730f000)
> 	libbsd.so.0 => /lib/i386-linux-gnu/libbsd.so.0 (0xf72f3000)
> 	/lib/ld-linux.so.1 => /lib/ld-linux.so.2 (0xf77d1000)
> 	libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xf72ed000)
> 	libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xf72e6000)
> 	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf72dd000)
> 	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf72c0000)

In checking ELF against the binary, this came up: 

> 	[Requesting program interpreter: /lib/ld-linux.so.1]

So as a test I copied ld-linux.so.1.9.11 and its symlink ld-linux.so.1 to my /lib and go in the new ldd:

> /home/shared/Drop/appimage/AppDir/opt/product/bin/executable: /lib/ld-linux.so.2: version `GLIBC_2.1.1' not found (required by /home/shared/Drop/appimage/AppDir/lib/libc.so.6)
> /home/shared/Drop/appimage/AppDir/opt/product/bin/executable: /lib/ld-linux.so.2: version `GLIBC_2.2.3' not found (required by /home/shared/Drop/appimage/AppDir/lib/libc.so.6)
> /home/shared/Drop/appimage/AppDir/opt/product/bin/executable: /lib/ld-linux.so.2: version `GLIBC_2.2' not found (required by /home/shared/Drop/appimage/AppDir/lib/libc.so.6)
> 	linux-gate.so.1 (0xf7790000)
> 	libXt.so.6 => /home/shared/Drop/appimage/AppDir/usr/X11R6/lib/libXt.so.6 (0xf7742000)
> 	libX11.so.6 => /home/shared/Drop/appimage/AppDir/usr/X11R6/lib/libX11.so.6 (0xf7666000)
> 	libXpm.so.4 => /home/shared/Drop/appimage/AppDir/usr/X11R6/lib/libXpm.so.4 (0xf7657000)
> 	libm.so.5 => /home/shared/Drop/appimage/AppDir/lib/libm.so.5 (0xf764e000)
> 	libc.so.5 => /home/shared/Drop/appimage/AppDir/lib/libc.so.5 (0xf7590000)
> 	libSM.so.6 => /home/shared/Drop/appimage/AppDir/usr/X11R6/lib/libSM.so.6 (0xf7588000)
> 	libICE.so.6 => /home/shared/Drop/appimage/AppDir/usr/X11R6/lib/libICE.so.6 (0xf7572000)
> 	libc.so.6 => /home/shared/Drop/appimage/AppDir/lib/libc.so.6 (0xf7455000)
> 	/lib/ld-linux.so.1 => /lib/ld-linux.so.2 (0xf7792000)

To which I verified the non-locatable string in the binary:

> joel@cybaryme/h/s/D/appimage> strings AppDir/opt/product/bin/executable|grep lib
> /lib/ld-linux.so.1
> libXt.so.6
> libX11.so.6
> libXpm.so.4
> libm.so.5
> libc.so.5
> /usr/lib/X11/app-defaults

...and fixed the first one.  Now ldd is not providing any useful information and am back to where I started in terms of errors:

> joel@cybaryme/h/s/D/appimage> sed -i -e 's|/lib/ld-linux.so.1|ld-linux.so.1|g' AppDir/opt/product/bin/executable
> joel@cybaryme/h/s/D/appimage> AppDir/AppRun 
> 	statically linked
> AppDir/AppRun: 8: exec: /home/shared/Drop/appimage/AppDir/opt/product/bin/executable: not found

The relevant strace:

> wait4(-1, 	statically linked
> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 12170
> --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=12170, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
> rt_sigreturn({mask=[]})                 = 12170
> execve("/home/shared/Drop/appimage/AppDir/opt/product/bin/executable", ["/home/shared/Drop/appimage/Corel"...], [/* 44 vars */]) = -1 ENOENT (No such file or directory)

Is there anything else (or differently) I should be doing?

**Comment by TheAssassin** [comment]
You could try copying the linker into the AppDir, and call it explicitly on the binary like `$HERE/ld-linux.so.1 bin/mybinary`.

**Comment by probonopd** [comment]
Half on topic, you may find some inspiration in https://github.com/AppImage/AppImageKit/wiki/Bundling-Windows-applications. Especially in the section about bundling all the 32-bit stuff and about patching ld-linux (which may or may not be applicable in your case). I am relatively optimistic that it can be made work, but it's a lot of trial and error and fiddling around in my experience.

Not really in the scope of AppImageKit though.

**Comment by joelmaxuel** [comment]
Update... I tried as suggested, also have thrown in a little $LD_PRELOAD.  Which brings me to my best of a bad situation.  

For now, copied all the libs to /lib32/retro on the system, and used patchelf on the executable to point ld-linux.so.1 to that directory.  This is my latest AppRun:

```
#!/bin/sh
HERE=$(dirname $(readlink -f "$0"))
export LD_LIBRARY_PATH=/lib/retro
#export LD_LIBRARY_PATH="$HERE"/lib:"$HERE"/usr/lib:"$HERE"/usr/X11R6/lib:"$HERE"/usr/486-linuxlibc1/lib
ldd "$HERE"/opt/wp8/wpbin/xwp
#exec "$HERE"/opt/wp8/wpbin/xwp "$@"
$HERE/lib/ld-linux.so.1 ./xwp
```

Which results in:

> joel@cybaryme/h/s/D/appimage> Corel_WordPerfect_8/AppRun 
> 	linux-gate.so.1 (0xf7764000)
> 	libXt.so.6 => /lib32/retro/libXt.so.6 (0xf7716000)
> 	libX11.so.6 => /lib32/retro/libX11.so.6 (0xf763c000)
> 	libXpm.so.4 => /lib32/retro/libXpm.so.4 (0xf762b000)
> 	libm.so.5 => /lib32/retro/libm.so.5 (0xf7622000)
> 	libc.so.5 => /lib32/retro/libc.so.5 (0xf7564000)
> 	libSM.so.6 => /usr/lib/i386-linux-gnu/libSM.so.6 (0xf751b000)
> 	libICE.so.6 => /usr/lib/i386-linux-gnu/libICE.so.6 (0xf74fe000)
> 	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7347000)
> 	libuuid.so.1 => /lib/i386-linux-gnu/libuuid.so.1 (0xf7341000)
> 	libbsd.so.0 => /lib/i386-linux-gnu/libbsd.so.0 (0xf7325000)
> 	/lib32/retro/ld-linux.so.1 => /lib/ld-linux.so.2 (0xf7766000)
> 	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf731c000)
> 	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf72ff000)
> Segmentation fault

Doing all that has the best `ldd` outcome, however there are still some libs that the executable must not like, especially after getting to know [this response](http://linuxmafia.com/wpfaq/problems.html#ACCELERATEDX).  

I was hoping for an AppImage to make getting this app across a few of my machines easier, however I have put pause on it for now, as I have a (slightly more difficult to deploy, but it does work) chroot jail of an older linux version that I am not seeing any issue with.

Thanks for the pointers.  Although the outcome was not as expected, I feel that this is in some way still close.

**Comment by probonopd** [comment]
Try to run it with `LD_DEBUG=libs ./Corel_WordPerfect_8/AppRun` to see what libraries get loaded before the crash...

**Comment by joelmaxuel** [comment]
Apologies for the delay, but here is the paste of that.
https://pastebin.com/ZjGLaSRR

I don't like how all those x86_64 libs are being called before the seg fault in spite of the overriding before.  WP8 is finicky with even age-appropriate OS versions (down to the unspecific segfault error) as well, FWIW.
