### ISSUE TITLE
Create an online Store

### ISSUE THREAD

**Issue by maverick74** [AppImage/AppImageKit#885]
Ok, i know it's a loooooong shot!

I know resources are scarce and that this probably won't see the day of light in a few years - if ever - but...

I think it would be productive to discuss it, because it would bring good publicity to AppImage to have a central location where to get AppImages (or maybe just light the fire so that other *stores* (imagine download.com or flathub, for example) start picking up the idea)

This is probably related to #882 but with better GUI and features :)

**Comment by azubieta** [comment]
Hi @maverick74, you may want to take a look at the are already existent solutions:
- https://www.appimagehub.com/
- https://appimage.github.io/
- https://github.com/Nitrux/nx-software-center

**Comment by maverick74** [comment]
I was only aware of appimage.github.io, but that did not seem like a _"real"_ store!

appimagehub.com, however, really does the job!!!

And the nx-software-center completes it!!! :D

Now: why doesn't this get recommended on appimage webpage?
**That would be great!**

**Comment by probonopd** [comment]
Third-party stores, websites and app centers are welcome to use the data from https://github.com/AppImage/appimage.github.io, some are listed there.
