### ISSUE TITLE
Save two external processes for $HERE

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#891]
We are using this construct in may places to make the rest of bash scripts relative to the location of the script:

https://github.com/AppImage/AppImageKit/blob/a01f60bb728af07a73644e677d73467985e8dca7/resources/AppRun#L2

@Lekensteyn suggests in https://code.wireshark.org/review/#/c/30953/ to change this to

```
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
```

saving two external processes, `dirname` and `basename`. Can this have any ill side effects in portability? This needs to be tested e.g., in `busybox`.

**Comment by probonopd** [comment]
https://www.shellcheck.net/ does _not_ complain about this:

```
#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
print"$HERE"
```

```
$ shellcheck myscript
No issues detected!
```

Looking promising so far.

Can we condense it to one line?

**Comment by Lekensteyn** [comment]
These features are indeed supported by dash (/bin/sh on Debian/Ubuntu) and busybox. It is part of POSIX, see https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html

> `${parameter%word}`  
> Remove Smallest Suffix Pattern. The word shall be expanded to produce a pattern. The parameter expansion shall then result in parameter, with the smallest portion of the suffix matched by the pattern deleted.
>
> `${parameter##word}`  
> Remove Largest Prefix Pattern. The word shall be expanded to produce a pattern. The parameter expansion shall then result in parameter, with the largest portion of the prefix matched by the pattern deleted.

**Comment by TheAssassin** [comment]
Both `dirname` and `basename` are part of POSIX, too. Both tools are made for working with paths, the shell snippet is some weird string hacking. I'm not sure how safe it is, even if shell "check pages" don't complain it doesn't mean it is verified to work. Did you even validate this snippet? I don't see any evidence. It's more like a "change a system that's running fine". (By the way, we don't use `basename` anyway, do we?)

The code was _much_ more readable before. The only real issue with it is that the escaping is pretty broken.

**Comment by shoogle** [comment]
Should be fine as long as you can be certain that `${SELF}` contains at least one slash, which it should as `readlink -f` is supposed to return an absolute path.

**Comment by TheAssassin** [comment]
"Should be" in the new vs. the previous implementation guaranteeing this...

**Comment by TheAssassin** [comment]
And what's the big advantage? The whole script runs 5 milliseconds faster?

In fact, the new script introduces a lot of assumptions. There's so many "should"s in this whole story. Who says `readlink -f` will always return a full path? It's not part of POSIX. If this tool could be avoided, I'd say "genius", but in this case, the new script causes a lot of headaches, doesn't provide any significant advantages, is much harder to read and verify, ...

**Comment by Lekensteyn** [comment]
`readlink -f` is a GNUism, so POSIX is indeed not relevant for `readlink` anymore. The info page says it will return an absolute (full) path: https://www.gnu.org/software/coreutils/manual/html_node/readlink-invocation.html

(Disclaimer: I have not looked closely at AppImage, so I don't know the environmental assumptions. I just got pinged and am just providing some feedback.)

**Comment by probonopd** [comment]
Our "environmental assumptions", or requirements, are that it works independent of a particular shell, e.g., `bash`, `dash`, `busybox`.

**Comment by Lekensteyn** [comment]
> Our "environmental assumptions", or requirements, are that it works independent of a particular shell, e.g., bash, dash, busybox.

Well, the new shell constructs will definitely work there since it adheres to POSIX. What I was wondering about though was assumptions on available programs. `readlink`, `cut` and `head` are part of coreutils. grep is.. well, grep :)

**Comment by TheAssassin** [comment]
`grep` is part of POSIX.

**Comment by shoogle** [comment]
> Who says `readlink -f` will always return a full path? It's not part of POSIX.

Indeed, it is only GNU's `readlink` (and a few copycats) that have a `-f` option to return a full, canonical path. However, there is unfortunately no POSIX command that provides that functionality, so it's a choice of assuming GNU `readlink` or not having the functionality at all (well there is a third option which is to write a library of shell functions using only Bash built-ins, [which is what I had to do](https://github.com/shoogle/bash-essential-functions/blob/master/modules/bef-filepaths.sh#L239-L273), but that only works in Bash).

Anyway, `${...%/*}` is perfectly readable to those who have seen it before, and it would only take a small comment to explain it to those who haven't. `basename` and `dirname` are technically only manipulating strings; they don't do any checks to make sure the path is valid or even exists.
