### ISSUE TITLE
SIGHUP might be blocked, so don't use SIGHUP to terminate the fuse process

### ISSUE THREAD

**Issue by dimbleby** [AppImage/AppImageKit#896]
An appimage might reasonably be run in an environment where `SIGHUP` is ignored: most obviously, if someone goes `nohup my-long-running-appimage &`.

But in that case when the payload process exits and we try to clean up with `SIGHUP` - [here](https://github.com/AppImage/AppImageKit/blob/10451d3420a14bec61979395bcbbd7cc3a605037/src/runtime.c#L148) - the signal will be ignored.  And so the fuse process is leaked.

I actually hit this in different circumstances, running `crontab -e` with the neovim appimage as my editor.  It turns out that `crontab` also blocks `SIGHUP` (I'm not sure this makes a lot of sense for `crontab -e`, but it's true anyway), which is inherited by child processes, and when I was done editing my cron jobs I found that the neovim process was still hanging around.

Suggest that using `SIGTERM` would fix this, and make more sense anyway.

>  It is the normal way to politely ask a program to terminate. 

which is exactly what we're doing.  (Unless you had some particular reason for preferring `SIGHUP`?)

**Comment by TheAssassin** [comment]
As long as FUSE terminates with `TERM`, too, there's nothing that prevents us from changing this. Could you send a PR, please? Then we can test it.
