### ISSUE TITLE
appimagetool/master branch removed

### ISSUE THREAD

**Issue by sudden6** [AppImage/AppImageKit#898]
In https://github.com/AppImage/AppImageKit#building you suggest to use this branch, but it doesn't exist anymore. Is this a mistake or deliberate change?

We relied on this branch and now our TravisCI builds using it are failing.

**Comment by TheAssassin** [comment]
It's been renamed to `master`. We've announced that in a few places, but forgot that document. Going to fix that asap.

**Comment by TheAssassin** [comment]
Thanks for the hint, by the way.

**Comment by sudden6** [comment]
Thanks, will update our CI accordingly.

**Comment by TheAssassin** [comment]
Only one break so far... I expected way more. I updated all our references to that branch already. I am not a fan of hardcoding repo hosting URLs anyway. For linuxdeploy, I plan to get a domain at some point, and set up a little web service redirecting to the actual targets. That way, it's under _our_ control, not under <insert hosting service here>.

**Comment by probonopd** [comment]
You know that I ever only trust infrastructure that has backing in the millions to billions ;-)

**Comment by TheAssassin** [comment]
Which is a big misconception...
