### ISSUE TITLE
Check for Categories=

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#909]
I am sick and tired of AppImages that do not have `Categories=` set in the desktop file.
Example: https://github.com/AppImage/appimage.github.io/pull/1193

The authors of those should get an error already when they try to produce the AppImage, not only after we have tested it on AppImageHub.

**Comment by probonopd** [comment]
Hence we should run https://github.com/AppImage/pkg2appimage/blob/master/appdir-lint.sh as part of `appimagetool`.

**Comment by TheAssassin** [comment]
Seems like a good idea, but there should be an integration test for this.

**Comment by probonopd** [comment]
What do you mean by "integration test" other than it passed the Travis CI test which means it was able to package itself successfully?

**Comment by TheAssassin** [comment]
https://github.com/AppImage/AppImageKit/blob/master/test-appimagetool.sh

https://en.wikipedia.org/wiki/Software_testing#Testing_levels

**Comment by probonopd** [comment]
Sorry, I know what "integration tests" in general mean, but I don't know what you want me to do here in particular. Add a test that fails when `Categories=` is missing?

**Comment by TheAssassin** [comment]
No. We should add a test that actually _passes_ when `Categories` is missing and appimagetool reports that correctly.

**Comment by probonopd** [comment]
That's what I meant. I am all for it :+1: please do

**Comment by TheAssassin** [comment]
I thought you should do it. I don't have any time. Please open an issue.
