### ISSUE TITLE
[Question] Travis CI Building

### ISSUE THREAD

**Issue by rebekah65** [AppImage/AppImageKit#915]
Are there any good video tutorials on building Appimages from Travis CI.
Thanks

**Comment by TheAssassin** [comment]
Nothing official at least. Please see https://docs.appimage.org/ and https://docs.appimage.org/packaging-guide/hosted-services/travis-ci.html.

**Comment by probonopd** [comment]
> Are there any good video tutorials on building Appimages from Travis CI.

https://www.youtube.com/watch?v=UJJKnr-WO0Y

**Comment by rebekah65** [comment]
@probonopd 
Thanks

**Comment by zero77** [comment]
@probonopd 
This video is great but, is there any info that covers other things like Python or Js.
Thanks

**Comment by probonopd** [comment]
For those we don't have videos yet but our documentation at http://docs.appimage.org/ covers those cases as well.
