### ISSUE TITLE
Git "version" detection code quite buggy

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageKit#919]
https://github.com/AppImage/AppImageKit/blob/cddcc2ec0823c4ff9124e23cd5b1977338d74159/src/appimagetool.c#L565-L583

At a first glance, you could think the code flow makes sense, however we have a case where git failed to run but appimagetool doesn't recognize that and prints the following messages:

```
fatal: Not a git repository (or any of the parent directories): .git
NOTE: Using the output of 'git rev-parse --short HEAD' as the version:
      
      Please set the $VERSION environment variable if this is not intended
```

Source: https://phabricator.kde.org/T10428

The code lacks quite some error handling and should be revised asap.

**Comment by probonopd** [comment]
If the automagic does not work, then the user is (correctly) advised to set the `$VERSION` environment variable. Why do you think there is a bug here?

**Comment by TheAssassin** [comment]
Please re-read the post, you probably misread the code (the message is a "on success" message, not an error message).

**Comment by probonopd** [comment]
In any case, the solution is to export `$VERSION`.

**Comment by TheAssassin** [comment]
@probonopd no, the solution is to fix the error treatment in that code section. It shouldn't "continue" if the git process exits with a non-null return code...

**Comment by tim-janik** [comment]
There are 3 errors that should be checked for in the code:

1) g_spawn_command_line_sync can return FALSE, in this case shell_parse or spawning failed. The code checks for this.
2) A non-NULL GError **error can be returned, usually that's true in the same cases that (1) errors. The code checks for this.
3) The exit status of the command being executed may be non-0, for 'git rev-parse', it's 128 when executed outside of a git repository.  g_spawn_command_line_sync provides this as an argument (gint *exit_status). The code passes this argument as NULL and does *NOT* check for this.

So you need something like:

    - int ret = g_spawn_command_line_sync(command_line->str, &out, NULL, NULL, &error); 
    + int status = -1, ret = g_spawn_command_line_sync(command_line->str, &out, NULL, &status, &error); 
    + g_assert (status == 0);

(Or a more graceful handling than g_assert)

See also:
https://developer.gnome.org/glib/stable/glib-Spawning-Processes.html#g-spawn-command-line-sync
