### ISSUE TITLE
Website: Point to https://subsurface-divelog.org/downloads/

### ISSUE THREAD

**Issue by Harvie** [AppImage/AppImageKit#925]
I was interrested in appimage, so i've googled it and browsed to https://appimage.org/ There was demo link pointing to subsurface at https://subsurface-divelog.org/downloads/Subsurface-4.6.4-x86_64.AppImage to test how appimage performs.

I've tried to launch it on latest upgraded archlinux and got this error:

`/tmp/.mount_Y7t3GV/usr/bin/subsurface: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory`

Not really impressive demo :-) Also note i've been testing the same thing months ago when i first heard about appimage. I don't remember details, but it didn't worked, so i gave it some time. But now i see it's still broken.

I understand that archlinux is supported, since you have arch logo on your website. I also heard that appimage needs target system to be same or newer than system used to build the appimage, which i surely have. But obviously there is some problem with subsurface demo appimage...

**Comment by Harvie** [comment]
OTOH this version works:
https://subsurface-divelog.org/downloads/Subsurface-4.8.5-x86_64.AppImage

So you might update your website to point to that instead...

**Comment by probonopd** [comment]
@TheAssassin could you help here please?

**Comment by TheAssassin** [comment]
Should we just link to the landing page instead of single files?

**Comment by probonopd** [comment]
Yes, just link to the landing page, not to the individual files. Or, even better, straight to https://appimage.github.io/. I would have done it if I could do it in a minute, but I am terribly busy atm.

**Comment by probonopd** [comment]
This was closed, yet I still see deeplinks to the two Subsurface AppImages on https://appimage.org/. Hence reopening.

**Comment by TheAssassin** [comment]
Forgot to push.
