### ISSUE TITLE
Python AppImage spec unclear

### ISSUE THREAD

**Issue by notklaatu** [AppImage/AppImageKit#928]
I've looked at the wiki page about building Python AppImages, and I've tried a few of the methods without success (and some of the examples linked to use the old-style AppImage, building an ISO image instead of SquashFS). I'm wondering if there's a way to get a reference implementation demonstrating a simple "hello world" Python AppImage.

**Comment by probonopd** [comment]
Hi @notklaatu. First of all, there is no such thing as an "Python AppImage spec". Asking for one is like asking for a "Python zip file spec". An AppImage is just a self-mounting filesystem that executes whatever you put inside it.

https://github.com/AppImage/AppImageSpec/blob/master/draft.md#contents-of-the-image

So the question really is, how to properly bundle your Python application as a standalone AppDir that it includes Python, the needed Python libraries and modules, and any other dependencies that cannot be assumed to be there in a recent enough version on every target system (distribution) in the default installation.

There are many different ways to achieve this. One that I think is especially powerful is using https://github.com/linuxdeploy/linuxdeploy-plugin-conda.

Other options are described at https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps.

**Comment by notklaatu** [comment]
I'm sorry, I must be missing something.

I've read the docs at https://docs.appimage.org/packaging-guide/manual.html and I've read the Python samples at https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps, and if I understand correctly, the latter docs are saying that in order to build an AppImage successfully from Python, I should learn to build a Conda package and then convert that package to an AppImage. Is that correct?

I haven't been able so far to get a basic Python AppImage build to work, even just a hello-world style test. I am guessing with the switch to SquashFS, bundling Python is a hard requirement, because my test app builds render this error:

    Fatal Python error: Py_Initialize: Unable to get the locale encoding
    ModuleNotFoundError: No module named 'encodings'
    Current thread 0x00007f87c97bd700 (most recent call first):
    Aborted

I've tried bundling Python, and I get this:

    ImportError: No module named site

Example code:
https://github.com/notklaatu/739b06-test

**Comment by probonopd** [comment]
Yes, please bundle Python and everything it needs to run that cannot be assumed to be part of every target system. Especially, all of the Python modules that your code is using (e.g., encodings).

There are many ways to do this, one is to use Conda, but doing it by hand is fine as well.

**Comment by notklaatu** [comment]
When I attempt to bundle Python itself, I get 'site' module errors. In my experience, that means the PYTHONPATH is set incorrectly. What's the correct way of setting environment variables within an AppImage? 

For example, if I move into my AppDir manually, I can execute the bundled Python executable:

```bash
$ cd foo.AppDir
$ ./usr/bin/python2.7
>>> import sys
>>> sys.path
['', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gst-0.10', '/usr/lib64/python2.7/site-packages/gtk-2.0']
>>> import site
>>> exit()
```

But once it's an AppImage, it can't seem to figure out how to run Python.

I've also added this, from the wiki page on Python AppImages:

```bash
$ cat ../lib/python2.7/sitecustomize.py 
import sys,os
prefix = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(sys.path[0]))))
sys.path = [ prefix+s for s in sys.path if not s.startswith(prefix) ]
```

I've tried bundling a shell script wrapper, which sets ``export PYTHONPATH=../lib/python2.7`` but that doesn't work, either.

**Comment by probonopd** [comment]
Maybe using `virtualenv` is the easiest way to get a relocatable Python installation?
