### ISSUE TITLE
Check Batis

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#93]
https://batis-installer.github.io

> Batis is a way to distribute and install desktop applications on Linux. Users can get up to date software directly from the authors, whichever Linux distribution they use.
> 
> Any user can install a Batis package, even if they don’t have Batis installed. Packages are regular tarballs, and include a standalone install script to run at the command line. See Packaging an application to distribute your program like this.

**Comment by kskarthik** [comment]
sounds similar to appimage. Any pro's ?

**Comment by kskarthik** [comment]
@probonopd what's the thing here. Appimagekit sounds better than this.

**Comment by probonopd** [comment]
This ticket is basically a self-reminder for me to check this out when I have time. The author had contacted me and made me aware of the project, but he mentioned that he is currently not working actively on it.

**Comment by hideout** [comment]
I tested batis yesterday( https://batis-installer.github.io ) the installer
is really sweet and it works pretty well
... but ofc appimage is much better *sign* ;)
but maybe its not bad for us to have a deeper look on it.

cheers

2016-03-01 10:18 GMT+01:00 probonopd <notifications@github.com>:

**Comment by azubieta** [comment]
The [batis repo](https://github.com/batis-installer/batis) haven't seen any update since 3 years ago. 
Closing the issue.
