### ISSUE TITLE
Update BUILDING.md

### ISSUE THREAD

**Issue by jrxxviij** [AppImage/AppImageKit#930]
**in BUILDING.md **

`sudo wget -c "https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetoolx86_64.AppImage" -O /usr/local/bin/appimagetool`

should be replaced by

`sudo wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O /usr/local/bin/appimagetool`

**Comment by TheAssassin** [comment]
Want to send a PR?

**Comment by probonopd** [comment]
We don't even have a `BUILDING.md`?

**Comment by jrxxviij** [comment]
@probonopd You're right! The issue is related to another project (linuxdeployqt) depending to this one.
