### ISSUE TITLE
Use the OVERLAYFS driver for the temporal mount point.

### ISSUE THREAD

**Issue by luis-lavaire** [AppImage/AppImageKit#933]
Hi!

[This issue](https://github.com/Nitrux/znx/issues/29) was discovered by @UriHerrera. I think that using the [OVERLAYFS](https://en.wikipedia.org/wiki/OverlayFS) driver could solve this. Instead of just mounting the compressed filesystem, the runtime could mount it via the OVERLAYFS driver. `$PATH` should also be modified so that it only points to locations under the overlay mount point. In this way, the binaries bundled in the AppImage would have execution priority over those that exist in the system.

The lower directory of the overlay should be the filesystem root, and the upper directory should be the mount point of the compressed filesystem.

**Comment by luis-lavaire** [comment]
Perhaps prepending the AppDir search paths to `$PATH` could solve this in an easier way:

`PATH=$APPDIR/bin:$APPDIR/sbin:$APPDIR/usr/bin:$APPDIR/usr/sbin:$PATH`

**Comment by probonopd** [comment]
Hi. Two challenges:
* Keep in mind that the AppDir also needs to work when being extracted from the AppImage 
* Only the application inside the AppDir is supposed to see the overlayed filesystem
