### ISSUE TITLE
Add required attributes to thumbnails

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#936]
As per https://bugs.kde.org/show_bug.cgi?id=402721, in order to make the thumbnails also work in KDE, we need to add the required attributes to the image files.

```
By Thumbnail Managing Standard: https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-0.8.0.html

-> 5.2. Thumbnail Attributes: https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-0.8.0.html#ADDINFOS

"The following keys and their appropriate values must be provided by every program which supports this standard...

Table 1. Required attributes.
Thumb::URI The absolute canonical uri for the original file.
Thumb::MTime The modification time of the original file!

If you just add an image to the cache it won't have those.
```

@azubieta can you have a look please and answer in the KDE ticket? Thank you very much.

**Comment by TheAssassin** [comment]
> Been talking to @kbroulik and the main reason KIO ignores thumbnails is not the lack of these extended attributes, but KIO not showing thumbnails for files it doesn't have (enabled) thumbnailers for. The logic seems to be "no thumbnailer in the list -> thumbnailer must be disabled", the use case "thumbnailer doesn't exist" isn't covered. Now, you might think "okay, then let's change that and add a 'fallback' thumbnailer that looks for existing thumbnails and can make use of them when there's no thumbnailer at all", but that wouldn't really solve the issue either, since we have a _proper_ AppImage thumbnailer and don't have to rely on the thumbs AppImages create.
>
> Therefore: not worth the effort.
>
> On the AppImage side, adding these attributes to thumbnails is a non-trivial task that will bloat our runtime and will add dependencies. Therefore: also not worth the effort.

Source: https://bugs.kde.org/show_bug.cgi?id=402721#c12

**Comment by probonopd** [comment]
> Been talking to @kbroulik and the main reason KIO ignores thumbnails is not the lack of these extended attributes, but KIO not showing thumbnails for files it doesn't have (enabled) thumbnailers for. 

Is that logic somehting @kbroulik feels strongly about and wants to keep? (I am like: If we have thumbnails, why not show them? After all, that is what other desktops seem to be doing)
