### ISSUE TITLE
Automatically install desktop integration bits when first run, and don't ask to relocate app

### ISSUE THREAD

**Issue by Pointedstick** [AppImage/AppImageKit#938]
Right now, when you first run an AppImage, AppImage Launcher pops up a dialog asking the user if they want to install the desktop integration bits and if they want to install it in the applications folder.

This presents some issues. First of all, casual Linux users of the type targeted by the AppImage project have no idea what desktop integration means and have no conception that this is something that could even ever not happen automatically. Linux users are accustomed to this happening automatically.

**Therefore:** AppImage should conform to that expectation and automatically install the dekstop file, mimetype handlers, etc when the AppImage is first run. Don't even ask. They should likewise be removed automatically when the AppImage is deleted, which already happens, at least in Plasma. :)

Second, asking to move the AppImage to the applications folder is not really very useful because there is no distinct and user-visible "applications folder" on Linux-based operating systems the way there is on macOS for example (`/usr/bin` doesn't count since it's an implementation detail and not intended to be used directly by the casual user). Creating ~/Applications and then putting it there is therefore not expected or useful, and presents the possibility of confusion: the user opens an AppImage, reflexively clicks "Yes" in the dialog box without reading it, closes the app, and sees that it's disappeared! This is not ideal.

**Therefore:** don't offer to move it to the "applications folder". AppImages should be installed in an appropriate location automatically by the app store app like Discover; users who download AppImages from random websites off the internet should be expected to manage this themselves.

**Comment by Pointedstick** [comment]
Moved to https://github.com/TheAssassin/AppImageLauncher/issues/141

**Comment by probonopd** [comment]
AIL is not part of the AppImage project. The official one is the optional appimaged daemon.

**Comment by probonopd** [comment]
Would appreciate your thoughts on https://github.com/AppImage/appimaged/issues/30.

**Comment by probonopd** [comment]
By the way, I think most users would not need special AppImage desktop integration at all if desktops would ask "Should I make this file executable?" when one double-clicks an ELF that is lacking the executable bit... @Pointedstick

**Comment by probonopd** [comment]
Or similar to this 

![](https://cloud.githubusercontent.com/assets/2480569/24582176/6b5e0c50-172a-11e7-9167-1bcd8d008413.png)

**Comment by Pointedstick** [comment]
Yes, I agree. That's the only confirmation dialog that users should be shown. Once they agree to make it executable and run it, the desktop integration buts should be automatically installed IMO.
