### ISSUE TITLE
"BAD signature" when validating signed AppImage

### ISSUE THREAD

**Issue by rajivshah3** [AppImage/AppImageKit#949]
## Description

I'm trying to sign an AppImage in a Docker container ([Dockerfile](https://github.com/iotaledger/ci-containers/blob/trinity-desktop-ci/Dockerfile)) by following the instructions at https://docs.appimage.org/packaging-guide/signatures.html but working around the FUSE issues. It signs successfully, but when I run the `validate` program it says `BAD signature`.

## Steps to reproduce

1. Build and sign the app
```
docker run -it iotacafe/trinity-desktop-ci:latest /bin/bash
mkdir workdir
git clone https://github.com/iotaledger/trinity-wallet
cd trinity-wallet
yarn && yarn deps:shared && yarn deps:desktop
cd src/desktop
yarn build
yarn compile:linux
cp out/trinity-desktop-0.4.6.AppImage /app/workdir
cd /app
chmod a+x appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage --appimage-extract
cd workdir
chmod a+x trinity-desktop-0.4.6.AppImage
./trinity-desktop-0.4.6.AppImage --appimage-extract
cd ..
./squashfs-root/AppRun ./workdir/squashfs-root ./workdir/trinity-desktop-0.4.6.AppImage --sign
```
<details>
<summary>Output of AppImage signing</summary>

```
root@1feb358c9ecc:/app# ./squashfs-root/AppRun ./workdir/squashfs-root ./workdir/trinity-desktop-0.4.6.AppImage --sign 
appimagetool, continuous build (commit ce61b83), build 2077 built on 2019-04-06 03:59:18 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
Using architecture x86_64
/app/workdir/squashfs-root should be packaged as ./workdir/trinity-desktop-0.4.6.AppImage
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/trinity-desktop.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information or use the generator at http://output.jsbin.com/qoqukof.
Generating squashfs...
Parallel mksquashfs: Using 2 processors
Creating 4.0 filesystem on ./workdir/trinity-desktop-0.4.6.AppImage, block size 131072.
[=============================================================|] 1638/1638 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
    compressed data, compressed metadata, compressed fragments, compressed xattrs
    duplicates are removed
Filesystem size 70268.48 Kbytes (68.62 Mbytes)
    35.01% of uncompressed filesystem size (200722.98 Kbytes)
Inode table size 5432 bytes (5.30 Kbytes)
    58.72% of uncompressed inode table size (9251 bytes)
Directory table size 904 bytes (0.88 Kbytes)
    52.35% of uncompressed directory table size (1727 bytes)
Number of duplicate files found 0
Number of inodes 91
Number of files 79
Number of fragments 7
Number of symbolic links  2
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 10
Number of ids (unique uids + gids) 1
Number of uids 1
    root (0)
Number of gids 1
    root (0)
Embedding ELF...
Marking the AppImage as executable...
Embedding MD5 digest
gpg2 and sha256sum are installed and user requested to sign, hence signing
Success

Please consider submitting your AppImage to AppImageHub, the crowd-sourced
central directory of available AppImages, by opening a pull request
at https://github.com/AppImage/appimage.github.io
```
</details>

2. Validate signature
```
git clone https://github.com/AppImage/AppImageKit
cd AppImageKit
apt-get update
./install-build-deps.sh
./build.sh
cd build/out
./validate /app/workdir/trinity-desktop-0.4.6.AppImage
```
<details>
<summary>Output of signature validation</summary>

```
root@1feb358c9ecc:/app/AppImageKit/build/out# ./validate /app/workdir/trinity-desktop-0.4.6.AppImage
Skipping ELF section .sha256_sig with offset 176712, length 1024
d450bdb70c4f309586e45c227f467adf0ff7689ed78ea2642d9730c3257fe789
/usr/bin/gpg2 --verify /tmp/trinity-desktop-0.4.6.AppImage.sig /tmp/trinity-desktop-0.4.6.AppImage.digest
gpg: Signature made Sun Apr 14 20:23:31 2019 UTC
gpg:                using RSA key DDF6BC26B3784A376567081FFF579E869C60F611
gpg: BAD signature from "Test Test <test@example.com>" [ultimate]
```

</details>

I tried reproducing the issue in an Ubuntu 18 VM but the `validate` program wouldn't build for some reason

**Comment by probonopd** [comment]
@theassassin can you have a look please and see whether the signatures are working in general?

**Comment by TheAssassin** [comment]
Since the validation works in AppImageUpdate... yes. I have never really looked into what that `validate` thing does in what way, so I can't give any guarantees. It's most likely that it's outdated, since it doesn't skip a few sections introduced to make AppImageUpdate much more efficient.

**Comment by probonopd** [comment]
Please update `validate` if you change stuff. I don't like that my stuff breaks when you make changes. Thanks.

**Comment by rajivshah3** [comment]
Is there a way to run the validation from AppImageUpdate by itself? I would try to fix the `validate` program in AppImageKit myself but my C skills aren't great 😅

**Comment by TheAssassin** [comment]
Nope, there is not. It's run only on updates.

**Comment by rajivshah3** [comment]
I see. Is there a workaround to verify it manually with `gpg`/`gpg2` or should I wait for this to be fixed?

**Comment by TheAssassin** [comment]
You will have to wait.

**Comment by probonopd** [comment]
Possibly the reason for https://www.reddit.com/r/Electrum/comments/blmx73/electrum_334_signature_confirmation/?

> You will have to wait.

For how long?

**Comment by cvarley100** [comment]
@probonopd @TheAssassin Do you guys have an ETA for this?

**Comment by TheAssassin** [comment]
No, this is the least priority issue right now to work on. I'm very short on time right now. Free software projects just can't give you any SLAs, unfortunately. This is on the TODO list.

**Comment by cvarley100** [comment]
Okay, that's understandable. I was just hoping you might have some indication of when you will begin work on it (it's somewhat of a blocker for us).

**Comment by TheAssassin** [comment]
PRs welcome, if you feel confident please feel free to apply the changes yourself (shouldn't be too hard, check out AppImageUpdate's verification code for comparison which works already).

**Comment by probonopd** [comment]
> AppImageUpdate's verification code for comparison which works already

Wouldn't this be a good thing to move to libappimage then, and consume it in the `validate` tool?

Also, does AppImageSpec need to be updated?

**Comment by TheAssassin** [comment]
I am not quite convinced this validate tool is useful at all. It just checks whether the signature is valid, but what does that tell you? From an information theory point of view, you first need to trust the key, then you can trust valid signatures made with it. But that "trust the key" bit isn't implemented at all by this `validate` tool. So the tool is pretty pointless.

**Comment by probonopd** [comment]
The tool is the reference implementation to check whether the signature in an AppImage is valid. It is meant (also) as a starting point for everyone who wants to work with those signatures.

**Comment by TheAssassin** [comment]
I guess we should drop it entirely and add functionality to libappimage, then build a tool there that can be used to validate signatures the right way...

**Comment by probonopd** [comment]
Add functionality to libappimage, then convert the `validate` tool to use libappimage (statically linked).
Do not throw away everything that exists, keep its outer shell while improving its innards. It should be a pattern by now.

**Comment by TheAssassin** [comment]
You can do it however you want, but I won't follow this annoying and couterproductive pattern. This old code code can't be saved, it will be rewritte in C++ if any. I don't see the need for it to be in AppImageKit, given that's all pure C.

**Comment by probonopd** [comment]
> annoying and couterproductive pattern

Huh? It's called "not breaking stuff". And it's one of my #1 principles.

**Comment by TheAssassin** [comment]
Seriously? Come on. This is not a change that breaks anything. That tool never has been used by anyone in the past years. Don't tell me _you_ have. It's not built and shipped anywhere. It doesn't matter where it is and how it's programmed. If the functionality gets into libappimage, we should also put the binary there, it's a demo for that code. Also, there will be more CLI helpers in the future in libappimage anyway. Let's start with this very simple one.

**Comment by probonopd** [comment]
>  That tool never has been used by anyone in the past years. Don't tell me you have.

Sure I have, when I wrote the whole checksumming thing, and tested it.

**Comment by TheAssassin** [comment]
What I mean is, that change in signature validation is quite old already, in the meantime nobody's used that tool actively, which means by reimplementing it you can't break anyone's scripts or so.

**Comment by probonopd** [comment]
@TheAssassin any chance this will get fixed anytime soon? Has been broken for way too long now for my taste.

**Comment by TheAssassin** [comment]
Feel free to fix it. I am super short on time and this has a *very* low priority.

**Comment by probonopd** [comment]
That would mean reverting to about https://github.com/AppImage/AppImageKit/tree/b06eb870724844571a55c1c671f388ca194b162d when it was working.

**Comment by probonopd** [comment]
> his has a _very_ low priority

![](https://user-images.githubusercontent.com/2480569/69480662-72ae4080-0e01-11ea-9719-857aa38770bc.png)

You know my rule. Something breaks, all other work stops until it is un-broken.

**Comment by TheAssassin** [comment]
Get me some help to handle the daily business! If that's your rule, please obey to it! Stop writing some weird Go code and fix the tool!

**Comment by TheAssassin** [comment]
If you *really* think two years of work are worth nothing, go revert. But then I'll be leaving.

**Comment by probonopd** [comment]
> fix the tool

I have not broken it; in fact I have not touched it in years and now it no longer works due to unrelated changes in other places that violate the AppImageSpec.

**Comment by shufps** [comment]
Any news on this issue? :)

**Comment by probonopd** [comment]
Can we confirm that https://github.com/AppImage/AppImageKit/pull/1090 is working correctly?
