### ISSUE TITLE
Providing Docker Image

### ISSUE THREAD

**Issue by ShalokShalom** [AppImage/AppImageKit#951]
I just saw that Kdevelop offers a special docker container to actually build their AppImage, I think that is actually cool to setup a build environment simply and fast, without setting up a whole OS.

https://github.com/KDE/kdevelop/tree/master/appimage

We might offer an own container, including linuxdeploy and stuff.

**Comment by probonopd** [comment]
In fact, the AppImageKit project uses Docker to build appimagetool and the other components on CentOS 6.x.

> We might offer an own container, including linuxdeploy and stuff.

That's for https://github.com/linuxdeploy/linuxdeploy then ;-)
