### ISSUE TITLE
Cannot run appimagetool without an icon

### ISSUE THREAD

**Issue by Gymmasssorla** [AppImage/AppImageKit#954]
Recently I was trying to compile my application that hasn't got an icon:
```bash
$ ARCH="x86_64" ./../appimagetool-x86_64.AppImage myapp.AppDir
```

Then I have an error:
```
appimagetool, continuous build (commit 225057b), build 1874 built on 2018-10-21 12:21:27 UTC
Using architecture x86_64
/home/gymmasssorla/Desktop/hello-world-appimage should be packaged as hello-world-appimage-x86_64.AppImage
Icon entry not found in desktop file
(null){.png,.svg,.svgz,.xpm} defined in desktop file but not found
For example, you could put a 256x256 pixel png into
/home/gymmasssorla/Desktop/hello-world-appimage/
```

My .desktop file conststs of those two lines without an icon:
```
[Desktop Entry]
Type=Application
Name=hello-world-appimage
```

How to solve this problem? I just want to keep my app without an icon.

**Comment by probonopd** [comment]
Works as designed. An icon is required.

**Comment by KittenEvil** [comment]
> Works as designed. An icon is required.
Specifications say otherwise: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html that the icon is optional. Why do you consider it required?

**Comment by probonopd** [comment]
It is optional for desktop files, but it is mandatory for AppImages because we want to provide a good user experience. AppImage was conceived with GUI applications in mind, and for those an icon is considered good practice. (Granted, you can also package CLI tools with `Terminal=true`, but this really never was our focus.)

**Comment by probonopd** [comment]
Now, the workaround is `touch usr/share/icons/hicolor/apps/appname.svg`...
