### ISSUE TITLE
Cannot run ARM/ARM64 appimagetool on Ubuntu 14.04

### ISSUE THREAD

**Issue by enzo1982** [AppImage/AppImageKit#966]
I cannot run the ARM/ARM64 appimagetool on Ubuntu 14.04 x64 with binfmt_misc support.

It keeps complaining `This doesn't look like a squashfs image.`. Same when running with `--appimage-extract`, so I cannot even extract the contents.

libfuse is installed for the AppImage architecture. It works with the same AppImage on an otherwise identically set up Ubuntu 16.04.

I did not try on a native ARM box as I don't have one running Ubuntu 14.04. i686 and AMD64 appimagetool runs fine on Ubuntu 14.04.

**Comment by TheAssassin** [comment]
We recently upgraded to Ubuntu xenial for ARM builds simply because trusty is EOL. I think this is a wontfix, please build on systems no older than xenial, since they still receive updates.

**Comment by probonopd** [comment]
Are we not using CentOS 6 anymore?

**Comment by enzo1982** [comment]
Nevermind, I already switched my ARM builds to xenial.
Just thought I'd report it here in case it might be an easy one to fix.

**Comment by TheAssassin** [comment]
Thanks for reporting, but that was to be expected I guess. I think we can close this. If you encouter further issues please feel free to reopen or comment.
