### ISSUE TITLE
Get back the source of a symlink to an AppImage?

### ISSUE THREAD

**Issue by niess** [AppImage/AppImageKit#967]
I have the following issue:

- When calling an AppImage through a symlink, inside the image, `${APPIMAGE}` points to the actual image location. I.e. the symlink seems to be resolved? Since `$0` points to an `${APPDIR}` location, the source of the symlink would be lost.

This is problematic in some cases where the source of the symlink is needed, instead/in addition of its target. E.g. Python's initialisation relies on this in order to detect a virtual environment. _Is there a way to find back the source within the app?_

Note that this behaviour is opposite to the "usual" one. Below is an example in bash in order to illustrate the problem:

```bash
#! /bin/bash

cat <<EOT > 'target.sh'
#! /bin/bash
echo "I'm \${0}, and that's fine"
EOT

chmod u+x target.sh
ln -fs 'target.sh' 'source.sh'
./'source.sh'
```

It yields `I'm ./source.sh, and that's fine`, whereas when the target is in an AppImage , `${APPIMAGE}` would yield `target.AppImage` while`$0` would be inside `$APPDIR`.

In order to preserve this information, it would be more relevant to me that `${APPIMAGE}` points to the  source rather than to the target, if that's technically feasible. Since then one can always follow the link down to the target if needed. But the opposite is not possible as far as I know?

**Comment by TheAssassin** [comment]
Have you tried `$ARGV0`?

**Comment by niess** [comment]
Just found by greping the [source](https://github.com/AppImage/AppImageKit/blob/master/src/runtime.c#L728). Yeah, that's good :) Saves my day. Sorry for the noise :P

**Comment by TheAssassin** [comment]
*I* am sorry for wasting a bit of *your* time.

**Comment by TheAssassin** [comment]
@niess documented them here https://docs.appimage.org/packaging-guide/environment-variables.html, please feel free to send PRs to improve that description.

**Comment by niess** [comment]
@TheAssassin, That's fine as so :) Good to have them listed somewhere. Actually, I just recently realised this "subtle" difference between `$ARGV0` and `$APPIMAGE`. Not sure that I would have noticed it at first by reading the doc :P

**Comment by TheAssassin** [comment]
We should add a little sentence when to use which of these.

**Comment by TheAssassin** [comment]
Done.

**Comment by niess** [comment]
Very good :)

I didn't think about using `ARGV0` that way for multi-binaries. That's a nice idea indeed. I was using a scheme the like:
```
./exe.AppImage command [...]
```
where `command` refers to a binary inside the image and where an AppRun script dispatches the command and its arguments. But instead I could do:
```
ln -s command exe.AppImage
```
and then parse `ARGV0` in AppRun
