### ISSUE TITLE
Fuse on WSL?

### ISSUE THREAD

**Issue by niess** [AppImage/AppImageKit#972]
Hello,
trying to run an appimage on WSL/Ubuntu 18.04 we get the following:
```
AppImages require FUSE to run.
...
```
By googling I understood that FUSE is not supported on WSL (but would soon be on WSL2). Is that correct? Do you know any work-around meanwhile? In order to run the appimage without extracting it? -Which works :)
Thanks!

**Comment by probonopd** [comment]
Yes, that is correct.

WSL2 should be able to run AppImages thanks to the built-in FUSE support, although I have not tested it.

For WSL (not 2) you need to extract the AppImage. Most AppImages support `--appimage-extract.` FUSE is not needed for extracting. I have tested this on WSL.

**Comment by niess** [comment]
Thank you for the confirmation. Extracting worked for us as well, on WSL. We are trying to upgrade to WSL2. I let you know if it indeed works or not.

**Comment by Calinou** [comment]
@niess IIRC, there's also `--appimage-extract-and-run` if you want to extract and run an AppImage directly.

**Comment by niess** [comment]
Thanks @calinou. I didn't know this option. That's a fair substitute indeed :)

**Comment by antony-jr** [comment]
@probonopd here is a interesting project which implements libsquash without using fuse, https://github.com/pmq20/libsquash, If we could integrate this into AppImage then AppImage does not require fuse at all.

**Comment by TheAssassin** [comment]
We don't require FUSE per se, only for running. I don't see how libsquash could provide a suitable virtual filesystem in which all files could be accessed normally, so a program can run without any modifications. It is more for reading SquashFS images and extracting data from them, for which it might be easier to work with than squashfuse, since it's made to be linked to by other programs, but that doesn't help in our use case.

**Comment by probonopd** [comment]
Thanks for confirming @jtodap

**Comment by michalfapso** [comment]
Yes, it works on WLS2. I just had to `sudo apt install libfuse2` on my Ubuntu 22.04 to make it work as suggested here:
https://unix.stackexchange.com/a/731191/151304

**Comment by buburakk** [comment]
For those who might need, it also works on WSL2 with Arch Linux after installing the `fuse2` package from the official Arch repository.
