### ISSUE TITLE
Can't run appimagetool under cron

### ISSUE THREAD

**Issue by ccoupe** [AppImage/AppImageKit#976]
Sorry for quick push on the button.  My app build process has a weekly cron job to build everything for the platforms I support (linux,bsd,osx,windows) and appimagetool dies in cron. First you need a the DBUS session env var. If I add that then it dies with two of these:
```txt
      Failed to execute operation: Process org.freedesktop.systemd1 exited with status 1
      Failed to start appimagelauncherd.service: Process org.freedesktop.systemd1 exited with status 1
      See user logs and 'systemctl --user status appimagelauncherd.service' for details.
```
I got around this by building the appimage/squashfs by hand as mentioned in the README.md but that's not ideal.

**Comment by azubieta** [comment]
`Failed to start appimagelauncherd.service` this looks really weird.  appimagelauncherd should not be executed by appimagetool?

Are you sure this is not an AppImageLauncher issue ?

**Comment by ccoupe** [comment]
I've got a running appimage of my app that works and I previously installed the AppImageLauncher for my Mint 18.1 system and they work (there's an icon issue but that's not this bug). It's only in the sad little environment of cron that things are wrong.

**Comment by azubieta** [comment]
It seems `AppImageLauncher` is interfering with `appimagetool` at the moment of being executed by cron. This is a side effect of using `binfmt.d` to intercept AppImage file executions.

@TheAssassin any thoughts ?

**Comment by ccoupe** [comment]
I found a workable method. I was executing the appimagetool-x86_64.appimage  in the cron script and that's what wasn't working. I built AppImageKit from github source and did a `sudo make install` and now the cron script calls the 'appimagetool' in /usr/bin and everything works as expected. 

I also cross compile my app for the Raspberry PI  and using the --runtime-file pointing to a runtime.armhf file copied from a AppImageKit built on the pi - it works! It doesn't have the desktop integration because I don't have the AppImageLauncher on the PI. Still, it's good for me.

**Comment by TheAssassin** [comment]
> I built AppImageKit from github source and did a sudo make install and now the cron script calls the 'appimagetool' in /usr/bin and everything works as expected.

That's not really a solution, though.

Do you run your cron job as root? AppImageLauncher hasn't been tested with root really.

**Comment by ccoupe** [comment]
> Do you run your cron job as root?

No, as my user name. FWIW, here's the line to add to the cron script to get a DBUS_SESSION_BUS_ADDRESS
```txt
      export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pidof cinnamon)/environ | cut -d= -f2-)
```
replace `pidof cinnamon` with your desktop manager - an ugly hack in two dimensions. I don't feel too bad about building the AppImageKit from source as a prerequisite for developers to use AppImage although I do understand why you feel differently. 

Is there a way to turn off desktop integration even if appimaged or AppImageLauncher has been installed?  [My app ](https://walkabout.mvmanila.com/downloads/linux-downloads/) already has an installer based on the old  makeself script and knows how to create the desktop menus if needed.

**Comment by TheAssassin** [comment]
The reason I don't consider your thing a solution is that there is an issue with appimagelauncherd interferring with a cron job.
`sudo *anything*` is ugly for us because AppImages provide a non-root experience normally. And all our tools are of course available as ready-to-use AppImages.

You can deactivate AppImageLauncher temporarily (or also permanently), but I guess what you want to do is just flag your app as "hey, I don't need to be integrated". You can do so by adding `X-AppImage-Integrate=false` to your desktop file.

**Comment by probonopd** [comment]
So this is an AppImageLauncher issue and not an AppImageKit/appimaged issue. Hence closing here. Feel free to continue in https://github.com/TheAssassin/AppImageLauncher/issues.
