### ISSUE TITLE
Export QT_QPA_PLATFORMTHEME=gtk2 for Gtk based desktops 

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#977]
Set `QT_QPA_PLATFORMTHEME` to make Qt applications look more native on Gtk+ based systems. The C equivalent of 

```
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*|)
        export QT_QPA_PLATFORMTHEME=gtk2
esac
```

should be added to `AppRun.c`. Note that by itself this does nothing, unless a Qt application is bundled with `platformthemes/libqgtk2.so` and `styles/libqgtk2style.so`.

https://github.com/TheAssassin/AppImageLauncher/issues/103#issuecomment-507013065

**Comment by TheAssassin** [comment]
ld-p-qt can do this w/o having to `AppRun.c` (which thankfully nobody has to use anymore really, it's got so many drawbacks like force-changing the working directory...) implement this once https://github.com/linuxdeploy/linuxdeploy/issues/81 is implemented.

**Comment by TheAssassin** [comment]
linuxdeploy supports installation of hooks with initiation code by plugins now. We could install a hook now that does your snippet above. I'm not sure if we should however. Let's continue discussion there, though. This is not the kind of thing AppImageKit has/should have to deal with.

**Comment by TheAssassin** [comment]
As announced in https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/33#issuecomment-523869817, I've just corrected the syntax error in the OP. The code still interprets empty values, which I think is an error, but I didn't touch that part.

**Comment by alexander-buerger-met-no** [comment]
We have a software that uses `QT_QPA_PLATFORM=offscreen` and runs without `DISPLAY`. To make our software start as AppImage on a GNOME desktop we either
- `unset QT_QPA_PLATFORMTHEME` in a wrapper script inside the AppImage, or
- `unset XDG_CURRENT_DESKTOP` before starting the application

It looks like the gtk platform theme otherwise fails as it cannot connect to the X11 server.

**Comment by probonopd** [comment]
It's probably best to use a custom AppRun script inside the AppImage then.

**Comment by bphd** [comment]
Using a custom script implies extracting the appimage, what if we only want to arbitrarly pass a variable punctualy to an appimage that we directly run? Like we would do in a normal binary with `$ VARIABLE=value binary`?

**Comment by probonopd** [comment]
With "custom script" we mean that the author of the application's AppImage puts a custom script into the AppImage as the `AppRun` file.

**Comment by bphd** [comment]
Sure, that's what I meant. But what if I'm a *user* of the application, not its *author*. And I want to apply a variable at run, rather than in the author package definition?

**Comment by probonopd** [comment]
Just export that variable before running the AppImage.

**Comment by bphd** [comment]
https://github.com/AppImage/AppImageKit/issues/1154#issuecomment-2466172097
