### ISSUE TITLE
How to read icon of Appimage file ?

### ISSUE THREAD

**Issue by sonichy** [AppImage/AppImageKit#985]
I am write a FileManager with Qt, I want to read icon of Appimage.

**Comment by azubieta** [comment]
Hello @sonichy, please take a look at [AppImageServices](https://github.com/azubieta/AppImageServices) and [plasma-appimage-integration](https://github.com/azubieta/plasma-appimage-integration). The first one is a dbus services that provide all the methods you may require in your file manager and ensures interoperability with other applications (like software centers o AppImageLauncher). The second is a set of plasma extensions that already make use of AppImageServices and you can use as reference.

If you have any other questions or need an special feature please feel free to open an issue on the AppImageServices repo.

**Comment by probonopd** [comment]
If you are going the dbus route, the dbus server needs to be running, which cannot simply be assumed to be the case. So unless you are building your own distro where you can ensure that the dbus server is running, it's probably easier to just consume libappimage (and ideally link to it statically).

**Comment by sonichy** [comment]
I heard that KDE can display icon of Appimage file.
DBus is too dependent, I want to use more indeppendent like read file methord.
I have already read out the ID3 cover image in mp3.
Caja, Thunar, DeepinFM can display mp4 file icon, I do not know how.

**Comment by probonopd** [comment]
KDE is using libapimage. https://github.com/AppImage/libappimage

**Comment by TheAssassin** [comment]
@probonopd the docs are at https://docs.appimage.org/api/libappimage/, please feel free to put a link wherever it makes sense to you.

**Comment by probonopd** [comment]
I have linked them in README.md. Thanks.
