### ISSUE TITLE
AppImage for Redox OS

### ISSUE THREAD

**Issue by Joe23232** [AppImage/AppImageKit#995]
#98 Similar to this request but for [Redox OS](https://www.redox-os.org).

Redox OS is a new Unix-like operating system (in pre-alpha) that uses a microkernel. It would be great if it supports AppImage as well.

**Comment by probonopd** [comment]
Does it support FUSE?

I doubt any of the AppImage developers has time to work on a a pre-alpha Unix-like operating system, but certainly we'd be happy to support Redox OS developers in case they want to port AppImage and have questions.

Did you make a request for AppImage support at the Redox OS ticketing system?

**Comment by Joe23232** [comment]
Nah I haven't yet but ok sure I can do that.
